core/core-editor.el, private/my-bindings.el
The smart-forward package does not provide the functions smart-left or smart-right. Instead, the functions should be named smart-forward and smart-backward.
=> Fix wrong smart forward and backward bindings

core/defuns/defuns-company.el
I'm trying to fix two things with this PL:
1) I noticed that when using C-x C-l in insert mode, the line-autocomplete would not work because company was not enabled. I now load company mode when using that command.
2) If using the command C-SPC to autocomplete, if company mode is not enabled, enable it.
Feel free to add both hunks, only the first one, or none ;)
=> Enable company mode when asked to autocomplete

core/core-packages.el
Add `persistent-soft` to `doom-protected-packages` to avoid install failure.
=> Fix persistent-soft make dependency

modules/feature/version-control/+git.el, modules/feature/version-control/packages.el
I've been migrating to a new emacs config based on yours after coming from Spacemacs and am still very much a novice at emacs configuration and elisp, so please let me know if you see anything that needs to be changed.
I ran into two small challenges integrating ```git-timemachine```:
+ The default mode keybindings were not being applied, so I added them manually in the ```def-package!``` definition.
+ On entering the ```git-timemachine``` minor mode, none of the mode specific keybindings would work (they were still bound to their evil equivalents), until I hit escape (```evil-force-normal-state```), after which all of the ```git-timemachine``` specific keybindings functioned properly. To work around this I added a hook to execute ```evil-force-normal-state``` on entering the minor mode. …
=> add git-timemachine

core/autoload/editor.el, core/core-editor.el
Add a prompt that will ask to open large files literally to avoid performance issues. A large file is determined by the checking the file size against the variable ```doom-large-file-size``` (default: 1MB). Opening a file literally essentially means that:
* Major and minor modes are disabled
* Buffer is readonly
* Undo is disabled
This results in drastic performance increases when opening a large file with the intention simply viewing it. This does not interfere with the built in emacs prompt when opening very large files.
Also, let me know if this functionality should be located somewhere else. ```core/editor``` seemed like the most logical location for it.
=> add `doom/large-file-check to prompt literal open of large files

modules/feature/evil/autoload/neotree.el, modules/feature/evil/config.el
Add additional h/j/k/l keybindings to neotree.
* ```h``` - if current node is expanded collapse it, otherwise move up to parent node
* ```j``` - select next node
* ```k``` - select previous node
* ```l``` - expand node (if folder) or open (if file)
=> add simple h/j/k/l keybindings to navigate neotree

modules/feature/evil/config.el, modules/feature/evil/packages.el
Add the evil-mc package. 
It worked perfectly for me in my config, however using your config only the current cursor would delete characters properly. After a little digging I was able to get it to work properly after commenting out the following line in your ```+bindings.el``` file:
:i [remap delete-backward-char]   'doom/deflate-space-maybe
Overriding ```delete-backward-char``` was conflicting with the delete functionality for the other cursors. I haven't looked into it, but you can probably get it to work with your custom delete function without too much trouble.
Quick Highlights:
```ctrl-n``` - place cursor next matching word
```ctrl-p``` - place cursor at previous matching word
```gru``` - clear cursors
```grj``` - make cursor and move down
```grk``` - make cursor and move up …
=> added evil-mc

modules/feature/evil/config.el
This should fix the backspace issue and will properly execute ```doom/deflate-space-maybe``` across all cursors.
=> add `doom/deflate-space-maybe' as a custom evil-mc custom known command

core/core-os.el
Disable automatic copying to clipboard anytime visual state changes. This was previously only applied when running on macOS, but has now been modified to apply to linux as well.
=> disable copy on visual state change for BOTH mac and linux

modules/lang/org/config.el
Currently loading ```org-mode``` will disable ```show-paren-mode``` globally. Previously this wasn't noticeable because it was toggled on and off frequently via hooks, however it is not being re-activated after loading an ```org-mode``` buffer. This commit will make ```org-mode``` only disable show-paren-mode locally in the ```org-mode``` buffer.
Also, holy cow you've been slinging some elisp. All of your recent changes have been awesome!
=> only disable show-paren-mode locally for org mode buffers

modules/ui/doom/config.el
Make ```doom/blink-cursor``` an interactive function, so that it can easily be called on demand to flash the cursor line.
=> make doom/blink-cursor interactive

README.md
Ripgrep link in README.md was not working
=> Fix README ripgrep link

modules/completion/ivy/config.el
I recently added the ability to customize the behavior of the 'magic slash' in ivy when adding a slash to a non-match when working with files. Specifically the variable ```ivy-magic-slash-non-match-action```, which has three possible values:
* ```’ivy-magic-slash-non-match-cd-selected``` - automatically 'cd' into closest matching directory (default)
* ```’ivy-magic-slash-non-match-create``` - automatically create a new folder based on the currently entered text and cd into it
* ```nil``` - do nothing and add the slash literally
The reason I added this variable to ivy was because the default behavior made it impossible to create files inside of folders that don't exist, but whose name would also match an existing folder. For example, trying to add the file: ```~/doc/todo.org``` is …
=> disable ivy magic slash non-match action

core/core-editor.el
=> Fix *scratch* immortality

modules/lang/purescript/config.el, modules/lang/purescript/packages.el
I think I was doing some `:config` stuff in `:init`. Tiny improvements and documented why `flycheck-purescript` is commented out.
=> lang/purescript: small improvements

core/core.el
I wanted to try this config without moving my current `.emacs.d` directory, so I cloned into a different directory and launched with that directory as my HOME:
HOME=/home/tsanders/doom emacs
This caused the following error:
File error: Cannot open load file, Not a directory, core-lib
After looking into it some more, I think the paths are (partially?) expanded as part of the `make compile` process, so my `load-path` would contain `~/doom/.emacs.d/core`, which expands to `/home/tsanders/doom/doom/.emacs.d/core` instead of `/home/tsanders/doom/.emacs.d/core`, etc..
Compiling with the alternate HOME seems to fix the issue:
HOME=/home/tsanders/doom make compile
However, this patch is another fix I have tried that appears to work for me regardless of the compile environment: If we expand HOME …
=> Support running from non-standard HOME directory

modules/lang/go/config.el
=> lang/go: add missing command-go-gocode-command variable

.gitignore
Hey, until now I had my private module in a separate repo and sym linking it inside your repo but today I decided to fork your config and place my private module there. What I noticed is that init.el file in my private module was ignored and I saw that you had ignored all init.el files in the repo which I think is a mistake. I've updated the .gitignore to ignore only the root init.el.
=> Ignore only root init.el

core/core-keybinds.el
aB now correctly does a-block,
iB now correctly points to inner-block. It was the opposite before.
=> fix :text-obj map macro

modules/org/org-babel/config.el
sh was renamed to shell in Org 8.2 [1] and this may result in some undesired
behavior as it will fall back to the bundled ob-sh.el
[1] http://orgmode.org/cgit.cgi/org-mode.git/plain/etc/ORG-NEWS
=> Fix: org/babel: sh -> shell

modules/feature/syntax-checker/config.el, modules/feature/syntax-checker/packages.el
This is used to set up the flycheck load-path correctly for emacs-lisp package
development.
=> Add: feature/syntax-checker: add flycheck-cask for emacs-lisp

modules/lang/scala/config.el
See valid values at https://github.com/ensime/ensime-emacs/blob/f1ca2bd6de9b4e7eabe198ada75196183a1862c0/ensime-vars.el#L51
Alternatively, could be set to nil (to avoid slowdown for complex project by default).
=> Fix invalid default for ensime-eldoc-hints (now set to 'all)

modules/feature/version-control/autoload.el
Pretty self explanatory ... I was receiving void function errors when ```+hydra-smerge/body``` was being called when the hydra feature was not enabled.
On the plus side, this promped me to enable the hydra module which is pretty awesome! 👍
=> Check if the hydra feature is enabled before opening smerge hydra

modules/completion/ivy/autoload/ivy.el
When trying to use +ivy-tasks in one of my projects it was failing w/ error:
`(Stack overflow in regexp matcher)`. This was due to ripgrep searching a folder
in the project root containing a minified bootstrap css source map file (which
had a `TODO:` in it). Since that file was a single line of text concatenated
together, the regex was getting passed ~540KB of text.
To make it easier to recognize what is causing +ivy-tasks to fail I wrapped the
failing code in `condition-case-unless-debug` and report the error and the file
causing the error using `message!`. So now if there is a failure during the
extraction of a task from the search cmd's results, it returns non-failing results
and alerts the user in separate pop-up with information about why it failed.
Below is text and screenshot …
=> Gracefully handle +ivy-tasks match errors

modules/lang/haskell/config.el
I'll need someone to double-check this for me, but on my computer, I don't have any `inf-haskell-mode-map`, so I was getting errors like `(void-variable inf-haskell-mode-map)`.
There is however an `inferior-haskell-mode-map` (seems like poor naming convention on their side...), which at least seems to remove the error when I replace it with.
=> inf-haskell: fix mode-map name

modules/feature/workspaces/autoload/workspaces.el
Started getting into doom's workspace usage today, and these seemed to fix a few issues – not sure if they're unique to my machine or not.
This fixes renaming workspaces to work interactively by prompting for a new name from the minibuffer.
This also fixes the saving and loading of workspaces, however, an error still shows up after saving saying that it failed, despite writing to the persp file (and successful re-loads following).
I'm curious if the 'main' workspace can be renamed dynamically - i tried some code to do so but hit a few issues so thought I'd ask if it was a true necessity to protect it.
=> fix(wrkspcs): interactive rename, save + load dir

core/core-editor.el
_savehist-save-minibuffer-history_  was misspelled as _savehist-save-minibuffer-his**s**tory_. I assume that this was not intentional, so I fixed it.
I could not find any information about contributing (the link at the bottom of the readme is broken), so I hope that this is fine. If I made some kind of mistake, just tell me.
=> Fix a spelling mistake during variable assignment

modules/lang/javascript/config.el, modules/lang/javascript/packages.el
This the following features mentioned in #185 have been implemented using the `def-project-mode!`:
- Auto Format Code: eslint w/ prettier
- Use eslint_d if available otherwise fallback to eslint
I didn't know how you prefer the documentation for this feature be added so I am leaving it here in pull request. 
This project mode enables automatic formatting of javascript source on save using `eslint --fix`.
This project mode requires `eslint_d` for auto formatting.
```sh
npm -g install eslint_d
```
To enable this feature for a specific project you can use `.dir-locals.el` to set `doom-project` to include `+javascript-eslintd-fix-mode`. Here is an example of my `.dir-locals.el` file which is located next to `package.json` in the root of my JS project: 
```elisp
;;; Directory Local Variables …
```
=> Add project-mode +javascript-eslintd-fix-mode

modules/lang/markdown/config.el
This pull request is pretty straight forward and prevents the markdown localleader keybindings from being added to the global keymap.
=> Fix markdown specific keybindings being added to global map

modules/org/org-present/config.el
This is a pretty simple commit that just fixes the keybindings for `org-tree-slide-mode`.
One thing I find a bit curious is that additional keybindings are added identically to org-mode below in the file, yet those seem to work propertly without the mode specifiers:
```emacs-lisp
(map! :map org-mode-map
"<f8>" #'+org-present/org-tree-slides
"<f7>" #'+org-present/next)
```
Also, note that the `+org-present/next` function seems to be missing.
Used this mode successfully while giving a talk at an Emacs meetup last night, thanks for implementing it! :+1:
=> Fix org-tree-slide-mode keybindings

modules/feature/version-control/autoload.el
loading `git-link` when `+vcs-root` is called.
=> When calling +vcs-root, load git-link first.

modules/feature/workspaces/autoload/workspaces.el
After pressing SPC q Q, I get this error. Seems, that `(interactive)` fixes the problem.
=> Fix 'Wrong type argument: commandp' in +workspace/kill-session-and-quit.

modules/app/email/config.el
Hey!
I just got a pull request into ace-link that supports highlighting and opening various types of links in the mu4e message view mode. It works for opening mu4e links, shr rendered links, and email attachments. If your interested in using it, I've bound it to 'o' in when in mu4e-view-mode in this PR.
=> Add keybinding for ace-link in mu4e message view mode

modules/private/README.org
Currently the links in [modules/private/README.org](https://github.com/hlissner/doom-emacs/blob/3d323e6ecfca571e1e4d66f0b466711e6a108d6f/modules/private/README.org) are broken. I propose using absolute links, since they work in forks and locally.
Feel free to use relative links if you want.
=> Fix private module readme's links

modules/feature/syntax-checker/config.el
- Fix issue: Symbol’s function definition is void: flycheck-popup-tip
=> Call flycheck-popup-tip-mode correctly

modules/feature/evil/config.el, modules/private/default/+bindings.el
1. `evil-numbers` is in the `packages.el` of feature/evil, but not configured with any `def-package!` statements
2. About the keybinding, I think it would be better to use the same keybindings as vim (since doom is "An Emacs configuration for the stubborn martian vimmer"). It might be uncomfortable for Emacs users (since it takes `C-x`), but I've been using this config for some time, and it works fine for me (a former vim user and spacemacs user)
=> feature/evil: add mapping for evil-numbers

modules/lang/cc/config.el
If rtags is not installed, a more suitable message is displayed when cc-mode is activated.
Previously, if rtags was not installed, the error message would state that "nil" was not found.
=> Correctly report when rtags's client or server are not found.

modules/feature/syntax-checker/config.el
Eldoc uses a default idle delay timer of 0.5.
In your cc module flycheck also is using a `flycheck-display-errors-delay` of 0.5.
This is leading to a race between flycheck and eldoc for the minibuffer, and in my case flycheck never displays the error message and eldoc is showing the docstring even though there is an error in the function parameters.
So i have delayed the flycheck display from 0.5 to 0.7 so that it overrides eldoc in case of errors.
=> Fix race between eldoc and flycheck by delaying flycheck

modules/feature/evil/autoload/folds.el
- this function only worked in magit-status-mode but not other modes like
magit-log-mode, magit-process-mode, etc.
=> feature/evil: fix +evil/matchit-or-toggle-fold in magit modes

modules/completion/ivy/config.el
Small fix: make counsel-descbinds an autoload function.
'counsel-descbinds' can now be called without having to wait until counsel is loaded by some other command.
=> Add 'counsel-descbinds' to councel defer commands.

core/autoload/help.el
When I call `(doom/describe-module)` from dashboard the function raises an error, because buffer-file-name is not defined for dashboard.
=> Check if buffer-file-name is nil before passing it as argument.

modules/lang/latex/config.el
This PR added settings to use `Skim.app` as a PDF viewer for LaTeX export.
=> Add: +skim as pdf viewer

modules/lang/ess/README.org, modules/lang/ess/autoloads.el, modules/lang/ess/config.el, modules/lang/ess/packages.el
This is a `ESS / R` ported from `spacemacs`. 
Currently I only added extremely basic `+eval/repl` support 
(+eval code with `quickrun`). But the ordinary ESS inferior mode is pretty 
usable (start `R` with `localleader-'` and send code use `localleader-,`).
Check the README.org for other keybindings.
=> Add ESS / R module

core/autoload/buffers.el, modules/app/rss/config.el
Hi there. I have turned on rss module and found two bugs.
1. After fresh start of emacs org is not loaded. This prevents elfeed-org to be invoked when I start elfeed.
2. When I press `q` in elfeed I get error message about `kill-buffer` arguments.
=> Fix rss module.

modules/lang/cc/config.el
When evil is disabled functions like `rtags-find-symbol-at-point` don't work because the function evil-set-jump isn't defined. I'm proposing the simple fix of only adding the hook when `(featurep 'evil)`
=> Fix adding evil-set-jump to rtags-jump-hook when evil is not enabled

modules/private/default/+bindings.el
Both flycheck-mode and toggle-frame-fullscreen seem to be bound to "SPC t f", which means that only the second binding gets applied and there's no binding to toggle flycheck. This PR simply changes the fullscreen binding to capital F.
=> Fix keybinding

modules/feature/evil/config.el
Before this commit, pressing `t` in org-agenda buffer resulted in activation of evil-snipe instead of setting todo state as how it is intended by [evil-org](https://github.com/Somelauw/evil-org-mode/tree/491b0b302b95d44ceb73d291dedbb9d5517ccee2#agenda)
(If this was on purpose and Doom has some custom way for setting todo states from org-agenda buffers I am not aware, I apology for pointless pull request)
=> feature/evil: add org-agenda-mode to evil-snipe-disabled-modes

modules/lang/clojure/config.el
When opening an EDN file in Emacs I noticed Clojure code wasn't automatically applied. I think this is because the mode is deferred and Doom doesn't tell Emacs that `.edn` files belong to Clojure.
Fingers crossed I've fixed this in an idiomatic way!
=> Add edn to Clojure mode extensions

modules/lang/clojure/config.el
Quick change that I've been running locally as the namespace is [`clojure.string`](https://clojure.github.io/clojure/clojure.string-api.html) as opposed to `clojure.str`.
My full list right now looks like this:
``` emacs-lisp
(nconc cljr-magic-require-namespaces
'(("async" . "clojure.core.async")
("byte-streams" . "byte-streams")
("cache" . "clojure.core.cache")
("cli" . "clojure.tools.cli")
("codec" . "ring.util.codec")
("component" . "com.stuartsierra.component")
("d" . "datomic.api")
("data" . "clojure.data")
("deferred" . "manifold.deferred")
("gen" . "clojure.test.check.generators")
("jmx" . "clojure.java.jmx")
("json" . "cheshire.core")
("medley" . "medley.core")
("prop" . "clojure.test.check.properties")
("r" . "clojure.core.reducers")
("random" . "crypto.random")
("s" . …
```
=> Fix magic require of clojure.string

core/core-editor.el
Let whitespace dynamically set `whitespace-line-column` depending on the current
state of the variable `fill-column`. Changing the value to `nil` does exactly that.
=> Let whitespace dynamically use fill-column

modules/feature/file-templates/templates/js-mode/__webpack.config.js
Webpack 4 has some syntax changes, mainly using `rules` key instead of `loaders`.
=> Update webpack file template for latest version

modules/tools/password-store/autoload.el, modules/tools/password-store/config.el, modules/tools/password-store/packages.el
Now that auth-password-store has been renamed to auth-source-pass and it matches
the name and functionality of the feature included in emacs 26 I've removed the conditional loading and use of different packages. 
I was getting an error on emacs load because `auth-source-store` wasn't loaded (and couldn't because the name is incorrect) but was defined with `def-package!`. There were several incorrect variations of the correct package names (e.g. `auth-store-pass`, `auth-source-store`) causing problems. Now that `auth-source-pass` works for both emacs 25 & 26 life should be better.
I updated auth-source-pass to only be installed when the +auth flag is set. I also moved the condition into the :when of the !def-package. If there is any reason to leave it as it was I'd appreciate any education …
=> Update password-store +auth to only use auth-source-pass

modules/lang/web/+html.el
Web mode has a bunch of helpful commands under `C-c`, this replicates the same
bindings, but in leader-key style. E.g.: `C-c C-a k` becomes `SPC m a k`
=> Feature: lang/web: add local leader bindings for web-mode

modules/ui/posframe/config.el
Do not assume the :size is 18.
That confused me for a bit because I use 20 and was wondering why posframe child frames didn't fit right in with the rest of my Emacs.
I think this is a more reasonable default.
=> Cut: ui/posframe: don't set ivy-posframe-font

init.example.el, modules/lang/erlang/config.el, modules/lang/erlang/packages.el
Since Elixir is supported out of the box, it seems unfair to leave out Erlang :). I'm still relatively new to working with elisp, so let me know if I could be doing things differently. I added some customizations which add some additional support for rebar3 and some common Erlang files (e.g. `sys.config`). I think there is probably room here to expand this to maybe provide EDTS/Wrangler or something along those lines, but I wanted to start simple - this module is basically what I built for myself so far.
=> Add language support for Erlang

modules/feature/evil/autoload/folds.el
PS: "d %" never works. Disabling evil-matchit fixes that.
=> Fix "z o".

core/core-ui.el
I see "Buffer %s is modified; kill anyway?" quite often. Looks like `buf` is missing from the call to `y-or-n-p`.
=> Add missing buffer name to kill confirmation

core/core-packages.el
When working with a proxy or other insecure environment, the environment variable `INSECURE` will prevent TLS certificate check, but Doom still tries to use HTTPS repo's for packages. This prevents users without HTTPS from installing Doom. We can fix this by checking for this variable and using the the HTTP versions for `package-archives`.
=> Don't use HTTPS when INSECURE variable is set

modules/lang/javascript/autoload.el, modules/lang/javascript/config.el, modules/lang/javascript/packages.el
Tide provides much better support for code intel and completion and it is actively maintained unlike tern. Tide also does not require users to install outside dependencies such as the tern javascript package in order for it to work. Adding the local node_modules to the emacs exec path allows for users to then use the project versions of flow, prettier, jest, eslint, etc.
=> [*] Removes tern in favor of tide, adds local node modules to path

core/core-keybinds.el
Note: which-key says `which-key-show-operator-state-maps` is hacky, but imo it should be enabled anyways
=> enable which-key's evil support

modules/lang/javascript/config.el
Add flycheck-mode to typescript. The hook has been probably lost in the last refactor of the javascript module.
=> fix(lang/javascript): add flycheck-mode to typescript-mode hooks

init.example.el, modules/lang/nim/README.org, modules/lang/nim/config.el, modules/lang/nim/packages.el, modules/lang/org/packages.el
Add basic support for the [nim](nim-lang.org) programming language.
Adds:
- `<localleader>` Build menu
- Syntax checking and highlighting (`nim-mode`)
- Code completion (`nim-mode`)
- Org babel support (`ob-nim`)
=> Basic support for Nim

modules/lang/web/packages.el
[slim-mode]: https://github.com/slim-template/emacs-slim
Adds support for [slim](https://github.com/slim-template/slim) syntax hightlighting
=> Add [slim-mode] to :lang web +html

modules/completion/helm/config.el
It looks like an extra letter snuck into a `nil` in 67dab98. This is causing a
startup error on develop.
=> Fix typo causing startup error in helm module

modules/lang/go/config.el, modules/lang/go/doctor.el
- Fixed typo for gocode command in `doctor.el`
- Only enable flycheck mode if the syntax-checker feature is enabled
=> Small fixes for go-mode

modules/completion/helm/config.el, modules/completion/helm/packages.el
Some sensible defaults I feel like would be widely appreciated, disabling them I just found myself re-enabling them out of frustration.
=> completion/helm: cleanup and set some more sensible defaults

modules/lang/ocaml/config.el
Just a typo in config (although it seems working fine on my machine).
=> Fix typo in OCaml module.

modules/lang/org/+ipython.el, modules/lang/org/autoload/ipython.el, modules/lang/org/config.el, modules/lang/org/packages.el
This PR adds ob-ipython and related config to doom-emacs as `+ipython` in `lang/org` module.
Main features including:
1. Support for remote kernels
2. Integrate `python-shell-*` and (if using) `lpy-mode` so that you can send code from `org-edit-src-code` window to `REPL`
3. (Optionally through `+right-popup`) popup editing window / REPL at right hand side.
=> lang/org: +ipython

modules/tools/magit/config.el
I'd have to run a magithub command to get everything to pop up like pull
requests and what not. I think this was an oversight -- just removing
this will still lazyload it, but instead when magit runs!
=> Fix magithub not loading after magit

modules/tools/magit/config.el
This really seems like it should be a default, it's so handy to get better
diffs, sort of like how github does it. if set to 'all then it'll show on all of
them, but I think t is good enough.
=> tools/magit: Show word-granularity on chosen hunk

modules/lang/latex/config.el
After opening the reftex TOC in a latex document, every call to `C-g` would mess up the open windows.
Remove the binding that was causing this problem.
=> Fix latex C-g quitting latex after opening the reftex table of contents

modules/lang/cc/config.el
To keep rtags protocol consistency, I think it's better to use `rtags-install` to install or update rtags instead of compile it by ourselves. So put rtags with others tools under doom-etc-dir maybe a good idea.
=> lang/cc: set rtags-install-path to ${doom-etc-dir}/rtags/

modules/lang/latex/config.el
By default, nested enumerates are indented with too many spaces (relative to how things are indented in DOOM).
This small PR changes the defaults to match DOOM indentation standards.
=> Better looking default indentation for nested latex lists

modules/config/default/+bindings.el, modules/tools/magit/config.el
Relatively often I find myself in need to remove some files from a Git repository. I submit for your consideration the following binding (`SPC g x`) to make it conveniently available right under the fingers. ;)
=> bindings: magit | add `file-delete` as `SPC g x`

modules/tools/pdf/config.el
A refactoring spree introduced a bug by incorrectly making a hook symbol a function. This fixes this.
Let there be page numbers again!
=> Fix: restore the correct display of current and total pages in PDFs

modules/tools/wakatime/autoload.el
Sometimes it doesn't prompt to decrypt gpg, etc etc. Regardless, I think this
should be interactive so it's easily re-initialized
=> Make +wakatime-init interactive

init.example.el
I've been keeping my init up-to-date with the example, but the example
still has `electric-indent` whereas `make` warns me it's been renamed to
`electric`. This provides the correct module name in the example.
=> Fix init.example `electric` module

modules/lang/org/packages.el
the feature is in `init.el` as `rest` not `restclient`; the way this was `ob-restclient` will never get installed
=> Look for the correct feature name for org+rest

modules/lang/latex/config.el
Note that zathura with synctex is already supported as a viewer option by AUCTeX, making this a simple one-liner.
=> Added Zathura as a viewer option

modules/lang/clojure/config.el
str => clojure.string is already defined in `cljr-magic-require-namespaces'
re-frame + reagent is subjective (for personal configuration IMO)
fighweel aspect is now handled upstream by giving a prompt
see: `cider-cljs-repl-types'
=> Cut: lang/clojure: unneeded + subjective parts

modules/lang/haskell/+dante.el, modules/lang/haskell/doctor.el, modules/lang/haskell/packages.el
- removed dependency on `company-ghc` (`dante` supports `company`)
- enable `dante-mode` automatically in `haskell-mode`
- add `flycheck` and `hlint` support to `dante-mode`
- add `doctor.el` check for `hlint` executable.
=> Refactored +dante feature

modules/lang/markdown/config.el, modules/lang/markdown/doctor.el, modules/lang/markdown/packages.el
The `markdown` module currently comes with no option to set a compilation method. This PR adds the `+pandoc` feature to the `markdown` module, adding basic integration between `markdown-mode` and `pandoc-mode` as recommended in Jason Blevins' (author of `markdown-mode`) [guide to markdown mode](https://jblevins.org/projects/markdown-mode/).
- `pandoc --from=markdown --to=html --standalone --mathjax --highlight-style=pygments` is set as the default markdown command.
- `pandoc-mode` is automatically enabled for a markdown file iff a pandoc settings file is present.
- added a doom doctor check for the `pandoc` binary, iff the `+pandoc` feature is enabled.
=> Added basic +pandoc feature to markdown module

modules/app/irc/README.org, modules/app/irc/autoload/irc.el, modules/app/irc/config.el, modules/config/default/+bindings.el
This PR adds `SPC o I` as a keybinding to open IRC. When in a `circe` buffer some additional keybindings are available to make it easier to switch channels and sent private messages.
I also added an example of a pass entry to the documentation.
=> Add keybindings for circe

modules/lang/markdown/doctor.el
Really minor change.
Fixes the obvious:
```bash
./bin/doom doc         
Doom Doctor
Emacs v26.1
Doom v2.0.9 (c8de34fb)
shell: /bin/zsh
Compiled with:
XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL
GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11
MODULES THREADS LIBSYSTEMD LCMS2
uname -a:
Linux myarchbox 4.16.16-1-ck-haswell #1 SMP PREEMPT Sat Jun 16 08:24:52 EDT 2018
x86_64 GNU/Linux
Checking your OS...
Checking your fonts...
Checking gnutls/openssl...
Testing your root certificates...
Checking for GNU/BSD tar...
Checking your enabled modules...
> (:lang markdown) Syntax error: (end-of-file
/home/haozeke/.emacs.d/modules/lang/markdown/doctor.el)
There is 1 error!
```
=> doctor: Fix error with markdown

modules/completion/ivy/config.el
As the title said. The previous code does not work.
=> Fix disable ivy fuzzy search in counsel-grep and swiper

modules/lang/common-lisp/config.el
`set-repl-handler!` helps with opening a repl when a particular mode is
active in a buffer. We want to be able to open a `sly-mrepl` whenever we
are in a lisp buffer, so we should have the repl handler look for
`'lisp-mode` to define opening a sly repl.
I assume the lookup handlers should be making sure we are in a lisp
buffer (similar reasoning to the repl-handler).
=> Fix handler calls to reference lisp-mode.

modules/lang/haskell/+hindent.el, modules/lang/haskell/+intero.el, modules/lang/haskell/config.el, modules/lang/haskell/doctor.el, modules/lang/haskell/packages.el
`hindent` was previously only loaded as part of the `+intero` feature. It's now factored out as part of `config.el` with a `doom doc` check for the `hindent` executable.
=> Factor out hindent

Makefile
This allows 'make quickstart' to work on Windows when using GNU make (appreciate Windows isn't officially supported)
=> Double quote doom binary location

modules/lang/org/+present.el
This grabs all minor versions upto 4.xx
If in doubt about the new changes, check [the changelog](https://github.com/hakimel/reveal.js/releases).
=> org: Update revealJS url

modules/lang/haskell/+intero.el, modules/lang/haskell/doctor.el
Adds the `hlint` checker for `intero` users. Note that this used to be the default in `intero`: https://github.com/commercialhaskell/intero/commit/06527fc4c9a5239e7921845f9c7cd4d2783eb030
Note this adds some redundancy, since the `hlint` checker is declared in two places. 
Since `intero` is broken on NixOS, this needs testing!
=> Intero hlint

modules/lang/nix/config.el, modules/lang/nix/doctor.el, modules/lang/nix/packages.el
For future investigation:
- [nix-company.el](https://github.com/NixOS/nix-mode/blob/master/nix-company.el) seems to be broken.
- [nix-buffer](https://github.com/shlevy/nix-buffer) looks interesting but probably shouldn't be lazily loaded, due to its nature.
=> DONE: improve nix module

modules/lang/haskell/config.el
=> minor haskell tweaks

modules/lang/markdown/config.el
Enables:
- syntax highlighting of latex math fragments
- org-mode compatible checkboxes
=> Markdown tweaks

modules/completion/helm/autoload/posframe.el
With (helm +childframe) in doom! section, without this patch
execute-persistent-action opens an extra non-child frame. This
doesn't play nicely with my tiling window manager.
This patch is taken from helm-posframe, and seems to fix it.
=> fix helm execute persistent action

modules/app/notmuch/autoload.el, modules/app/notmuch/config.el
This is a simple fix to allow users to be able to specify the sync backend they
wish to use for NotMuch.
=> Configurable sync backends for NotMuch

modules/lang/ess/config.el, modules/lang/ess/packages.el
The ess loading point has been changed from ess-site to ess-mode as described here: https://github.com/emacs-ess/ESS/pull/404 and here https://github.com/emacs-ess/ESS/issues/589.
Additionally [emacs-smart-equals](https://github.com/genovese/ess-smart-equals) package is broken because ess has made ess-S-assign obsolete and an alternative called ess-assign-list introduced. I have removed the package and disabled the functionality of smart assignment.
I will probably try to create a pull request to fix the emacs-smart-equals package, but it doesn't seem to be active. so no guarantee that it will be accepted.
=> Fixed ess main load point

bin/doom
The `term.el` package defines an environment variable `EMACS` inside its shell process, containing the Emacs and term.el version, in a string that looks like this: `26.1 (term:0.96)`. This interferes with the `bin/doom` command, which expects that environment variable to be a path to an Emacs binary. Trying to run make inside a doom terminal thus gives you this error:
```
Emacs isn't installed
make: *** [Makefile:5: all] Error 1
```
This simple fix just checks if `$EMACS` looks like a term version string, and ignores it if so.
=> Fix running make from inside doom

modules/lang/cc/config.el
this cause wrong tab width in c mode
=> delete redundant comma

modules/lang/coq/README.org, modules/lang/coq/autoload.el, modules/lang/coq/config.el, modules/lang/coq/packages.el
Adds basic support for the coq proof assistant via proof general (sadly, not packaged on elpa/melpa) and company-coq.
=> DONE: add coq module

modules/lang/coq/autoload.el, modules/lang/coq/packages.el
`company-coq` is now only loaded if company is enabled.
=> Put company-coq behind conditional

modules/lang/haskell/config.el, modules/lang/haskell/doctor.el, modules/lang/haskell/packages.el
`hindent-mode` is superseded by `format-all`.
=> Removed hindent (included in format-all)

modules/config/default/+bindings.el
This PR adds a default binding for deft under the "notes" header, if the deft module is enabled.
=> Adds a default binding for deft

modules/lang/coq/autoload.el, modules/lang/coq/config.el, modules/lang/coq/packages.el
`company-coq` does more than just provide company completion.
- define lookup handlers based on `company-coq` functions.
- disable company features if company is disabled.
=> Company-coq tweaks

modules/lang/org/config.el
A few bindings for navigating the calendar in the `org-read-date` prompt. The default bindings are using `Shift` and `Shift-Meta` + the arrows, which is having us leave the comfort of the home row.
=> lang/org: Add evil-friendly calendar navigation

modules/completion/ivy/README.org
The wrong commands are listed for `SPC b b`/`SPC b B`. Just a simple typo fix
=> Fix typo in ivy/README.org

core/core-ui.el
Setting the charset to `'unicode` caused emacs to segfault. Setting it to `nil` retains failback behaviour.
=> Fix unicode regression

modules/lang/coq/packages.el
Proof-general no longer has to be loaded via quelpa's git fetcher.
https://melpa.org/#/proof-general
=> proof-general now on melpa

modules/ui/fci/autoload.el
Hello, and sorry for my poor English...
I think this change avoids the error caused when the variable `fci-mode` is void.
Thanks.
=> Improve +fci|disable-when-company-activates

early-init.el
describe-variables `gcs-done`, it used to be 4, now it is 1.
Unfortunately `emacs-snapshot` segfaults when compiling doom twice, so I'm  back to Emacs26.
=> Emacs27+: reduce number of GCs on startup from 4 to 1

core/core-ui.el
Even when an `.elc` is preset `load-theme` would attempt to load the `.el` first,
to give the opportunity to inspect the theme.
However we are loading themes automatically from (M)ELPA, and loading a
theme package is no more dangerous than loading a regular package.
So override the search order for themes and atttempt to load the `.elc`
first.
This looks a bit ugly, but improves startup time by ~25ms with the default theme.
=> Load .elc even for themes

modules/lang/agda/README.org, modules/lang/agda/config.el, modules/lang/agda/doctor.el
This PR adds basic support for the agda language. Since `agda2-mode` isn't packaged on (m)elpa, but instead accompanies each agda release, this module automatically finds the location of the emacs support files via the built-in `agda-mode locate` command. If the user doesn't have agda installed, this naturally won't work.
A couple of modifications are made to upstream `agda-mode`:
- local leader keybindings
- colorscheme agnostic syntax highlighting, mostly based on haskell and idris
=> :lang agda (done)

modules/tools/magit/config.el
As someone that doesn't use evil, it seems this call needs to be guarded.
=> magit: only implement leader key logic when doom-leader-key is non-nil

core/core-ui.el, modules/app/write/autoload.el, modules/app/write/config.el, modules/editor/format/autoload/format.el
I set a custom font for variable-pitch and it was not taking effect (it was quite obvious, because I set a serif font, and I got a sans serif one instead).
I also checked with `SPC u C-x =` and looks like the font I set had no effect.
Two reasons:
* the font only got set for new frames, and not for the main emacs frame
* the +write-mode-hook was not actually run, because we assigned to the hook before +write-mode minor mode got defined (and the autoloads only generate autoloads for the mode, not the hooks)
I fixed these, perhaps not in the most elegant way. Feel free to suggest improvements.
Also got a bugfix for format.el, so included it here (wrong type, `cons` expected a list as 2nd argument, but it really wanted to just build a list of 2 elements here).
=> Fix write mode fonts and format.el

modules/app/email/config.el
I believe the `mu4e-confirm-quit` is meant to be nil according to the comment
above. Feel free to close if this was intended.
=> mu4e-confirm-quit should be nil instead of t

core/core-lib.el, modules/editor/format/autoload/settings.el, modules/lang/org/config.el
Couple things I noticed when running `make compile`
=> Fix some error path and typos spotted by `make compile`

modules/tools/macos/autoload.el
A quick fix for invoking `+macos/open-in-default-project` under `ranger-mode`
=> fix `+macos/open-in-default-project` under `ranger-mode`

modules/lang/org/config.el, modules/lang/org/packages.el
When `:tools pdf` is enabled, org links to pdf files should be opened in `pdf-view-mode`. Additional support is added for links to a specific *page* in the pdf.
=> Open org links with `pdf-view-mode` (with `:tools pdf`)

modules/lang/coq/README.org, modules/lang/coq/config.el
This line deactivates the expansion of abbreviations since it is hard to work with Coq in evil mode when this is active. For example, if my cursor is next to the letter L and I hit escape, it gets expanded to: `
Lemma # : #.
Proof.
#
Qed.
`
That makes it hard to work with ProofGeneral.
The solution I found is from a [ProofGeneral Github issue](https://github.com/ProofGeneral/PG/issues/174). I was not sure where to add the line. Apparently it has to be before loading evil-mode.
Let me know if you want me to add it in a different place or just close the PR if you don't want to have this at all.
Thank you for your work. I really enjoy using emacs using doom.
=> Deactivate expansion of abbreviations (ProofGeneral/Coq)

modules/lang/clojure/config.el
Add a local leader keybinding to both switch to the CIDER REPL buffer and set the namespace according to the file buffer.
Additionally, this fixes the clobbered "r" binding, and some minor changes.
=>  lang/clojure: add binding to switch/set namespace 

modules/lang/org/+capture.el
- The built-in capture templates now add a link to the file from which capture was initiated - this integrates well with a capture-based workflow, and also means that the built-in templates play nicely with, e.g., `org-mu4e-store-and-capture`.
- Checkboxes have been changed to TODOs - other components of doom, e.g., `magit-todos` assume TODOs and don't recognize checkboxes. In any case, in org-mode checkboxes are standardly used for subtasks.
=> Capture template tweaks

modules/lang/ocaml/README.org, modules/lang/ocaml/config.el, modules/lang/ocaml/doctor.el, modules/lang/ocaml/packages.el
See the included [README.org](https://github.com/edwintorok/doom-emacs/blob/ocaml/modules/lang/ocaml/README.org)
In OCaml, `opam` is a source-based package manager that also installs `.el` files along with tools that have editor support. I preferred to load these from opam's `$(opam config var share)/emacs/site-lisp` directory instead of MELPA because some of these are not present on MELPA (e.g. `ocamlformat`), and others are outdated on MELPA (e.g. merlin is fetched from a several month outdated `beta` branch, the release version is much newer).
The only exception is tuareg-mode (which needs no executable), and `flycheck-ocaml` (which only exists on MELPA).
The disadvantage is that these were not byte-compiled, so I added code in packages.el to do that, but that doesn't fit in nicely …
=> OCaml module improvements

modules/lang/ocaml/README.org, modules/lang/ocaml/config.el, modules/lang/ocaml/packages.el
Thanks for mergin my PR, I see you've been busy refactoring it :)
Here are a few more  tweaks, `merlin-eldoc` is something I've recently come across, and merlin already had `imenu` and `iedit` support in the `merlin` package, just had to bind it to some keys/enable it.
=> merlin: eldoc, imenu and iedit support

modules/lang/ocaml/config.el
A copy+paste error slipped  through in my previous PR, this would cause problems due to `merlin-imenu` not being available at the time `merlin-iedit` is initialized.
=> lang/ocaml: drop bad imenu initialization

modules/editor/lispyville/README.org, modules/editor/lispyville/config.el, modules/editor/lispyville/packages.el
I didn't include the `additional-movements` key theme because it has yet to work (the keys in that key theme are not being mapped to any corresponding `lispyville-` function), and `text-objects` key theme because that seems to be more useful with [targets.el](https://github.com/noctuid/targets.el) which is a whole different package to configure.
=> added :editor lispyville

modules/ui/fci/config.el
without those hook handles:
with those hook handles:
=> turn off fci when window is narrow than fill column

modules/editor/lispy/config.el
With this setting lispy closes the ending quote which is in alignment
with how Doom treats quotes in other modes.
=> Close the ending quote in lispy-mode

modules/lang/go/config.el
This PR fixes a bug which caused 'SPC m b r' to fail in go mode.
=> Fix 'SPC m b r' in go-mode.

modules/ui/popup/autoload/popup.el
This accidentally reuses windows in other frames, especially when there are multiple compliation buffers.
=> Don't scan frames other than current in popup

core/core-projects.el, modules/tools/magit/config.el
[fd](https://github.com/sharkdp/fd) is a rust program **significantly faster** than find and git ls-files that **respects .gitignore**.
This change is also recommended in the [projectile docs](https://projectile.readthedocs.io/en/latest/configuration/), or a screenshot: ![screenshot](https://i.imgur.com/oCmBGb5.png)
=> Use fd for populating projectile cache

.gitignore
Change .gitignore to exclude "modules/private" when attached as symlink.
=> Change .gitignore to exclude "modules/private" when attached as symlink

modules/emacs/dired/config.el
To avoid endless spam in \*Messages\*, disable "Omitted 2 lines" every
time a new dired buffer is opened.
=> fix: disable verbose message for dired-omit

core/core-ui.el
It was highlighting the expected white space style.
=> Fix highlight-non-default-indentation

modules/app/email/README.org
Thank you for contributing to Doom!
Before you submit this PR, please make sure your PR is targeted at develop, not
master (unless this is a fix for a critical error). Then replace this message
with a description of your changes.
the dotfiles repository url is wrong. it gives a 404 error.
=> fix wrong url of dotfiles repository

modules/ui/vc-gutter/config.el
This change checks whether a file is remote before checking whether it's a version controlled repo, rather than the other way around. Gives a slight speed improvement to Tramp.
Also thank you for making doom-emacs such a wonderful coding experience!  I really appreciate all the works that goes into maintaining such a project. I know many people (myself included) that have a much better time using doom-emacs than vim. Continue the good work!
=> ui/vc-gutter: switch git-gutter order

modules/tools/pdf/+modeline.el, modules/tools/pdf/config.el
When using the new modeline module, pdf tools was not displaying the modeline correctly. This PR fixes it.
Also, remove some TODO comments that have already been addressed.
=> pdf-tools: fixes for the new `modeline` module

modules/lang/latex/config.el
The varible `TeX-mode-local-vars-hook` doesn't exist. Instead, we use
`TeX-mode-hook` to enable flyspell. We append to the hook, however, to
enable disabling flyspell with
`(setq-hook! 'TeX-mode-hook +spellcheck-immediately nil)`
=> latex: enable flyspell correctly in latex buffers

core/core-projects.el
When indexing it ignores hidden files, which is especially annoying for dotfiles
where everything starts with a dot. If you just have -H it'll index .git too
though, so we exclude that
=> Improve projectile-git-command

modules/lang/common-lisp/config.el
The `q` binding for `sly-popup-buffer-mode-map` was overriding `sly-db-mode`'s binding, causing lots of issues.
=> common-lisp module sly-db-quit fix

modules/config/default/+evil-bindings.el
A bug left from legacy code.
syntax-checker is now in "features" and not in "completion".
=> bindings: correctly detect if syntax-checker is on

core/core-keybinds.el
Fixes #1071.
Also `general-non-normal-states` has the value `(insert emacs hybrid iedit-insert)`. I'm not sure if I should bother with `hybrid` and `iedit-insert` modes.
=> Fix an issue where doom-leader-alt-key and doom-localleader-alt-key does not work in emacs mode

modules/lang/org/+babel.el
ipython implements its own `async` keyword. As ob-async is loaded now by
default, we need to explicitly tell ob-async not to touch ob-ipython blocks.
=> org: let ob-async ignore ob-ipython

modules/config/default/+emacs-bindings.el, modules/config/default/+evil-bindings.el, modules/config/default/config.el
With the `default` module and the `+bindings` flag enabled, non-evil users will have a default set of bindings suitable for Doom emacs.
=> bindings: default set of bindings for emacs users

modules/app/irc/config.el
This prevents default keybindings from using `tracking-next-buffer' so that a user doesn't accidentally end up in a weird mixed workspace.
=> irc: remap tracking-next-buffer to +irc/tracking-next-buffer

modules/app/irc/config.el
It seemed I mistakenly put this in an `evil` block and didn't notice.
=> irc: fix lui track bar not being enabled

modules/lang/solidity/packages.el
Fixes #1152. Though there's still an upstream issue of the `solc` command should
now be `solc-js`
=> Solidity Fix

modules/config/default/+evil-bindings.el
I noticed that previous/next for some of the bindings had changed. When looking into the +evil-bindings function I saw that the description of the commands didn't align with the actual functions being called.
This patch updates the named sections with harmonized description and function calls.
=> Harmonize previous/next commands

modules/lang/ruby/autoload.el
This enables compilation of the Ruby module where previously the
following error would cause a breaking error.
../../../lang/ruby/autoload.el:48:45:Error: &rest without variable name
✕ Failed to compile modules/lang/ruby/autoload.el
=> Add missing variable name

modules/lang/clojure/config.el
Both `cider-browse-ns-find-at-point` and `cider-browse-ns-doc-at-point` are functions that meant to be used inside of the Cider's [namespace browser](https://docs.cider.mx/en/latest/miscellaneous_features/#browsing-namespaces) and not in the regular source files, so I switched lookup handlers to use functions which actually work in source files. 
I've also added references lookup handler based on `clj-refactor` as Cider itself [doesn't support it (yet)](https://github.com/clojure-emacs/cider/issues/1840).
=> Fix Clojure mode lookup handlers

modules/lang/clojure/config.el
For some reason descriptions are not shown for minor mode maps (such as `cider-mode-map` and `clj-refactor-map` in Clojure package), so for now I've switched all mappings to major `clojure-mode-map`. I'm not sure if it's a right way to do it and what could be broken due to this switch, but so far I haven't encountered any problems with it.
I'm not really a Emacs expert, but initial investigation shows the following: 
`map!` macroexpands to the expression containing `:major-modes t` option:
```
ELISP> (macroexpand '(map! (:localleader (:map cider-mode-map (:prefix ("h" . "help") "d" #'cider-find-doc)))))
(general-define-key :keymaps
'(cider-mode-map)
:infix "h" ""
(list :ignore t :which-key "help")
"d" #'cider-find-doc :states
'(normal visual motion insert)
:major-modes t :wk-full-keys nil …
```
=> Add descriptions for clojure-mode map

modules/config/default/+evil-bindings.el
this adds back the dismiss behavior of "magit popups" that was lost from the
magit-popup -> transient update
=> Add transient quit evil-bindings

modules/lang/haskell/packages.el
Looks like a leftover from https://github.com/hlissner/doom-emacs/issues/158
=> lang/haskell: only require intero when flag is set

modules/lang/rust/packages.el
In fact, Rust LSP already works :+1: :tada:  , this PR just disable racer when +lsp
=> Add LSP for Rust

modules/config/default/+evil-bindings.el
to make it more consistent with `ivy-minibuffer-map` rather than it being bound to `ivy-call-and-recenter` which is already mapped by `C-SPC`
=> Bind C-l to ivy-done in counsel-ag-map

modules/lang/cc/config.el, modules/lang/cc/packages.el
The `cquery` language server is unmaintained and simply broken at this point.  Instead, we should use `ccls` which is well maintained and works very nicely.
https://github.com/MaskRay/ccls
@MaskRay
=> Replace cquery with ccls for C/C++ LSP support

modules/completion/ivy/autoload/ivy.el, modules/completion/ivy/config.el, modules/config/default/+emacs-bindings.el
Added `+ivy/switch-workspace-buffer-other-window` so we have matching behaviour for `C-x b` and `C-x 4 b`.  Ideally this would be a replacement for `persp-switch-to-buffer-other-window`, but that doesn't exist.
Also added `switch-to-buffer-other-window` binding for `C-x 4 B` to mirror `switch-to-buffer` on `C-x B`.
Also added the other-window variants to the ivy-rich enhancement list.
=> Improved switch-to-buffer-other-window for ivy

modules/lang/haskell/+lsp.el, modules/lang/haskell/config.el, modules/lang/haskell/packages.el
A few things are left wanting in this mode which has been mentioned on discord.
One of the glaring things is that when company-lsp has snippets, the line is
incorrectly indented when chosing a completion, and you have to unindent the
line. 
The other glaring issue is eldoc only shows what the function will return,
which would be bearable if company worked with snippets!
Some more digging re: eldoc should get you looking at `lsp-eldoc-render-all` and `lsp-markup-display-all`
[The lsp server is hie](https://github.com/haskell/haskell-ide-engine/)
=> Add haskell +lsp

modules/lang/cc/autoload.el
Removes the call to the builtin `c-or-c++-mode` from doom's `+cc-c-c++-objc-mode`.  The built-in mode can't be customized and always falls back to `c-mode`, which is annoying if that's not actually correct.
=> Restore C/C++ default-header-file-mode support

modules/config/default/config.el
The default config module sets `c-tab-always-indent` to `nil` when smartparens are enabled, but it's not clear why (it seems to come from the earliest days of this project).  This setting is not consistent with other modes, or with "standard" emacs behaviour.  Note that `tab-always-indent` is set `t` in `core-editor.el`.
=> Remove C/C++ tab-always-indent override

modules/lang/cc/autoload.el, modules/lang/cc/config.el, modules/lang/cc/doctor.el
`rtags` supports custom binary names.
=> Use configured variables for rtags binary names

modules/lang/cc/autoload.el
The regex wasn't matching numbers; `FOO_BAR` would be pretty, but `FOO_BAR_1` would not.
=> Fix cc fontification for constants with numbers

modules/completion/ivy/autoload/ivy.el
Let-binding `ivy-use-virtual-buffers` is neater and more robust than the previous solution using some copy-pasta.  Calling the unwind routine will become important once counsel is patched to restore buffer-list.
See: https://github.com/abo-abo/swiper/pull/1954
=> Tidy up +ivy-buffer-preview functionality

modules/feature/workspaces/autoload/workspaces.el, modules/feature/workspaces/config.el
The `+workspaces|switch-to-project` routine was unnecessarily switching to dashboard when `+workspaces-on-switch-project-behavior` was `nil` (forcing to re-use the current workspace).
=> Only switch to dashboard when creating a new workspace

modules/completion/company/config.el
The latest company-box refactored how icons are configured.  This change maintains our icon configuration in the new order.
=> Fix latest company-box all-the-icons configuration

core/autoload/help.el, core/core-editor.el, modules/config/default/+emacs-bindings.el, modules/lang/emacs-lisp/autoload.el
Patch the apropos button types so they call helpful instead of the
built-in describe functions.  Also add some bindings to apropos-mode-map
so it behaves like other help modes.
Add `doom/describe-symbol` function, which shows documentation for
callable and variable symbols.  If a symbol is both a variable and a
callable, it dispatches to apropos.  This gives a better workflow than
`helpful-symbol`, which annoyingly prompts the user.
Remap `describe-symbol` to `doom/describe-symbol`, and update
`+emacs-lisp-lookup-documentation` to call it also.
=> Improvements to apropos and describe-symbol

modules/config/default/+emacs-bindings.el
This was simply hooked to `helpful-mode.el` instead of `helpful.el`.
=> Fix ace-link-help binding in helpful-mode

core/autoload/debug.el
Previously this would error due to undefined `doom-debug-on-error`
variable.  Now behaves like a minor-mode function to toggle both
`doom-debug-mode` and `debug-on-error`.
=> Fix doom/toggle-debug-mode

modules/lang/emacs-lisp/config.el, modules/lang/emacs-lisp/packages.el
This is an extremely useful package which adds little examples to the
help docs for a massive number of elisp functions.
https://github.com/xuchunyang/elisp-demos
=> Add elisp-demos to lang/emacs-lisp module

modules/lang/ruby/config.el
Some rspec-mode's functions can be used under any Ruby source files. So
adding some localleader bindings for them.
Signed-off-by: Huy Duong <huy.duong@employmenthero.com>
=> Bind some rspec functions for ruby and enh-ruby mode

core/core-editor.el
We use `helpful--read-symbol` which isn't already autoloaded.
=> Fix autoloading helpful for doom/describe-symbol

modules/editor/multiple-cursors/config.el
The package is split in a way that `multiple-cursors.el` is normally not
required when autoloading from commands; `multiple-cursors-core.el` is
always loaded.
Unfortunately the `mc/list-file` location is still not being set
properly, a fix has been submitted: magnars/multiple-cursors.el#355
=> Fix loading of multiple-cursors configuration

modules/lang/ruby/config.el
Last PR has wiped out basic bindings in rspec-mode.
This PR re-adds theme.
=> Re-add missing bindings for rspec-mode

modules/ui/doom-dashboard/config.el
Since bb3f027c moved `projectile-mode` into `doom-init-ui-hook`,
projectile was getting initialized after the dashboard.  This means for
non-evil users, the `C-c p p` binding is not shown, because it's not yet
loaded.
=> Initialize dashboard later in window-setup-hook

modules/ui/doom-dashboard/config.el
This needs to be appended so it runs after `project-mode`.
=> Initialize dashboard later on doom-init-ui-hook

modules/config/default/+evil-bindings.el, modules/editor/multiple-cursors/config.el
`evil-mc-undo-last-added-cursor` was introduced upstsream and bound to "gru" by
default, with the `evil-mc-undo-all-cursors` binding shifted to "grq"
Bar cursors don't display well by default on Mac and Windows, see
https://github.com/gabesoft/evil-mc/issues/49
=> Updates to evil-mc config

core/autoload/buffers.el
This was erroring when run inside a popup (eg. `M-x ielm` `C-x k`) due
to a missing check for `window-live-p`.  We don't need to do anything if
the window has already gone away.
The real vs unreal check was backwards; we should only try
`previous-buffer` if the current buffer is *not* real.
=> Fixes for doom/kill-this-buffer-in-all-windows

modules/completion/ivy/autoload/ivy.el
Upstream updated `counsel--switch-buffer-update-fn` to check
`ivy--virtual-buffers` instead of `ivy-use-virtual-buffers`.
=> Fix +ivy-buffer-preview no longer ignoring virtuals

core/autoload/ui.el, modules/config/default/+evil-bindings.el, modules/lang/org/autoload/org-present.el
The default behavior for the windows key bindings is to *enlargen* instead of replacing all windows in the given direction. For me it sounds more sensible to do replacement but if you don't agree it's fine with me. I can keep this functionality in my private separate configuration.
I copied the maximize functions from Spacemacs. Apparently, they were copied from a blog post that no longer exists.
The second commit just adds the missing register key mapping for helm.
=> Maximize window vertically/horizontally

modules/feature/workspaces/autoload/workspaces.el
The `current-buffer` wasn't being updated after switching workspaces and
was therefore failing the `doom-buffer-frame-predicate` check. As a result
deleting a workspace resulted in the previous window's buffer being 
replaced with the doom dashboard.
Replacing it with `window-buffer` seems to target the intended buffer and 
prevents this from occuring.
=> Don't open `doom-fallback-buffer` on del workspace

core/core-projects.el, core/doctor.el
Binary name is not `fd` in some distribution eg, it is `fdfind` in debian
=> Use variable for `fd-find` binary name

modules/feature/evil/config.el
`jk` doesn't work as expected in `vterm`. 
Do I need to also check for `vterm` feature flag?
=> Add vterm-mode to evil-escape-excluded-major-modes

core/core-keybinds.el
Fixes a bug where the regexp for which-key leader prefixes aren't escaped. This it makes it possible to use regex special characters leader keys, such as `C-\`.
=> Escape key regexps when building which-key leader prefix

modules/app/calendar/autoload.el
This PR addresses issue #1190 regarding calfw grid size when opening the calendar with `=calendar` from the calendar module.
* Calfw calendar displays with an incorrect grid size
* Caused by [the new calendar workspace](https://github.com/hlissner/doom-emacs/blob/be6efd8dbff18c29953c4af8bfef88b8091added/modules/app/calendar/autoload.el#L18) displaying the doom splash screen with window margins
* Calfw [uses the selected window](https://github.com/kiwanami/emacs-calfw/blob/03abce97620a4a7f7ec5f911e669da9031ab9088/calfw.el#L784) to determine the size of the calendar grid
* Selects the scratch buffer before creating the calendar
* Calfw generates the calendar grid based off of the resulting correct window margins
* Calendar displays correctly with both workspace feature enabled and disabled …
=> Create calfw calendar with correct grid width

modules/tools/flyspell/config.el
* Previously, a user could not choose which spell checker to use.
Instead, the first one found was used.
* This PR adds the flags `+aspell` and `+hunspell` which allow a user to
choose which spellchcker to use (even if both are installed).
* Report an error if spell checking is enabled but no spell checker
is found.
=> Choose which spell checker flyspell will use

modules/lang/common-lisp/config.el
The Sly documentation which these were originally based off of is out of
date, causing some of the bindings to have no longer defined functions.
=> Changed some wrong common-lisp bindings

modules/completion/ivy/config.el
Upstream recently added `swiper-isearch`, which is a more isearch-like variant of `swiper`.  Like swiper, it shouldn't fuzzy-match.
=> Disable fuzzy-matching for swiper-isearch

modules/lang/go/README.org
Updated the Go README to correct the install link for gore.
See: https://github.com/motemen/gore#installation
=> Update Go module README

modules/lang/clojure/config.el
This PR fixes #1293 by biding `SPC m r c` to `'cider-find-and-clear-repl-output`.
Also, it adds some maps to `cider-repl` major mode that are similar to maps already available in `SPC m r`.
=> Cider map fixes

modules/completion/company/README.org
Just documenting `+tng` flag that I saw looking at `company/config.el` code and it wasn't documented before.
=> Document company +tng flag

init.example.el, modules/lang/org/+habit.el, modules/lang/org/config.el
Added a simple way to make the org-habit consistency graphs align to the
right margin as well as being responsive to the width of the window.
This is added as a feature to the org module.
=> feat: org-habit

modules/lang/javascript/config.el
Updated the format mapping for the Javascript module to use the correctly named tide-format.
See: https://github.com/ananthakumaran/tide#commands
=> Correct Javascript module tide format mapping

modules/lang/clojure/config.el
Fixes issue #1357
Previously references lookup handler defined in `clj-refactor` package definition overwrote definition and documentation lookup handlers defined in `cider` package definition. To avoid this I've assigned handlers to their backing minor modes instead of the major Clojure mode.
=> Set Clojure lookup handlers for specific minor modes to avoid overwriting

modules/lang/rust/doctor.el
There is no `rust` binary in Rust, but a `rustc` one for its compiler.
=> fix rustc detection

modules/completion/ivy/autoload/ivy.el, modules/completion/ivy/config.el
Corrects the ivy-switch-buffer transformer to use buffer icons (not file icons), and fixes alignment issues in the icon display.
=> Fixes for ivy-switch-buffer icons

modules/config/default/+emacs-bindings.el
Update treemacs open command toggle `+treemacs/toggle`
`+treemacs/open` is no longer defined.
=> Update treemacs open command

modules/ui/popup/README.org
Not sure what I am doing, but I cannot run the example with the `.` and the example on the previous line also use `:size` without a `.` before the size value.
=> One dot in wrong place

modules/lang/org/config.el
This PR adds some localleader bindings to `org-agenda-mode-map` that reflect those of `org-mode-map`. I only included the bindings that are useful to manipulate meta-information (schedule, deadline, refine, and todo state).
=> Add localleader bindings to org-agenda

init.example.el
No need for a `do` when you have `{}`.
=> Fix snarky ruby in example init.example.el

core/core-editor.el
As per request when submitting `better-jumper` to MELPA, I've added a minor mode. This pull request enables `better-jumper-mode` when the package is loaded.
=> Enable `better-jumper-mode` when loaded

modules/completion/ivy/autoload/ivy.el
Fixes #1406
Yes this is a dubious hack, but it works, and ivy-resume still works.  Not sure that there's anything else which could be affected.
=> Fix ivy-switch-buffer virtual buffer support

modules/lang/python/config.el, modules/lang/python/packages.el
Added pyimport support.
I figured that it just uses modules imported in currently opened python files, and don't looks for installed modules.
Keybindings :
- Import missing module via `<LocalLeader> i m`
- Remove unused imports via `<LocalLeader> r u`
=> Added pyimport support

modules/completion/company/config.el, modules/completion/ivy/README.org, modules/completion/ivy/config.el, modules/completion/ivy/packages.el
This adds the `+prescient` flag to enable the `ivy-prescient` package for filtering and sorting of ivy completions.  When used with the `+fuzzy` flag, uses prescient's fuzzy completion instead of `flx`.
Also increased the value of `ivy-flx-limit` from the default 200 to 10000.  This is a performance vs utility tradeoff, but the impact is minimal in my testing.
=> Add +prescient option for :completion ivy

modules/tools/magit/config.el
https://github.com/alphapapa/magit-todos/tree/3c59aa03b217b55b1baa0e88470e10996aaeea9b#12
Since `magit-todos` 1.2 `magit-todos-require-colon` has been removed. The default value of `magit-todos-keyword-suffix` is `"\\(?:([^)]+)\\)?:"` which require a colon as suffix to the keywords.
=> magit-todos 1.2 removed magit-todos-require-colon

init.example.el, modules/editor/objed/README.org, modules/editor/objed/config.el, modules/editor/objed/packages.el, modules/ui/modeline/config.el
Integrates `objed` with Doom Emacs to provide text-object manipulation for non-evil users.
See https://github.com/clemera/objed
=> Add :editor objed module

modules/tools/ein/README.org
Small change to README.org with an example of how to bind ein hydra. The code is based on hlissner's suggestion when I asked about this on Discord. Might be useful for other users setting up ein who are not too familiar with hydras (I didn't know you have to append `/body` to hydra definition to actually call it).
=> Added example of how to activate +ein-hydra

modules/config/default/+emacs-bindings.el, modules/editor/objed/README.org, modules/editor/objed/config.el
Setting the flag `+manual` of the `objed` module makes the user responsible for calling `objed-activate` when needed. The binding `M-SPC` is set in the default Emacs bindings.
Fix small typo.
Update `objed` README file.
=> objed: add a manual activation flag

core/core-projects.el
Prevent `projectile-find-file` to be littered with escape codes when the
environment variable LS_COLORS is set.
=> projectile: fd never use colors

modules/tools/magit/autoload.el
magit-clone function has changed signature to work with transient.
So using the new magit-clone-regular instead.
Signed-off-by: Huy Duong <huy.duong@employmenthero.com>
=> Fix magit-clone error

modules/completion/ivy/config.el
`ivy-postframe` go updated and became a minor mode. It broke doom's setup in it's way.
=> completion/ivy: ivy-posframe upstream update

modules/editor/format/autoload/format.el, modules/editor/format/autoload/settings.el, modules/editor/format/config.el, modules/editor/format/test/test-format.el
This should fix [1470](https://github.com/hlissner/doom-emacs/issues/1470)
I'm completely new to emacs and have no clue what I'm doing, so be warned and bear with me if this is is all bonkers ;)
=> fix: format-all upstream definitions

modules/lang/scala/config.el, modules/lang/scala/packages.el
lsp-scala is deprecated. It's now bundled in lsp-mode as lsp-metals.
=> Remove lsp-scala, as lsp-metals is bundled in lsp-mode

modules/lang/go/config.el
This is a potential fix for https://github.com/hlissner/doom-emacs/issues/1521
=> lang/go: prioritize lsp over guru

modules/tools/ansible/config.el
A simple fix for upstream renaming all their functions.
=> ansible: fix upstream changing function names

init.example.el, modules/lang/scheme/README.org, modules/lang/scheme/autoload.el, modules/lang/scheme/config.el, modules/lang/scheme/packages.el
Adds a simple scheme module with geiser backend, supports all major scheme implementations except racket, which I have left out considering racket has its own module that will probably serve users better.
=> Add scheme module

core/core-lib.el
``` emacs-lisp
(lambda!! #'avy-goto-char-timer t)
```
Before:
``` emacs-lisp
(lambda nil
(interactive)
(let ((current-prefix-arg t))
(call-interactively avy-goto-char-timer)))
```
After:
``` emacs-lisp
(lambda nil
(interactive)
(let ((current-prefix-arg t))
(call-interactively
(function avy-goto-char-timer))))
```
=> Fix quoting of command in λ!!

modules/tools/lsp/config.el
When opening a buffer, company-mode is not activated and therefore there's no completion. this was introduced in 149b2617 and now fixes the mistake
=> tools/lsp: cache company candidates automagically

modules/lang/elixir/config.el, modules/tools/lsp/README.org
- Document Elixir with LSP via elixir-ls
- Add `+lsp` flag to `:lang elixir`
Goes with #1510.
=> Add support for Elixir LSP via elixir-ls

modules/lang/racket/config.el
Add a lookup handler for racket-mode to enable `SPC c d` to jump to definition (`, g d` is already bound to `racket-visit-definition`, but not the generic Jump to definition).
This is a bit buggy if you don't already have a Racket REPL open, which `racket-visit-definition` seems to rely on. That said, racket-mode will open a basic REPL even if you have errors in the buffer and many things will still work.
=> lang/racket: set lookup handler to find definition

modules/lang/rust/packages.el
Removing the dependency for flycheck-rust since it is no longer used and causes problems when required without being set up.
=> Remove flycheck-rust since it is no longer used.

modules/completion/company/autoload.el
If the same line is present more than once in the buffer, it will be
offered more than once as a candidate. This commit deletes duplicate
lines from the completion list.
=> Uniquify completion candidates of whole lines

modules/lang/python/config.el
For several years, the default location for a miniconda install has been `~/miniconda3` (`~/miniconda2` if using the python 2 version). This PR adds this path to the list considered by the conda package.
=> Update list of lang/python considered conda homes

modules/lang/racket/config.el
`racket-smart-open-bracket-enable` has been replaced by a function that inserts the right type of bracket (see https://github.com/greghendershott/racket-mode/commit/669275b3a620a940ce1c52610909577e94abf55f), which we need to bind to [ in insert mode.
This feature used to work, then Issue #1452 was filed to request it be configurable, then it broke, and now I'm fixing it. This indicates that maybe instead of just fixing it we should make it configurable, or users should do this customization themselves and this PR should just stop setting the obsolete `racket-smart-open-bracket-enable` flag. Note that DrRacket does not enable this setting by default.
=> lang/racket: Fix smart open bracket insertion

core/core-packages.el
There was a format command but it was in a literal string.
=> Fix :fetcher warning to include package name

modules/lang/clojure/config.el
Originally `cider-jack-in-clojurescript` but said command was deprecated.
Copy of https://github.com/hlissner/doom-emacs/pull/1595 because history happened, and I don't know how to fix it. 😅
=> rebind "\"" to cider-jack-in-cljs

modules/ui/pretty-code/+iosevka.el
The ligatures are defined for the fontset `#Xe100 -> #Xe1cc` but the hook function did not use that complete space for the ligatures
=> Use +pretty-code-iosevka-font-name on complete set

modules/lang/clojure/config.el
There are quite a few useful cider functions that are not mapped in doom's clojure module. The keys chosen for running tests match the keys used in the default cider keybindings.
=> Add more cider functions to the clojure keymap

modules/lang/plantuml/autoload.el
This is the one they currently redirect to.
Fixes #1637.
=> lang/plantuml: change mirror for +plantuml/install

core/core-lib.el
Self-explanatory: make the docstring agree with the macro definition.
=> Correct argument name in `defadvice!' docstring

modules/app/write/config.el
On macos, the libexec directory for languagetool, as installed by brew,
lives in a version directory. To find the jar, we need to increase the
search depth, since the version directory will change with every version.
Example of brew-installed languagetool:
```bash
$ tree -L 2 /usr/local/Cellar/languagetool
=>
/usr/local/Cellar/languagetool
└── 4.6
├── CHANGES.md
├── CHANGES.txt
├── COPYING.txt
├── INSTALL_RECEIPT.json
├── README.md
├── bin
└── libexec
```
=> fix: bump languagetool jar search depth on macos

core/autoload/packages.el
Because it's not loaded for some reason.
Also, `require` is not a big problem IMO: if you run this interactively, the
`require` cost probably doesn't matter much already.
Fixes #1618.
=> Require straight.el in doom/reload-packages

modules/config/default/+evil-bindings.el
Instead of relying on the optional ":ui workspaces" feature, the
built-in `evil-window-delete` is used and
`+workspace/close-window-or-workspace` is only used if ":ui workspaces" is
enabled.
Fixes https://github.com/hlissner/doom-emacs/issues/1640.
=> Fix evil-window "c" binding

modules/lang/clojure/config.el, modules/lang/web/+html.el
Salut!
I added some bindings to _Clojure_ and _Web_ modules.
**Clojure**
- map the bindings to _clojure-map-mode_ AND _clojurescript-mode-map_
- modify _cider-jack-in_ to _cider-jack-in-clj_
- add bindings for _cider-connect-*_
- add binding for _cider-enlighten-mode_
- add binding for _cider-repl-return_
**Web**
- add prefix descriptions
=> Bindings for Clojure and Web modules

modules/ui/pretty-code/+hasklig.el, modules/ui/pretty-code/config.el
Took the list of symbols from
https://github.com/minad/hasklig-mode/blob/master/hasklig-mode.el ,
only rudimentary testings has been done on this (meaning I open some `cpp` files and checked `<<` and `::`)
=> Add Hasklig pretty-code configuration

modules/lang/php/packages.el
Previously this was included automatically with phpactor, but now the
phpactor package call is only pulling in phpactor.el and its
requirements.
So this is necessary for proper auto-completion.
=> Added company-phpactor to packages

core/autoload/fonts.el
There is a small spelling mistake in `fonts.el`. This is just a small PR to fix it.
=> fix small spelling mistake in fonts.el

modules/lang/csharp/config.el
*TL;DR* Found that the unit test keybinds are using broken keybinds that don't work
anymore. Decided to fix them, along with any keybinds that seem to not work.
I personally found this to actually hinder my workflow, and added my
own keybinds to use the updated functions. However, the dead keybinds that don't
work anymore would always come up on which-key, almost trying to ridicule me for
my laziness in not fixing this issue myself. So here I am to fix it!
Not much of a big change so I doubt any real review is needed. Each commit has
decent information (well I suppose anyway).
=> Fixing up csharp mode's keybinds (mostly unit-test ones)

modules/lang/cc/autoload.el
It seems that during the renaming hooks to a new convention one call in the cc lang feature autoloads remained unchanged which causes `Symbol's function is void: +cc|irony-init-compile-options`. This PR fixes that.
=> Call renamed hook in the +cc/reload-compile-db autoload

core/cli/upgrade.el
Since there is a lot of logic in `bin/doom upgrade` than just running
two commands, I thought we should also add a timeout flag just like
`update` has.
I was having lots of timeout issues so I found this flag helpful.
=> cli/upgrade: add timeout flag

modules/lang/agda/config.el, modules/lang/agda/doctor.el, modules/lang/agda/packages.el
We can fetch the mode directly from straight. There's no need to rely on
having this .el file installed for us. Now agda's el files can be edited
directly like all other emacs packages.
=> Use straight for agda

modules/lang/org/config.el
While point is in a babel src block, do not autoexpand emphasis markers.
Without this change, editing code in babel src blocks is cumbersome: every time you type `*` or `=` (among other characters), a pair is inserted that then needs to be manually deleted. This change checks if point is in a source block to decide if emphasis markers are duplicated.
=> lang/org: smarter smartparens in org src blocks

modules/input/chinese/config.el, modules/input/japanese/config.el
Previously submitted a fix in issues, which is the processing of \<br /\>\n in Chinese and English mixed text. Later, I found that this would be invalid for the case of \<br /\>\n between pure English, so I made the following changes: first delete only \<br /\>, then \n between multi-byte text Delete, so you can adapt to all situations.
=> Fix defadvice bug of Chinese and Japanese org-html-paragraph

modules/lang/sh/config.el
Removed duplicate "cat" and added missing "ln", which IMO is common enough to be included.
=> Add ln to +sh-builtin-keywords

modules/config/default/+emacs-bindings.el, modules/term/eshell/config.el
Hi @hlissner. I finally have a PR for you to fix some of the outstanding issues that the default emacs bindings had. There were some bindings that would shadow many emacs things.
I've also added missing emacs bindings for `eshell`. Could you take a look at these? I'm not sure if I have to repeat the binding or if there is a way to tell `map!` to use something for vi and emacs at the same time (i.e., using `:e`?).
=> bindings: fix emacs bindings and add more

modules/lang/go/README.org, modules/lang/go/config.el, modules/lang/go/packages.el
Hello. This pull request add the package [go-add-tags](https://github.com/syohex/emacs-go-add-tags) to :lang go module.
Here is a screencast of what it does (taken from repository):
https://github.com/syohex/emacs-go-add-tags/blob/master/image/go-add-tags.gif
=> Add go-add-tags for go-mode

modules/lang/plantuml/config.el
Sorry for my negligence, the whitespace at the beginning of the regular expression should be [[:blank:]], and I mistakenly wrote \\w .
=> Fix a regexp bug of (defadvice! +plantuml--fix-atstart-in-org-src-blocks-a ...)

core/autoload/themes.el
We need to unwrap the outer list returned by the inner calls `doom--custom-theme-set-face`.
Also need to flatten the face with the rest of the spec list so that:
```
((foo bar baz) :weight bold)
```
Is equivalent to:
```
(foo :weight bold)
(bar :weight bold)
(baz :weight bold)
```
Instead of:
```
(foo (:weight bold))
(bar (:weight bold))
(baz (:weight bold))
```
=> Fix the multi-face form of custom-set-faces!

modules/ui/hydra/config.el
The variable `lv-use-seperator` is not defined anywhere, but I found the variable `lv-use-separator` in the `lv.el` file, which is only one letter apart, so I guess the variable name is wrong.
=> Fixes wrong variable name: lv-use-seperator to lv-use-separator

modules/lang/rust/config.el
Fix override/around typo.
Stubbing package-installed-p to return true is sufficient, rustic happily activates the configured backend (lsp), which is then autoloaded properly.
=> Fix package-installed-p hack for rustic

modules/lang/web/+html.el
With the merge of https://github.com/fxbois/web-mode/pull/1074, web-mode now supports Svelte templates. This change activates web mode when opening a `.svelte` file.
=> Add .svelte to web-mode

modules/completion/ivy/config.el
This is the more sensible option as locate isn't configured by default
and spotlight is turned on by default.
=> Use mdfind for counsel-locate on a Mac

core/cli/upgrade.el
----
A small fix for `doom upgrade -t TIMEOUT` that was recently broken by the new
code for `doom refresh --thread THREADS`.
=> cli: fix wrong argument and add docs

modules/tools/macos/autoload.el
It should be mdfind since spot light is on by default.
I think you could still improve things further by not making users that prefer `locate` on a mac to override two options, but this is better already.
=> Set locate-command in tools macos

modules/lang/latex/+viewers.el
Previously, the last viewer set in `+latex-viewers` would take
precedence. The list is now reversed before applying changes so that the
first set has precedence.
The wrong hook variable was used to revert view buffers after compilation.
=> lang/latex: +pdf-viewers ordering and hook type-o

modules/lang/plantuml/autoload.el
Now this should redirect to the auto-selected mirror.
Related: #1637 #1639
=> lang/plantuml: fix jar download path (again)

modules/lang/rust/README.org
Trying to install with cargo fails with the following error:
```
Caused by:
failed to run custom build command for `clippy v0.0.302`
Caused by:
process didn't exit successfully: `/var/folders/66/180ynjt55z74l338gh0stq0c0000gn/T/cargo-installkNqJBB/release/build/clippy-bcde765a4c9acf93/build-script-build` (exit code: 1)
--- stderr
error: Clippy is no longer available via crates.io
help: please run `rustup component add clippy-preview` instead
```
Just a tiny doc update
=> Fix install command for clippy, uses rustup

core/core.el
When x-window commands emacs to quit, emacs saves a session in `.emacs.d/session.*` by default. There is no easy way to change the location of this session file. This PR overwrites the function responsible for creating the session file name `emacs-session-filename`. The new function sets the session file to reside in `doom-cache-dir`/sessions.
=> doom/core: avoid the litter of session.* files

modules/lang/emacs-lisp/autoload.el, modules/lang/emacs-lisp/config.el
`, d f` - turn on debugging for defun
`, d F` - turn off debugging for defun
=> [emacs lisp] Add bindings for debugging defuns

modules/ui/hydra/config.el
`+hydra/window-nav` uses functions from `hydra-examples.el` but the file
is never loaded. Adding this does not actually define any hydras (this
would require `hydra-examples-verbatim` to be `t`), it just load the
utility functions to make the hydras defined in doom work.
=> Load hydra examples without using example hydras.

modules/lang/org/config.el, modules/lang/org/packages.el
As the title states, commands from this package are bound, but the package is not installed. Let me know if I should fix anything.
=> Add helm-org (bound but not installed).

modules/completion/ivy/README.org, modules/email/mu4e/README.org, modules/lang/cc/README.org, modules/lang/elixir/README.org, modules/lang/go/README.org, modules/lang/haskell/README.org, modules/lang/javascript/README.org, modules/lang/nim/README.org, modules/lang/php/README.org
These instructions were tested on openSUSE Tumbleweed and openSUSE Leap
15.1. There are some modules left that are not documented yet, but this
already improves the sitution for common openSUSE users.
=> Add openSUSE prerequisite instructions

modules/lang/latex/README.org, modules/lang/latex/config.el
The user documentation of +latex-viewers did not keep up with changes to
the variable. This commit realigns its documentation.
=> Update documentation of recognized latex viewers

modules/lang/scala/config.el, modules/lang/scala/doctor.el, modules/lang/scala/packages.el
Ensime just went missing from everywhere. On ensime.github.io, they encourage to switch to [metals](https://scalameta.org/metals/) - a new Scala language server [already supported by `lsp-mode`](https://github.com/emacs-lsp/lsp-mode#supported-languages).
This commit:
- removes `ensime` completely
- adds a `doctor.el` to check for `metals-emacs` binary
[Original issue](https://discordapp.com/channels/406534637242810369/406554085794381833/628809956103028747)
[Metals](https://scalameta.org/metals/docs/editors/emacs.html)
Closes #1846.
=> lang/scala: replace ensime with metals

modules/ui/doom/config.el
This is need to call `solaire-mode-swap-bg` if the theme is `doom-solarized-dark`.
=> Add doom-solarized-dark to +doom-solaire-themes

modules/config/default/+evil-bindings.el
Add missing bindings when flycheck module is not active.
- `SPC c x` binds to `flymake-show-diagnostics-buffer` if `flycheck` is inactive
- `SPC t f` binds to `toggle flymake` if `flycheck` is inactive
I saw there are a bunch of specific `flycheck-mode-map` bindings, and there are probably the same bindings in flymake, I'll probably add them too.
=> Add missing conditionals for flymake/flycheck bindings

modules/lang/python/README.org
Quick fix to the README for python language module to correct the required python package for `pyimport.el` to `pyflakes` as mentioned in its own [README](https://github.com/Wilfred/pyimport).
=> Correct a requirement in README.org

init.example.el, modules/lang/org/README.org, modules/lang/org/config.el, modules/lang/org/contrib/+hugo.el, modules/lang/org/packages.el
add support for [ox-hugo](https://github.com/kaushalmodi/ox-hugo) to the org module. The change is straightforward as most of the module configuration is done in the org-files themselves.
=> ox-hugo for (:lang org)

modules/lang/python/autoload/pyenv.el, modules/lang/python/config.el
Hi,
This should solve #736 . The pupose is to set correct pyenv version as stated in leading `.python-version` file.
I'm not an elisp guru. I'm thinking of the following improvements:
- ~~set pyenv-version only on python-mode buffers~~
- ~~saving .python-version in some projectile per-project register ?~~
Any help appreciated.
=> Set python version from .python-version file

core/core-editor.el, core/packages.el
Increase `undo-limit`, `undo-strong-limit` and `undo-outer-limit` by a factor of ten, which should prevent emacs from prematurely truncating the undo history and corrupting the tree.
Restore `undo-tree-auto-save-history` which was disabled to avoid exacerbating the undo history truncation.
Change the `undo-tree` recipe to grab the latest version from the maintainer's repostiory instead of the outdated ELPA version.
Restore `undo-tree-enable-undo-in-region` which should be fixed in the latest version of `undo-tree`.
**WARNING:** There may still be a problem with `undo-tree-auto-save-history` causing a stack overflow on startup while deserializing the saved history.  This needs testing!  If you decide to test it, be prepared for undo history corruption!
=> [WIP] Experimental fixes for undo-tree

modules/ui/doom/README.org
Reformats ui/doom/README.org to match __doom-readme template as per #1166
=> Reformats ui/doom/README.org to match __doom-readme template

modules/lang/org/config.el
This commit adds keybindings for exporting org to HTML, analogous to those that are defined for markdown and reveal.js.
=> Add keybindings for org-html-export

modules/completion/company/config.el, modules/lang/org/config.el
Added regex for company-files to recognize file links in org-mode.
I can move changing `company-files-regexps` if there is better place to modify it.
=> added company-files support for file links in org mode

modules/config/default/+emacs-bindings.el
Just fixes comments for IRC and mu4e bindings
=> Fixes comments for M and I in +emacs-bindings.el

bin/doom-doctor, core/autoload/debug.el, core/autoload/help.el, core/autoload/packages.el
When no regular expression is present, it's faster and simpler to use
search-forward
=> re-search-forward to search-forward when no re

core/core-projects.el
This function isn't autoloaded so we should include it in the list of
commands like some other projectile functions.
=> Fix uses of projectile-locate-dominating-file

modules/lang/ocaml/config.el
These files are generated and hence this detection fails if they haven't
been generated yet. Merlin is essential for basically all OCaml
development so there's no need for this extra check.
=> Remove detection for .merlin files

modules/lang/ocaml/config.el
This binding should be available whenever tuareg is loaded. Previously,
it would loaded only after merlin.
=> Fix tuareg-find-alternate-file binding

init.example.el, modules/config/default/+evil-bindings.el, modules/lang/org/README.org, modules/lang/org/config.el, modules/lang/org/contrib/pomodoro.el, modules/lang/org/packages.el
This is a resurrection & review of #1484.
Adds `SPC t t` binding to toggle `org-pomodoro` (mnemonic "toggle timer").
Sends notifications using growl or libnotify if available.
=> Add support for org-pomodoro

modules/lang/clojure/autoload.el
Before this PR, opening a REPL when in clojurescript-mode would result in an
infinite loop. With this PR, the REPL is started correctly.
=> lang/clojure: start clojurescript repl correctly

modules/config/default/+evil-bindings.el, modules/editor/multiple-cursors/config.el
Two useful functions added for evil-mc
`evil-mc-make-cursor-in-visual-selection-beg`
Create cursors at the beginning of every visually selected line.
`evil-mc-make-cursor-in-visual-selection-end`
Create cursors at the end of every visually selected line.
=> Add: evil bindings for 2 evil-mc functions

modules/editor/word-wrap/README.org, modules/editor/word-wrap/autoload.el, modules/editor/word-wrap/config.el
Adds `+word-wrap-text-modes`, a list of modes which shouldn't get any extra indentation. This is used for text and markdown modes, which should just indent to the parent depth.
Adds `+word-wrap-visual-modes`, a list of modes which shouldn't enable `adaptive-wrap-prefix-mode`. This is used to fix the prefix indentation in `org-mode`, which provides its own implementation.
Tweaks the indent behaviour to treat strings the same as comments so they don't receive additional indentation.
=> Improve +word-wrap in non-code buffers

modules/lang/emacs-lisp/config.el
Taken from http://www.modernemacs.com/post/comint-highlighting/
Currently this uses `dash`, but that can be removed if the PR is approved.
=> Add syntax highlighting to ielm buffers

modules/lang/python/README.org, modules/lang/python/config.el, modules/lang/python/packages.el
Enable optional cython support in Python module
=> Add cython-specific flag and packages

modules/lang/markdown/README.org, modules/lang/markdown/config.el, modules/lang/markdown/doctor.el, modules/lang/markdown/packages.el
This adds support for [grip-mode](https://github.com/seagle0128/grip-mode) through `+grip`.
Also, fixing up some stale documentation for markdown here.
Happy to make any changes!
=> Add grip-mode for live markdown previews

modules/lang/coq/config.el
These send input to coq too agressively. It's often the case that this
causes delays in coq.
=> [coq] disable electric proof terminators

modules/config/default/+evil-bindings.el
Put `save-buffer` back on `SPC f s` to save without prompt, and add `write-file` as `SPC f S` for saving with prompt for filename.
Fixes #1923
=> Restore save file binding on SPC f s

modules/lang/go/README.org, modules/lang/go/config.el, modules/lang/go/doctor.el, modules/lang/go/packages.el
Hello. This pull request add the package [go-gen-test](https://github.com/s-kostyaev/go-gen-test) to :lang go module.
I customized doom config for this feature, but I thought it would be more useful if it was supported by default, so I created this PR.
=> Add support for go-gen-test for go-mode

modules/term/eshell/autoload/company.el
This function is called from the eshell module
=> autoload company-pcomplete-available

modules/lang/latex/config.el
Every time auctex does style update, it somehow messes up rainbow-delimiters-mode. See also https://tex.stackexchange.com/questions/272320/emacs-auctex-preserve-highlights-from-other-modes-after-apply-style-hooks
This pull request fixes rainbow-delimiters-mode, and also fixes a typo introduced in my previous pull request :/
=> lang/latex: fix rainbow-delimiters-mode

modules/lang/ocaml/packages.el
merlin, merlin-eldoc, merlin-flycheck are all unnecessary when lsp is
turned on
=> [ocaml] disable more features with lsp

modules/ui/modeline/config.el
The advice was pulling in an `icon-name` in the args list but the whole body considers `args` as containing everything. So now `args` contains everything.
=> ui/modeline: fix ligature advice for hlissner#1216

modules/lang/org/doctor.el
`doom doctor` should catch `gnuplot` not being installed when the `+gnuplot` feature is enabled.
=> [org +gnuplot] Warn if gnuplot is not installed

modules/ui/doom-dashboard/config.el
I keep forgetting that there's a searchable FAQ, and I thought that having it on the dashboard was the best place : first screen someone sees when opening Doom. Especially until the user manual is not done, I discovered that while adding the menu item
Feel free to change the wording/icon if you think something else should be used
=> Add an FAQ action to doom-dashboard

modules/email/notmuch/autoload.el, modules/email/notmuch/config.el
This PR adds various features to the notmuch module
- Filter read messages in notmuch show (by folding them automatically)
- Refresh all notmuch buffers after sync (via process sentinel)
- Support custom sync commands (introduces an additional defvar)
- Add command to select From email prior to composing via ivy
I wasn't sure if you prefer separate diff or one big diff. Please let me know if you want me to split this into separate PRs.
=> Improvements to notmuch module

modules/lang/org/README.org
`+org-cycle-only-current-subtree-h` is being added to hook in `evil-org`  config, not in `org`'s one.
Also snippet wouldn't work with `local` flag (last arg of  `remove-hook`).
=> doc - fix instruction on removing +org-cycle-only-current-subtree-h

modules/ui/popup/config.el
[C-x m] should not appear in a popup.
In fact, I think this rule should be applied to all `message-mode` buffers.
=> [popup] ignore send mail buffers

modules/lang/ruby/config.el
This PR add a hook that auto switches to inf-ruby when the compilation buffer matches the `inf-ruby-breakpoint-pattern`.
=> lang/ruby: auto enter inf-ruby when breakpoint detected

core/autoload/help.el
Currently the generated lambda would place an unquoted list in the value position of `cl-destructuring-bind`, causing it to be interpreted as a function call.
=> Fix buttons in doom/help-packages

docs/index.org
This un-hard-codes a few links I found in the docs. Most of those would work fine in most setups but were hard coded to `~/.emacs.d/...` so I changed them to `..`
=> [docs] correct some links

docs/api.org
This PR adds a snippet on docs/api.org page regarding cursor-shape-change under terminal Emacs, as referenced in #1994.
=> Add terminal-cursor-change snippet.

modules/editor/evil/README.org
This addresses minor typos in the evil module's README.
=> [evil] correct typos in readme

README.md, docs/contributing.org, docs/faq.org, docs/getting_started.org, init.example.el
Wed Oct 30 14:43:09 GMT 2019
This PR corrects some typos throughout the project - mainly in the `docs` directory.
There was one instance where the British spelling was used: `recognised`.  This was corrected to North American spelling: `recognized`.
Also, `MacOS` was changed to `macOS`.
Most of the others were for commonly misspelled words.  (Note - this was not corrected in init.example.el.) ;-)
=> Correct some typos

modules/lang/clojure/config.el
When using `cider-connect` to an external server, this function would throw
an exception because nrepl-server-buffer is nil
=> [clojure] Check for nrepl-server-buffer in advice

docs/getting_started.org
Fix formatting for `export PATH="$HOME/.emacs.d/bin:$PATH"` to include the right type of quotes.
=> fix markdown formatting

modules/config/default/+evil-bindings.el, modules/config/default/config.el
`SPC w m` did not have a prefix.
~~Neither did `SPC h d` and `SPC h r`~~
~~I used a variable to define the help key to avoid hard-coding to `h`. I don't know if it's the smartest choice.~~
~~(I also don't really know why the help-map is not mapped with `map!` but I left it like that)~~
=> [config] which-key descriptions for prefixes

docs/getting_started.org
A couple of the links to the Customize section were 404-ing, so this PR attempts to address those.
Also, there was a reference to lispyville.el in the "Installing packages from external sources" which I found confusing.  Perhaps what it used to refer to was removed at some point?  The PR contains a suggestion for alternative text.
=> Update Customize section links and a bit

docs/getting_started.org
The docs already mention in in the load path, but I found that to be a little bit hidden. I think it makes sense to explictly mention it when explaining how to write your own modules?
=> Mention $DOOMDIR/modules explictly in docs

modules/lang/org/config.el
Invoking the org-attach commands under the SPC-m-a prefix resulted in errors. It seems there was a plus sign omitted in the commands' names.
=> Fixed keybindings to org-attach commands

modules/lang/racket/config.el
This fixes #2023 . Added racket-smart-open-bracket-mode as a minor mode hook, as expected by the upstream change https://github.com/greghendershott/racket-mode/commit/8049267e4c733715f62101bc11d0187d73459ea4
=> Fixes:2023, added racket-smart-open-bracket-mode

modules/lang/go/README.org, modules/lang/go/config.el, modules/lang/go/doctor.el, modules/lang/go/packages.el
go-add-tags isn't maintained and has a few issues.
This library will fix those issues by using a binary intended for this.
=> replace go-add-tags with go-tag

modules/lang/org/config.el
I frequently find myself using the native keybinding which has recently become more verbose: [`C-c C-x C-a`](https://orgmode.org/manual/Archiving.html).
=> Add org archive keybinding

modules/lang/javascript/config.el
These provide useful hints for `js2-refactor`'s deeply nested bindings.
`tide-rename-symbol` is remapped to `SPC r r s` to de-conflict with `js2-refactor`'s `r s` mapping.
=> [lang/javascript] Add prefix names to JavaScript bindings

init.example.el
PR #2020 adds support for a `lang/rst` module, but it wasn't added to the example `init.el`, which I believe is the one that's placed in `~/.doom.d/init.el` during a new installation ?
I think this greatly improves discoverability :)
=> Add rst module to init.example.el

modules/ui/hydra/config.el
Hydra displays the hints in a buffer created by lv-window, which
triggers nav-flash. By advicing lv-window, we can inhibit the nav-flash
hook.
=> Avoid nav-flash after each hydra action

modules/completion/ivy/autoload/ivy.el
For empty buffers which don't have any lines, `(thing-at-point 'line)`
will return `nil`. This broke `+ivy/jump-list`.
=> Fix nil error in +ivy/jump-list for empty buffers

core/autoload/files.el
Hi there,
this pull request addresses a minor issue when sudo-editing remote files: The implementation of `doom/sudo-find-file` was adjusted in such a way, that the correct file is found, if the remote user is not given explicitely, i.e. if the file passed to the function is of the form:
`/ssh:otherhost:myfile`
instead of
`/ssh:alice@otherhost:myfile`
In that case, the previous implementation invoked `find-file` with a file name that contained an extra @ character.
Hope the code is not to obtuse or convoluted. I don't code much in elisp :-)
=> Fixed sudo edit on remote files

modules/lang/org/config.el
The org-clock-modify-effort-estimate is only useful after we've clocked
in a task.
=> Add binding for setting effort

core/core-editor.el
Guessing the indentation can be awfully slow because it scans the whole
buffer. This PR overrides the guessing mechanism to scan at most 10000
points.
=> Speed up indent guessing

modules/completion/ivy/config.el
Before https://github.com/hlissner/doom-emacs/commit/a66872fe259ee6a99b6f4fae63ac4854102dc2b7  `counsel-ag` was disabled for ivy-posframe. Now it makes sense to disable `counsel-rg` for ivy-posframe.
=> ivy-posframe: ignore counsel-rg

modules/lang/latex/+viewers.el
In LaTeX forward search doesn't work for me with the Skim PDF-reader. This fix appears to be necessary.
The format string for opening Skim is taken from [Skim's documentation](https://sourceforge.net/p/skim-app/wiki/TeX_and_PDF_Synchronization/).
=> lang/latex: Support forward search with Skim

modules/lang/python/README.org
=> lang/python: fix minor documentation mistakes

docs/index.org, modules/lang/javascript/README.org
Currently, it is a bit hard to figure out that Doom supports TypeScript.
I looked for a `typescript` module in `init.el` but couldn't find one. I then looked for a `typescript` directory in `modules/lang` but couldn't find one. It took me a while to realize that the JavaScript module also supports TypeScript. This PR improves discoverability of this fact by:
* Mentioning in the default user `init.el` that the JS module supports TS such that people can find it when searcing for "typescript".
* Make it clearer in the JavaScript module documentation that it also works for TypeScript.
If other people have additional ideas for improving discoveability I'll update the PR. One could also add a `modules/lang/typescript` directory with a readme that simply points to the JavaScript module. But, …
=> Documentation: Make it clearer that JavaScript module also is for TypeScript

modules/lang/go/README.org, modules/lang/go/config.el, modules/lang/go/packages.el
The added plugin runs
[golangci-lint](https://github.com/golangci/golangci-lint) in the
background and gathers the results in a checker.
I don't know if there's a macro already to add a checker to flycheck, I don't know which hook to aim for if I want to run `(flycheck-add-next-checker 'lsp-ui 'golangci-lint)` only in `go-mode` buffers (without the lsp-ui setup destroying the flycheck checkers priority list just after)
=> [FEATURE] Add flycheck-golangci-lint

modules/emacs/dired/autoload.el, modules/emacs/dired/config.el, modules/emacs/dired/packages.el
This PR makes a couple of simple changes to the dired module which I find useful:
- Add dired-git-info package and enable it automatically in git (sub)dirs
- Add support for toggling dotfiles
- Hide dotfiles and dired details by default
=> [dired] add dired-git-info and hide dotfiles/details

modules/lang/org/config.el, modules/lang/org/packages.el
This PR adds support for [org-cliplink](https://github.com/rexim/org-cliplink). org-cliplink takes a URL from the clipboard and inserts an org-mode link with a title of a page found by the URL into the current buffer.
=> lang/org: add support for org-cliplink

modules/ui/modeline/config.el
Now that doom-modeline #260 is resolved, `irc-buffers' is back so let's
add it back to the `special' modeline definition.
=> modeline: add irc-buffers back

modules/tools/debugger/autoload/debugger.el
The variable changed name in
emacs-lsp/dap-mode@7768e145be56c9c6f2575ef9090b763bc9fb3730
=> Fix dap-debug-template-conf.. void-variable

docs/index.org, modules/lang/kotlin/config.el, modules/lang/kotlin/doctor.el
`lsp-mode` has built in support for Kotlin. This makes it automatically used if you use the `+lsp` flag.
=> Add LSP support to Kotlin

modules/editor/evil/README.org, modules/editor/evil/config.el, modules/editor/evil/packages.el
This introduces the `g o d` text object for comparing regions. It works
like evil-exchange. Select two regions in sequence with `g o d` and an
ediff buffer of the selections will pop up.
=> Add evil-quick-diff

modules/config/default/+evil-bindings.el, modules/ui/workspaces/autoload/workspaces.el
When a user tries to switch to a named workspace that doesn't exist,
create it, instead of just failing.
This is consistent with bookmarks for example
=> Easier creation of named workspaces

modules/lang/go/config.el
This allows users to be responsible for their use of the feature. I definitely misread the documentation about the checker.
=> Remove envvar setter in golangci-lint checker

modules/email/mu4e/config.el
- before this change: refile would use mu4e-trash-folder as the target
- after this change: refile would use mu4e-refile-folder as expected
Question: 
- Is a fancy icon needed for refile `:char`?
- What does `prompt` mean here? Do I need to change it to something else?
=> email/mu4e: fix refile target

modules/config/default/config.el
This PR adds a new prefix and keybindings under that prefix to the help map. The bindings provide access to several commands that allow for the inspection of keymaps.
=> Add keybindings for commands that show keymaps

modules/ui/popup/autoload/popup.el
- before this change: when reusing a window, select option would get ignored
- after this change: when reusing a window, select option would be used
just as a new popup
=> ui/popup: respect :select nil when reusing a window

modules/lang/org/config.el
Default Org binds 'SPC' to `org-agenda-show-and-scroll-up`, which
displays the original location of the Agenda item in another window
without moving focus from the Agenda window.
This is useful to preview items while staying in the Agenda window.
Since we can't use 'SPC', bind it to 'localleader SPC'.
See https://orgmode.org/manual/Agenda-commands.html
=> lang/org: Bind org-agenda-show-and-scroll-up

modules/ui/popup/config.el
process, timer, abbreviations, output, occur buffers are all better
displayed in a maximized fashion. Otherwise, they aren't really useful.
=> Popup rules for more builtin types

core/autoload/ui.el
The optional 3rd arg to the function was removed in f9190c08bfb908df1df3cc49ee2ecec4b360d42c
=> Fix interactive call of doom/narrow-buffer-indirectly

modules/email/mu4e/autoload/email.el
- if module workspaces is not used, an error would be raised when calling `=mu4e`
`=mu4e: Symbol’s function definition is void: +workspace-switch`
- if module workspaces is not used, an error would be raised when quiting mu4e
`=mu4e: Symbol’s function definition is void: +workspace/delete`
This PR fixes these two issues.
I think there might be a better fix:
Like extracting these workspaces tweeks to a new file and adding a `;;;###if (featurep! :ui workspaces)` check at the beginning?
=> email/mu4e: add featurep check for workspaces

modules/email/mu4e/autoload/email.el
`featurep` works a bit different from` featurep!`, which is required in this
case.
Fixes problem reported in the PR that introduced `featurep` in [this comment](https://github.com/hlissner/doom-emacs/pull/2123#issuecomment-563003555)
=> Use featurep! in mu4e/autoload/email.el

modules/term/vterm/config.el
emacs-libvterm@376db7cf416 had a breaking change for
`vterm-exit-functions` which sends the event as the second argument.
=> vterm: adapt to new function signature

modules/tools/magit/config.el
https://git-scm.com/docs/git-credential-cache
I believe that the default location for git-credential-cache should be
$XDG_CACHE_HOME/git/credential/socket
Which is where I found it running git from the command line.
=> Changed to correct default location

modules/email/mu4e/README.org
mu4e is not available from the main repos in Arch Linux, so I fixed the documentation
=> mu4e is only available from the AUR

modules/lang/elixir/README.org
Fix typo in elixir module documentation.
=> Fix typo in elixir-mode link.

modules/lang/python/README.org, modules/lang/python/autoload/python.el, modules/lang/python/config.el, modules/lang/python/packages.el
This PR introduces a new feature to the python module for `isort`. 
`isort` is a python tool which sorts imports which is actively maintained and used extensively by the python community. Emacs integration for this tool is done using the py-isort emacs package available on melpa.
The only thing that is missing from this PR is registering the hook to sort on save but i think this can be left to user-config rather than having it done automatically by doom.
=> Add py-isort feature to the python module

modules/lang/rust/README.org
Using the previous config did not change the language server to rust analyzer for me. I think it is because setting it after lsp-rust has been initialized is too late.
=> fix doc for enabling rust analyzer

modules/lang/clojure/config.el
CIDER removed `cider-grimoire-web` as Grimoire is no longer available. Now it uses ClojureDocs:
- https://metaredux.com/posts/2019/06/29/farewell-grimoire.html
- https://github.com/clojure-emacs/cider/issues/2663
For reference, taken from [cider_mode.adoc](https://github.com/clojure-emacs/cider/blob/master/doc/modules/ROOT/pages/usage/cider_mode.adoc#key-reference): 
Command | Keyboard shortcut | Description
-- | -- | --
`cider-clojuredocs` | `C-c C-d c` or `C-c C-d C-c` | Lookup symbol in ClojureDocs.
`cider-clojuredocs-web` | `C-c C-d w` or `C-c C-d C-w` | Open the ClojureDocs documentation for symbol in a web browser.
=> lang/clojure: Update to cider-clojuredocs

modules/ui/doom/config.el
I believe that `doom-gruvbox` supports solaire, which means that the background colors are swapped. This PR adds the `doom-gruvbox` theme to the list of supported solaire themes.
=> fix: gruvbox theme with solaire-mode

modules/lang/plantuml/doctor.el
This patch changes the recommendation from +plantuml/install to
plantuml-dowload-jar, when the plantuml.jar can't be found. The command
+plantuml/install has been removed in a previous patch.
----
When running bin/doom doctor and plantuml.jar is not found the recommendation is
to use the +plantuml/install command. But this command has been removed some
time ago. Instead it works to run the commnand plantuml-dowload-jar. This commit
updates the subscription by the doctor.
=> Update plantuml doctor prescription

modules/lang/ess/config.el
- `ess-smart-S-assign-key` and `ess-expression-offset` are deprecated variables
- `ess-default-style` has been replaced with `ess-style`
None of these are super important, but a bit of cleanup can never hurt 😄
=> Fix deprecated ESS variables

modules/app/irc/config.el
Users probably don't want ":-(" to be autocompleted as ":-()" so let's
turn of smartparens for chatting.
=> irc: turn off smartparens mode for circe buffers

modules/tools/debugger/config.el
Previously, this would put the .extension directory in
`user-emacs-directory' which in doom's case will be in the root of the
doom directory.
So, we move the directory to doom's cache dir and also name it something
descriptive instead of 'extension'.
=> dap-mode: set extensions variable to doom-cache

modules/editor/evil/config.el, modules/tools/flyspell/config.el
Yesterday, flyspell-correct had a new release, version 0.6.1 which removed aliases used in modules/tool/flyspell/config.el and modules/editor/evil/config.el
https://github.com/d12frosted/flyspell-correct/commit/7b4cf8c9ba5ac65e3bb2b62f5b72d45f4c9cf7b6
This patch updates those calls.
=> fix flyspell-correct

core/core-modules.el
=> docs/core: typo in `featurep!` docs

modules/app/irc/autoload/irc.el
I think this got accidentally flipped in 436d36fcd when `unless` was changed to `when`.
=> irc: fix logic for creating a workspace

modules/ui/doom-dashboard/README.org, modules/ui/doom-dashboard/config.el
Doom's dashboard faces are currently hardcoded to font-lock faces set by the current theme. These changes let you customize the faces independently of the current theme without having to change the widget functions themselves.
=> ui/doom-dashboard: De-hardcode dashboard faces

docs/faq.org
The example of using a third party theme previously didn't work, because there is no package `solarized`. Instead, `solarized-theme` provides the theme.
=> Fix name of solarized package

modules/ui/popup/+hacks.el
- If there's only one other window, delete-window would be called,
instead of delete-other-windows
- when there is only one window other than the popup, this other window
is the main window in this frame, delete it would raise an error:
`delete-window: Attempt to delete main window of frame <frame name>`
=> Suppress delete-window in org related functions

modules/editor/evil/README.org
These commands were deleted [here](https://github.com/hlissner/doom-emacs/commit/263c82def11ec7cd90f950b086b2c4e32e1fce1e#diff-8a6b6a4d5e97dc53317340b597c5352eL63), but not all docs have been updated.
=> editor/evil: fix: outdated log

bin/doom
Fixes https://github.com/hlissner/doom-emacs/issues/2303.
=> cli: Handle --help without an argument

core/cli/env.el
I noticed a typo when I ran `doom help env`, so I fixed it in core/cli/env.el.
=> Fix typo in env.el

modules/lang/markdown/config.el
I'm currently experiencing problems getting the source code highlighting to work with https://github.com/markedjs/marked
The reason is that Marked outputs the following structure:
```html
<pre><code class="language-js">const hello = 'world';</code></pre>
```
and the current selector expects the `pre` tag to have a `lang` attribute. 
This PR splits the forwarding of the `lang` attribute to a class and the code that initialise the highlighting for each block. It will try to initialise the highlighting for every `code` block that is inside a `pre` tag.
=> Fix source code highlighting when using marked.js

core/cli/doctor.el
On my redhat 6 box, I always had this "couldn't find font" warning, even though I have installed them and don't have any problem using them. As it turned out, calling `fc-list` prints
```sh
> fc-list
Liberation Mono for Powerline,Literation Mono Powerline:style=Bold Italic
Nimbus Sans L:style=Bold Condensed Italic
URW Bookman L:style=Demi Bold Italic
Liberation Sans:style=Italic
Source Code Pro for Powerline,Source Code Pro Black:style=Black,Regular
Source Code Pro for Powerline,Source Code Pro Light:style=Light,Regular
Meslo LG M DZ for Powerline:style=Regular
...
```
So the results don't have the font location, therefore `doom doctor` think they are not installed. The correct command to call is `fc-list : file`.
=> Be explicit about `fc-list` when listing fonts

modules/lang/clojure/config.el
Cider deprecated `cider-refresh` in favour of `cider-ns-refresh` in version 0.18.
https://github.com/clojure-emacs/cider/blob/master/CHANGELOG.md#changes-6
=> Use newer cider-ns-refresh in Clojure bindings

modules/editor/evil/+everywhere.el
The bindings that it creates are weird and conflict with lispyville's
own bindings.
=> Remove lispy from evil-collections

modules/checkers/syntax/config.el
A bunch of `(void-function +flycheck-init-popups-h)`
=> Fix flycheck migration void-function

core/autoload/files.el
Hi Henrik,
this PR allows doom/sudo-this-file to be called from dired-buffers, opening the directory as root. Previously such invocations would lead to an error, since buffer-file-name is nil for dired-buffers.
=> Make sudo-this-file usable in dired-buffers

modules/tools/pdf/config.el
Runnning `pdf-outline` resulting in the error `Invalid side 'right specified`. This PR fixes it.
=> Fix pdf-outline error

modules/tools/lsp/config.el
Update the lsp-server-install-dir to doom-etc-dir. This aligns the installation
location with other lsp servers.
----
Other lsp servers are installed under doom-etc-dir. When the user installs a
server through the command lsp-install-server it make sense if those servers
are also installed under the doom-etc-dir. At the moment they are instead
installed in the default location which is .emacs.d/.cache/lsp.
=> Update lsp-server-install-dir location

modules/config/default/+evil-bindings.el
This patch updates the check for enabling flycheck bindings to the new
module location.
----
the evil-bindings check for enabling flycheck bindings is not synced with the
new module location.
=> Update feature check of flycheck in evil-bindings

docs/getting_started.org, modules/tools/lookup/README.org
- Update the keybinding for +doom/help-autodefs
- Remove silver_search from the lookup module. Ripgrep is the supported
dependency.
----
Just some minor updates to the documentation that I ran into and thought I might
as well address.
=> Minor updates to documentation

modules/editor/format/autoload/format.el
Currently `+format-completing-read` returns a cons cell like `(symbol . t)`, where `+format/buffer` expects a symbol. This commit makes `+format-completing-read` return a symbol instead. Fixes #2349.
=> Fix #2349: Make +format-completing-read return symbol

modules/tools/docker/config.el
This patch setups the appropriate docset to use in dockerfile-mode.
Similar to how it is done for other major-modes that have associated
docsets.
----
When dockerfile-mode is active it make sense to activate the Docker docset.
=> Use Docker docset for dockerfile-mode

modules/lang/cc/README.org
CMake error occurred when followed the instruction on the cc language page for MacOS for building irony-mode:
```
CMake Warning at src/CMakeLists.txt:4 (find_package):
By not providing "FindClang.cmake" in CMAKE_MODULE_PATH this project has
asked CMake to find a package configuration file provided by "Clang", but
CMake did not find one.
Could not find a package configuration file provided by "Clang" with any of
the following names:
ClangConfig.cmake
clang-config.cmake
Add the installation prefix of "Clang" to CMAKE_PREFIX_PATH or set
"Clang_DIR" to a directory containing one of the above files.  If "Clang"
provides a separate development package or SDK, be sure it has been
installed.
CMake Error at /usr/local/Cellar/cmake/3.16.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:146 …
```
=> Fix broken MacOS irony-mode building command.

modules/lang/ruby/doctor.el
This fixes an issue where `doom doctor` was giving me the error:
```
! No versions of ruby are available via rbenv, did you forget to install one?
```
even though I have `(ruby +rvm)` in my `init.el` and don't use rbenv.
=> Doctor: Check whether rbenv is enabled before complaining

modules/lang/org/config.el
https://github.com/hlissner/doom-emacs/issues/2343 seems to describe an issue where the correct `journal.org` isn't found. I experienced the same problems. Based off https://github.com/hlissner/doom-emacs/issues/2343#issuecomment-572719940, I figured that setting `(setq +org capture-journal-file (expand-file-name "my_journal.org"  org-directory)` in `.../org/config.el` would fix the issue, which it did. 
If there is a more elegant solution you'd prefer, I'd be happy to change (I'm still a relative noob when it comes to elisp!)
=> Fix for https://github.com/hlissner/doom-emacs/issues/2343

modules/config/default/+emacs-bindings.el
Added `toggle` (C-c t), `code` (C-c c), `open` (C-c o) and `insert` (C-c i) bindings.
Moved org bindings from the `C-c o` to the `C-c n` prefix.
Updated the `file` (C-c f) and `quit` (C-c q) bindings.
Removed the `terminal` bindings, now under `open` (C-c o).
Removed standalone bindings for the REPL (now under `open` (C-c o)).
@hlissner, if merged, it would be good to mark the merge as "breaking". That is, users that use the default emacs bindings would need to be aware of the changes. Maybe even a notice in the #announcements Discord channel would also be good.
=> bindings: default emacs up to the state of the art

modules/emacs/ibuffer/config.el
This introduces the +ibuffer-current-workspace function which open an
ibuffer with only buffers from the current workspace.
This proof of concept already works and is proving to be quite useful for me, but there are still some imperfections:
* The workspace filter is displayed in an ugly way in the ibuffer window. (it's pretty printed as an emacs lisp struct)
* We should be using something like `ivy-read` to read the workspace in `:reader`.
=> Add ibuffer filter group for the workspace

modules/editor/format/autoload/format.el
Make `+format-buffer` copy all buffer-local variables from the original buffer into the temporary buffer. When resolving a symbol inside of a formatter, the value it is bound to in the formatted buffer will now be used instead of the default value. Fixes #2036.
=> Fix #2036: Copy local variables into formatting buffer.

modules/tools/debugger/config.el
Quoting my comment [here](https://github.com/hlissner/doom-emacs/commit/9a93aa1df99423c57e08147e3219f059a00b60a5#commitcomment-36934820):
> Looking at the [source](https://github.com/realgud/realgud/blob/master/realgud/common/run.el#L156) for the overridden function, it looks like the `eval` is intended, but the problem is that this advice renamed `minibuffer-history` to `minibuffer-history-var` everywhere _except_ on this line. Therefore I think the correct fix is actually:
> 
> ```
> (set minibuffer-history-var
>      (cl-remove-duplicates
> ￼     (cons cmd-str (eval minibuffer-history-var)) :from-end t))))))
> ```
> 
> Otherwise, when launching the debugger, you will get garbage entries in the minibuffer history.
=> Fix garbage minibuffer history when launching debugger

modules/checkers/spell/config.el
Fix for https://github.com/hlissner/doom-emacs/issues/2381
A CLI argument specific to `aspell` was also passed to `ispell`, which was then unable to start and printed its help message instead.
=> Move an aspell specific argument to appropriate block

modules/completion/helm/autoload/posframe.el, modules/completion/helm/config.el
- Fixes https://github.com/hlissner/doom-emacs/issues/2397
- Displays Helm input in header line on top of posframe if `helm-echo-input-in-header-line` is set to true.
=> Helm posframe fixes

modules/lang/org/autoload/org.el
No change of behaviour in non-emacs modes, but in emacs-mode stays there
instead of switching to insert-mode.
--
In upstream Doom Emacs hitting C-RET in org-mode switches to insert-mode regardless
even if the editor was in emacs-mode, which I at least find quite disorienting.
=> make +org--insert-item respect emacs-mode

docs/getting_started.org
I believe llvm package is correct way to get clang:
https://formulae.brew.sh/formula/llvm
https://github.com/Homebrew/homebrew-core/blob/4f169c6375b1bc8c23ddf374a78d33a0caba8ec9/Formula/llvm.rb#L72
=> use updated brew package name to get clang

modules/term/eshell/config.el
Hello there,
`ls` aliases for Eshell do not take any params and it is a bit annoying to use different commands between the current directory and subdirectories. Let's allow them to take params.
=> Make `ls` aliases work with subdirectories (Eshell)

modules/lang/web/autoload/html.el
< and > were missing from `+web-entities-list`
=> Add {little,greater}-than to +web-entities-list

modules/email/mu4e/README.org
`--with-emacs` arg no longer exists in the formula
Just a docs PR, skipped a bunch of the template steps that aren't needed.
=> docs: update mu macos install cmd

modules/lang/javascript/config.el, modules/lang/solidity/config.el
- ~[ ] Enable flycheck checkers by default~
https://github.com/ethereum/emacs-solidity/blob/master/solidity-flycheck.el#L89
if we set it active by default, it throws errors when the executables were not found.
- ~[ ] Format a Solidity file with Prettier + prettier-plugin-solidity~
-> don't do in this PR because it's still experimental.
=> Improve solidity layer

docs/modules.org, modules/lang/ess/README.org, modules/lang/ess/config.el
- Add LSP support for ESS R
- Refer R Dash doc for the symbols in an R buffer
- Add `lintr` to prequisites in the module doc
=> Add LSP support for ESS R

core/cli/install.el
prevent installing `all-the-icons` fonts on windows, which require emacs to be running with elevated privileges to install anyway, for most Windows users downloading & installing fonts manually is more idiomatic (I imagine)
=> disable all-the-icons font install on windows

modules/lang/cc/config.el
This fixes a `void-variable` error.
=> Fix typo: ffap-list -> ffap-alist

modules/lang/ledger/config.el
Previously, a list would be passed as an argument to 'executable-find' in '+ledger--check-version-a'.
This instead passes "hledger" as an argument if found, else "ledger".
=> Fix list passed as argument to executable-find

modules/lang/go/autoload.el, modules/lang/go/config.el
go supports running benchmarks much similar to running tests,
the new key bindings will run single or all benchmarks.
=> add benchmark bindings (,tbs and ,tba)

docs/modules.org, modules/tools/docker/README.org, modules/tools/docker/config.el
- Add LSP support for Dockerfile. This enables:
- code completion
- documentation
- diagnostics
- Currently the server doesn't complete file paths.
=> Add LSP support for Dockerfile

modules/completion/ivy/config.el
This makes `+ivy--counsel-file-jump-use-fd-rg-a` also search for the `fdfind`
executable, and not only `fd`. (On debian its called 'fdfind'.)
=> Also look for 'fdfind' executable

docs/modules.org, init.example.el, modules/lang/fstar/README.org, modules/lang/fstar/config.el, modules/lang/fstar/packages.el
Add a module for [F*](https://fstar-lang.org/), a language for program verification from Microsoft Research.
I roughly followed https://github.com/kyoDralliam/fstar-layer/ to get an idea of what aspects of `fstar-mode.el` should be supported but more closely mirrored the existing Coq module as far as keybindings. This way all three people that use F* and Coq won't get confused (when the other two of them switch to doom).
=> Add fstar module

docs/modules.org, modules/lang/latex/README.org, modules/lang/latex/config.el, modules/lang/latex/packages.el
This adds a cdlatex support to the latex module.
The whole configuration is just disabling parts of cdlatex that overlap with
standard doom features; I've specified the reasons in comments, and added a
section in the docs about how to re-enable cdlatex's snippets despite having
yasnippet enabled.
=> Add cdlatex feature in LaTeX

modules/editor/evil/config.el
This PR adds after-advice to following evil search functions:
- evil-ex-search-word-forward
- evil-ex-search-next    
- evil-ex-search-previous
=> Fix recenter after evil search

modules/tools/lsp/packages.el
Contains a fix for signature help disappearing
https://github.com/emacs-lsp/lsp-mode/commit/7f68f9231f248ec613afe4d15cd69c8f37f27059 bump is to a commit after this
=> Bump lsp-mode

modules/lang/org/config.el, modules/lang/org/contrib/present.el
In org-re-reveal, a reveal.js plugin will look for things relative to the path specified by the variable `org-re-reveal-root`. E.g. the `notes` plugin will look for `.../plugin/notes/notes.html`. But the current URL gives the `notes.html` file in .txt form, rendering the plugin unusable.
Instead, consider using `https://revealjs.com`, which is one of the customization option of the variable [[1]](https://gitlab.com/oer/org-re-reveal/-/blob/master/org-re-reveal.el#L228).
=> Change org-re-reveal reveal.js root path to https://revealjs.com

modules/checkers/spell/config.el
Not sure why flyspell was not enabled in text-mode before. For me, it's a bit annoying when I write commit messages in magit, but it's NOT spell-checked.
=> Enable flyspell in git-commit-mode

docs/index.org
`SPC d h` didn't work for me, `SPC h d h` did.
=> Fix documentation shortcut

docs/getting_started.org
I noticed the conversation in Discord. Updated docs for installing emacs via Scoop.
Emacs is in the 'extras' repo/bucket because Scoop only keeps CLI tools in the 'main' bucket.
https://github.com/lukesampson/scoop/wiki/Criteria-for-including-apps-in-the-main-bucket
https://github.com/lukesampson/scoop-extras/blob/master/bucket/emacs.json
=> Add install instructions for scoop emacs

modules/config/default/+emacs-bindings.el
Fix the description of the binding `C-c f X` binding for emacs users. The correct and new description is "Switch to scratch buffer".
=> bindings: correct description type-o

modules/tools/terraform/config.el
A parenthesis was missing in PR #2553, this makes doom fail to load his config.
=> Fix missing parenthesis in terraform config

modules/lang/ruby/config.el
This adds support for podspecs used by Cocoapods, Brewfiles from Homebrew Bundle, and Fastfiles from Fastlane.
=> lang/ruby: Add detection for additional files

modules/lang/haskell/autoload.el, modules/lang/haskell/config.el
Overwrite the 'o' and 'O' normal mode commands to correctly indent
new lines.
Code was adapted from: https://github.com/haskell/haskell-mode/issues/1265
This adresses an issue where new lines created by 'o' and 'O' where not correctly indented.
=> Correct behaviour of normal mode 'o' and 'O' in haskell-mode

modules/lang/go/README.org
github.com/mdempsky/gocode is an unmaintained fork of github.com/nsf/gocode which is also unmaintained.
github.com/stamblerre/gocode seems to be the current working module, which is also in "maintenance" mode as people are recommended to switch to `gopls`.
This is get the doom go module in working order until it can be switched to use gopls.
=> mdempsky doesnt work with modules, updating to stamblerre

modules/lang/org/config.el
Otherwise if you forgot a trailing slash on your `org-directory`, you end up with a wrong file
=> Construct org-id-locations-file using expand-file-name

modules/term/vterm/autoload.el, modules/term/vterm/config.el
It is useful to be able to enter normal mode in vterm, but going back to insert
gets weird, because there is only one place where inserting makes sense in
vterm; where you left it.
Setting some buffer local hooks for insert entry/exit, and storing `(point)` in
a buffer local variable.
This is my first PR to doom :) Thank you for this awesome project, brought me
back to emacs <3
=> VTerm remembers insert point when leaving normal mode

modules/completion/ivy/config.el
The behavior is explained by prescient author in https://github.com/raxod502/prescient.el/issues/35#issuecomment-471206879.
=> completion/ivy: sort projectile files with prescient

modules/lang/clojure/config.el, modules/lang/clojure/packages.el
[Clj-kondo](https://github.com/borkdude/clj-kondo) is a much more full-featured and actively developed linter compared to Joker, and is set as the (recommended) default on Spacemacs and the VScode Calva plugin.
=> Change clojure linter to clj-kondo

modules/lang/python/doctor.el
Related: #2180, #2193 
A few questions and a comment:
1) Should line 8 be an assertion? Is `python` not being installed a blocker?
2) I realize these doctor checks are all checking for global installations of various packages. How does this conflict with the various virtualenv solutions people are using?
3) How do you determine where to put intermixed dependencies? For example, should the `editor` module also check if `python` is enabled and warn about `black`?
4) Finally, I settled on using the format of "couldn't find $executable. $feature will not work". Doom seems to be a little bit inconsistent here, but this format seemed to be most common.
=> lang/python: add additional checks

modules/lang/clojure/config.el
Looks like this bug was introduced in a65403011e930fceaa59664dceabdee27b4c4cb4.
It causes Doom Emacs to fail on start-up if the `:lang clojure` module is enabled.
The workaround would be to disable this module until this change is merged in.
=> Fix syntax error in Clojure module

modules/tools/macos/autoload.el
`+macos/open-in-iterm` opens the current directory in `iTerm`. 
[`iTerm`](https://iterm2.com/) is a popular alternative to the macos's default terminal emulator `term`.
=> add `open-in-iterm` shortcut for macos module

modules/editor/evil/README.org, modules/editor/evil/config.el, modules/editor/evil/packages.el
This is a direct response to #2559. 
I've updated `:editor evil`'s docs about it accordingly.
`evil-lion` autoloads the correct operators, so there's really not much left for
me to do.
----
Adds `gl`, `gL` operators for alignment.
=> Integrate evil-lion into evil-mode

modules/lang/emacs-lisp/config.el
I often read the extracted source code in helpful. This would allow using
`+lookup/documentation` and co. in helpful, which saves a few key presses
compared to the ivy/helm stuff on `SPC h f/v`.
=> Set elisp lookups for helpful-mode

modules/editor/file-templates/templates/org-mode/__
`s-titleized-words` of the file name is generally a much better heuristic for
the title than just the file name.
I didn't want to add s.el as a dependency for file-templates, so if not defined,
the template uses the normal `buffer-file-name`. If you think its legit to add
s.el as a dependency, I'll do so.
=> Use s-titleized-words (if defined) for title in org template

docs/modules.org
Now the link is relative and not dependent of the absolute location of `doom-emacs-dir`.
=> Fix clojure link in modules.org

modules/lang/org/config.el
I think it's pretty common for people (myself included) to name their capture file `capture.org` file, and currently this rule matches it, so if you open capture.org, your end up with it opened in a popup (I believe it wasn't intended?). My fix makes it so it matches only capture buffers (they've got name like `CAPTURE-filename.org`). I believe there shouldn't be any unanticipated consequences of the change?
As far as I understand, the problem is that in elisp, regexes are case insensitive by default, and the sensitivity is controlled by a [variable](http://ergoemacs.org/emacs/emacs_regex.html), so I struggle to see what's the proper way to control it (especially considering the window manipulation happens in `window.el`). If you know of a way to deal with this, happy to implement and …
=> Adjust org-capture popup rule to exclude capture.org filename

docs/modules.org, modules/tools/lsp/README.org, modules/tools/lsp/config.el, modules/tools/lsp/packages.el
I'm opening this PR without thorough testing, though I've tried every change I introduced at least once and so far it seemed to work with my setup. What this PR does (currently in separate commits, in case some changes appear desirable and others don't):
1. `company-lsp` is replaced by lsp-mode's newly introduced `capf` functionality. According to the `lsp-mode` performance guide, this improves performance (and it reduces the number of required packages by one). Since I don't know of any capf downsides compared to `company-lsp`, I have decided not to make `company-lsp` a user-selectable alternative. This commit also bumps `lsp-mode` and `lsp-ui` versions and pulls in one `capf`-related improvement (https://github.com/emacs-lsp/lsp-mode/commit/1b5963dc04c6aa2f29c508ed3863f99b932974ac)
2. …
=> Modernize lsp integration

bin/org-capture
Avoids an extraneous `nil` log when invoking `org-capture` CLI.
=> bin/org-capture: Suppress output for initial emacsclient call

modules/ui/popup/autoload/settings.el
`more tha one` -> `more than one`
=> minor documentation spelling fix

modules/config/default/+evil-bindings.el, modules/emacs/vc/config.el, modules/ui/vc-gutter/autoload.el, modules/ui/vc-gutter/config.el
This PR extends support for non-git version control systems in the following ways:
1. `git-gutter:handled-backends` is extended to `(git hg svn bzr)`. I'm using the `hg` backend with no issues so far, though I haven't tried `svn` or `bzr`. In the latter two cases I'm relying on git-gutter's claim of support but if that is deemed to risky we might as well reduce it to `(git hg)` for now
2. if both `hydra` and `vc-gutter` are enabled, `<leader> g .` is bound to the (IMO very useful) `+vc/gutter-hydra`.
3. `+vc/gutter-hydra`'s quit functions are extended to automatically close the `git-gutter` popup (not sure if that is what other users want, as it doesn't currently differentiate between popups opened through the hydra itself and a preexisting git-gutter popup)
4. I believe the popup rules …
=> Extend backend-agnostic vc functionality

core/test/init.el, modules/tools/ein/test/test-ein.el
Rudimentary regression test for :tools ein.
=> [:tools ein] ensure keybindings still valid

modules/lang/ruby/config.el
Without this, Rails 6 (new version) always try to use spring.  Adding this modification, fix it for all rails versions.  If the user really want, they can add on config.el.
=> Fix Spring bug on Ruby Rspec Mode

modules/editor/evil/autoload/files.el
`:cp` was not autoloaded correctly beforehand. I just changed `+evil:copy-this-file`'s autoload
signature it so it would match `+evil:move-this-file`, with which I had no issue - and it works!
=> Make +evil:copy-this-file autoload interactively

modules/lang/rust/config.el, modules/lang/rust/packages.el, modules/tools/lsp/packages.el
I moved some code to lsp-mode because there are issues with requiring lsp-mode related code in doom. An error will be thrown when starting the first lsp session. I've tried the fix in doom, but it would be good if somebody can confirm this.
=> bump rustic

modules/lang/web/+html.el
Although xhtml files are indeed xml, they usually have embedded JavaScript and CSS like
normal HTML, so `web-mode` fits them better than `nXML-mode` (the default)
=> Associate xhtml files with web-mode

modules/lang/ess/packages.el
As of ESS 19+, ess-noweb and ess-swv libraries are now obsolete, and
polymode should be used instead (https://emacs.stackexchange.com/a/17065).
=> Add polymode to handle RMarkdown and RNoweb files

modules/lang/haskell/+dante.el
`dante-mode` was using `haskell-process-load-or-reload` on `, l` and `haskell-mode` complained about it being obsolete.
This PR changes it to `haskell-process-load-file`, same as bound to `C-c C-l`.
=> Replace obsolete elisp function in dante-mode

docs/faq.org, docs/getting_started.org
These links to org headers didn't work for me when they contain `%20` instead of space. Should they have?
=> Fix internal documentation links containing "%20"

modules/editor/format/autoload/format.el
Fix `+format/buffer` not to take an argument because it results in an error:
```
let: Wrong number of arguments: (0 . 0), 1
```
=> Fix region formatting

modules/lang/org/contrib/dragndrop.el
In line with latex and html attributes. Essential for high resolution displays.
=> dragndrop: insert #+attr_org: :width if specified

modules/lang/plantuml/config.el
Hello,
There is a problem with PlantUML on macOS at the moment, the default executable (from HomeBrew) produces warnings in the output, and the `plantuml-mode` does not filter them. As a result, when you try to preview your graph within Doom Emacs you will see something like this instead of the image:
```
2020-03-17 01:16:07.106 java[8100:11358722] CoreText note: Client requested name ".SFNS-Regular", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2020-03-17 01:16:07.106 java[8100:11358722] CoreText note: Set a breakpoint on CTFontLogSystemFontNameRequest to debug.
2020-03-17 01:16:07.107 java[8100:11358722] CoreText note: Client requested name …
```
=> Prefer jar file for plantuml-mode if it is available

modules/completion/helm/config.el
Hey Henrik,
this PR addresses some minor issues with the helm module. Currently, helmized command (i.e. commands that will use helm's completion interface because `helm-mode` is active) as well as some native helm commands will provide only very basic pattern matching behaviour. This is because they will match according to `completion-styles` which is equal to `(basic partial-completion emacs22)`, at least for my doom/emacs installation.
I've also removed code that sets values of variables that have, in the meantime, been removed from helm's source code.
=> Minor changes to the helm module

modules/editor/evil/autoload/textobjects.el
The docstring for +evil:defun-txtobj was obviously wrong.
Btw what a "defun" is is hard to describe. In Lisp it seems to be the top-level form, but in Python it's the closest `def`, not necessarily at the top-level.
=> Fix +evil:defun-txtobj docstring

modules/app/irc/config.el
This PR addresses the problem mentioned in issue #1862 where the IRC module circe is hanging on TLS connections when using OpenSSL versions > 1.1.0. In this case, `tls.el` does not correctly determine the end of the info block and hangs.
This workaround was first proposed here: https://github.com/jorgenschaefer/circe/issues/340#issuecomment-454521683
Since it looks like it will not be fixed upstream, this might be a good place to incorporate the workaround.
Additionally, this PR fixes `circe-network-defaults' being overwritten on init: by default, this list is filled with predefined server details for e.g. Freenode.net which is rather useful.
Please note that this code works fine on my setup and with my OpenSSL setup (1.1.1a on Ubuntu Mate 19.10) connecting to Freenode.net but I have not …
=> IRC/circe fixes: TLS connection workaround and default server settings

core/autoload/debug.el, core/core.el, modules/lang/rest/config.el
- Check whether the current gnutls library supports tls1.3, should fix #2781 as well.
- Add more tests for `doom/am-i-secure`.
=> Fix TLS error caused by #2763

init.example.el
Thought it will be added, but I see it's absent after the merge so I added it myself.
=> Add dart to `init.example.el`

modules/lang/org/contrib/dragndrop.el
By default Gnome based distros (like Ubuntu) have `gnome-screenshot`
installed. This change modifies `+dragndrop` to support gnome-screenshot
by default.
=> Add default gnome support for org +dragndrop

modules/tools/terraform/config.el
terraform apply requires typing 'yes' to actually execute the change
=> enable comint mode for terraform apply

modules/lang/org/config.el
By default it's `python` so suffers from the same issues as `python-shell-interpreter`.
tbh, not sure if the way I'm suggesting is a good one, maybe it make more sense to simply copy-paste the [bit of logic](https://github.com/hlissner/doom-emacs/blob/56cba7828c295acafbbd0e14938f62dd23080a3d/modules/lang/python/config.el#L51-L55) for python-shell-interpreter. Let me know what you think is the right way!
=> Set org-babel-python-command to be same as python-shell-interpreter

modules/config/default/+evil-bindings.el, modules/lang/org/contrib/roam.el
The command org-roam-show-graph was marked obsolete in favor of org-roam-graph-show by org-roam commit 22b9d4b (before org-roam's pinning at b86d2c8), see https://github.com/jethrokuan/org-roam/pull/363.
=> Move away from obsolete org-roam function in org +roam

modules/checkers/grammar/config.el
On nix we create a wrapper script that handles java for us, so allow setting `langtool-bin` instead of forcing looking for the `jar`.
=> grammar/langtool: support setting the path to the binary i/o jar

modules/lang/latex/+ref.el, modules/lang/latex/README.org, modules/lang/latex/config.el, modules/lang/latex/packages.el
Ivy/helm-bibtex is unused throughout the latex module, aside from implicitly by setting the `bibtex-completion-bibliography` variable. This is confusing, and unnecessary.
Ivy/helm-bibtex is a great tool, but it is also language agnostic (it can be used to insert citations in org and markdown modes), and latex mode already has excellent citation autocompletion from `company-reftex`. In my opinion, ivy/helm-bibtex would be a good candidate for inclusion in a distinct bib module, but should be removed from the latex module.
=> Remove Ivy/helm-bibtex

core/core-projects.el
So it matches the doom project marker `.project`. Otherwise you need to
create both a `.project` and then a `.projectile` with the project
configuration.
To maintain backwards compatibility, it will prefer a `.projectile` file
for dirconfig if found.
=> Change projectile dirconfig file to .project

modules/emacs/dired/packages.el
With current version of ranger.el if you copy file with ranger and paste it in the same place ranger fails  with erro instead of  appending "~1" as before. 
Related issue:
https://github.com/ralesi/ranger.el/issues/217
If newer features are not worth it, maybe we should pin older commit while waiting for fix.
=> fix: revert ranger version to fix paste over

modules/lang/org/config.el, modules/ui/pretty-code/config.el
org-mode recently changed the standard for naming blocks. Previously, it would use capitalized names; now it uses lower case names.
E.g., `#+BEGIN_SRC` -> `#+begin_src`
This change adds support for both naming conventions within the pretty symbols mode. Note that in many org files in the Doom documentation mix both styles and this PR helps in having a consistent visualization. This doesn't mean that we should probably choose only one "casing" convention and stick to it. I personally prefer the new style (i.e., using lower case, I don't like my code screaming back at me). 
Also, add a "quote" symbol for the `#+{begin,end}_quote` block.
=> lang/org: pretty symbols for the old and new word case style

modules/ui/treemacs/autoload.el, modules/ui/treemacs/config.el, modules/ui/treemacs/packages.el
With https://github.com/Alexander-Miller/treemacs/issues/592 merged,
treemacs now fully supports perspective mode. That is, each treemacs
buffer is scoped to a perspective and initializes itself using projectile.
This change re-enables treemacs-persp, enables the `Perspectives` scope,
and adjusts the doom treemacs init behavior to support the new
treemacs-persp behavior.
I haven't been able to reproduce the prior errors with melpa so I think
this is safe to re-enable now. In my testing it seems to work
well.
Only one issue is that users might need to remove their treemacs persist
file (`~/.emacs.d/.local/cache/treemacs-persist`) after this change if
using persp-mode. I'm not sure if it is necessary since I blew away my
own before testing.
=> Enable treemacs workspace/persp support

docs/modules.org, modules/lang/latex/README.org, modules/lang/latex/autoload.el, modules/lang/latex/config.el
This utilizes auctex's TeX-fold package to auto-fold latex macros after commands
that usually insert macros: snippets, cdlatex, and auctex's macro insertions. And on startup.
Demo of me using it, expanding a snippet and inserting a macro with cdlatex:
I've had this in my latex config for a very long time. Not long ago @tecosaur
also got interested, and I thought I should just make it a doom module.
=> Add +fold flag to lang/latex for TeX-fold

modules/lang/org/config.el
On macos/bsd systems, uuidgen produces all uppercase output. On
Linux/GNU systems it produces all lowercase output. This leads to
problems when managing org files across both systems (see e.g.
https://lists.gnu.org/archive/html/emacs-orgmode/2019-07/msg00081.html).
This change adds a defadvice for `org-id-new` to always lowercase the
output of `uuidgen` so the behavior is consistent across platforms.
=> Make uuidgen consistent for org-id-new

modules/app/irc/autoload/irc.el
This fixes a problem where calling IRC (e.g. C-c I I) will switch to
a (seemingly random but is ordered by load order) buffer.
----
#
=> irc: only use the switch buffer logic during creation

modules/completion/ido/config.el, modules/completion/ido/packages.el
- ido will actually be loaded at startup - I'm hoping there's a better
way to optimize this.
- ido-sort-mtime-mode was fixed
- Up/Down were added to get closer to
`(setq ido-vertical-define-keys 'C-n-C-p-up-down-left-right)`
- Faces were re-enabled
- The number of results are now displayed with ido
=> Fix and improve ido module

core/core-editor.el, core/packages.el
This PR is for issue #2671 
A clipboard package for remote TTY users without the need for X forwarding.
Any comments is welcomed!
=> Add clipetty for TTY users.

docs/getting_started.org
The install link in the docs is incorrect. This will link to the install section at the top of the file.
=> Fix install link

modules/ui/deft/config.el
By default deft will save a changed buffer that it opens after 1 second.
This causes problematic interactions with the rest of doom - like with
wsbutler (insert space, try to insert a link, and it will eat the
space before the link is inserted).
I think it's best for auto-save to be managed by a separate package,
rather than this ad-hoc save that occurs only in buffers that deft opens.
=> Disable deft's buffer auto-save

modules/tools/lookup/autoload/lookup.el
The synosaurus-wordnet--command variable is defined in synosaurus-wordnet rather than in synosaurus.
=> tools/lookup: fix synosaurus -> synosaurus-wordnet

docs/modules.org, modules/lang/julia/README.org, modules/lang/julia/config.el, modules/lang/julia/packages.el
This pull request adds a README, additional functionality for `julia-repl` and a `+lsp` flag to the Julia module.
The language server must be manually installed, as per guidelines.
I have overriden some defaults in `julia-repl`. In particular, I override:
- `julia-repl--bufer-name` to name the Julia REPL as `*julia:[workspace-name]*`. 
- The escape sequence from `C-c C-x` to `C-c C-c`.
=> Add +lsp to Julia and override some defaults in julia-repl

modules/lang/org/packages.el
Was running into a `company-org-reveal` not found issue. Also trying to manage it separately in `packages.el` led to https://github.com/jethrokuan/org-roam/issues/367
=> Update org-roam to fix errors

modules/editor/lispy/config.el
=> editor/lispy: fix hook for lisp-mode

modules/lang/latex/README.org
Ghotscript <=9.27 is [reported buggy in general](https://www.gnu.org/software/auctex/manual/preview-latex/No-images-are-displayed-with-gs-9_002e27-and-earlier.html), and auctex's preview doesn't need `dvipng`/`dvips`. It can use them if you ask it to, but the default pipeline is only pdflatex and ghotscript. 
I couldn't be sure if `preview` actually used `dvi(png|ps)`, so I manually moved them out of `PATH` and re-ran the previews. (It worked.)
=> Clarify LaTeX prerequisites

modules/lang/org/packages.el
Includes fix of a recent breaking bug: https://github.com/non-Jedi/emacs-jupyter/commit/5c2469dbe40a3ee82537ecb549ee0b05ef35e194
=> bump jupyter

modules/completion/helm/config.el, modules/completion/helm/packages.el
This package allows for easier navigation of the assigned bindings.
The inbuilt describe-bindings (C-h b b) feature is remapped to the helm
equivalent.
Signed-off-by: Brian McGillion <brian@ssrc.tii.ae>
=> Add helm-descbinds

modules/lang/org/contrib/roam.el
`org-roam` has a buffer that shows backlinks to the file currently displayed. If the backlink is in a multiline paragraph, `org-roam` will show it as a single line inside this buffer, making it unreadable for Doom users by default, since `truncate-lines` is `t`.
This adds a hook to enable `visual-line-mode` (soft wrapping) when in the `org-roam-backlinks` buffer.
I've made the change in my private config, but I feel like this is a good default for Doom users.
Before: 
After:
=> Enable visual-line-mode in org-roam-backlinks buffer

modules/config/default/+emacs-bindings.el, modules/config/default/+evil-bindings.el, modules/tools/biblio/config.el, modules/tools/biblio/packages.el
Addressing #2827, this is a minimal biblio module that provides `ivy-bibtex` or `helm-bibtex` (which were recently removed from the latex module in #2838) depending on completion feature, and provides a single global keybinding.
The idea is this provides the core functionalty, and the community can iteratively build it up as appropriate.
=> adding new biblio module

modules/editor/file-templates/templates/sh-mode/__
Adds a line with set -euo pipefail to the sh-mode file template, which improves the erroring of bash scripts.
As described by https://ashishb.net/all/the-first-two-statements-of-your-bash-script-should-be/
=> Add set -euo pipefail to sh-mode file template

modules/editor/god/config.el, modules/editor/god/packages.el
In this change:
* Bump version pin of `god-mode`
* Use default value of `god-exempt-major-modes`  as commit https://github.com/emacsorphanage/god-mode/commit/567eb3bd1f15bfd2920a47434415828405de4bfb includes all the modes (previously) in `god/config.el`
=> Use default god-exempt-major-modes in :editor god module

modules/tools/biblio/config.el, modules/tools/biblio/packages.el
helm-bibtex split out bibtex-completion into a separate package
in MELPA. Add an explicit pin of bibtex-completion and bump the versions
of {helm,ivy}-bibtex to match.
=> Bump helm-bibtex and ivy-bibtex

modules/lang/csharp/config.el
If you have omnisharp & csharp set up, and you close a cs file, you'll get `Symbol's function definition is void: +csharp-cleanup-omnisharp-server-h`.
This is because 169f9a6121d8e0c75c0b27c2566f050477828dce moved its definition to csharp/autoload.el, but also renamed it to +csharp-kill-omnisharp-server-h.
This PR updates the hook to match the new name.
=> Update hook to match rename from refactoring

modules/lang/org/config.el
currently if someone wants to use them, it has to manually autoload
them first in user `config.el` with `(unless (fboundp ...) (autoload ...))`
=> Autoload all 4 org decrypt/encrypt user commands

modules/config/default/+emacs-bindings.el, modules/config/default/+evil-bindings.el, modules/lang/org/README.org, modules/lang/org/config.el, modules/lang/org/contrib/noter.el, modules/lang/org/packages.el
This package allows the creation of notes on a document (pdf, EPub,
etc.) which will be kept in sync with the document. Providing context
sensitive annotations that are managed in plaintext.
=> Add org-noter package

modules/editor/evil/+commands.el
The doom/ prefix for popup commands no longer exists
=> Fix :last and :popup

core/core-ui.el
This would offer a convenient way for people to globally opt-out of the default [indentation highlighting](https://github.com/hlissner/doom-emacs/blob/develop/docs/faq.org#why-do-i-see-ugly-indentation-highlights-for-tabs). The idea of opting into `whitespace-mode` to make it less prominent is kind of unintuitive, but I'm not sure how else it could be done; there's no way to tell if `global-whitespace-mode` was explicitly set to `nil` or just not initialized, as far as I know. Happy to take any feedback!
=>  Respect global whitespace mode config if set

modules/ui/zen/config.el
Currently, the TODO is fixed-pitch but DONE is mixed, which I find very odd. If there _is_ a reason for it, I'd be curious to hear it.
=> Register org's DONE as fixed pitch in mixed-pitch

modules/editor/evil/+commands.el
Makes it available as `:capture` which is a slightly easier to understand
name. The short alias is still available
=> Add full name to :cap

modules/tools/tmux/autoload/tmux.el
Specifying a session and / or window to +tmux-list-windowsand +tmux-list-panes just failed, because of the special characters used in the ids for sessions & windows ($ and @). Quoting the ids before building up the tmux command fixes this.
Specifically, the following don't work before this fix (you'll need to start a tmux session first):
```emacs-lisp
(+tmux-list-windows (car (+tmux-list-sessions)))
(+tmux-list-panes (car (+tmux-list-sessions)))
```
=> tmux: Quoting shell arg in listing windows / panes

modules/lang/scheme/config.el
Scheme mode was pretty bare for a long time now and lacked many of
geiser's useful features like `geiser-smart-tab` and starting the geiser
repl on entering a file. This turns them on by default for the
productive schemer.
Besides that the following key bindings were remapped
+ `SPC m e e` -> `geiser-eval-last-sexp`
+ `SPC m e d` -> `geiser-eval-definition`
+ `SPC m e D` -> `geiser-eval-definition-and-go`
This brings the geiser keymaps in line with other lisp modes in doom.
Another change involves adding macro expand commands under `SPC m m` so
schemers can see what evil lurks beneath their commands.
Geiser autodoc commands have also been added under `SPC m h` for
schemers to read the docs, though they can still use `SPC c k` to do the
same thing.
=> Add useful defaults and bindings to scheme mode

modules/lang/org/contrib/roam.el
I do not understand why this is the case, but the conditional setup for the completion system was causing fuzzy completion to fail in ivy. This fixes that.
=> switching org-roam-completion to use 'default

core/autoload/config.el
When using the internal doom/upgrade command to upgrade using the CLI
tool, do so with the -y flag.
This is admittedly a temporary solution, but without it the CLI tool
will prompt for confirmation, which cannot easily or obviously be given
while inside Emacs.
A better solution would be to somehow integrate the prompt so that it
appears in the minibuffer as normal Emacs prompts do. But for now this
at least fixes doom/upgrade.
=> doom/upgrade use -y CLI flag

modules/lang/yaml/config.el
There was a typo in the `use-package!` definition.
Requesting a pull to hlissner:develop from peterhoeg:fix_yaml
Write a message for this pull request. The first block
of text is the title and the rest is the description.
=> yaml: hook -> mode

modules/config/default/+evil-bindings.el
This fixes a typo for a minibuffer keybinding.
@hlissner `*-char` and `*-word` commands in this section are generally mixed up, please let me know if I should include the fix to them as well.
=> Fix typo in key bindings

modules/email/mu4e/README.org, modules/email/mu4e/autoload/email.el, modules/email/mu4e/config.el
`mu4e` 1.4 brings quite a few changes, including the deprecation of previously used variables. These are now guarded by a version comparison. `org-mu4e` is not needed for linking anymore, `org-mu4e-link-query-in-headers-mode` was renamed. It's new version defaults to `nil` and is therefore not set anymore -- I am not sure if the default was changed or setting it was not strictly needed previously.
=> mu4e: Adjust config to mu4e 1.4

docs/modules.org, modules/lang/python/README.org, modules/lang/python/config.el, modules/lang/python/doctor.el, modules/lang/python/packages.el
Poetry is a tool for managing Python projects. There's a very nice wrapper around that tool called [poetry.el](https://github.com/galaunay/poetry.el). I think it's worth adding a module flag for it.
=> Add Poetry support

modules/lang/web/+html.el
Seeing that the `web` lang module already supports .jinja files, I don't think it's a far cry to add the .jinja2 extension to the list.
It's not super fancy but better than no major mode support.
Working with limited lisp experience to expand the highlighting functionality. :shrug:
=> Add .jinja2 file extension to supported web files.

modules/completion/ivy/config.el
Under windows the formatting of the ```--path-separator``` argument was wrong.
=> Make rg --path-separator argument work under Windows

modules/tools/lsp/config.el
Remove `lsp-groovy-server-install-dir` setting since it no longer exists.
https://github.com/emacs-lsp/lsp-mode/pull/1319
=> Remove `lsp-groovy-server-install-dir`

modules/completion/ivy/config.el
This adds a column that displays the path where the bookmark exists.
=> Improve ivy-rich with counsel-bookmark

modules/config/default/+emacs-bindings.el
Replaced :tools flycheck and flyspell with :checkers syntax and
spell.
=> Fix emacs bindings to use :checkers

modules/app/calendar/config.el, modules/app/calendar/packages.el
Looks like `org-gcal` stores sensitive data in `~/.emacs.d/org-gcal` (by default) without encryption. 
Here's a few changes to make it a bit more secure. :lock: 
* Move `org-gcal-token-file` to `doom-cache-dir`
* Encrypt `org-gcal-token-file` using GPG
* If old file exists, move it to new location with encryption
* Bump `org-gcal` pin
Any feedback is more than welcome!
=> Encrypt and change location of org-gcal-token-file

modules/lang/javascript/config.el
Tide doesn't work with `rjsx-mode` after changing to `*-mode-local-vars-hook`.
Fixed by adding `+javascript-init-lsp-or-tide-maybe-h` for
`rjsx-mode-local-vars-hook` as well.
Signed-off-by: Huy Duong <huy.duong@employmenthero.com>
=> Fix tide not working with rjsx-mode

modules/completion/ido/config.el
This adds support for up/down/C-n/C-p for file dir navigation. For some reason the keybinds are overridden there and they don't do what I'd expect.
=> ido: fix up and down keybinds in file dir navigation

docs/getting_started.org
Hi
This is to fix [https://github.com/hlissner/doom-emacs/issues/3035](https://github.com/hlissner/doom-emacs/issues/3035)
=> Adding Fedora dependencies block in getting_started document

modules/lang/java/+lsp.el
This is a first pass at making `+lsp` more functional:
* Fix lsp not starting automatically when opening java-mode buffers.
Placing it in the lsp-java hook does not work.
* Fix root path for lsp-jt.
=> Make some improvements to java +lsp

modules/config/default/+emacs-bindings.el, modules/config/default/+evil-bindings.el, modules/editor/format/autoload/format.el
Currently the user has to select `SPC c F` for lsp format. But if
lsp-mode is enabled, the user will always want to use the LSP formatter.
So this changes the default `SPC c f` to use lsp formatter if available.
This simplifies the interface a bit so the user doesn't have to worry
about selecting the "right" format, just like how other commands get
auto bound to LSP functions.
=> Use lsp-format-region-or-buffer if available

modules/editor/format/autoload/settings.el
Remove `:install` from supported keywords.
=> Fix set-formatter! documentation

modules/ui/pretty-code/README.org
Hopefully this will make it clear that emacs-mac does something special to get ligatures working with the composition-function-table method ; and it serves as an entry point for people who want to get into this kind of detail
=> [:ui pretty-code doc] Add link to emacs-mac-port source code

modules/tools/lookup/README.org, modules/tools/lookup/config.el
Add Dash docsets + Xwidget integration. We can see Dash docsets in Embedded Webkit Widgets.
=> Add Dash docsets + Xwidget integration

modules/lang/java/+lsp.el, modules/lang/java/README.org, modules/lang/java/autoload.el
This configures dap-mode appropriately so the user can run tests
directly from Doom. It adds two test bindings similar to
other major modes:
* `SPC m t t` runs the test class or method at point.
* `SPC m t a` runs all tests in the current class regardless of point.
* `SPC m t d` debugs the test class or method at point using dap-mode.
* `SPC m t D` debugs all tests in the current class regardless of point.
I also expanded the README with more details about configuring `+lsp`.
=> Configure java +lsp test runner via dap-mode

modules/term/vterm/autoload.el, modules/term/vterm/config.el
When `default-directory` is remote, prepare the toggled vterm at remote
location. The added code is taken from `multi-term-switch-buffer` in `multi-term.el`.
=> Allow +vterm/toggle to open remotely

modules/lang/org/config.el
Following b40d85e9b, make the bindings for the agenda the same
=> Unify org-agenda-clock bindings with org-clock

modules/email/mu4e/README.org, modules/email/notmuch/README.org
Made the links to my mail config permalinks since I moved to `mu4e` and add an initial `notmuch` README. I couldn't remember the git magic to find where a module was created, so the date and version are wrong.
=> Add a few Email docs

modules/tools/lookup/README.org
As the branch name suggests, using `sudo` with `yay` is an anti-pattern and so this fixes that.
=> lookup: Update docs

modules/lang/elixir/README.org
Now that the JakeBecker project has been [moved](https://github.com/JakeBecker/elixir-ls/commit/9d4c1485e951b7ebdc0ed5b4f521451c5c99ad68), update the README.
=> Update README to point to new elixir-ls org

core/core-projects.el, modules/completion/ivy/config.el
Show slash instead of backslash
=> Change path separator on Windows when using fd

docs/getting_started.org
I noticed this when getting my config ported over.
=> Documentation fix - use-packages! typo in getting started

modules/tools/lookup/autoload/lookup.el, modules/tools/lookup/config.el, modules/tools/lsp/config.el
Support lookup handlers for implementations and type definition.
I didn't still add key bindings for them.
https://github.com/hlissner/doom-emacs/issues/2579
=> tools/lookup: Support lookup handlers for implementations and type definition

modules/lang/org/config.el, modules/lang/org/packages.el
I noticed that doom-emacs now uses rustic for org-babel so I guess ob-rust is not needed anymore.
=> remove ob-rust

docs/getting_started.org
Default options for brew install emacs-mac compile wihtout
modules preventing to use vterm.
=> Add --with-modules to emacs-mac documentation

modules/editor/lispy/README.org, modules/editor/lispy/config.el
Currently the list of key themes for lispyville is hardcoded in the package config. The user can add more, but there is no way to unload a theme once it has been loaded.This simple change lets users set their own keys themes by setting `lispyville-key-theme` in their private config.
=> Allow the user to override lispyville themes

modules/input/japanese/README.org
I have found that openSUSE's repos don't contain cmigemo, so may as well add the link to the README for Japanese input.
Aside from that everything seems to work out of the box.
=> Add the needed migemo variants to the requirements for Japanese input.

modules/checkers/spell/config.el, modules/editor/evil/config.el
`flyspell-correct-at-point` is not defined unless the the `spell` module is enabled.
=> Wrap flyspell-correct-at-point in feature check

init.example.el, modules/config/default/+emacs-bindings.el, modules/config/default/+evil-bindings.el, modules/ui/minimap/README.org, modules/ui/minimap/config.el, modules/ui/minimap/packages.el
Created a new Minimap module based on `minimap.el` from ELPA. The module sets some DOOM-specific config, and better defaults. Also added keybindings for it.
Some things that can be worked on/improved:
- Fix positioning when window split
- Sometimes it doesn't close when `minimap-mode` is disabled
- Adding more major-modes that the minimap will show in, or showing it in all modes (it is currently at the default which is showing in any mode derived from `prog-mode`)
=> Minimap Module

docs/getting_started.org
I recently installed Doom Emacs on openSUSE, there were a few more steps to get it done than I'd expected. Thought it would save other users some googling if I noted the steps down here.
=> add openSUSE installation section to getting started guide

init.example.el, modules/config/default/+emacs-bindings.el, modules/config/default/+evil-bindings.el, modules/tools/taskrunner/README.org, modules/tools/taskrunner/autoload.el, modules/tools/taskrunner/config.el, modules/tools/taskrunner/packages.el
This is a rework for #2035.
- Prefer longer commit hashes to pin packages
- Fix conflicts with the latest `develop`
- Fix some indentation
- Fix arguments for `helm-taskrunner-minor-mode`, `ivy-taskrunner-minor-mode`
- Remove unnecessary file diffs
- Defer loading `taskrunner`, `helm-taskrunner`, `ivy-taskrunner`
- Move `+default/project-tasks` to taskrunner module
=> Add tools/taskrunner module

modules/config/default/+evil-bindings.el
gating "toggle minimap" keybinding behind `minimap` rather than `zen`.
#3154
=> using dedicated minimap flag

docs/modules.org
So I would know when to look for an extra feature for a module I did a little regex 🙈:
`find  .emacs.d -type f -name *.el -exec grep -Po "\(featurep! .*?\)" {} + | uniq | grep --color=always -P "\s\+\w+"`
=> add missing +features to modules.org

modules/config/default/+emacs-bindings.el, modules/config/default/+evil-bindings.el
Update emacs bindings to match recent evil bindings.
Remove the `g` (lookup) prefix and merge those bindings onto the `s` prefix (just like in the evil bindings).
Add more `remote` bindings for emacs and evil users.
=> bindings: update bindings / add remote bindings

modules/app/rss/README.org
The previous recommendation for `(setq elfeed-seearch-filter "")` was
not working. This PR addresses that by exposing a new variable
`+rss-initial-search-filter` that can be overwritten by the user in
their `config.el`. This also updates the documentation to reflect the
change and clean up a bit of the wording, removing template comments.
----
#
=> Update documentation for app/rss

docs/getting_started.org
Just tried installing on Windows, you need to use "scoop bucket add extras" not "scoop enable extras"
=> Fix scoop install instructions

modules/ui/doom/packages.el
Updates the Pin of [doom-themes](https://github.com/hlissner/emacs-doom-themes) to the latest, which includes a number of fixes, notably the faces for the minimap.
=> Bump doom-themes version

modules/lang/markdown/README.org, modules/lang/markdown/autoload.el
- Fix documented bound keys for `markdown-preview`
- Fix missing mention to `multimarkdown`
First PR to doom, yay!
=> Fix inaccuracy in markdown docs

modules/lang/org/README.org
I noticed that the links in `modules/lang/org/README.org` were still pointing to the original `jethrokuan/org-roam` repo so I've updated them to `org-roam/org-roam` as `org-roam` now has it's own *cough* org in Github. That's a lot of orgs.
=> Update org-roam hyperlinks in org/README.org

modules/lang/ruby/config.el
Without this tweak, its impossible to see the rspec results without manually up the page.
before
after:
=> better popup for rspec

modules/lang/org/config.el
These relatively new bindings (#3082) were lost during the rebase performed in #3043. This PR restores these, and also unifies the `org-agenda` bindings for deadline/schedule with the ones from `org-mode`.
=> Restore new org-agenda bindings

init.example.el, modules/lang/gdscript/README.org, modules/lang/gdscript/config.el, modules/lang/gdscript/packages.el
This commit adds the gdscript language module. It's a simple one as we packed all functionality in the gdscript-mode module, and lsp-support is built into lsp-mode.
Would it make sense to e.g. add an automatic lsp mode hook when the lsp module is available? or should there be a `+lsp` for that?
Closes #3229
=> Add gdscript module

modules/lang/web/+html.el
Elixir / Phoenix has a new file definition for LiveView templates. This ports over the same change that was added to the web-mode library in fxbois/web-mode#1070
=> Support LiveView templates in web module

docs/api.org
Replicates spacemacs' paste-transient-state, felt it may be useful as a starting example for something slightly more complex to make Spacemacs users feel more at home. I'm happy to move it if you feel it belongs somewhere else, and no love lost if you don't wish to include this at all.
=> Added paste-transient-state to API recipes

modules/config/default/+emacs-bindings.el
Change the space of the multiple-cursors keymap to a "-".
=> Remove space from mc prefix map

modules/tools/magit/config.el
This way, URL returned by remote are clickable. e.g.:
```
0 git … push -v fork refs/heads/magit-goto-address\:refs/heads/magit-goto-address
Poussée vers git@github.com:bersace/doom-emacs.git
Écriture des objets: 100% (6/6), 1.10 KiB | 1.10 MiB/s, fait.
Total 6 (delta 4), réutilisés 0 (delta 0)
remote: Resolving deltas: 100% (4/4), completed with 4 local objects.        
remote: 
remote: Create a pull request for 'magit-goto-address' on GitHub by visiting:        
remote:      https://github.com/bersace/doom-emacs/pull/new/magit-goto-address        
remote: 
To github.com:bersace/doom-emacs.git
* [new branch]          magit-goto-address -> magit-goto-address
updating local tracking ref 'refs/remotes/fork/magit-goto-address'
```
This is how it shows :
=> magit: Enable goto-address-mode in process buffer

modules/tools/lsp/packages.el
Forcefully install the gnu-elpa-mirror recipe of project makes it move
emacsmirror/project@0d31141 (0.1.3) -> emacs-straight/project@da0333a (0.3.0)
Fixes #3269
=> Bump :tools lsp

modules/lang/lua/README.org, modules/lang/lua/config.el
Add LSP support for `lang/lua` module
- lsp-mode provides a [configuration](https://github.com/emacs-lsp/lsp-mode/blob/master/lsp-clients.el#L762) for using [EmmyLua/EmmyLua-LanguageServer](https://github.com/EmmyLua/EmmyLua-LanguageServer), and since I'm currently using only eglot I didn't try to setup a lsp-mode configuration for [sumneko/lua-language-server](https://github.com/sumneko/lua-language-server)
- I purposefully left `TODO` items that should really act as questions
=> [lang/lua] Add LSP flag and support for Lua

modules/lang/org/autoload/org-capture.el, modules/lang/org/config.el
Prevents the frame opened by `+org-capture/open-frame` from immediately closing when refiling captured entry (`C-c C-w`).
The cause for the problem is that `org-capture-refile` performs capture finalization which triggers `org-capture-after-finalize-hook` and it causes early frame deletion.
=> Prevent doom-capture frame from closing when refiling

modules/lang/org/contrib/roam.el
Replaces the now obsolete org-roam-buffer-no-delete-other-windows
=> (org +roam): use org-roam-buffer-window-parameters

modules/lang/scheme/config.el
Initially I believed it would be a good idea to start the repl upon
entry into a scheme file, but this has so far preempted tools that rely
on direnv to create ad-hoc environments leading to not all dependencies
being availabe for scheme files. I had not realized how annoying this
could be because at the time all of my scheme libraries were installed
in my user environment.
Another reason for this change is it brings the scheme module back into line with
the repl based modules for other lisps like clojure.
=> unset geiser-mode-start-repl-p

modules/editor/multiple-cursors/config.el
Lispy commands in insert-state register only on one cursor, so this disables lispy temporarily when using evil-mc.
=> Add lispy to evil-mc-incompalible-minor-modes

modules/email/mu4e/README.org
Tiny documentation clean up for /modules/email/mu4e/README.org
Fixed some intra-document links.
@hlissner's dotfiles repo has been refactored, so I pinned the config example to an arbitrary point in time when the example still existed.
=> Updated Documentation for mu4e 

core/autoload/help.el, modules/lang/javascript/config.el, modules/lang/web/+html.el
Add a new mode: `typescript-tsx-mode` derived from `web-mode`.
Enable TSLint and ESLint for `typescript-tsx-mode`.
=> lang/javascript: Enable TSLint and ESLint for TypeScript-TSX

modules/config/default/+emacs-bindings.el
This bug exists only in Emacs flavor keybindings
=> Fix typo in function name binded to jump to an IRC channel

modules/ui/unicode/autoload.el
Fixes https://github.com/hlissner/doom-emacs/issues/3328.
The problem was simple: testing the variable `initial-window-system` is deprecated. One should call `(display-graphic-p)`
=> Make unicode-fonts-setup run when emacs is started in daemon mode

modules/config/default/autoload/search.el
The prefix arg for +default/search-project is intended to enable the
user to pick search location, however when it propagates to the ivy
search function it turns on the "search ignored files" functionality,
which us typically not intended and, furthermore, can be (if desired)
turned on simply by typing the search command in, for exampe,
counsel-rg's case as `-uu -- mysearchterm`
----
#
=> Don't set prefix-arg when delegating to ivy/helm from +default/search-project

modules/ui/unicode/README.org, modules/ui/unicode/autoload.el
+ Add documentation
+ Add support for doom-unicode-font as default candidate for non-latin glyphs.
Fixes https://github.com/hlissner/doom-emacs/issues/3329
=> :ui unicode module improvements

modules/lang/racket/README.org, modules/lang/racket/autoload.el, modules/lang/racket/config.el
- Fix Racket's `+lookup/documentation` in the same way as
https://github.com/hlissner/doom-emacs/commit/f20f477a44138d3bc8b
- Support the `+xp` feature which enables racket-xp. When it's not
enabled, default handlers to the traditional racket-repl
(which requires users to run code first)
=> Fix visit docs for Racket & support racket-xp

core/core-projects.el
It's already done for `rg`, and it's probably worth it to do the same for `fd` for consistency. Even though it's not the best to add ignored directories, users may expect that changing `projectile-globally-ignored-directories` will have effect of files search.
=> Make `fd` respect `projectile-globally-ignored-directories`

docs/getting_started.org
Change the emacs-plus icon from spacemac's logo to a more neutral modern emacs icon.
=> Change emacs-plus icon

modules/lang/scala/packages.el
lsp-metals was extracted out of lsp-emacs into a separate package. This change adds that separate package to the scala module when the lsp feature is selected.
Fixes hlissner/doom-emacs#3362
=> Add separate package for lsp-metals

modules/lang/python/config.el
Based on the discussion over here, the absolute path is needed to make conda work.
https://github.com/necaris/conda.el/issues/63#issuecomment-642404300
=> python: fix conda path

modules/tools/magit/README.org, modules/tools/magit/config.el
**What did you expect to happen?**
I expected to view my commit without delay.
**What actually happened?**
I wasn't connected to the internet and magit waited for the gravatar request to expire before it showed me the commit.
**Screenshot:**
https://i.imgur.com/twPRDAO.jpg
**Steps to reproduce:**
1. View a commit in magit
**Suggested change:**
In `modules/tools/magit/config.el`, change
```lisp
magit-revision-show-gravatars '("^Author:     " . "^Commit:     ")
```
to
```lisp
magit-revision-show-gravatars nil
```
(or remove it because the default is `nil`)
It should be opt-in because it's connecting to an external server.
https://github.com/hlissner/doom-emacs/issues/2333 might be related.
I've updated `magit/README.org` with the deleted line.
=> Gravatars now opt-in. Magit README updated.

modules/tools/lsp/packages.el
Now that straight.el fixed the bug upstream there's no reason to force it anymore
=> Remove forced project.el recipe hack

core/autoload/text.el
Context : https://github.com/joaotavora/eglot/issues/503
Fixes a bug where having eglot enabled in a buffer will make `SPC *` search the whole project for literally `LSP Identifier at point.`
=> Filter out 'eglot backend from doom-thing-at-point

modules/tools/eval/autoload/repl.el
"Wrong number of arguments: (_mode fn . plist), 0"
=> Fix error when opening REPL from unsupported mode

modules/config/default/+emacs-bindings.el, modules/config/default/+evil-bindings.el, modules/lang/org/contrib/roam.el
This function allows the creation of file references in org-roam, without opening org-capture
=> Org-roam: Add keybinding for org-roam-insert-immediate

modules/tools/magit/config.el
- Adds `magit-gitflow-popup` as `%` keybinding in the `magit-dispatch`, mirroring the keybinding in `magit-mode-map`.
- The existing binding `magit-worktree` is moved to `*`
Fixes #3410
=> Add gitflow and move worktree in magit dispatch

docs/modules.org, modules/tools/lookup/README.org, modules/tools/lookup/autoload/xwidget.el, modules/tools/lookup/config.el
Remove :tools/lookup +xwidget and provide `+lookup-xwidget-webkit-open-url-fn` instead so that we can manually configure Xwidget WebKit browser for `+lookup/online` or `+lookup/in-docsets`.
Fixes #3441.
=> tools/lookup: Update Xwidget WebKit browser support

modules/tools/lookup/config.el
Closes #3446
Just changing the default Rust Doc to be std library instead of editions guide.
=> change rust doc lookup to std library

core/core-projects.el
Essentially this makes projectile work properly (again?) when using tramp.
This causes the following (all of it on tramp):
- If `projectile-locate-dominating-file` is disabled then `projectile-find-file` doesn't work, which also makes `+ivy/projectile-find-file` only able to search in the current directory.
- It allows `projectile-vc` to work again (only on machines with the same OS).
- Projects are now added properly: they now appear with `counsel-projectile-switch-project` (accessible in Open project) in the dashboard.
- LSP autocompletion now includes files from the whole project (LSP still doesn't work properly though, see #3390).
I tested it with Emacs 26.3 and 27.0.91 , both with ssh and sshx.  The infinite loop was no longer present.
=> Enable projectile-locate-dominating-file on tramp

modules/lang/dart/packages.el, modules/lang/java/packages.el, modules/lang/python/packages.el, modules/lang/scala/packages.el, modules/tools/debugger/packages.el, modules/tools/lsp/packages.el
lsp-mode did a huge migration to use plists instead of hash-tables.
This PR bump all lsp related projects.
More info here: https://github.com/emacs-lsp/lsp-mode/issues/1751
=> Bump lsp packages

modules/config/default/+emacs-bindings.el
Adds a missing `featurep!` conditional to the Emacs bindings. The check is already in place for the Evil bindings.
=> Emacs bindings: Conditionally bind workspace keys

modules/ui/window-select/README.org
I clarified the pros and cons of the different window packages and added an example to show users how to customize the ace-window letter.
=> Clarify ace-window font size and add example

modules/lang/org/contrib/pomodoro.el
This adds notification support for pomodoros in org-mode when using MacOs via [terminal-notifier](https://github.com/julienXX/terminal-notifier). 
Growl is propietary commercial software and libnotify doesn't seem to work properly on Catalina.  The list of supported alert styles in alert.el is [here](https://github.com/jwiegley/alert/blob/master/alert.el#L134)
In order to test it:
1. Install terminal-notifier ( `brew install terminal-notifier` helps)
2. Enable the `+pomodoro` flag
3. Open / create an org file with a headline
4. Put the cursor under the headline
5. Start and end a pomodoro immediately with `M-x org-pomodoro`
6. Give terminal-notifier accessibility permissions if it asks for them.
=> Add terminal-notifier support for org-pomodoro

modules/term/vterm/doctor.el
According to [emacs-libvterm](https://github.com/akermu/emacs-libvterm#requirements), `libvterm` is an optional dependency and not required to compile. 
I am seeing this manifest in my system on Ubuntu 20.04 with `libvterm-dev` installed. It doesn't include the `vterm-ctrl` binary, but `vterm` works just fine in my install. However, `doom doctor` persists with the warning message.
=> remove doctor warning message for optional vterm dependency

docs/getting_started.org
The parameter is wrong. It must be --with-modern-cg433n-icon and not --with-modern-icon-cg433n
You can check it on the github repo site https://github.com/d12frosted/homebrew-emacs-plus
=> Update Mac Install for emacs-plus

modules/tools/magit/config.el
Hi!
This PR adds `zt` and `zb` motions to magit-mode since these two keybinds aren't mapped to anything by default, and `zz` motion already exists. I've been using the following snippet in my config for a while:
``` emacs-lisp
(map! :map magit-mode-map
:nv "zt" #'evil-scroll-line-to-top
:nv "zb" #'evil-scroll-line-to-bottom)
```
=> tools/magit: map zt/zb motions in magit-mode

modules/email/mu4e/config.el
Evil masks most of the keybindings that are set by mu4e-view-mode. Since
this is a read-only buffer anyway use Emacs for that mode.
=> Switch to emacs mode in mu4e view mode

docs/getting_started.org
There were a few links using `[[*header-name][Header Name]]`, resulting in dead links when rendered by github.
I changed then to `[[#header-name][Header Name]]`
I looked into others documentation files, and found no other instance of `[[*`
=> Fix deadlinks on "Getting Started" documentation file

modules/config/default/autoload/text.el, modules/tools/lsp/README.org
Clojure was not in the list, but the functionality exists.
Signed-off-by: Johan Thoren <jthoren@itrsgroup.com>
=> Added clojure to list of supported lsp languages.

modules/lang/lua/+lsp-mode.el, modules/lang/lua/config.el
Register a `lsp-mode` client for `lua-langserver`. 
This could go upstream eventually, but the quickest patch to get it working was to use the same doom utils as the `eglot` config
=> Add support for lua-langserver in lsp-mode

modules/config/default/+emacs-bindings.el
org-tree-slide-mode toggling binding was calling a non-existing (obsolete?) function.
It now call `org-tree-slide-mode` as evil bindings does.
=> Fix emacs binding for toggling org-tree-slide-mode

modules/emacs/undo/config.el
Since gpg files are explicitly meant to be encrypted it doesn't make a lot of sense to store undo data unencrypted. This commit adds gpg files to the `undo-fu-session-incompatible-files` list.
=> Make gpg files incompatible with undo-fu session

modules/config/literate/autoload.el
Literate configurations trigger issue #3266 when tangling on interactive save and epdfinfo is missing. For some reason, pdf-tools-install's prompt for installation ends up calling `message(nil)` which our `letf!`version does not handle well. My patch ignores these cases, which results in the prompt working and both epdfinfo installation and tangling succeeding when saving a literate config.
=> fix for #3266: wrong-type-arg stringp from format

modules/config/default/+emacs-bindings.el, modules/config/default/+evil-bindings.el, modules/editor/format/autoload/format.el, modules/tools/lsp/+eglot.el
* Fix evil key bindings for LSP shown even when lsp module is not enabled
* Make `SPC c f` use eglot LSP formatter when `+format-with-lsp` is `t` (like lsp-mode)
* Bind general implementation lookup handler
-> I do another PR:
https://github.com/hlissner/doom-emacs/issues/3251
=> tools/lsp: Improve eglot support

modules/tools/ansible/packages.el
paradoxxxzero/jinja2-mode@4540f99 -> paradoxxxzero/jinja2-mode@ecd19a4
----
This should fix #3555 as upstream has merged the PR to disable the indentation on save by default.
=> Bump :tools ansible; fix #3555

modules/lang/elixir/config.el
The built-in Elixir formatter uses an underscore to delimit long numbers. However, the generic regex for `highlight-numbers-mode` does not recognize them. This adds a mode-specific regex for `elixir-mode`.
I have also added direct support for font face on numbers to elixir-editors/emacs-elixir#459 if you have any feedback on that as well as I don't want things to conflict with `highlight-numbers-mode`
=> Support number highlighting for long Elixir numbers

modules/lang/python/README.org, modules/lang/python/config.el, modules/lang/python/packages.el
This should add pyright support to lsp-mode with an opt-in +pyright flag.
=> Add support for pyright language server

core/cli/packages.el
Adds experimental support for native-compilation, built on top of the experimental native-compilation support for straight.el (https://github.com/raxod502/straight.el/pull/507).
To play with this, you'll need an emacs built from the `feature/native-comp` branch, and the version of `straight.el` linked above.
=> [WIP] Support native compilation of packages

core/core-ui.el
Comint buffers like *Python*, *shell*, etc. will benifit from this
change as the prompt wont be deletable.
=> [UI] Set prompt to readonly in comint buffers

modules/tools/magit/config.el
Hi!
This PR will add `gi` and `gm` mnemonics in magit-mode to quickly jump to issues and pull requests respectively. I chose `m` for pull requests because `p` was already taken and it makes sense for GitLab users, not sure if GitHub users will agree.
P.S. I'm not sure if this is the proper way to go about it as I'm new to Elisp; please let me know if/how it could be improved.
=> tools/magit: map Forge jumps in evil-mode

modules/lang/org/doctor.el
org-roam fails with [very unhelpful](https://discord.com/channels/406534637242810369/406554085794381833/737720230507315200) errors when `sqlite3` executable is not found.
Perhaps checking it in `doom doctor` will make it a bit easier to find the problem.
=> org-roam: check for sqlite3 executable in doctor

modules/app/calendar/config.el, modules/app/calendar/packages.el
As mentioned in https://github.com/hlissner/doom-emacs/issues/3331 there's a dependency missing in calendar app module to be able to follow the README along and configure local diary source.
This PR fixes it.
=> Add calfw-cal dependency to allow local diary source

modules/app/calendar/README.org, modules/app/calendar/config.el
The example in the README to include org files from other sources in the calendar view doesn't really work, because the binding to `org-agenda-files` is lost e.g. when calendar view is refreshed.
Fortunately, there is the function `cfw:org-create-file-source` that allows us to list other org files in the content sources.
=> Change :app calendar README and add cfw:org-create-file-source to list of commands

modules/ui/tabs/config.el
The default modified marker looks unfit to the tab's height and font size, the smaller one is more appropriate.
=> ui(tabs): use a smaller dot to show unsaved file status

modules/editor/file-templates/autoload.el
Currently, when I create a `.el` file anywhere in `doom-private-dir`, the automatically generated file header contains an absolute path. This PR fixes this issue by extending `+file-templates-get-short-path` to return a path relative to `doom-private-dir`, where applicable, as it already does with `doom-emacs-dir`.
=> Fix Elisp file template header in doom-private-dir.

modules/lang/racket/config.el
The problem is that at this point, flycheck-mode might not be active
yet. Calling flycheck-disable-checker will always call (flycheck-buffer)
which would result in an error: (user-error "Flycheck mode disabled")
=> racket-mode: avoid using flycheck-disable-checker

core/core-lib.el
Currently, `add-load-path!` doesn’t check for duplicates in `load-path`, because `cl-pushnew` tests for equality with `eql`. This changes the predicate to `string=`, fixing the bug.
=> Fix deduplication in add-load-path!

docs/getting_started.org
Emacs 27.1 has been released and emacs-plus (https://github.com/d12frosted/homebrew-emacs-plus) now installs 27.x by default.
=> Updates getting_started.org following the release of Emacs 27.1

modules/app/calendar/README.org
Link to actually mantained `org-gcal` repo
=> Update `org-gcal` repo link

modules/ui/pretty-code/config.el
This works for me using emacs HEAD (`emacsGit` from the [Nix emacs overlay](https://github.com/nix-community/emacs-overlay)) with Fira Code and Iosevka.
=> Enable native ligature support on emacs-28/mac

modules/os/tty/README.org
=> Fix typo in new os/tty module readme

modules/emacs/dired/config.el
`dgi-commit-message-format` set to
`%h`  - Abbreviated commit hash
`%cs` - committer date, short format (YYYY-MM-DD)
`%s`  - subject
First two are fixed-width, which makes it look neater.
`dgi-auto-hide-details-p` set to `nil`, assuming a wide window.
I'm not sure if these are supposed to be inside `use-package!` after reading the previous commits to the file.
Screenshot:
=> Configure dired-git-info variables

modules/lang/julia/config.el
Hi!
This commit fix some problems related to highlighting math operators in Julia that created some problems like https://github.com/JuliaEditorSupport/julia-emacs/issues/141
The problem is that, different from MATLAB, Julia can have function and variable names with `!`. Thus, I tried to address some cases, like `!` before an empty space or beginning of the line. However, there things like `a==!var` or `(!var)` is also valid but cannot be treated inside this function. For a full support, we would need a full parser.
I also add some tweaks for `:` (which defined a symbol) and also added the operator `===`.
Before:
After:
=> Improve highlighting of Julia operators

modules/email/mu4e/README.org
As Ubuntu does not include mu4e with the mu package I added a step to
tell the use to install mu4e and add it to their load-path. I have also
added a find command to find the directories likely to have mu4e in them
=> adding another trouble shooting step to make sure mu4e is loaded properly 

modules/ui/hydra/README.org
Not a big deal but I found this typo.
=> Fix typo in `:ui hydra` module readme

docs/getting_started.org
https://www.archlinux.org/packages/extra/x86_64/emacs/
We could point to emacs-git AUR package for emacs 28:
https://aur.archlinux.org/packages/emacs-git/
But I think the reference to emacs 27 was there simply because emacs 27
is the recommended version so I didn't include a replacement AUR link in this PR.
=> ArchLinux packages now have 27.1 as default

modules/lang/scheme/config.el
By default geiser will re-use an existing REPL with the same interpreter.  This doesn't work well when with multiple projects using dir-locals or direnv to provide project-specific settings that affect the REPL (ie. binary and library paths).
Support for per-project REPLs was added upstream; this patch enables it by default for doom.
Also disabling `geiser-smart-tab-p` because TAB needs to stay in its lane.
@elais ping
=> Use separate geiser REPLs per project

modules/ui/nav-flash/autoload.el
`vterm-mode` is morally equivalent to `term-mode` (but `vterm-mode` is not derived from `term-mode`), so I would expect functions that exclude `term-mode` to exclude `vterm-mode` as well.
=> ui/nav-flash add vterm to +nav-flash-blink-cursor-maybe

modules/input/layout/+bepo.el
The original function tries to map `C-c !` in
minibuffer-local-completion-map although `C-c` is a non-prefix key in
this map for bepo users
=> Fix #3783: advice org-completing-read in bepo

bin/org-capture
The `bin/org-capture` script was using `-eq`, which is a numeric comparison, and was producing an "integer expression expected" error. Changed to `=`, the string comparison operator.
=> [Fix] string comparison in TERM check in org-capture

modules/config/default/config.el, modules/input/layout/+bepo.el
Contains 2 fixes
It looks like we are not using helm-ag anyway
The old method was too eager and, when using `:completion helm`, no completing-read can be performed because of void variables on the maps (helm-rg and helm-read-file)
=> [Fix] be lazier for minibuffer maps in :layout bepo

modules/checkers/syntax/config.el
It's faster and stylistically compliant.
=> Change the warning prefix to a non-unicode character

modules/lang/org/README.org, modules/lang/org/contrib/present.el, modules/lang/org/packages.el
The +present option now automatically checks out the reveal.js
repository and configures org-re-reveal to use it. It also now uses
reveal.js 4 instead of 3.9.2.
=> Automatically download reveal.js and use local copy, default to v4

core/cli/packages.el
Fixes #3257 
This prevents auto-generated files like .DS_Store on macOS from causing an error when running `doom sync`
=> Filter directories when rebuilding straight repos

modules/config/default/autoload/deferred.el
Non evil environment error
<details><pre>
Debugger entered--Lisp error: (void-variable evil-this-operator)
(if evil-this-operator (progn (where-is-internal evil-this-operator evil-normal-state-map t)))
(progn (if evil-this-operator (progn (where-is-internal evil-this-operator evil-normal-state-map t))))
eval((progn (if evil-this-operator (progn (where-is-internal evil-this-operator evil-normal-state-map t)))) t)
elisp--eval-last-sexp(nil)
eval-last-sexp(nil)
eros-eval-last-sexp(nil)
#<subr funcall-interactively>(eros-eval-last-sexp nil)
apply(#<subr funcall-interactively> (eros-eval-last-sexp nil))
funcall-interactively(eros-eval-last-sexp nil)
#<subr call-interactively>(eros-eval-last-sexp nil nil)
apply(#<subr call-interactively> (eros-eval-last-sexp nil nil)) …
=> Fix non evil environment (void-variable evil-this-operator)

modules/lang/javascript/config.el, modules/lang/javascript/packages.el
This allows one to use `xref-find-definitions-other-window` which has no (working) counterpart in tide itself
=> Upgrade tide, enable xref-tide-xref-backend

core/core-packages.el
This was added to straight with the original native-compilation support, but apparently never worked for Doom package definitions!
=> Allow :no-native-compile in package recipes

modules/completion/ivy/README.org
=> Fix typo Ivy README.org

modules/config/default/+evil-bindings.el, modules/input/layout/+bepo.el, modules/input/layout/README.org, modules/input/layout/autoload/bepo.el
Fixes #3858
This is the biggest, most meaningful change. Using `evil-collection-translate-key` instead of `general-translate-key` prevents all the void-variable errors that happened because the general utility doesn't defer the key remapping on keymaps that aren't defined yet. See emacs-evil/evil-collection#368
There are changes that are not necessarily oriented only to evil users, so splitting these off makes sense to know what you get if you enable this module without evil enabled.
=> :input layout bepo enhancements

modules/checkers/spell/autoload/+flyspell.el
This addressed #3890 and #3935
``+spell/add-word`` expects `flyspell-get-word` to return as a string
the current word. Instead, it returns a list of the form
`(<word> <start-pos> <end-pos>)`.
=> Fix `+spell/add-word` when using flyspell

modules/editor/snippets/config.el
Auto load when `yas-activate-extra-mode` or `yas-deactivate-extra-mode` is called. These functions are called in `.emacs.d/modules/editor/snippets/autoload/snippets.el` by function `+snippets-enable-project-modes-h`, which may be called before yasnippet is loaded.
=> Load yas when yas-activate-extra-mode is called

docs/getting_started.org
Original link to company module in section "Writing your own modules" was pointing to a malformed path. This changes it to point to the correct path of the company module readme.
=> Fix link in gettting_started.org

docs/getting_started.org
Remove fat formatting that interferes with inner monospace/code formatted text.
This caused "=" and "~" signs to be displayed (at least in the browser, on the github readme page).
=> Fix conflicting text formats in "getting started" steps.

modules/lang/agda/config.el
agda2-mode has its own function for jumping to a definition, which this adds as a lookup handler.
=> Add lookup handler to Agda module

modules/editor/evil/config.el
Added they Evil keybinding `SPC w T` for `tear-off-window` since that is a fairly useful windowing function.
This is just a simple 2-line change, but I thought it would be a nice addition.
=> Add keybinding for tear-off-window

modules/config/default/+evil-bindings.el
Add SPC / alias for "Search project" (SPC s p)
- Searching is one recurring action by developers
- Spacemacs has the same keybinding,
so it close one gap between Spacemacs and Doom keybindings (#2542)
- It's consistent with SPC * "Search for symbol in projet"
as it's Vim "*" and "/" equivalent but project-wide
=> Add SPC / in evil-bindings

docs/modules.org, modules/checkers/spell/README.org, modules/checkers/spell/config.el
Support using [Enchant](https://abiword.github.io/enchant/).
Main motivation is using other backends than aspell/hunspell, but those can be used through enchant as well.
=> checkers/spell: add support for using enchant

modules/config/default/+emacs-bindings.el, modules/config/default/+evil-bindings.el, modules/ui/doom/packages.el, modules/ui/fill-column/autoload.el, modules/ui/fill-column/packages.el, modules/ui/indent-guides/packages.el, modules/ui/minimap/packages.el, modules/ui/modeline/packages.el, modules/ui/tabs/packages.el, modules/ui/treemacs/packages.el, modules/ui/window-select/packages.el, modules/ui/workspaces/packages.el, modules/ui/zen/packages.el
Emacs 27 introduced `display-fill-column-indicator-mode` which replaces `hl-fill-column`. This commit adds some conditionals to use `display-fill-column-indicator-mode` on Emacs 27+, or falls back to `hl-fill-column-mode` on older versions.
This also fixes the deprecation message so I removed it. Once Emacs 27 is more common I would suggest marking it as deprecated again and removing the module entirely. I'll add the message back if you still want it there.
I suggest merging #3815 first since that adds documentation which I can update to match this change.
Any and all suggestions welcome! I'm not great at Elisp yet and in particular the `add-hook!` macro gave me trouble which led to a bit of repetition in the code.
=> Improve fill-column module for Emacs 27+

modules/ui/doom-quit/config.el
Fixes a missing word in Cave Johnson's legendary quote
=> Add missing 'the' in Portal 2 quit message

modules/input/layout/+bepo.el
w has the same location as é and é is not used so might as well go all the way
=> [bepo] Map ace window to <leader>éé (from ww)

modules/checkers/spell/config.el
It causes aspell 0.60.8 to fail with message `the key "check-tex-comments" is unknown`.
=> modules/checkers/spell: remove tex option

modules/tools/direnv/README.org
In Archlinux,  `direnv` is available though the AUR, not the official repositories.
=> Fix installation instructions for Archlinux in direnv/README.org

modules/lang/json/config.el
These are the keybindings currently under `C-c`, with some modifications to fit evil conventions.
=> Add `json-mode` keybindings under the local leader

modules/lang/java/doctor.el
Code formatting in Java doesn't work without clang-format, but no
warning is shown in `doom doctor`.
=> Added warning for clang-format in doom doctor.

modules/checkers/spell/config.el
Changes the default ispell dictionary from "en" to "english" since the
former isn't actually a default dictionary name listed in ispell. See
https://github.com/emacs-mirror/emacs/blob/9f30a6b1a417cebe795956a7eef44b8cd9b71557/lisp/textmodes/ispell.el#L471
Otherwise, enabling checkers/spell doesn't do anything even if aspell and the
aspell-en dictionary are installed according to the module README file.
=> checkers/spell: fix default ispell dict

core/packages.el
A recent update to evil that affects the behavior of tracking jumps across buffers caused `better-jumper` to add unnecessary jumps every time a buffer boundary was crossed. The most recent version fixes that. (#4050)
=> Pin new version of `better-jumper`. Fixes #4050

core/autoload/help.el
On many installations, the .el files that are builtin to emacs are
compressed. We should search these as well.
=> Search compressed .el files in load history

modules/lang/latex/packages.el
jwiegley/auctex@59e251c -> jwiegley/auctex@9e7406c
iyefrat/evil-tex@06234c9 -> iyefrat/evil-tex@a3b6875
iyefrat/evil-tex#3 fixes selection/navigation in LaTeX files which are not the root document and makes section regex-matching more strict, to avoid partial matching.
=> Bump :lang latex

modules/lang/cc/autoload.el, modules/lang/cc/config.el
Most of these changes come from MaskRay's private configuration found
here :
https://github.com/MaskRay/Config/blob/c078dfad340041673f2e056729a44c3df05a6248/home/.config/doom/modules/private/my-cc/config.el
- Limit ccls threads to be maximum half the available core count
- Add wrappers to call ccls LSP extensions
- Enable ccls-code-lens-mode
- Set initial state to emacs when navigating ccls-tree
- Use 'font-lock for semantic highlighting, making the speed choice
according to variable's docstring
=> Add ccls-specific configuration

modules/tools/magit/autoload.el
This fixes the behavior of e.g. magit-diff-show-or-scroll-down.
When in magit-log-mode, said action should not move focus to the diff
window because it would otherwise behave identical to pressing
magit-show-commit.
When reviewing the change history of a series of (especially small) commits, the current behavior of `+magit--display-buffer-in-direction` is annoying because the focus is always put into the diff with the changes and I have to move back to the magit-log window quite a lot. With the following bindings, I just have to press j/k and ,/; to quickly scroll through the changes of the diff and I can use my left hand to drink some coffee while doing so. :-) It's also the way magit behaves by default.
```elisp
(use-package! magit
:bind
(:map magit-log-mode-map
("," . …
```
=> Respect magit-display-buffer-noselect

modules/lang/clojure/README.org
Adds a table describing the key bindings under `localleader` in clojure-mode.
I had to use zero width spaces to get the table to render correctly for bindings ending in single or double quoutes. [The org-mode mailing list explains the problem and workaround.](https://lists.gnu.org/archive/html/emacs-orgmode/2010-04/msg00330.html).
=> Add table describing keybindings for clojure module

core/cli/autoloads.el, core/cli/packages.el, core/core.el, core/packages.el
Adds ahead-of-time compilation of all packages on load-path, ensuring all core and site Elisp is actually native-compiled.
Exports `comp-deferred-compilation-black-list` to runtime, bringing us one step closer to properly supporting deferred compilation.
WARNING: There are currently some upstream bugs which makes testing this PR difficult:
1. Ensure that `~/.emacs.d/eln-cache` exists.
2. Run `emacs -q`, wait for async compilations to finish.
3. Ensure that `~/.emacs.d/.local/cache/eln` exists.
4. Run `doom sync`.
5. Run `doom build -r`, kill it when it hangs on "Waiting for NNN async jobs".
6. Run `doom build -r` again, it will work this time, wait until it finishes.
7. Run `doom build -r` again, it should have nothing to rebuild.
8. Run emacs!
=> Improvements to native-comp support

modules/lang/org/packages.el
Just cleans up the residue
Signed-off-by: Brian McGillion <brian@ssrc.tii.ae>
=> [:lang (org +roam)] company-org-roam is depricated

modules/tools/magit/README.org
Mention how to turn on granular diffs for all hunks, as requested in #4109.
=> tools/magit: add magit-diff-refine-hunk to readme

modules/ui/popup/config.el
Its content is typically thrown away after a quick glance, so make it popup.
=> popup: add rule for list-processes

modules/lang/scala/README.org
This pull request adds basic documentation for the `scala-mode` and specifically using it with LSP. This should contain enough information to get users up and running with LSP properly along with pointers to the metals emacs documentation.
I modeled this readme after the one for `java-mode`. Let me know if I should make any changes to it.
=> Add scala module documentation

modules/editor/format/config.el
Fixes #3626
To fix this, 
```lisp
(format-all-mode +1)
```
Was replaced with:
```elisp
(+format-on-save-h)
```
This ensures that `+format/buffer` is used instead of `format-all-buffer`
In the function `+format-on-save-maybe-h` located in `modules/format/config.el`
=> Format with LSP if supported on save

modules/lang/python/config.el
It is now obsolete, it has been renamed to `python-pytest-dispatch` in
https://github.com/wbolster/emacs-python-pytest/commit/ee61741d4e35dc639b5e269efaa488d743da9c35
Not sure if we need to update the keybindings, though.
=> Fix python-pytest-popup

modules/editor/evil/autoload/textobjects.el
Add typographic single quotation marks to ‘any quote’ text objects.
(It could be argued that «guillemets» should be added too, but what is considered the left and right varies between languages, so I decided against adding them.)
=> Add single quotes to ‘any quote’ text objects

modules/lang/scala/config.el
Metals (the scala LSP server) does not support formatting blocks of code and does appear to be interested in adding it in the future. This pull requests disables lsp indentation when using `+lsp` in `scala-mode` so that emacs will fall back to using indentation provided by `scala-mode` versus providing no indentation at all.
Relevant issue on formatting within Metals: https://github.com/scalameta/metals/issues/1649
=> Disable lsp indentation in scala mode

core/autoload/store.el
Explicitely states that a `nil` TTL means "no expiration"
Make it clearer that TTL is an offset to current-time, and not a timestamp in seconds
=> Clarify doom-store-put docstring

modules/lang/python/config.el
Added a keybinding for a "test all functions" for pytest analogue to "a" #'nosetests-all.
=> Add keybinding for testing all project functions with pytest

modules/lang/markdown/config.el
Added Mathjax to html previews for markdown.  This can be tested by running `markdown-preview` on some markdown file.
Before:
After:
=> Add mathjax support for markdown preview

modules/lang/php/README.org
Add some explanation for phpactor server and its prerequisites in `modules/lang/php/README.org`.
=> fix: add explanation for php document

modules/lang/latex/config.el
=> delete extra paren in :lang latex

modules/editor/format/config.el
Having this on renders it difficult to work with debug-on-error, since a
_lot_ of filetypes don't have formatters
=> Suppress format-all-mode error when no formatter is available

modules/lang/python/config.el
Implements #3826.
Enable `poetry-tracking-mode` in the first `python-mode` buffer (if `python +poetry` enabled).
=> Enable poetry-tracking-mode

modules/lang/org/config.el
Fixes Windows file share paths from a forward slash to a back slash.
Has been tested and resolves #4212
=> Fix Issue #4212; Use Back-Slash for Win FileShares

modules/term/eshell/config.el
`eshell-buffer-shorthand` was removed in Emacs 25, see https://github.com/emacs-mirror/emacs/blob/master/etc/NEWS.25#L1078-L1082
=> Remove eshell obsolete variable

modules/completion/helm/config.el
This PR addresses the issue discussed [here](https://discord.com/channels/406534637242810369/406554085794381833/773488497515429889).
The suggested solution of changing `helm-completion-style` did not work for all cases, since some helm commands (e.g. `helm-M-x`) use `completion-styles` nonetheless. I opted for moving the helm styles to the back of `completion-styles` to have them act as a fallback.
=> Demote overly aggressive completion styles

modules/tools/ansible/config.el
Ansible roles _often_ have a `tasks/main.yml` file in them, and benefit
from some of the nice ansible syntax highlighting.
=> Add detection for projects that are ansible roles

modules/config/default/+emacs-bindings.el, modules/editor/fold/README.org, modules/editor/fold/config.el
This PR adds emacs bindings for vimish-fold when evil is disabled. It also adds documentation for the bindings. Finally, it reports a weird bug and explains a way to bypass it.
=> Add emacs bindings and documentation in fold module 

modules/ui/doom-dashboard/config.el
The dashboard banner looked like this for me:
```
=================     ===============     ===============   ========  ======== 
\\ . . . . . . .\\   //. . . . . . .\\   //. . . . . . .\\  \\. . .\\// . . // 
||. . ._____. . .|| ||. . ._____. . .|| ||. . ._____. . .|| || . . .\/ . . .|| 
|| . .||   ||. . || || . .||   ||. . || || . .||   ||. . || ||. . . . . . . || 
||. . ||   || . .|| ||. . ||   || . .|| ||. . ||   || . .|| || . | . . . . .|| 
|| . .||   ||. _-|| ||-_ .||   ||. . || || . .||   ||. _-|| ||-_.|\ . . . . || 
||. . ||   ||-'  || ||  `-||   || . .|| ||. . ||   ||-'  || ||  `|\_ . .|. .|| 
|| . _||   ||    || ||    ||   ||_ . || || . _||   ||    || ||   |\ `-_/| . || 
||_-' ||  .|/    || ||    \|.  || `-_|| ||_-' ||  .|/    || ||   | \  / |-_.|| 
||    ||_-'      || || …
```
=> ui/doom-dashboard: center bottom line of banner

modules/lang/org/config.el
As of emacs 27.1 we can evaluate org-babel emacs-lisp src blocks that manage the UI. This PR comes from a discussion in the upcoming discourse to backport that functionality. 
This also preludes an experimental project to provide an interactive guide for doom-emacs to better introduce users to customizing their emacs experience with emacs-lisp in Doom.
=> Created PR to backport emacs-lisp org-babel evaluation to manage the UI

modules/lang/org/contrib/roam.el
Update to the latest functions - after the following commit:
https://github.com/org-roam/org-roam/commit/47e83f7d
Org-Roam-Dailies deprecated the older forms of the functions
and replaced with the new constructs.
Signed-off-by: Brian McGillion <brian@ssrc.tii.ae>
=> :lang org: (+roam) Replace deprecated functions

modules/lang/org/contrib/roam.el
This PR makes it so that `org-roam-db-location` is treated in the same way as `org-roam-directory`.
=> Do not overwrite user's value of org-roam-db-location

modules/checkers/spell/autoload/+spell-fu.el, modules/checkers/spell/config.el
If aspell (or a spell-fu acceptable equivalent) cannot be found, 
warn the user. If +spell-correct-interface is not bound, bind it.
Remove previous hack. It prevents use of +spell/correct if spell-fu does
not try to highlight a word. This is extreamly common is docstrings, for
example. I think having +spell/correct should check any word it is
called upon, even without general text highlighting.
=> Fix behaviour without aspell

core/core.el
Sometimes compiling this file hangs; adding it to the compilation black-list prevents that.
Re: #3655
=> Add with-editor.el to the compilation black-list

core/core.el
Something in `jupyter-channel.el` of emacs-jupyter does not get compiled correctly and raises void-variable jupyter-channel errors, see https://github.com/nnicandro/emacs-jupyter/issues/297.
I initially fixed it for myself by putting this in my `packages.el`:
```elisp
(package! jupyter :recipe (:no-native-compile t))
```
But some more testing suggested that preventing native compilation for just `jupyter-channel.el` also works, so I put that in this PR.
=> Prevent native compilation for emacs-jupyter

modules/lang/racket/README.org, modules/lang/racket/config.el
`racket-mode` has an optional unicode input mode that replaces Greek letter names with unicode Greek characters (ex: 'pi' -> 'π'). Doom enables this input mode by default for `racket-repl-mode` buffers, but not for `racket-mode` buffers. This PR removes the `racket-repl-mode` hook and adds some documentation about `racket-mode`'s unicode input mode to Doom's Racket plugin readme. An alternative would be to enable unicode input for both modes, but some Racket DSLs don't interpret `λ` as `lambda`.
=> Remove unicode input mode default from Racket REPL

modules/editor/god/config.el, modules/editor/god/packages.el
In this change:
* Bump version pin of `god-mode`
* Call [`which-key-enable-god-mode-support`](https://github.com/justbur/emacs-which-key#god-mode) after loading `which-key` to enable support for `god-mode`. Prior to this change, keys entered in `god-local-mode` will not invoke `which-key` :no_entry:
As always, any feedback is more than welcome!
=> Enable god-mode support for which-key if required

modules/input/japanese/config.el
If we enable `:input/japanese` and press Esc before autoloading `skk`, an error occurs: 
```
Symbol's function definition is void: skk-mode-exit
```
This PR forces to load `skk` when calling `skk-mode-exit`.
=> input/japanese: Do not eval skk-mode-exit if ddskk not loaded

core/core-lib.el
I was browsing the source trying to understand how/when these doom hooks get triggered and found this TODO. Hope this description is accurate and helpful!
=> core-lib: Add docstring for add-hook-trigger!

core/cli/packages.el, core/core.el, core/packages.el
Renamed `comp-deferred-compilation-black-list` to `comp-deferred-compilation-deny-list`.
Removed the `late` load flag which is no longer required.
Added a check against the deny list when compiling all Elisp on the load-path, so we don't inadvertently compile something we shouldn't.
This change depends on https://github.com/raxod502/straight.el/pull/637.  I've added a hacky commit here to depend on the patched version of straight; that needs to become a proper bump commit once it's merged upstream.
=> Update for the latest native-compile-async API

modules/lang/org/README.org
This was removed in https://github.com/hlissner/doom-emacs/pull/4081.
=> remove company-org-roam from lang/org/README.org

modules/config/default/+emacs-bindings.el, modules/lang/org/contrib/roam.el
"t" to tag a roam file with the `#+roam_tags` property.
"T" to untag the file
=> Add keybindings for roam tagging

modules/tools/rgb/README.org
This readme still contains comments from the template and a double space. Sorry about that!
=> :tools/rgb minor README fixes

modules/completion/ivy/config.el, modules/completion/ivy/packages.el
`ivy-avy` makes it possible to select a candidate with `avy` by using `C-'` in an ivy minibuffer.
This functionality used to come with `swiper`, but it was split: https://github.com/melpa/melpa/pull/6951
This could be added as a module flag as well.
Also, I'm not sure if this keybinding should be added to the ivy module documentation.
=> Add `ivy-avy`

core/cli/byte-compile.el
When compiling standalone files such as `init.el`, instead of saying
that it belongs to module `nil nil`, say that these files are
standalone.
=> Improve byte compilation message

modules/lang/emacs-lisp/config.el
In `+emacs-lisp-append-value-to-eldoc-a`, if the `frame-width` of the minibuffer
is smaller than the length of the documentation + " [...]" + 1, a negative
maximum %s bound is passed, causing the error in the title.
Fix this by clamping the computed LIMIT to 0.
If needed, I can make a full issue, but I hope that from my description, the cause is clear: `limit` = `(frame-width)` (minibuffer, in eldoc) - `(length str + length " [...]" + 1)` -> can be negative -> error.
=> Elisp `eldoc': fix "Invalid format operation %-"

modules/tools/magit/config.el
"Fix blacklisted evil-collection-magit keybinds" had one too many
closing parens. 2828281af7d0c5fc05a94d2b1c0a3417b318f414
=> magit: fix mismatched paren in parent

core/cli/upgrade.el
Previously, `doom upgrade` would emit:
```
New revision: fatal: amb (fatal: ambiguous argument '_upgrade/HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
```
It appears it's not possible to remote revisions with
`<remote>/<revision>`. Instead, we fetch the upgrade remote into a named
revision and then use it.
=> Fix doom upgrade

core/cli/upgrade.el
Use `doom-repo-url` in diff url to show diff.
=> Unhardcode upstream repo in diff url

modules/checkers/grammar/config.el
Macports is quite popular a way to install some application to macOS and it is shame that it doesn't support such way by default.
=> grammar: macports compatibility

modules/completion/ivy/config.el
fix #4344 
tries to get the filename and if it's not set -> return `""`
That's the first first time I got an elisp functions to do what I want ;)
Getting there :)
=> counsel-bookmark use filename only if available

core/cli/upgrade.el
`doom-cli-upgrade` calls `git fetch` to fetch remote branch and tags and check output code of this command to complain when it failed.
It fails when remote server isn't available that is good.
But it also fails when it can't to fast-forward a branch that will be used to upgrade doom-emacs.
The last case created a loop and the only way to broke this loop is remote a branch that should be used for upgrade.
Unfortunately user has no idea about branch name and can't do anything, just enjoy crash with `Failed to fetch from upstream` message.
This commit added `--force` flag to `git fetch` that forces it to overwrite branch that is used to upgrade that prevent such loop.
It also fixed https://github.com/hlissner/doom-emacs/issues/4346
=> upgrade.el: force fetch

core/cli/upgrade.el
The upgrade process leaves a left over ref:
```
$ git branch
...
_upgrade_HEAD
...
```
This commit deletes that.
=> Upgrade: remove leftover ref

modules/checkers/spell/README.org
The original instruction made nix install the language packages in different directories than the `aspell` package.
Use solution provided here https://github.com/hlissner/doom-emacs/issues/4138#issuecomment-717266771
closes https://github.com/hlissner/doom-emacs/issues/4138
=> fix nix aspell installation instructions

modules/config/default/+emacs-bindings.el, modules/config/default/+evil-bindings.el
`org-roam` changed its `org-roam-dailies`-interface recently: https://github.com/org-roam/org-roam/commit/47e83f7d3f7fbc8d35af4e9314715e4483c04d86
(This already got fixed for the `org +roam` module in 6225cc5337bfd23dd2311566bdc5aca42669a41c, but not for bindings in the `default` module.)
=> config/default: update deprecated org-roam-dailies bindings

modules/checkers/spell/autoload/+spell-fu.el
`(bounds-of-thing-at-point 'word)` can return `nil`. This checks that it
does not, giving an `user-error` if no word is found. I think this is better
then the `(wrong-number-of-arguments (start . end) nil)` error message.
=> Add word existence checking for +spell/correct
