doomemacs/doomemacs

core/core-editor.el
`doom-init-smartparens-in-minibuffer-maybe-h` is responsible for enabling
`smartparens` in the minibuffer, which it does by checking `this-command'.
However, the list of commands doesn't include `edebug-eval-expression`,
preventing the mode from being enabled for it.
Fix this by enabling `smartparens` in `eval-expression-minibuffer-setup-hook`,
unconditionally, which means that anything using `interactive' "x" or
`read--expression` will work correctly.
To reproduce this:
1. `M-x eval-expression`: parens auto-close themselves
2. `M-x edebug-eval-expression`: parens don't auto-close themselves
3. Even more fun to debug: `read--expression`, called directly in the `interactive` form of `edebug-eval-expression`, has auto-closing parens for some reason.
Do you know when …
=> Enable smartparens for `edebug-eval-expression'

core/autoload/help.el
If called with a C-u prefix, `doom/help-modules` now browses the module's
directory instead of opening its documentation. This exposes the VISIT-DIR
argument to `interactive` use.
=> `doom/help-modules': C-u -> browse directory

core/core-editor.el
febf960 introduced a regression, in that it caused `smartparens-mode` to
no longer be enabled for `evil-ex`. This is because the latter doesn't
call `read--expression`, but calls the minibuffer directly instead.
Return `doom-init-smartparens-in-minibuffer-maybe-h`, enabling
`smartparens` for `evil-ex`. The hook responsibly for enabling it in
`eval-expression-minibuffer-setup-hook` was renamed to
`doom-init-smartparens-in-eval-expression-h`, since otherwise the naming
would have been awkward.
Also explicity enable `smartparens-mode` instead of toggling it.
=> Enable `smartparens' for `evil'

modules/lang/emacs-lisp/autoload.el
`+emacs-lisp-lookup-definition` does not work when browsing the directory of a
module, because, due to a possible bug in `counsel`, the visited buffer is not
immediately visible after calling `counsel-find-file` (unlike with `find-file`).
As such, the backend should return `deferred` for that case.
See abo-abo/swiper#2752. This should be removed once that PR is merged.
=> Workaround: fix goto definition on modules

modules/lang/python/README.org, modules/lang/python/doctor.el
Followed lang/python/config.el which already checks for python3
when setting the python-shell-interpreter.
Python version naming is a hot mess:
https://www.python.org/dev/peps/pep-0394/
=> Add "python3" to possible names for the python binary

modules/ui/popup/autoload/popup.el
Function (buffer-file-name) always returns nil with indirect buffer as
an argument. Extracting base buffer and checking if base buffer visiting
file fixes data loss in indirect buffers showed in popups.
E-mail thread in the org-mode mailing list:
https://lists.gnu.org/archive/html/emacs-orgmode/2020-12/msg00085.html
=> popup.el: consider auto-saving indirect buffers too

modules/editor/format/autoload/format.el
Only attempt to format the org source block if the point is in it, else do nothing.
`format-all-buffer` failing to look up the formatter for Org mode is causing issues like #4319 . Instead of just excluding this, this PR uses a compromise: only format the code block region the point is currently in, if any.
I don't like this workaround, but it is the best compromise I can think of and it prevents this common error.
I'm not sure what the idiomatic way to format normal org text on save would be, but `format-all-buffer` seems to be for LSP formatters, not for internal Emacs formatting (as far as I can tell).
=> A workaround for formatting org mode

modules/lang/org/contrib/journal.el
This allows functionality like completion of org-roam items seamlessly work in org-journal-mode files too.
Same setting is already set for org-mode itself.
=> Prioritize company-capf back-end in org-journal

modules/completion/ivy/config.el
There are two hydras that can be opened from ivy interface:
1. `ivy-dispatching-done` (doom key: `"C-o"`, vanilla key: `"M-o"`)
2. `hydra-ivy/body`           (doom key: `"M-o"`, vanilla key: `"C-o"`)
Original behavior is that they both can be exited / toggled by the same key they were opened.
This PR:
1. sets hydra as default interface for `ivy-dispatching-done`
Contrary to original assumption outlined in https://github.com/hlissner/doom-emacs/issues/4427 hydra works just fine as `ivy-dispatching-done` interface. Regression introduced in https://github.com/hlissner/doom-emacs/commit/c4a0174fe2d02741df73e1ff97fa56b2c3ea2a42 was a result of assigning function to the wrong kind of variable.
2. restores the original toggle behavior but does it without reverting the decision to swap the …
=> Better ivy hydras usability

modules/os/tty/config.el
`(xclip-mode +1)` will raise an error when `xlip` is not found, which can interrupt the whole initialization process.
=> Do not panic when xclip is not available

modules/term/eshell/autoload/eshell.el
`+eshell/split-window` eventually calls `+eshell--bury-buffer`, which
invoked `+eshell/here` with `t` instead of a command string, erroring.
=> Fix `+eshell/split-window' error

core/packages.el
When utilizing workspaces, upon creating a new perspective and switching to that perspective, `persp-mode` will use the current window (and all of it's associated properties) as a basis for the new perspective and as a result, the current window's jump list is leaked into the new perspective. This causes jumps to be shared between multiple perspectives instead of being properly isolated between them.
The new version of better jumper contains added protections to ensure that a jump list is never leaked into a new perspective. Anytime a new perspective is created, better jumper will initialize it with an empty jump list when it is activated.
More details here: #2826
=> Bump better-jumper. Fixes #2826

core/core-packages.el
The `:ignore` (or `:built-in`) property for the `package!` macro currently doesn't work as intended when packages are installed as dependencies of another package. I noticed this behavior while attempting to replace Doom-managed packages with Nixpkgs ones:
```nix
emacsWithPackages (epkgs: with epkgs; [ emacsql-sqlite3 pdf-tools ])
```
```elisp
;; packages.el
(package! emacsql-sqlite3 :built-in 'prefer)
(package! pdf-tools :built-in 'prefer)
```
```elisp
;; init.el
(doom!
...
:tools
pdf
...
:lang
(org +roam)
...
)
```
```console
$ doom -y install --no-config
...
→ Building saveplace-pdf-view...
→ Building saveplace-pdf-view → Cloning pdf-tools...
→ Building saveplace-pdf-view → Cloning pdf-tools...done
→ Building saveplace-pdf-view → Building pdf-tools...
→ Building saveplace-pdf-view → …
```
=> Respect the :ignore property for packages installed as dependencies

modules/lang/org/doctor.el
- Added platform-dependent checks for some of the executables needed for
org-download-clipboard to work.
- Fixed a typo in one of the error messages for org-roam.
----
#
=> Add checks for executables needed by org-download

modules/lang/scheme/config.el
With `:lang racket` enabled, `scheme-mode` still pops up on `.rkt` files.
=> Disable scheme-mode for .rkt files if :lang racket

core/autoload/packages.el
The function expects 'package' to be a symbol instead of a string.
=> Fix interactive call of doom/bump-package

core/core-projects.el
I have `projectile-index-method` set to `alien` as using `hybrid` is too slow in my project of around 3800 files when cache is disabled (I disable cache since I switch branches often and was constantly deleting my cache).
When using `alien` `.git` files are being included which would otherwise be filtered by `'hybrid` so this PR passes a flag to exclude `.git` to `fd`.
Note that this is already being done in the `rg` fallback below.
=> Add `--exclude .git` to fd in `projectile-generic-command`

modules/editor/snippets/autoload/snippets.el
This enables snippets to be accessed by UUID in parent modes of the
current mode. Prior behavior was to only look up for the current mode,
but the active modes (and those suggested in the prompt) include
parent-mode snippets (e.g., text-mode snippets when major-mode is org-mode).
The method `+snippet--get-exact-template-by-uuid` was a necessary clone of `yas--get-template-by-uuid` because the latter method does not handle lookups for modes that don't have any loaded tables that may be a parent of the queried mode.
For example, folks may have snippets in org mode and text mode, but the mode / parent order produces by `yas-modes-to-activate` adds outline mode between, which likely does not have a table.
I tested a few modes by calling `+snippets/edit` to ensure that snippets for the …
=> Improving snippet lookup behavior

modules/lang/emacs-lisp/config.el
`+emacs-lisp-append-value-to-eldoc-a` `error`s if the symbol isn't
bound, because `symbol-value` errors in that case. Fix that bug by only
modifying the result of `elisp-get-var-docstring` if the symbol is
bound.
=> Emacs-lisp eldoc: fix error if symbol unbound

modules/lang/markdown/config.el
This PR adds ~20 insert commands leader keybindings to markdown (inserting headings, code blocks...) with descriptions.
After pressing <kbd>leader</kbd><kbd>m</kbd><kbd>i</kbd>, you get this:
Let me know if I should change anything! I wasn't sure about "Header dwim", I don't know what "dwim" means; it creates a heading level the same level as the previous one.
=> Markdown: add keymap for insert commands

core/core-projects.el, modules/completion/ivy/config.el
Fix #3215 
With 523e945a3ae2347bae556ec4fe367d03ffddf8f0 we only prevent path auto expand in Git Bash.
To fix this on MSYS2, we need `MSYS2_ARG_CONV_EXCL=--path-separator`.
We need no space between `--path-separator` and `/` otherwise it still get auto expanded.
Detail https://github.com/sharkdp/fd/issues/537#issuecomment-636422669
=> Fix path separator in msys2

modules/lang/ocaml/README.org
This updates and corrects the documentation on bindings for the `ocaml` doom module.
=> Update ocaml bindings docs

modules/editor/evil/config.el, modules/editor/file-templates/templates/emacs-lisp-mode/__package, modules/lang/fsharp/README.org, modules/lang/julia/config.el, modules/ui/doom/README.org, modules/ui/unicode/README.org
There were a few other links below that I was unsure of how to handle, but I think this is a strict improvement.
```
http://www.culater.net/software/SIMBL/SIMBL.php
https://github.com/hlissner/dotfiles/tree/master/shell/mu
https://github.com/maskray/ccls/blob/master/src/symbol.h
https://gitweb.gentoo.org/repo/gentoo.git/tree/net-mail/mu/files/70mu-gentoo.el
```
=> Fix various broken links

modules/editor/evil/autoload/advice.el
`comment-line-break-function` requires a single `soft-newlines` argument.
Follow up on 64222c69c88c230424d630ddb452c6786d3c0d27
How to replicate
---
When hitting `o` within `nxml-mode` in this document in NORMAL evil mode:
```xml
<?xml version="1.0" encoding="utf-8"?>
<Root>
</Root>
```
I get this error:
```
Debugger entered--Lisp error: (wrong-number-of-arguments (1 . 1) 0)
nxml-newline-and-indent()
funcall(nxml-newline-and-indent)
(if comment-line-break-function (funcall comment-line-break-function) (comment-indent-new-line))
(cond ((sp-point-in-comment pos) (setq evil-auto-indent nil) (if comment-line-break-function (funcall comment-line-break-function) (comment-indent-new-line))) ((and (eq major-$
(if above (if (save-excursion (nth 4 (sp--syntax-ppss pos))) (let ((goal-column …
```
=> Fix +evil--insert-new-line advice when opening new line inside a comment

modules/config/default/autoload/files.el
Given the following config:
`(setq projectile-project-search-path '("~/src/"))`
I ran into a few errors when attempting to discover projects. This is my first contribution, and my Lisp skills are not strong so if there's something I'm missing please let me know.
=> Fix for "Discover projects in folder"

core/autoload/help.el
The button was trying to open `path/to/README.org/README.org`.
=> Fix 'readme' button doom/help-packages

modules/completion/ivy/config.el
"SPC h o" now uses `counsel-describe-symbol` instead of plain `helpful-symbol` (maybe with completion) to get input.
This allows us to fully take the advantage of ivy's superior completion system:
- `[I]: info` and `[d]: definition` hydra heads in `ivy-dispatching-done`
- Quickly describe symbols with "C-M-n/p" (`ivy-next(or previous)-line-and-call` or with the `calling` hydra head on
Additionally the counsel one is prettier when icons are enabled.
Users who have the `+icons` flag with ivy are expected to notice the change visually when invoking "o" in help-map as icons now appear there. But it's an arguably good change anyway since originally "f1 f" and "f1 v" have icons but "f1 o" doesn't.
=> Remap `describe-symbol` to `counsel-describe-symbol` .

core/cli/doctor.el
The warning would always trigger when everything was fine but never when there was an issue.
=> Doom Doctor: Fix insteadOf check

modules/config/default/+emacs-bindings.el
Use default `doom/find-file-in-private-config` just like evil binding,
Or is it intended to?
=> Fix find file in private config for emacs bindings

modules/lang/common-lisp/doctor.el
Many users of sly also use roswell and set the inferior-lisp-program to
values like "ros run" or "ros -Q run". This is not detected correctly by
executable-find. Hence we try to extract the first part of the program
name.
=> Extract program name from inferior-lisp-program

core/autoload/text.el, modules/editor/evil/autoload/evil.el
Both `+evil:retab` and `doom/retab` are currently broken when used interactively. This PR fixes these issues and makes both commands behave like intended.
=> Fix interactive doom/retab.

modules/lang/gdscript/config.el
Added shortcuts for the new debugger support (add, remove breakpoint, continue execution...)
Also added descriptions for existing shortcuts, which should be more readable than the command named ("gdscript-debug-breakpoint-...")
=> Add shortcuts and descriptions for GDScript module

modules/editor/lispy/config.el
I think lispy module should have `ielm-mode` included in hooks
fix #4625
=> Add ielm-mode to lispy module

modules/lang/clojure/config.el
The CIDER debugging experience needs a little bit of improvement.
This PR fixes some issues, in particular:
* Maps cider-debug-at-point to "localleader d d" - so that you can easily drop into debug!
* Overrides evil keybindings to not interfere with the cider--debug-mode
bindings during the debug session - this overrides keys like 'j' and 'n' to allow you to 'inject expression' or 'step over'.
Thanks for a great editor Henrik!
=> [feature] Better CIDER debugging

modules/lang/org/config.el
The use case: if a user has their org directory stored in a synced
location (e.g. dropbox), this file is the same on all machines and is
almost always conflicted.
Given that it is just a cache on the org file locations for IDs, this enables users to move this file out of the directory.
This change enables users to override this in the :init section of their
config (or otherwise before org loading) and that the
+org-init-org-directory-h hook will detect an override.
=> Enabling user config override for org-id-locations-file

modules/lang/latex/autoload.el
Latex item indent ignore the existing variable `LaTeX-item-indent`.
This pull request fix this.
=> Fix latex item indent ignore `LaTeX item indent`

modules/editor/word-wrap/packages.el, modules/lang/latex/packages.el
Handle non-symbol values of `face` property and don't require `easymenu`
=> bump adaptive-wrap

modules/editor/snippets/autoload/snippets.el
Defun is `+snippets/edit` so the prompt to user should say `edit`.
=> snippets.el: Prompt should say `edit` and not `alias`.

modules/lang/scheme/config.el
It's convenient to access docs from the REPL buffer.
=> Add lookup handler for geiser-repl-mode

docs/getting_started.org
Chemacs doesn't works since early-init.el was introduced
=> Update instructions for Chemacs2

modules/term/eshell/README.org, modules/term/eshell/config.el
Makes eshell more ansi-friendly ootb. I'm not 100% tied to it being `xterm` if you think there's a better option.
=> Set default eshell TERM

modules/lang/org/config.el
This regular expression broke sorting by priority in agenda view. Reverting it back to the original one fixes the issue
=> Remove the custom org-priority-regexp

docs/getting_started.org
When installed via homebrew, the formula adds this patch
https://bitbucket.org/mituharu/emacs-mac/pull-requests/2/add-multi-tty-support-to-be-on-par-with/diff, which purports to solve the multi-tty issue.  The user experience I've had with emacs-plus is not a good one.
=> Full-throated recommendation of emacs-mac

modules/lang/cc/README.org
- _sudo_ should not be assumed, as _[doas](https://github.com/Duncaen/OpenDoas)_ is an optimal and more secure alternative for workstation use cases (sudo is suited for servers, where automation is important).
- ~~It's easier to tell if a line is a command by having $ (non-escalated) or # (escalated/root) before the command, as Arch Linux's wiki does by default.~~
This causes problems if you want to execute the command(s) directly in Emacs, see: \
http://howardism.org/Technical/Emacs/literate-devops.html (visual examples) \
https://orgmode.org/manual/Working-with-Source-Code.html
=> [doc: modules/lang/cc] Readability improvements

modules/lang/scala/autoload.el
On current develop trying to open a scala repl in an sbt project via `SPC o r` or calling the `+scala/open-repl` method would fail with
```
if: No buffer named *sbt*<~/project/path>
```
This change updates the check so that we don't attempt to kill an sbt buffer that doesn't exist
- the original method used only `comint-check-proc` before attempting to kill the buffer
- this method doesn't distinguish between a dead buffer process and a buffer that doesn't actually exist
- update to check that buffer exists and is dead before calling `kill-buffer`
1. I don't ever use scala without sbt so I didn't make the same change to line 50 (I'm not sure if its even broken for non-sbt users?). Should I update the logic in both places though?
=> +scala/open-repl don't kill non-existant sbt buffer

modules/tools/magit/config.el
Disabling magit-gitflow breaks magit-dispatch due to the unconditional application of `transient-replace-suffix`.
With this change it is possible to disable magit-gitflow by adding the following to your private Doom configuration:
(package! magit-gitflow :disable t)
=> Enable disabling of magit-gitflow

modules/lang/emacs-lisp/autoload.el
Due to `ivy-call` still causing files to be opened in the
background (which is not a bug in `ivy`),
`+emacs-lisp-lookup-definition` still needs to return `deferred` for
modules. The comment is as such misleading and needs to be removed (it
has been resolved).
=> [4415] remove FIXME comment

modules/lang/ruby/README.org, modules/lang/ruby/config.el
Rails <= 5.2 dont have this options, the users cannot use this feature without searching in the doc.  I think is better to leave enabled. 
If possible, make something to limit the `projectile-rails-server-mode` @hlissner .  Like, if has more then 1.5k lines, when create new logs, erase the old ones.
=> Revert Rails command change

modules/lang/org/config.el
I understand that what you tried to accomplish via CSright was; however, it doesn't make any difference from Cright, and so for other navigation keys -- h,j,k,l.
I fixed this discrepancy.
=> `evil-org-mode-map`'s `CSright` conflict with `Cright`

modules/editor/lispy/config.el
`eval-expression` is basically Elisp, therefore it makes sense to enable `lispy`.
=> Enable lispy-mode during eval-expression.

modules/editor/file-templates/templates/text-mode/__license-gpl3
Need to escape the backticks that should appear as literals in the GPLv3 license.
=> Fixing the gpl snippet template formatting

modules/editor/parinfer/README.org, modules/editor/parinfer/config.el, modules/editor/parinfer/doctor.el, modules/editor/parinfer/packages.el
This commit adds support for the `parinfer` module flag `+rust`, which will use `parinfer-rust-mode`
instead of `parinfer-mode`. `parinfer-rust-mode` makes use of an external library named `parinfer-rust`
to do the heavy lifting. As such, `--with-modules` must be enabled.
Resolves #4635.
=> Add support for parinfer-rust-mode

core/autoload/help.el
Hey there! Here's my work on the doom/help-packages function and the helper for inserting buttons. It fixes a bunch of bugs and oddities in the buffer content, and hopefully doesn't introduce too many more. I've also tried to generally improve readability and formatting where I can. 
I'm sure there are plenty more ways to improve this still. One idea I had would be to pull some data out of the package-desc structs like describe-package does. Currently packages from [M]elpa don't have a summary or description like they do in describe-package.
I'm still pretty new to lisp, and this is my first big contribution to Doom, so please let me know what I can improve!
=> Refactor doom/help-packages

modules/lang/org/config.el
Summary: This diff adds evil-esque keybindings for the org-agenda-priority
functions. These functions allow the org subtree priority to be set from
the agenda view.
Rationale: I love the existing `org-agenda-*` keybindings, but I find myself missing `org-agenda-priority` when doing exactly what you'd guess: trying to set an item's priority while in the agenda. This adds that keybinding in, along with a prefix menu for all of the `org-agenda-priority-*` functions.
I didn't see existing keybinding documentation for org-mode so I didn't add any myself, but let me know what is necessary to get this PR up to spec.
=> Add org-agenda-priority keybindings to org config

modules/lang/cc/config.el
=> Use new CPU counter function in cc module

modules/lang/org/autoload/org-refile.el
`+org/refile-to-other-window` does not work when working with an indirect buffer (e.g. with `org-tree-to-indirect-buffer`). This adds a call to `buffer-base-buffer` to make it work.
=> Fix +org/refile-to-other-window in indirect buffer

modules/config/default/+emacs-bindings.el
+default/yank-buffer-filename was replaced in
be9b3ff352f39f2f21812e13466bd6d2f26cd6e4 and +evil-bindings.el was
updated accordingly. This commit makes the corresponding updates in
+emacs-bindings.el.
=> Fix the "Yank file path" non-evil bindings

modules/lang/rust/autoload.el
I'm not sure if the execution of `cargo audit` with the `-f` flag has/had a specific reason. I opened an issue for this on #3852 to discuss this.
=> Rust module: Modify command for executing `cargo audit`

modules/tools/debugger/autoload/debugger.el, modules/tools/debugger/config.el, modules/tools/debugger/packages.el
Reworks the internals of how the debugger module stores the last-used configuration:
- car of the configuration indicates whether it is a realgud or a dap-based configuration.
- For dap-based debuggers, the entire dap configuration is stored, with code copied from `dab-debug`.
- When inside a project, don't store the configuration as a buffer-local variable, but instead as a project-local variable using `projectile-variable`.
Fixes #2367.
=> Fix +debug/start for dap-based debuggers.

modules/email/notmuch/README.org, modules/email/notmuch/autoload.el, modules/email/notmuch/config.el
@hlissner I would like to progress development of this module if no one else has interest. It seems to have been in a WIP state for a while.
What I did here is remove some aesthetic customizations that the doom module currently does on the notmuch-hello buffer. I think these customizations are easy to achieve with user config and I provided documentation to do so. As a user of `notmuch` with vanilla emacs I've grown very used to landing on the normal notmuch-hello buffer and I think that should be the default when using `notmuch` in doom as well.
I think I've struck a decent balance here of having unsurprising defaults, but also easy customization for those that want it. Please consider this PR for merge.
=> Notmuch module remove `*notmuch-hello*` buffer customizations + add some documentation

modules/tools/lsp/+lsp.el
This gives completion of snippets along with normal LSP completion,
similar to how the old company-lsp backend worked.
=> Include snippets in lsp completion

modules/lang/emacs-lisp/config.el
`fboundp` does not check if a variable is bound, but rather a function.
Use `boundp`.
I think this was a mistake introduced in one of my bug-fixing PRs...
----
#
=> Emacs lisp: fix variable value display in eldoc

modules/emacs/vc/config.el
`git-commit-summary-max-length` should be a number, not a symbol.
`git-commit-major-mode` should be checked more carefully, as otherwise
exploits are possible (e.g. if it is `erase-buffer` or some dangerous
function of the user's environment).
----
#
=> `git-commit`: fix variable predicates

bin/org-capture
Change org-capture to get text from positional args if present,
otherwise stdin.
Currently it gets text from positional args if interactive, and from
stdin otherwise, which lead to me scratching my head wondering why the script was eating
the passed texted when called from qutebrowser:
:spawn org-capture "[[{url}][{title}]]"
In its present form the script doesn't support this usage.
=> org-capture: accept text arg non-interactively

modules/tools/lsp/+lsp.el
I noticed after updating that I was seeing a lot of irrelevant results for certain completion scenarios and tracked it down to this commit. Swapping the order does the trick. This ensures that when doing things like completing on `this.` inside classes, the class fields and methods are shown before the yasnippet snippets.
Before: 
After:
=> Prioritize company-capf over company-yasnippet

bin/org-capture
org-capture foo bar baz
will fail with:
org/capture: line 33: [: too many arguments
Adding quotes to the expansion of $str will ensure that test -z has
only one argument.
Hope that it helps.
Cheers!
=> Fix 'too many arguments' error on org-capture

modules/emacs/dired/config.el
This pr sets `dired-create-destination-dirs` per default to `'ask`, so that the behaviour is more consistent with the one of `find-file`.
=> Better defaults for dired

modules/editor/evil/autoload/evil.el
According to the documentation of `evil-window-split` the variable
`evil-split-window-below` needs to be non-nil for the new window to be
created below; and for `evil-window-vsplit` it is the variable
`evil-vsplit-window-right` that needs to be non-nil for the window to be
created on the right.
=> Fix #4770: New window is focused after split

core/core.el
The doc strings for these hooks had "after" and "before" swapped:
- `doom-after-reload-hook`
- `doom-before-reload-hook`
=> Fix doom-{after,before}-reload-hook doc strings

modules/tools/debugger/autoload/debugger.el
Use `let*` instead of `let`, otherwise we get this error `completing-read: Symbol’s value as variable is void: result`.
=> Fix `+debugger/start` not working

modules/tools/eval/autoload/repl.el
Existing REPL commands has a dash ("-") before the "repl" suffix, but the function format to intern doesn't, currently I always get an error `"Couldn't find a valid REPL for %s"` whenever I open a non-default REPL.
For example, choosing "ipython" using `+eval/open-repl-other-window` with an `universal-argument` in `python-mode`.
=> Fix non-default REPL's format of command name.

modules/lang/julia/README.org
The repo links of `julia-mode` and `julia-repl` were swapped in `/modules/lang/julia/README.org`.  This corrects the repo links.
=> fix julia README

.gitignore, modules/term/vterm/autoload.el
1. lang/dart installs extension to ~/.emacs.d/.extension/vscode/Dart-Code.Dart-Code/.
2. emacs-libvterm makes +vterm/here not open new vterm buffer any more
due to commit: https://github.com/akermu/emacs-libvterm/commit/c2c2c8afb935c11778388721912250cd1103aaf9
=> ignore extension installed by lang/dart and recover behaviour of +vterm/here

modules/editor/file-templates/templates/c++-mode/__hpp, modules/editor/file-templates/templates/c-mode/__h
Using double underscore for an identifier in C/C++ invokes undefined
behavior.
From https://eel.is/c++draft/lex.name:
Each identifier that contains a double underscore __ or begins with an
underscore followed by an uppercase letter is reserved to the
implementation for any use.
=> Remove double underscore from c header templates

modules/term/vterm/config.el
akermu/emacs-libvterm@c2c2c8afb935c11778388721912250cd1103aaf9 changed
the default buffer name of vterm buffers, so Doom's popup-rule no longer
matches them. This causes functions like `+vterm/here` to use the entire
frame instead of creating a popup window.
Fix it by changing the popup rule to match the new naming scheme.
=> Fix vterm popup rule

modules/term/eshell/config.el
=> Tell git not to use pager in eshell

modules/lang/python/config.el
`poetry-tracking-strategy`'s docstring:
```
- `post-command' (default): check after every command (can be quite slow but ensure
that the virtualenv is always the good one).
```
With `(python +poetry)` and a Python buffer opened, Emacs dedicates ~25% CPU time (measured by `(profiler-start 'cpu)`) when scrolling continuously with `next-line`, which violates Doom's performance goal.
=> Change poetry-tracking-strategy for performance

modules/ui/indent-guides/config.el
Otherwise it constantly spams the echo area in tty Emacs.
=> Suppress highlight-indent-guides's auto errors

modules/lang/python/config.el
When "pyenv"'s executable isn't found, `pyenv-mode` fails miserably, making`python-mode` unusable.
"pyenv"'s executable is always searched for, so there's no additional performance penalty.
Use case: shared config among machines with and without pyenv installed.
=> Active pyenv-mode only when pyenv exe is found

modules/completion/ivy/config.el
It doesn't make sense to sort the outline, better to leave the order as-is.
=> Add counsel-outline to :not ivy-prescient-sort-commands

modules/email/notmuch/autoload.el, modules/email/notmuch/config.el
When #3933 was closed, part of it's documentation snuck in. The part about the `+afew` feature flag is in the docs, but it's not respected.
This change will make it be respected. It also edits the notmuch sync function to use `compile` in order to address the problems described in https://github.com/hlissner/doom-emacs/issues/3188
Please consider this for merge.
=> notmuch -- respect +afew feature flag, fix sync buffer kill

modules/input/layout/+bepo.el, modules/input/layout/README.org
- Run `doom-bepo--evil-collection-hook` on all minibuffer maps. This
allows all bindings in <insert-state> to be remapped in minibuffer
contexts
- Unmap `swiper-C-s`
=> Fix #4736 - remap insert state bindings in minibuffer maps

docs/modules.org, init.example.el, modules/lang/zig/README.org, modules/lang/zig/config.el, modules/lang/zig/doctor.el, modules/lang/zig/packages.el, modules/tools/lsp/README.org
This PR adds a language module for Zig. It turns out that there's less configuration than I expected, especially following updates to lsp-mode (https://github.com/emacs-lsp/lsp-mode/pull/2723), so let me know if you'd rather not add this as a module. Otherwise, I can write up the documentation for the module as well.
Ref. #4656.
=> Add `:lang zig` module

modules/lang/java/autoload/java.el, modules/lang/java/config.el
+java/groovy-open-repl -> +java/open-groovy-repl: the old name's format
can't be found via `+eval-open-repl`
=> Fix Groovy REPL's command name

modules/editor/evil/packages.el
emacs-evil/evil-collection@b45ec5b → emacs-evil/evil-collection@b6025cf
emacs-evil/evil@7eace67 -> emacs-evil/evil@d998a81
The register system has been rejigged in the last week, and some
packages in the Evil ecosystem are already making use of the new vars.
emacs-evil/evil@229ebb4
mamapanda/evil-owl#10
=> Bump :editor evil

modules/tools/lsp/+lsp.el
- otherwise, `+lookup-online-backend-fn` would be called as well
- lsp-describe-thing-at-point was marked as not async in
https://github.com/hlissner/doom-emacs/commit/d4eb7e31ac25107a35f9de567a497d9100fcc1ff
- but `lsp-describe-thing-at-point` calls `lsp--make-request`
internally (which is async I assume):
https://github.com/emacs-lsp/lsp-mode/blob/eda51c21662253fd05b4f3f20ad7b029d9c2aff7/lsp-mode.el#L4677
=> Indicate that lsp-describe-thing-at-point is async

core/core-modules.el
Inside `doom-module-mplist-map`, one of the code paths handling obsolete module warnings references a `key` variable, which appears to be unbound.
```elisp
(message "WARNING %s module was removed" key)
```
I changed `key` to `(list category module)`, which appears to be what was intended and is consistent with neighboring code paths.
__Note__: Untested. I don't have doom installed, but I noticed this while reading through the code.
=> Fix doom-module-mplist-map obsolete module warning

modules/ui/treemacs/doctor.el
The previous check was incorrect when eglot and treemacs without lsp was
on.
=> Fix treemacs + lsp doctor check

modules/lang/latex/README.org, modules/lang/org/README.org
I've noticed that some docs are a bit outdated, as homebrew doesn't have
`brew cask` command now, all features regarding to casks were moved to
the option `--cask` instead.
This commit just introduce such changes to be up-to-date with homebrew instructions.
=> Use correct `brew install --cask` command

core/core-editor.el
The current fix only specifies `minibuffer-inactive-mode`, which does nothing for me (Emacs 28 at https://github.com/emacs-mirror/emacs/commit/d55d5358b27dee15ebbd998131d22b221f5f4964). This PR adds `minibuffer-mode` to the mode lists, which fixes the issue for me.
=> Fix smartparens pairing ' and ` in the minibuffer.

modules/lang/swift/config.el, modules/lang/swift/packages.el
Bump the version of :lang swift and lsp-sourcekit which is used in it:
swift-emacs/swift-mode@95ff004 -> swift-emacs/swift-mode@ad12a30
https://github.com/emacs-lsp/lsp-sourcekit/commit/ff204ed820df8c3035ebdc4b5a583640d52caeeb -> https://github.com/emacs-lsp/lsp-sourcekit/commit/aafa9878a3df2f08e5a9c846d91fd53350ce3c99
Recent Xcode ships with the `sourcekit-lsp` server and the latest lsp-soucekit package [supports that bundled `sourcekit-lsp` as the default configuration](https://github.com/emacs-lsp/lsp-sourcekit/blob/aafa9878a3df2f08e5a9c846d91fd53350ce3c99/README.md#quickstart), so I have inserted the bundled `sourcekit-lsp` server path to the first place of the executable list.
Also, since the new version of lsp-sourcekit package changes the default executable from `sourcekit` to …
=> Bump :lang swift (update lsp-sourcekit and add support for sourcekit-lsp bundled with Xcode)

core/cli/packages.el
We are using the old straight--call function in the windows pathway. This switches us to using the new API
=> Fixing windows pathway to use latest straight API

modules/ui/ligatures/config.el
This is my first pull-request (ever), and it relates to issue #4916.
The mangled links described there only show up when an Info-mode link is followed by a right-parenthesis.
So I simply added Info-mode to the list of modes where ligatures are disabled.
=> Add Info-mode to list of ligature-excluded modes.

modules/lang/org/contrib/pretty.el
Add `if` cookie so that it doesn't get compiled by `doom compile`.
I know that you discourage to byte compile doom modules; nonetheless, it definitely speed up quite a lot. I felt it is annoying `pretty.el` file getting compiled with `doom compile`, so I added it to be consistent with other featured `.el` files.
=> lang/org: cleanup `+pretty` feature, mostly just adding `if` cookie

modules/lang/latex/+viewers.el
The Skim.app `displayline` command takes the flag `-g` which is "Do not bring Skim to the foreground"
when viewing the pdf results of the latex build, bringing skim to the foreground saves an `Alt+Tab` to open the app that I was intending to lauch by the auctex View command.
=> lang/latex: Remove the -g background flag on Skim.app to foreground the viewer

modules/lang/scheme/config.el
Some keys were bound to no-longer-existing commands, or commands which changed
name.
Others only made sense in the REPL, or /also/ in the REPL, so the keybinds are
now in `scheme-mode-map', `geiser-repl-mode-map', or both accordingly.
(recreating PR #4889 which was closed by accident)
=> fix and add keybinds in :lang scheme, with descriptions

modules/input/layout/+bepo.el
After the refactor, the main function to call to fix small inconsistencies went from a raw evil-collection-setup-hook
function to a proper helper function with a more logical signature. 
This fixes the calls to the new function, so that the custom fixes are properly applied
=> :input layout: fix calls of +layout-bepo-rotate-keymaps

modules/term/vterm/README.org
I hit a problem with `epkgs.vterm` from `nixos-20.09` being too old and thus missing `vterm-goto-char` which is present in newer versions of `epkgs.vterm`. Switching to `emacs` & `emacsPackagesNgGen` from `unstable` fixed the issue for me, and I assume this might be a helpful hint in the docs.
I added a note to mention this for future users, and added two other changes/clarifications as well; all changes:
* Changed `epkgs.emacs-libvterm` -> `epkgs.vterm`, as the old name is deprecated.
* Added note that `epkgs.vterm` already contains a `vterm-module.so`
* Added note that the version of `emacs` needs to be recent enough and that otherwise bugs might occur.
=> README.org: Add info about vterm in NixOS

core/core.el
We were making the value of doom-first-input-hook permanent-local
instead of doom-first-input-hook itself. That value is normally nil at
this point, which seems to be harmless. Reloading core.el from a script
(while doom-first-input-hook is not empty) results in an error.
Fix it by adding the missing quote present in the other calls.
=> Fix making doom-first-input-hook permanent-local

modules/app/rss/packages.el
Hey there,
In the default `~/.doom.d/init.el` this module is commented but listed with the +org flag `(rss +org)`.
I happened to try using it without `+org` and it still installs https://github.com/remyhonig/elfeed-org even though it's not needed. This PR makes it so you only need to install elfeed-org if you use +org flag
=> rss: +org flag control installation of elfeed-org

modules/lang/latex/+viewers.el
Pass the "noraise" flag to okular if it is used as a Latex viewer. If an
okular instance is already displaying the Latex compilation result,
subsequent invocations won't make okular steal focus from Emacs.
=> Prevent okular from stealing focus

modules/lang/emacs-lisp/config.el
Otherwise it will make Emacs to error with `(void-variable sym)` error when checking the variable.
=> lang/emacs-lisp: Replace sym with var in +emacs-lisp-log-unsafe-local-variables-a

modules/completion/ivy/config.el
It doesn't make sense to sort `counsel-jq`:
=> Add counsel-jq to :not ivy-prescient-sort-commands

modules/ui/modeline/README.org
I've added the code I used to finally fix modeline icon misalignment
problems in my own setup as a suggestion in the Troubleshooting section.
=> Add another potential fix for icon misalignment in doom-modeline

modules/input/layout/+bepo.el
Fixes #4847
Cause is explained [in this comment](https://github.com/hlissner/doom-emacs/issues/4847#issuecomment-835760552)
=> fix(:input layout bepo): Ensure eshell rotation goes after evil-collection maps

modules/email/notmuch/config.el
It was made buffer-local upstream [1] and included in the latest version
bump [2].
[1]: https://git.notmuchmail.org/git?p=notmuch;a=commit;h=42d32713be9a23346de09b84983e1dd3b44b3400
[2]: https://github.com/hlissner/doom-emacs/commit/ed4b1ef8879d20868504805d838fd04a45011e84
=> use setq-default for notmuch-search-oldest-first

modules/lang/org/config.el
With current hacks involving `org-agenda-files`, one cannot use org agenda
commands like clock in or change the entry's state to done, etc.
Specifically, the mangled behavior observed at #4901. This commit fixes those
problems around `org-agenda` buffer specific commands.
For more details, please refer to https://github.com/hlissner/doom-emacs/issues/4759#issuecomment-822100632.
=> fix #4901: suppress strange behavior involving org agenda commands

core/cli/byte-compile.el
-------
With a commit of e2a11d24fd4ea20fb198493b3dd12742c4fad6b0, when it comes to
`doom compile`, modules aren't loaded anymore, which corrupts the compiling process.
What I did is just adding the necessity parts for the doom's byte compiler.
=> Fix bin/doom compile error introduced by e2a11d24fd4ea

modules/email/notmuch/README.org, modules/email/notmuch/config.el, modules/email/notmuch/packages.el
Hi Henrik,
I'm not sure about this one. Feel free to decline.
This module is minimally configured and we're not providing anything extra on top with it. There may be many people that use this module and don't know `org-mime` is available to them. This PR removes `org-mime` and adds a section to the readme under a heading "Writing HTML Emails."
If you have ideas for why this module should stay, please share.
Best,
Will
=> notmuch: remove org-mime

modules/ui/ophints/config.el
Because lispyville (depending on how you configure it) replaces some
evil-mode mappings with its own function, we lose the indication of our
deletions/yanks/etc. This change adds all lispyville functions to the
evil-goggles--commands list.
=> ophints: Add hooks for lispyville

modules/app/rss/README.org
Per https://github.com/remyhonig/elfeed-org, the `modules/app/RSS` README.org had the incorrect command for setting a custom elfeed.org file. It was missing a `list` in the elisp.
=> fix typo in how to set custom elfeed.org

modules/completion/ivy/config.el, modules/config/default/+emacs-bindings.el, modules/config/default/+evil-bindings.el
`unicode-chars-list-chars` doesn't seem to be an actual function (not
defined in emacs or found online), and `insert-char` seems like what one
would want here.
Issue #3556 seems to have been about this but has been deleted.
=> unicode-chars-list-chars -> insert-char

modules/lang/elixir/config.el
The Elixir module adds this regex to the `lsp-file-watch-ignored-directories` variable: `"[/\\\\]\\_build\\'"`. This leads to this error message:
~~~
Lisp error: (invalid-regexp "Invalid regular expression")
string-match("[/\\\\]\\_build\\'" "...")
lsp--string-match-any(("[/\\\\]\\_build\\'" "[/\\\\]\\.git\\'" "[/\\\\]\\.hg\\'" "[/\\\\]\\.bzr\\'" "[/\\\\]_darcs\\'" "[/\\\\]\\.svn\\'" "[/\\\\]_FOSSIL_\\'" "[/\\\\]\\.idea\\'" "[/\\\\]\\.ensime_cache\\'" "[/\\\\]\\.eunit\\'" "[/\\\\]node_modules" "[/\\\\]\\.fslckout\\'" "[/\\\\]\\.tox\\'" "[/\\\\]dist\\'" "[/\\\\]dist-newstyle\\'" "[/\\\\]\\.stack-work\\'" "[/\\\\]\\.bloop\\'" "[/\\\\]\\.metals\\'" "[/\\\\]target\\'" "[/\\\\]\\.ccls-cache\\'" "[/\\\\]\\.vscode\\'" "[/\\\\]\\.deps\\'" "[/\\\\]build-aux\\'" "[/\\\\]autom4te.cache\\'" …
=> fix regex in lsp-file-watch-ignored-directories in elixir module

modules/lang/racket/README.org
> - [x] I've targeted the develop branch
> - [x] I've searched for similar pull requests and found nothing
> - [x] This change is NOT in Doom's do-not-PR list: https://doomemacs.org/d/do-not-pr
> - [x] If I've bumped any packages, I've done so according to https://doomemacs.org/d/how2bump
> - [x] I've linked any relevant issues and PRs below
> - [x] All my commit messages are descriptive and distinct
This PR fixes some minor typos I noticed in the README of the Racket module, and also mentions the available Arch Linux packages for Racket.
=> :lang racket: Fix README typos 

modules/lang/clojure/config.el, modules/tools/lsp/+lsp.el, modules/ui/modeline/+light.el
This PR improves `+light` modeline:
* Checks for LSP status 
* Checks CIDER if enabled for clojure buffers.
I used the same :rocket: icon from `doom-modeline`, but if you think that makes sense change to another, let me know it.
Just following the [idea from doom modeline](https://github.com/seagle0128/doom-modeline/issues/347), when CIDER is available/connected/disconnected we show an icon:
=> Add lsp and repl to +light modeline

modules/ui/modeline/+light.el
Fix for #3307 
Because of a wrong conflict solve on #3307, I missed one function to add the new arg
=> :ui modeline: Fix missing arg to +modeline-format-icon function

modules/lang/cc/README.org
This adds a missing clangd flag for LSP, needed to make it work correctly with company-mode.
It's from the default value of `lsp-clients-clangd-args`.
This is with `clangd version 11.1.0`.
If not set, I find C++ completion will produce a single space instead of showing up the list, in a case like `myVariable.`, triggering completion after the dot character.
=> Update suggested clangd flags in lang/cc docs

modules/tools/lsp/+lsp.el
I changed the lsp-peek handlers to be registered as :async.
This causes them to be considered successful by the lookup.el calls.
Without this, subsequent handlers registered (e.g. those from other
completion frameworks) will also pop up in addition to the peek UI.
This creates UI lock-up and is generally undesired.
Although I haven't tested it with php, it probably fixes #5069 . The symptoms are identical to what I saw in C++.
=> Noting the lsp-peek handlers as :async

modules/ui/vi-tilde-fringe/README.org
This is part of #1166 adding missing documentation for the `ui/vi-tilde-fringe` module.
=> Add vi-tilde-fringe documentation

modules/term/vterm/autoload.el
Fixes #4834 
Before this change, `+vterm/toggle` would toggle a vterm window and change directory to the directory of the current buffer.  Now it oppens the root of the current project when it does't get an universal argument.
The comments of the function indicate this should be the appropriate behavior.  `+vterm/here` behaves in a similar way.
Before:
After:
=> Fix +vterm-toggle not changing directory to project root

core/core-keybinds.el
Replace the use of featurep with featurep! in `define-localleader-key!`
This stops a race condition where a module with `(map! :map a-map :localleader ....` is loaded
before `evil` has been activated, so the macro expands to use the `doom-local-leader-alt-key` prefix.
=> define-localleader-key's featurep -> featurep!

modules/lang/qt/README.org
This is part of #1166, adding documentation for the `lang/qt` module.
I am not sure if I need to mention the `qml-beginning-of-defun` and `qml-end-of-defun` navigation commands provided by qml-mode or not?
=> Add qt module documentation

modules/emacs/dired/README.org
I added a small ranger section to "/modules/emacs/dired/README.org". This section simply explains that if the +ranger flag for dired is set in init.el often a "deer-mode" or minimal ranger buffer will be opened, and that "Z p" can be used to toggle between this minimal mode and the full ranger mode. I added this because I think deer-mode looks deceptively similar to standard dired-mode and it may not be obvious what is occurring and how to switch to full ranger if the +ranger flag was set without reading the ranger.el docs.
=> Add ranger documentation to dired README

modules/completion/ivy/config.el
Although `counsel-org-goto` is an alias of `counsel-outline`, while the latter is already in the list, the former's output is still sorted.
Github's "Files changed" is too noisy, here is Magit's more friendly diff:
=> Add :not counsel-org-goto to ivy-prescient-sort-commands

modules/editor/lispy/config.el
-------
I have sent a pull request to lispyville for making a keybinding more consistent (see https://github.com/noctuid/lispyville/pull/297). The maintainer does not seem to respond so until then I propose to advice the function in doom.
`lispyville-end-of-defun` doesn't go to the next defun when point is already at the end of a defun, whereas `lispyville-beginning-of-defun` does. This commit fixes this inconsistency by matching `lispyville-end-of-defun`'s behaviour with lispyville-beginning-of-defun.
=> Advice lispyville-end-of-defun to go past defuns

modules/lang/web/doctor.el
This quick PR adds a check for the `tidy` executable in `doom doctor`. The new output looks like:
=> doctor: Check for missing `tidy`

modules/lang/rust/config.el
`cargo doc --open` (the previous binding of `SPC m b d`) always opens a new
browser tab. For "doc-driven development" this isn't so nice, since we'd like to
stay in the same tab and just refresh its contents after editing. That's what
`cargo doc` (without `--open`) does, which is called by
`#'rustic-cargo-build-doc`.
This commit introduces a binding for the latter behaviour, but asigns it to the
old `SPC m b d`, with the "open" variant as `SPC m b D`. This matches Spacemacs
and follows the usual pattern of "the capital letter variant is the one you use
less often".
Of course if you'd rather not the existing binding be flipped, I'm perfectly willing to switch it.
=> lang/rust: Binding for `cargo doc`

core/core-packages.el
Remove reference to `bin/doom update` are renames to `bin/doom sync -u` according to this output
```sh
$ doom update
> Executing 'doom update' 2021-06-03 16:14:50
x This command has been removed.
To update Doom run 'doom upgrade'. To only update packages run 'doom sync -u'.
```
=> Fix typo doom update and replace with doom sync -u

modules/lang/csharp/config.el
When using evil the keybinds defined in the sharper package were not available. This PR maps sharper commands in a way that is mostly analogous to the keybinds originally defined in the package. I changed the bindings for various refresh commands to "gr", however, to be in line with similar other facilities in Doom.
=> Add evil-keybindings for various sharper commands

modules/editor/file-templates/templates/gitignore-mode/__
Adds "haskell" to the `yas-choose-value` list when creating a new `.gitignore` file. The actual contents of the template are taken from https://www.toptal.com/developers/gitignore/api/haskell.
=> Add haskell gitignore template

modules/checkers/syntax/README.org
Relevant to #1166 
Adds documentation for the flycheck module. I was not sure what to put for the since option, so I left that as ???. If anyone knows what should be placed here, tell me and I'll fix it.
=> Added Flycheck documentation

modules/lang/org/contrib/present.el
For reasons I don't entirely understand, calling `+org-present-hide-blocks-h` during `org-tree-slide-mode-hook` _does not_ 
hide block headers/footers.
Instead, hooking `org-tree-slide-play-hook` hides those headers/footers.
=> Use org-tree-slide-play-hook to hide blocks

modules/tools/pdf/config.el
There was an issue recently brought to light on reddit ([this](https://www.reddit.com/r/DoomEmacs/comments/o4b1yz/pdftools_error_after_opening_a_pdf_and_unable_to/) post) about not being able to open files after working with a PDF. I also have been running into an identical error while working with org capture wherein I could not capture anything without this error popping up.
As the error says, it comes from passing too many arguments to the function `abort-if-file-too-large` which only takes 3 arguments but is being passed an extra `nil`. To prevent this, I've changed the pdf module to only pass the 4th parameter when it is non-nil to begin with.
=> Prevent extra variable from being passed in macro.

modules/tools/lsp/+lsp.el
When Emacs 26.x support was in place this was originally:
```elisp
lsp-ui-sideline-actions-icon (if EMACS27+ lsp-ui-sideline-actions-icon-default)
```
But when it was removed it became:
```elisp
lsp-ui-sideline-actions-icon t
```
The docs for lsp-ui-sideline-actions-icon say:
```
Image file for actions.  It must be a png file.
```
Setting this to `t` results in lsp icons being missing from the buffer and a whole lot of these messages:
```
[lsp-ui-sideline]: Error with actions icon: (error Invalid image specification)
```
So the solution seems to me to be to set it to:
```elisp
lsp-ui-sideline-actions-icon lsp-ui-sideline-actions-icon-default
```
I've set this in my emacs and it restores the lightbulb icons on the lsp messages and the messages stop occurring.
=> Set the lsp-ui-sideline-actions-icon to the default

modules/config/default/+emacs-bindings.el, modules/config/default/+evil-bindings.el
Currently <kbd>SPC g L</kbd> runs `magit-log` which opens a context window for git log with an option selected that limits the log to the file open in buffer. The user then has to press <kbd>l</kbd> to actually see the log. The same result can be achieved by calling `magit-log-buffer-file` instead
=> Fix command to show git log of current buffer file

docs/modules.org
=> remove duplicate '+' from kotlin +lsp

modules/completion/helm/config.el, modules/completion/ivy/config.el
The default value is `'auto`, which handles the detection of the active
completion system, see the definition of `projectile-completing-read`.
-------
=> don't explicitly set `projectile-completion-system`

modules/lang/kotlin/packages.el
Trying to work with kotlin-ls & ktlint but the existing flycheck kotlin plugin wouldn't cooperate with the `brew install ktlint`-available ktlint (0.41.0). flycheck-kotlin had fixed it upstream, and so I've upstreamed my bump :)
=> bump flycheck-kotlin to support newer ktlint

modules/lang/sh/config.el
bats is a superset of shell script for writing automated tests exected
with TAP. sh-mode works very well with bats files.
This patch simply add `.bats` file suffix to sh-mode. Note that `.bats` is recommend by the bats project and used in for their own test suites.
=> Define sh-mode for bats files

modules/editor/format/config.el
Fixes #5128
In `+format--all-buffer-from-hook-a`, a call to `format-all--formatter-executable` with the formatter being equal to `'lsp` or `'eglot` returns `nil`. That's why `funcall` was never executed in those cases. To fix this issue, this PR introduces special checks for those cases.
=> Fix #5128: No format-on-save by lsp-formatters

modules/lang/json/doctor.el
since `counsel-jq` is only relevant for ivy
=> lang/json/doctor: only check for jq if ivy is on

modules/term/eshell/packages.el
Bash and fish completion work without company, e.g. when the user uses
the minibuffer for completion.
I've removed the feature gate behind company for fish and bash-completion. It works without company and there are people who don't use company. Furthermore it seems to cause some errors, see https://discord.com/channels/406534637242810369/406554085794381833/852098110624235550
=> Remove dependence on company for fish and bash completion in eshell

modules/lang/latex/config.el
This hook sometimes errors out because yasnippet ...forgets? to set `yas-snippet-{beg,end}`.
It occurs for *some* snippets and I think it only started about a month ago. Not sure why
=> lang/latex +fold: fix error when yas-snippet-{beg,end} are nil

modules/input/layout/autoload/bepo.el
`W` was used to emulate `C-w C-w`, which is useful to quickly change windows
most of the time. But this currently conflicts with edebug evil-collection bindings.
(gives `Key sequence W W starts with non-prefix key W` on the first loaded elisp buffer.).
Better to leave the key alone, avoid error messages altogether, and let users redefine
the binding if they want to.
=> [:input layout bepo] Remove "W" convenience remap

modules/config/default/+emacs-bindings.el, modules/config/default/+evil-bindings.el, modules/ui/workspaces/autoload/workspaces.el
This PR adds a small wrapper around `+workspace/new` for the primary use of binding to `SPC TAB N` and interactively prompting the user for the name of their new workspace. While both `+workspace/new` and `+workspace-new` can receive a named argument, neither are set up for user prompting in this way.
This binding offers a shortcut to the common pattern of creating a new workspace via `SPC TAB n` and then immediately renaming it via `SPC TAB r`.
=> `SPC TAB N` binding

modules/completion/helm/README.org, modules/completion/ivy/README.org
Doom already has the install instructions in the broader documentation,
and since ripgrep is a dependency for doom in general these are
redundant.
=> remove ripgrep dependency from ivy and helm readmes

core/cli/doctor.el, core/core.el, modules/completion/helm/config.el, modules/config/default/config.el, modules/editor/evil/init.el, modules/emacs/dired/config.el, modules/tools/lookup/config.el, modules/ui/popup/autoload/popup.el
- Remove remaining `EMACS27+` checks, since the whole codebase is
assumed to run at version 27 or above now
- Remove `EMACS27+` definition since it's no longer needed
---
I wasn't sure if you purposely didn't remove these in the dropping 26.x support commit, or if you just missed them. Figured this was the easiest way to find out.
=> Remove remaining `Emacs27+` checks

modules/editor/format/autoload/format.el
After the fix in 78dde6efdd81e4d11a21ba87a7f9b141d274e947, buffer-local variables such as `tab-width` are ignored for formatting, because `(current-buffer)` is used within the temp buffer instead of `origin-buffer`.
For example in `sh-mode`, [`set-formatter!`](https://github.com/hlissner/doom-emacs/blob/a1c80a5dcddec2bb14cec6acaf6dd15b167a0aa1/modules/lang/sh/config.el#L20) uses `tab-width`. If `dtrt-indent` detects it as `2`, the global value `4` is used instead because variables are copied from `(current-buffer)`, which doesn't have the local variables of `origin-buffer`.
=> Fix formatting ignoring buffer-local variables

modules/editor/multiple-cursors/config.el
After exiting `multiple-cursors`, when the previous state is
multiedit{,-insert}, return to normal state.
Use case:
- Mark occurrences with evil-multiedit
- `iedit-switch-to-mc-mode` ("M-M")
- Make some edit
- "C-g" to exit `multiple-cursors`
Expected behaviour: Return to evil's normal-state
Observed behaviour before the patch: Emacs stays on emacs-state
=> Improve multiple-cursors compatibility with evil-multiedit

core/autoload/help.el
Sometimes the `doom/help-packages` function encounters an error while printing the list of locations where the specified package is configured, if the line of code contains colon characters. This happens because the colon is interpreted as a separator between arguments to `cl-destructuring-bind`, thus causing a "wrong number of arguments" type of error if exactly three arguments are expected (filename, line number and line of code).
With the proposed fix, `cl-destructuring-bind` can accept an arbitrary number of arguments (three or more), thus removing the error without impacting code logic since only the first two are actually used.
=> Fix doom/help-packages to correctly print config locations

modules/tools/debugger/config.el
dap-cpptools is, for the time being, the recommended way of setting up 
dap-mode with Rust.
The setup I ended up being able to properly reproduce is available in a small [blog post](https://gagbo.net/post/dap-mode-rust/) and had to rely on `dap-cpptools` after some research and help from Ivan
=> Add dap-cpptools to auto-requires of dap for rust

modules/app/irc/autoload/settings.el
The indentation of set-irc-server! in the irc module's README.org differs from set-irc-server!'s current indentation settings.
=> Conform set-irc-server! indentation to the README

modules/editor/lispy/config.el
https://github.com/noctuid/lispyville/pull/297 was merged which makes
the changes from https://github.com/hlissner/doom-emacs/pull/5101 obsolete.
=> Remove workaround for upstream lispyville PR

modules/config/default/+emacs-bindings.el
Use `visual-line-mode' when the `word-wrap' module is not enabled. Uses
the same wording and logic as the evil bindings.
=> emacs-bindings: default toggle for wrapping

modules/tools/lsp/+lsp.el
As I’m trying to use [corfu](https://github.com/minad/corfu) for a bit, I found out that this hook prevents lsp-mode from starting if company-mode isn’t used.
=> Feature-gate :tools lsp company-specific hooks

modules/config/default/+emacs-bindings.el
The "C-RET" counsel-company binding does only seem to work when running Emacs in a
terminal. "C-<return>" makes it work when running the desktop version too.
=> config/default: Fix C-return binding in GUI Emacs

modules/lang/web/+html.el
[Phoenix.LiveView](https://hexdocs.pm/phoenix_live_view) has a project called [Surface](https://surface-ui.org/) that adds a `.sface` extension to files. These should be syntax highlighted as html.
First PR!
=> Syntax highlight .sface files as html

modules/config/default/+emacs-bindings.el, modules/config/default/+evil-bindings.el, modules/lang/org/README.org, modules/lang/org/autoload/contrib-roam2.el, modules/lang/org/config.el, modules/lang/org/contrib/roam2.el, modules/lang/org/doctor.el, modules/lang/org/packages.el
This PR introduces support in Doom for `org-roam` v2, which just recently was released. It's still WIP (though most of the things are now done) and the following need to be addressed first, before this will be turned into a PR that can be merged:
=> lang/org: Add `+roam2` flag for org-roam v2

modules/completion/vertico/autoload/vertico.el
Doesn't do anything, it's a leftover from when the function was ported from the ivy module.
=> vertico: remove +fuzzy check in +vertico-file-search

modules/completion/vertico/autoload/vertico.el
needed now that embark is lazy loaded
=> vertico: require embark in +vertico/embark-export-write

modules/editor/evil/config.el
I think this was just underlooked? Otherwise there's no way to sync to the latest changes in state without <kbd>M-x</kbd>ing or bindings this in your private config.
=> editor/evil: Add gr keybinding to refresh `helpful` buffers

bin/doom
The current string presented breaks the address on how to upgrade Emacs:
```
❯ doom install
Detected Emacs 26.3 (at emacs).
Doom only supports Emacs 27.1 and newer. A guide to install a newer version
of Emacs can be found at:
https://doomemacs.org/docs/getting_started.org#on-linuxAborting...
```
Just adding a `\n` at the end of the string would solve it.
=>  Adding new line on string on how to upgrade Emacs

modules/tools/lookup/autoload/docsets.el
Convert the let form to let* to fix `Symbol’s value as variable is void: sink`.
=> Fix +lookup/in-docsets's vertico section

modules/config/default/+evil-bindings.el
Unfortunately I had to truncate "Run" from `:desc`, otherwise other 24 lines must be aligned, too (which will produce diff noises).
=> Add "SPC p &" binding as projectile-run-async-shell-command-in-root

modules/editor/format/autoload/format.el
A lot of lsp servers don't support `textDocument/rangeFormatting` but support `textDocument/formatting`(eg: `rust-analyzer`). The fallback formatter has some issues (like in rust-mode it won't respect the project's cargo files). I think it's better to use lsp as the default formatter as long as the lsp server support file formating.
=> Changed editor/format lsp feature requirement from textDocument/rangeFormatting to textDocument/formatting

modules/completion/vertico/autoload/vertico.el
instead of the Perl style.
`concat` can't operate on characters.
=> Fix +vertico-file-search when separator is used

core/cli/env.el
The variable is obsolete once we switch between "x11" and "wayland".
Also Emacs can infer it perfectly without setting it first.
=> Black list XDG_SESSION_TYPE from doom-env

modules/editor/fold/README.org
The keybinding for fold all and unfold all was wrong (was missing a C-f)
Fixes #0000 
{{{ Summarize what you've changed HERE and why }}}
=> Fixed the keybind for fold/unfold all

modules/completion/vertico/README.org, modules/completion/vertico/autoload/vertico.el, modules/completion/vertico/config.el, modules/completion/vertico/packages.el, modules/config/default/+emacs-bindings.el, modules/config/default/+evil-bindings.el, modules/tools/lsp/packages.el, modules/ui/doom/packages.el
This PR contains:
- bumps for `:completion vertico` and `:ui doom`
- teco's recent theming improvements for marginalia and orderless
- better keys for `consult-crm`
- a fix for `<leader> c j` since it used `cmd!` instead of `cmd!!`
- binding the new `consult-line-multi` to `<leader s B>` (the prefix argument makes it search all buffers, without it it just searches buffers of the current project) 
- usage of the recently introduced new embark indicator format
- add marginalia annotations to functions that don't have them
- advise the marginalia annotations for the `project-file` category to use projectile
- a bugfix for `consult-recent-file`
- bugfixes for `+vertico/find-file-in`
- replacing an obsolete embark function
cc: @tecosaur @elken @minad
=> Vertico improvements: theming, bugfixes, new bindings, adaptations to upstream changes

modules/tools/lsp/+lsp.el
in normal state by ESC.
We should have a way to quickly escape this beside "C-g":
=> Allow evil users to quickly close the LSP signature buffer

modules/email/mu4e/autoload/mu-lock.el
`mu4e` complains about a missing function if loaded too early. I don't know if
there's a cleaner way to do this, but it's needed AFAICT.
=> Allow mu4e to be started early

modules/lang/go/README.org
As Gore repository has been moved we have to update URL because `go get` won't handle redirects.
=> Update Go tool URL in README

modules/completion/vertico/autoload/vertico.el
What vanilla Emacs, Ivy and Helm do by default.
It makes searching much easier & friendlier.
=> Enable rg's smart case for +vertico-file-search

modules/lang/latex/config.el
I know https://github.com/hlissner/doom-emacs/commit/0d6c32ff25292ecdef7ecdfd1542bb65807c4d9a was supposed to fix *something*, but I'm just unable to use any keybind on latex-mode-map.
Binding it on both is the safest bet I think.
=> Bind TeX-view in LaTeX-mode-map too

modules/lang/clojure/config.el
More than a year ago a change was added to ob-clojure that prevented
evaluating a Clojure code block without setting
`org-babel-clojure-backend`. This change sets this to a default value of
CIDER, since that is the main tool used in Doom.
Without this change, manual configuration is required to use Clojure in
org babel documents.
=> Add configuration to ensure that CIDER is used for babel

modules/editor/lispy/config.el
With evil mode, `j` is used for both `special-lispy-down` and `evil-escape` which is bounded to `evil-escape-key-sequence`, "jk" by default.
A demo:
https://user-images.githubusercontent.com/58051033/127784994-05af014c-b857-41c1-ad10-865f198c42c8.mp4
=> Fix lispy `j` collision

modules/email/mu4e/autoload/mu-lock.el
Autoload cookie was not working as expected
=> Remove autoload cookie

modules/email/mu4e/README.org, modules/email/mu4e/autoload/mu-lock.el, modules/email/mu4e/config.el
Let me know if you want something better, but the commits here should be pretty descriptive.
This fixes two issues that have been reported on Discord for mac and mu4e 1.6 users.
```
fix(mu4e): account for signature change in v1.6
Mu4e 1.6 changes the signature of `mu4e-draft-open'. Since we don't care
about the args replace funcall with apply to make sure it's happy no
matter how many args it expected.
fix(mu4e): improve mu-lock compatability with mac
On mac process args aren't defined, but comm is. Since comm also works
on Linux, we now check for that instead, accounting for a potential
capitalisation difference.
docs(mu4e): fix a typo (errors, plural)
Someone politely requested I add this to my PR on Discord ... why not.
```
=> Mu4e hotfixes

modules/tools/direnv/README.org
The lorri repository changed locations recently. The old link that doom has merely points to the old repository that points to the new one. The new link is the current link for lorri.
=> updated lorri link

docs/getting_started.org
In some cases, ubuntu may contain a preinstalled version of Emacs26, which cannot be simply removed with "sudo apt remove emacs", and needs additional "sudo apt autoremove" to properly uninstall emacs26. Only this will result with the command "emacs" opening other version than emacs26.
Ref https://unix.stackexchange.com/a/84488
=> docs: add how to remove emacs26 in installation guide

modules/lang/org/config.el
It may happen that `org-agenda-new-buffers` contains a killed buffer. Perhaps it happens for me more because I dynamically update my agenda after startup, or because I used sticky agenda. Whatever the case, I'll occasionally get into a state where `+org-defer-mode-in-agenda-buffers-h` will try to add a hook to a killed buffer. I added a check to just skip those.
The original reporter of #4468 encountered this issue when killing the agenda buffer directly instead of calling `org-agenda-quit` (`org-agenda-Quit` for sticky buffers). I am seeing this issue even though I am always calling `org-agenda-Quit` to delete the sticky buffer.
=> Fix #4468: +org-defer-mode-in-agenda-buffers-h tries to select killed buffer

modules/tools/lsp/+eglot.el
Otherwise major mode's handlers might take place. For
example as in go-mode
Fixes #0000 
{{{ Summarize what you've changed HERE and why }}}
=> Explicitly set xref handlers when eglot is enabled

modules/emacs/vc/packages.el
BREAKING CHANGE: browse-at-remote-remote-type-domains is replaced by
browse-at-remote-remote-type-regexps. If you have a custom domain
configured replace:
(add-to-list 'browse-at-remote-remote-type-domains
("git.example.com" . "github")
with
(add-to-list 'browse-at-remote-remote-type-regexp
("^git\\.example\\.com$" . "github")
Added support for Gittiles.
=> bump!: :emacs vc

modules/email/mu4e/README.org
- requires being in an (after! mu4e ...) to work
- minor fixes
-------
@tecosaur this fixes the issue I was having
=> docs(mu4e): fix msmtp config in readme

.gitignore
After a `doom sync -u`, I got `${EMACSDIR}/{places,transient/history.el}`. It doesn't seem related to Doom, so ignore them. 
Btw I only had changed the version of a package in my packages.el because the one from a module was old (https://github.com/hlissner/doom-emacs/pull/5290).
```
(package! bibtex-actions
:pin "f4d9af720d3854ce0e746312061372ae30e2cc97")
```
=> Ignore 'places', 'transient/' after doom sync -u

modules/lang/coq/config.el
This was disabled upstream in
https://github.com/cpitclaudel/company-coq/commit/7423ee253951a439b2491e1cd2ea8bb876d25cb7
due to a serious performance impact on some systems (even if the spinner
isn't visible in the modeline).
=> fix(coq): disable spinner by default

modules/editor/evil/init.el
I can't find a rationale for this in the git history, and from looking
through the evil-collection entry I can't think of one.
=> fix(evil): use evil-collection for package-menu

modules/lang/org/README.org
The link to org-roam v2 in the org readme is broken. This pr fixes that.
=> docs: Fix broken link to org-roam v2 in org readme

modules/lang/python/config.el
eglot does not work out-of-the-box with pyright, so I add the five lines
=> fix(lsp): support +pyright with eglot

modules/editor/file-templates/templates/gitignore-mode/__
Adds "clojure" to the `yas-choose-value` list when creating a new `.gitignore`.
The values were taken from leiningen default template: https://github.com/technomancy/leiningen/blob/master/resources/leiningen/new/template/gitignore and included a `.cpcache` for projects using clojure `deps.edn`.
=> Add clojure gitignore template

modules/email/wanderlust/config.el
wl-summary-mode would not start in evil-emacs-state otherwise.
=> Start wl-summary-mode in evil-emacs-state

modules/editor/multiple-cursors/config.el
Fixes #5374 
Disabled iedit's default keybinding because it conflicts with embark in the new `:completion vertico` module, and iedit would pop up an annoying warning buffer about it. Since iedit is only used in Doom as a dependency of evil-multiedit, this should only negatively impact users who use iedit directly without vim keybindings (probably a tiny number of people).
=> fix(multiple-cursors): keybind conflict with embark

modules/lang/org/config.el
It's currently mapped to `org-footnote-new`, but `org-footnote-action` does the same when in a context where you want to insert a new footnote, plus has additional useful functionality in different contexts, like jumping between definition and reference, sorting/renaming/deleting footnotes. See [the Org Mode manual](https://orgmode.org/manual/Creating-Footnotes.html) (search for "footnote action") and [the docstring of `org-footnote-action`](https://code.orgmode.org/bzg/org-mode/src/master/lisp/org-footnote.el#L955-L967).
=> Consider mapping org-mode-map "f" to org-footnote-action

modules/lang/scheme/config.el
Guix is detected with a simple `executable-find`, and this trick assumes
that guix is running on version 3 of Guile (which hopefully won't
change for a while)
ping @flatwhatson in case I'm doing something horrible
=> feat(scheme): auto-add guix channels to load-path

modules/completion/vertico/README.org, modules/completion/vertico/autoload/magit.el, modules/completion/vertico/autoload/vertico.el, modules/completion/vertico/config.el, modules/completion/vertico/doctor.el, modules/completion/vertico/packages.el, modules/config/default/+emacs-bindings.el, modules/config/default/+evil-bindings.el, modules/config/default/autoload/default.el, modules/editor/evil/+commands.el, modules/email/notmuch/packages.el, modules/tools/lsp/+eglot.el, modules/tools/lsp/+lsp.el, modules/tools/lsp/packages.el
- Fix a minor issue with the new prefix-help-command settings
- add more thorough explanations to the readme
- Bump the module, and adapt to upstream changes
- update `all-the-icons-completion`'s recipe as it got accepted to melpa
- highlight vertico candidate on embark-act
- explain in the readme how the consult async regexp checks work, and add doctor checks for pcre support in grep and ripgrep
- fix `+vertico/find-file-in`not creating new files
- fix `consult-notmuch` bug (#5369)
- remap `xref-find-apropos` to `consult-lsp-symbols`
- unify error listing under `+default/diagnostics` and use `consult-lsp-diagnostics` if applicable
(sidenote - should the which key listing still be `List Errors`? `List Diagnostics` is more correct, but less obvious in meanings also might require the change …
=> Improve `:completion vertico`

modules/input/layout/+bepo.el
Just as magit took control of 's' after "key rotation", magit (at least
when unpinned) takes control of 't' and we need to manually unmap the
key so that 't' goes down one line when the cursor is on a magit section
header
=> fix(layout): prevent magit from stealing t in bépo

modules/editor/snippets/autoload/snippets.el
`+snippets-prompt-private` is being overzealous that intercepts the candidates triggered by `yas-choose-value`.
For example, triggering `jupyter` in org mode, renders
#+begin_src jupyter-Wrong type argument: yas--template, "python" :session  :async yes
#+end_src
=> fix(snippets): yas-expand error when yas-choose-value

modules/config/default/autoload/text.el
Sometimes we also want to specify the project name to let others know which mentioned project is.
=> feat(default): +default/yank-buffer-path-relative-to-project includes project name if prefix arg is passed

modules/tools/magit/packages.el
magit/forge@6e8ab6c67e3b -> magit/forge@6e8ab6c67e3bf97bc47e9e2a
To fix https://github.com/magit/forge/issues/414
=> bump: :tools magit

modules/lang/php/packages.el
In the pinned version of `php-cs-fixer` present in the php module (when the format module is also enabled), custom `php-cs-fixer` binaries specified via the `php-cs-fixer-command` var do not work.
This new commit (merged [here](https://github.com/OVYA/php-cs-fixer/pull/16)) fixes the issue, and allows for users to specify custom binaries or paths for the `php-cs-fixer` program.
=> Bump `php-cs-fixer` version in php module

modules/editor/file-templates/templates/sh-mode/__
This reverts commit ce2fee138a7eef2d01e67e555654bba934623297.
As of https://github.com/hlissner/doom-emacs/pull/2906 `set -euo pipefail` is added to any newly created `.sh` script. This snippet made my bash behave strangely after I used doom emacs to create a new `.bashrc` file.
Examples of what happens when `.bashrc` starts with the snippet:
```
cd Doc<tab> -> terminal crash without error message, despite Documents existing.
cat Documents -> terminal crash without error message. This command makes no sense since Documents is a directory, but it normally outputs the error message "cat: Documents: Is a directory"
```
This had me confused for a while and I thought my OS was at fault before I realized what was going on. I'm sure this snippet is reasonable in most cases, but since it's added …
=> Revert "Add set -euo pipefail to sh-mode file template"

modules/lang/emacs-lisp/autoload.el
Previously, OrgMode src blocks that contained Emacs Lisp were not given special treatment by flycheck, and were thus were given obtrusive warnings that only usually apply to Lisp being written as part of an Emacs package.
This PR adds a detection mechanism for these Elisp src blocks that allows the flycheck warnings to be disabled, as in one's Doom config.
=> fix(emacs-lisp): quiet doc lints in org src blocks

modules/email/notmuch/autoload.el
Tidy notmuch update process
-------
Notmuch sync process is done asynchronously, but if the user switch to other buffer before update process, it complains like
```
error in process sentinel: #<window 98> is not a valid window
```
This commit simplifies cleanup process after mail syncing, and still maintain its functionality.
=> fix(notmuch): window is not a valid window error on sync end

modules/config/default/+emacs-bindings.el, modules/config/default/+evil-bindings.el, modules/config/default/autoload/search.el
As discussed on the discord.
I think this implementation is more readable than using `(+vertico/project-search nil nil user-emacs-directory)` calls, but tell me if you disagree.
=> feat(default): add .emacs.d search on <leader> s e

modules/email/mu4e/config.el
Just two little QOL improvements here.
- `org-msg` checks for attachments using an overly simply regex, there are too many false positives. So, let's tighten that up a bit.
- Accidentally sending an email without a subject isn't nice. So, we add a hook to confirm that the user really wants to do this, and if not enter their desired subject line.
=> Mu4e: improve message checks at send

modules/ui/modeline/+light.el
Add missing page indicator for `+light` modeline, with code from `doom-modeline`.
=> Add pdf pages to +light modeline

modules/lang/web/+html.el
Since lsp-mode supports XML (see
https://emacs-lsp.github.io/lsp-mode/page/lsp-xml/), it makes sense to
add nxml-mode to the list of automatically enabled lsp mode clients.
=> tweak(web): add nxml mode to LSP enabled modes

modules/lang/common-lisp/config.el
After I set inferior-lisp-program to "ros -Q run", I see "WARNING: Couldn't find `inferior-lisp-program' (ros -Q run)" when load a ros file.
I see fix code at common-lisp/doctor.el, and I think the same check in config.el should be fix too.
=> fix(:lang/common-lisp): check inferior-lisp-program like "ros -Q run"

modules/lang/javascript/README.org
Fix the keybinding for `tide-rename-symbol` in the documentation - a single letter was missing.
=> docs(javascript): fix tide-rename-symbol binding

modules/lang/common-lisp/README.org
This PR adds a README to the `common-lisp` module. I intended to bump the `sly` pin too but Big H beat me to it.
=> docs(common-lisp): add a README

modules/app/rss/README.org, modules/app/rss/autoload.el, modules/app/rss/config.el, modules/app/rss/packages.el
This PR makes minor improvements to `:app rss` by adding
- the `+rss/copy-link` command and binding it to `g c` 
This is similar to the `elfeed-search-browse-url` command but copys the link
instead of sending it to the web browser 
- integrates `elfeed-goodies` which provides a better and more configurable UI
=> improve `:app rss` module

modules/email/notmuch/autoload.el
Remove the dependency of (:ui workspaces) from the notmuch module
The notmuch module had a hard-dep on the (:ui workspaces) module which was unnecessary; these (very simple) changes fix that.
(I'm calling it a "feat" since it introduces new behavior (debatable))
=> feat(notmuch): allow notmuch module without (:ui workspaces)

modules/email/mu4e/autoload/advice.el
A typo and a missing `*` break the creation and insertion of LaTeX images. This PR is literally just two characters being changed + indent changes. I did notice that the indentation was a bit off though in the file, so I've added a second commit which is just me running `= a G` on the file.
Closes #5416.
=> fix(mu4e): minor errors with org-msg LaTeX eqns

modules/lang/org/config.el
Adds an additional org binding, useful for repeated tasks with minor variations in time or name.
=> feat(org): add binding for `org-clone-subtree-with-time-shift`

modules/editor/parinfer/README.org, modules/editor/parinfer/config.el, modules/editor/parinfer/doctor.el, modules/editor/parinfer/packages.el
As brought up initially in the Discord, this PR modernizes the `parinfer` module by:
**Note:** This is a fairly breaking change, as it actually assumes that the user's Emacs was compiled with `--with-modules`. However, given that Doom requires Emacs 27 at minimum and that the major distributions likely ship with an Emacs built with `--with-modules` (I haven't checked), should we be concerned?
=> Improve `:editor parinfer`

modules/tools/pass/autoload/ivy.el, modules/tools/pass/autoload/pass.el
The following functions are affected: `+pass/edit-entry`,
`+pass/copy-field`, `+pass/copy-secret`, `+pass/browse-url`. All of
these functions have counterparts in `password-store`. Additionally, the
functions in password store add git commits when files are
changed.
The obsolete functions can be removed at some point.
Questions:
- Should we also deprecate the `ivy` and `consult` versions? The
`password-store` versions work perfectly well here with `vertico` (not
sure about `ivy` though).
=> refactor(pass): make duplicate functions obsolete

modules/emacs/dired/config.el
Overrides ranger-travel to have better mode detection for which
completion framework to use, and default to emacs built-ins instead of
ido.
In theory this should be a temporary fix until ralesi/ranger.el#236 gets
merged, but the maintenance status of ranger.el is not clear.
Fix #5509
Ref ralesi/ranger.el#236
=> fix(dired): ranger-travel bug

modules/config/default/+emacs-bindings.el
Make bindings better conform to traditional sexp navigation ones.
Fix #5575
@hlissner I've chosen `C-M-<backspace>` for the non-standard `sp-splice-sexp`, I believe it's worth keeping a binding for the function but if you believe it's not the best key please let me know, at least it's not yet used and has mnemonic value.
=> tweak(default): improve smartparens vanilla bindings

core/cli/ci.el
dev(ci): fix false negative in commit linter
The one value allowed per trailer check shouldn't apply to names since
they often have spaces.
dev(ci): allow periods in names in commit linter
For initials.
=> Fix commit linter bugs

early-init.el
set-language-environment sets default-input-method, which is unwanted.
Fix: #5046
-------
@ineu @dukebarman please confirm on your end that this fixes the issue. It unsets the default input method, but I never had the locale autodetection thing, so I'm not sure if that's still a problem.
=> fix: unset default-input-method in early-init.el

core/core-editor.el
`doom--fix-broken-smie-modes-a` forces `dtrt-indent-mode` to expect exactly one argument so an error will be raised when the latter is turned on without arguments programmatically in lisp.
=> fix: wrong number of arguments when calling (dtrt-indent-mode)

modules/lang/clojure/config.el, modules/lang/clojure/packages.el
This PR use the new cider hooks to improve the REPL icon on modeline. At the moment we just show the REPL icon as yellow if cider not connected and green if connected, with this PR we add a new intermediate state of REPL in sync:
Now, If the REPL is not connected we show the icon:
If the REPL is connected but nothing was evaluated or cider is still evaluating any code, we show:
If cider is in sync/not evaluating anything, we show:
This is a follow up of https://github.com/clojure-emacs/cider/pull/3084 and https://github.com/clojure-emacs/cider/pull/3089
Another gif showing the new feature:
=> feat(clojure): Improve REPL icon modeline for cider

modules/lang/latex/config.el
This guarantees that `TeX-fold-buffer` is run after the style hooks and not before. Otherwise, it looks like they may reset/erase font-lock stuff you have set up.
Currently, `TeX-fold-buffer` sometimes is applied before font locking hooks, causing incomplete folding (usually wrong colorization).
=> fix(latex): run AUCTeX folding after font locking

modules/email/mu4e/autoload/email.el
Within +mu4e/capture-msg-to-agenda, the from address is stored in the
cdar not the cadr.
Unfortunately, I think I just made a typo in the original implementation, oh well — it comes up rarely but this should fix it.
=> quick fix(mu4e): incorrect access of from addr slot

modules/lang/org/contrib/roam2.el
This pr changes the hook `org-roam-find-file`, so that it checks if the buffer was opened by `org-capture`. 
PS: using `(not (window-parameter nil 'window-side))` instead of `(not org-capture-mode)` would probably work as well, but this line was removed in the transition from roam to roamv2, which is why I'm not sure if this line is still wanted
=> fix(org): no roam buffer for capture buffers

modules/email/mu4e/config.el
Tiny change.
Fixes bug about void function `+workspace/other` when pressing `h` in `mu3e` when workspaces are deactivated.
=> fix(mu4e): only bind `h` when `workspaces` loaded

modules/email/mu4e/autoload/mu-lock.el
Fixes #5788 
In the function `+mu4e-lock-pid-info` in `mu-lock.el`, the variable `coding-system-for-read` is set globally which is against its documentation's recommendation and can cause issues as described in #5788. Setting the value in the `let*` statement instead through `setq` fixes this issue for me.
=> fix(mu4e): do not set coding-system-for-read globally

modules/email/notmuch/autoload.el
`if-let*` returns a window type, not a buffer which would cause a `Wrong type argument: stringp, #<window 3 on *doom*>` when trying to access notmuch via `=notmuch` while it is already open in a workspace.
=> fix(notmuch): incorrect type used for window

modules/config/default/+emacs-bindings.el, modules/config/default/+evil-bindings.el, modules/tools/biblio/config.el, modules/tools/biblio/packages.el
bdarcus/bibtex-actions@08c6ca0e5b73 -> bdarcus/citar@fd33f5c4f798
bibtex-actions is now called citar, and the package comes with
configuration for embark.
Fix: #5723
Close: #5747
=> bump: :tools biblio

modules/config/default/autoload/files.el
Fix `+default/discover-projects` to read the depth in `projectile-project-search-path`.
=> fix: +default/discover-projects not reading depth

modules/emacs/vc/autoload/vc.el
Fixing vc/browse-at-remote in files opened via SSH on remote servers.
**browse-at-remote** uses **vc-git-root** to find git root project.  **vc-git-root** ignores directories matching **vc-ignore-dir-regexp**. **vc-ignore-dir-regexp** is set to ignore TRAMP buffers to speedup projectile. Which means vc-git-root can't find git root in TRAMP buffers.
Temporary revert **vc-ignore-dir-regexp** to default value (which doesn't ignore TRAMP buffers) 
Fixes #5660
=> fix(vc): +vc/browse-at-remote fails in TRAMP buffers.

modules/lang/org/autoload/org-refile.el
MEETS THE
FOLLOWING CRITERIA:
Summary:
Before this change, the refile to current file command would result in a list of headings in current file. 
In case of duplicate names, it was hard to tell which heading referred to which.
With org-refile-use-outline-path set to t, now you should see a baths to each heading in a file.
I can easily replace this function in my local config, but I think this change should be the default.
=> fix(org): show outline path on refile to current file

modules/tools/lsp/autoload/flycheck-eglot.el
Fixes #5644 
This PR only renames `flymake--diag-buffer` as `flymake--diag-locus` in `modules/tools/lsp/autoload/flycheck-eglot.el`.
=> fix: flymake--diag-buffer is now flymake--diag-locus

core/cli/doctor.el
The message simply test for the "not-a-version-yet" patch number and
displays an explanation to prepare users for raised error frequency and
having a backup version of Emacs if they do not want to deal with issues.
(Of course, feel free to discard it if it's too much).
Rendered (yes, I struggled with autofill :( ) :
=> dev(doctor): add error message for Emacs dev versions

modules/email/notmuch/autoload.el, modules/email/notmuch/config.el
Introduce `+notmuch-delete-tags` and `+notmuch-spam-tags` variables instead of hardcoding the tags. The default values are set to the previously hardcoded values and the change does thus not break any existing users.
=> refactor(notmuch): parameterize delete/spam tags

modules/ui/doom/README.org
This commit fixes doom-variable-font so it is consistent with the actual variable used within doom, which is 'doom-variable-pitch-font'.
=>  fix(doom): inconsistent doom-variable-pitch-font name

modules/email/notmuch/config.el
Tagging all messages can cause very heavy load and is not necessary.
Just indexing new messages is quicker and lighter.
If one needs to tag all messages again it is still possible to do so manually.
Changes `afew -a -t` to `afew -n -t` which is an equivalent of `afew --new --tag`.
=> feat(notmuch): only tag new messages w/ afew 

modules/tools/lookup/autoload/lookup.el
Fixes #5737 
This is not a mode specific issue but is actually caused by changes to _xref_. _Xref_ was changed in the emacs repo about a month ago. I have already created a patch for a mode that needed to adjust to _xref_'s internal changes.
[xref's recent history](https://github.com/emacs-mirror/emacs/commits/master/lisp/progmodes/xref.el)
Xref started many backwards incompatible changes in the name of performance. The marker ring no longer exists as a variable. `+lookup--xref-show` will silently fail every time.
Switches to using `xref-after-jump-hook` to test whether _xref_ actually jumped to a definition. The hook is part of the exposed interface and should hopefully not change in the near future.
=> fix(lookup): xref 1.3.0 removed var xref--marker-ring

modules/term/eshell/config.el
Currently eshell has a `clear` alias which maps to `eshell/clear-scrollback`. It also has a <kbd>C-l</kbd> binding for calling `eshell/clear`, which doesn't call the alias. This PR makes <kbd>C-l</kbd> call `eshell/clear-scrollback` for consistency with the alias.
=> tweak(eshell): C-l binding to clear scrollback

modules/lang/dart/config.el
This is unnecesary since hover search flutter in the path
Emacs says that file does not exists when I try to run any flutter command and I can't override `flutter-sdk-path` on the config file.
Removing these lines everything works fine
=> fix(dart): remove hardcoded path to flutter SDK

init.example.el, modules/tools/biblio/README.org, modules/tools/biblio/config.el, modules/tools/biblio/packages.el
Sorry; because of the massive recent merges, and my shaky git skills, I had to redo #5212 to get the git correct. 
This adds support for native org-mode `org-cite` citations. Specifically it:
1. configures the native `org-cite` processors
2. adds the `oc-bibtex-actions` processor for the vertico module, with "follow", "activate", and "insert" capabilities
3. ~adds and configures the new `org-ref` OC rewrite: https://github.com/jkitchin/org-ref-cite~ (removed for now because of unclear future)
3. installs [citeproc-el](https://github.com/andras-simonyi/citeproc-el), which is required for the `oc-csl` export processor, and will be needed also for forthcoming preview functionality
_Should bump org along with this_, as this depends on a recent change in org (namely that now loads oc-basic, …
=> Add org-cite to :tools/biblio

modules/tools/biblio/config.el
-------
Due to unconditional loading configuration for `citar-org` package, `org` is also being loaded eagerly.
Especially, causes a warning message from doom, like
``` text
‘org’ was already loaded by the time lang/org loaded, this may cause issues
```
=> fix(biblio): do not load org mode eagerly.

core/core-editor.el
Emacs 29.x introduces xref-go-{back,forward}. xref-pop-marker-stack is
now obsolete.
Fix: #5813
Signed-off-by: Clément Guidi <clementguidi@gmail.com>
=> fix: remap xref-go-* to better-jumper

modules/completion/vertico/README.org
They were generated using a subsequent Vertico PR, not the one that
added the module.
=> docs(vertico): fix #+CREATED and #+SINCE keywords

modules/lang/latex/+fontification.el, modules/lang/latex/+ref.el, modules/lang/latex/+viewers.el, modules/lang/latex/autoload.el, modules/lang/latex/config.el, modules/lang/latex/packages.el
See #5621, actual changes to code have been removed.
This is a huge set of pedantic changes, none them affecting actual code.
Mostly, I tried to:
- use consistent names; e.g, use LaTeX wherever possible, not latex;
- fix broken symbol links;
- use capitalized comments with full stops.
=> refactor(latex): nitpick, table d'hôte

modules/email/notmuch/config.el, modules/email/notmuch/packages.el
[org-contrib](https://git.sr.ht/~bzg/org-contrib) is moving a number of files to separate repositories, including ol-notmuch.el. ol-notmuch.el is set up by default in the notmuch module, but was no longer installed by default, resulting in a `Problems while trying to load feature ‘ol-notmuch’` message when opening the org-agenda.
The new repo location is referenced in the file at org-contrib: https://git.sr.ht/~bzg/org-contrib/tree/e14dfea5/item/lisp/ol-notmuch.el#L8
=> fix: ol-notmuch moved from org-contrib to new repo

modules/config/default/+emacs-bindings.el
this is to change the default keymap of persp-mode correctly and avoid
weird bugs
- https://github.com/Bad-ptr/persp-mode.el/blob/298df111f081b5925f0aa0126a1b8d334117e0a2/persp-mode.el#L1002-L1017
- https://www.reddit.com/r/DoomEmacs/comments/qgn814/adding_a_specific_package_as_a_module/?utm_source=share&utm_medium=web2x&context=3
- https://github.com/merrickluo/lsp-tailwindcss/issues/22
Under [some circumstances](https://www.reddit.com/r/DoomEmacs/comments/qgn814/adding_a_specific_package_as_a_module/?utm_source=share&utm_medium=web2x&context=3) `:config (default +bindings)` will fail to rebind the keymap of persp-mode which in turn breaks some bindings for projectile, to prevent this bug from happening, using a function [provided by …
=> Use persp-set-keymap-prefix instead of setq

modules/editor/evil/autoload/embrace.el
If the surround key is `\(`, the text should be surrounded as
`\( text \)`. The same for `\[` and `\{`.
Currently, when the surround key is `\(`, `+evil--embrace-escaped` returns `"\( " . "\ )"`, which changes the text to `\( text\ )` (notice a whitespace before `\` and `)`).
=> fix(evil): handle edge cases of embrace

modules/editor/evil/config.el
Use `evil-embrace` for typsetting quotations in latex instead of
`evil-surround`.
Single quotation marks are produced in LaTeX using ` and ' . Double quotation marks are produced by typing `` and ''. 
This should be an upstream fix for `evil-embrace` but looking at the latest commit of https://github.com/cute-jumper/embrace.el, I think it's better to send a PR to doom.
=> fix(evil): correct typesetting quotations in latex

modules/lang/sh/config.el
The `whatis` command is excessively slow on mac OS, rendering
company-shell unusable.
re: #5839
=> fix(sh): disable meta fetch by default on mac OS

modules/ui/popup/config.el
Steps to reproduce:
1. `report-emacs-bug`
2. Switch to buffer `*unsent mail to bug-gnu-emacs@gnu.org*`
3. Save the buffer, then kill it
4. Open the saved message
Observed:
- After step 1, the new buffer is poped up briefly, then replaced by `*Bug Help*` buffer and doesn't appear.
- After step 4, the buffer (whose name is `*message*-yyyymmdd-hhmmss`) who holds the saved message file is treated as a popup and at the bottom.
=> fix(popup): report-emacs-bug and its saved  files are treated as popups.

modules/lang/fsharp/config.el
Applies from .NET Core 2 onwards, so ideally this would just be hardcoded but it's fine to be gated too.
=> feat: change inferior-fsharp-program to dotnet

modules/lang/org/packages.el
org-roam/org-roam@a2e46db80848 -> org-roam/org-roam@abe63b436035
Recent Emacs master removed the `###autoload` cookie
about `ucs-normalize-NFD-string`, which will cause org-roam
not able to create nodes. org-roam has fixed this thus a bump
is needed.
Also, org-roam has introduced the way to customize how
contents are retrived. This should fix #5766.
Ref: https://github.com/org-roam/org-roam/issues/1981
Ref: https://github.com/org-roam/org-roam/pull/1990
Fixes #5766
=> bump: org-roam

modules/completion/vertico/autoload/vertico.el, modules/completion/vertico/config.el, modules/completion/vertico/packages.el
I have some feature additions I've been meaning to add, namely to improve the `consult-completing-read-multiple` keybindings and maybe remove some embark keybindings that relate to `M-x customize`, but I've been a bit busy and the module is a month out of date at this point, so I'm sending this in the meantime.
=> bump: :completion vertico

modules/lang/nim/packages.el
Includes [nim-suggest.el fix](https://github.com/nim-lang/nim-mode/commit/744e076f0bea1c5ddc49f92397d9aa98ffa7eff8) for nim-mode on Emacs 27+ (void function error).
=> bump: nim-mode

init.example.el, modules/lang/fortran/README.org, modules/lang/fortran/autoload.el, modules/lang/fortran/config.el, modules/lang/fortran/doctor.el
This PR adds support for the [Fortran Language](https://fortran-lang.org/), since an off-the-shelf solution mostly doesn't exist if you aren't using Visual Studio on Windows. Critically, this PR brings together all the treats of modernity recently added to the Fortran world; namely a package manager and LSP. It also bridges the gap between `gfortran` and Intel Fortran, since the latter is much loved but hard to integrate into development environments.
- ~Optional modeline buttons for building/running (`+buttons`?)~
- ~`+intel`~
**Note to Self:** Look into `ob-fortran`.
=> Add `:lang fortran` module

modules/tools/magit/autoload.el, modules/tools/magit/config.el, modules/tools/magit/packages.el
code-review is considered to be a superset of github-review, and as well
as supporting more forges (gitlab support is WIP) also better fits in
with magit.
Fix: #5812
=> feat(magit): replace github-review for code-review

modules/config/default/autoload/default.el, modules/config/default/config.el
`man -k "^"` is very slow on macOS, which is what `M-x man` uses for `completing-read`: https://github.com/emacs-mirror/emacs/blob/3af9e84ff59811734dcbb5d55e04e1fdb7051e77/lisp/man.el#L932
```
sh-3.2$ time man -k "^" > /dev/null
real	0m1.599s
user	0m0.391s
sys	0m1.209s
```
It's possible that this could just be a me issue, so if anyone else with a mac can fact-check this that would be great!
=> fix(default): only use `woman` on macOS

modules/lang/crystal/config.el
This adds some Crystal shortcuts mostly for specs that are modeled on ruby-mode.
=> crystal: enabled spec shortcuts for crystal

modules/tools/magit/config.el
The database and log file of `code-review` were put directly inside `.emacs.d`causing the repository to appear dirty. This PR moves the files inside the `.local/etc/code-review` folder to comply with the rest of doom functionality. 
The issue was introduced in 2d3a68df496f when switching to `code-review`.
=> fix(magit): move code-review files to etc dir

modules/lang/nim/packages.el
Wrong SHA in fd2788c (looks like a copy-paste mishap).
Ref: nim-lang/nim-mode@744e076
=> fix(nim): correct nim-mode SHA

modules/emacs/dired/packages.el
I just had `doom sync` fail during checkout of `dired-git-info`. It looks like the repo's git history has been rewritten, so that the previously-pinned commit no longer exists. I've updated the hash to point to the "new" `master` (which is still timestamped Dec 2019).
=> bump: :emacs dired

modules/checkers/grammar/config.el
Did I already mention that this `latex-mode` slash `LaTeX-mode`
ambiguity was a reeeeeeally bad decision upstream? Anyways, this very
small PR also loads `writegood-mode` with AucTeX, which uses
`LaTeX-mode`, and not `latex-mode`.
=> fix(grammar): `writegood-mode` in `LaTeX-mode`

modules/tools/lookup/README.org
`dash-docset-install-docset` does not exist.
=> docs(lookup): fix typos

modules/emacs/dired/config.el
On slow connections `dired-auto-revert-buffer` causes excessive
slowdowns; this limits its behavior to local files.
=> tweak(dired): don't auto-revert when remote

modules/tools/magit/config.el
code-review is built on magit-sections so it will have the same default
bindings for M-1, M-2 etc. To be consistent with the rest of doom, those
should be used for switching workspace and z1, z2 etc. should be used for
toggling outlines in a magit-sections buffer such as the code-review buffer.
This only affects users with :editor (evil +everywhere) enabled.
=> fix(magit): unbind M-1 etc. for code-review

modules/lang/python/config.el, modules/tools/eval/autoload/eval.el, modules/tools/eval/autoload/settings.el
Implements the `:send-region` and `:send-buffer` handlers as mentioned on the roadmap [here](https://discourse.doomemacs.org/t/development-roadmap/42#v2201-2), and sneaks in a fix for the Python REPL :)
Fixes #4375
=>  Add :send-region and :send-buffer options to `set-repl-handler!`

modules/lang/coq/README.org
Add the following to the :lang coq README
+ Hack: Abbrevs are replaced with snippets
+ Installation: To enable completion you also need :completion company
+ Installation: coqtop is required, link to coq download site
+ Troubleshooting: Link to related github issues
=> docs(coq): Expand README

modules/config/default/config.el
The default haskell-mode rules would result in an extra } appended to
the closing pair (#5448).
Fix: #5448
Close: #5450
-------
I want this to be fixed, but @celsobonutti seems to be busy, so I incorporated the review requests into a new PR. They're still credited as the commit author of course.
=> fix(default): smartparens rules for haskell

modules/lang/erlang/config.el, modules/lang/erlang/doctor.el, modules/lang/erlang/packages.el
1. Upgrade OTP version to fix broken erlang mode. See Github issue erlang/otp#5314
2. Remove `company-erlang` and `ivy-erlang-complete`. The lsp mode provides
much better function than these two packages. `ivy-erlang-complete`
would slow down the buffer enabled erlang mode when the buffer is huge
enough. It is not a good choice to integrate `ivy-erlang-complete` nowadays.
=> fix(erlang): fix broken erlang-mode

modules/lang/haskell/README.org
Small fixup to use the proper form when setting an alternative formatter using the `after!` macro.
_Small note:_ This PR targets the `rewrite-docs` branch as per [the Discord message here](https://discord.com/channels/406534637242810369/406624667496087572/927300806250754048)
=> docs(haskell): fix docs for alternative formatter

modules/lang/web/config.el
Hi 
Just send in a small tweak regarding angular and the ionic framework.
Here are the details: 
- Add @angular/core in detecting angular to set the web-angularjs minor
mode
- At the same time set the web-mode-engine to "angular" so that
`format-all` uses prettier to format ionic `*.page.html` files in
addition to `*.component.html` files.
When `format-all` sees the web-mode-engine is set to "angular", it
applies `prettier` as opposed to `html-tidy`, as `tidy` doesn't
recognise angular component tags and hence errors out. The current
web-mode only sets the engine to "angular" for "*.components.html".
However, ionic angular uses file names such as "*.page.html", setting
engine will apply prettier to these html fils.
Many thanks
Marty
=> tweak(web): detect and set angular in web-mode

modules/lang/clojure/config.el
As `clojurec-mode` is a distinct mode from `clojure-mode` when `+eval/open-repl-same-window` or `+eval/open-repl-other-window` is run in a buffer when `clojurec-mode` is the major mode the list of available REPLs will include REPLs for other languages, for example `emacs-lisp (default)`.
What's more, if you then try to select `clojure (default)` from the list you get the following error in the minibuffer:
```
and: Symbol’s function definition is void: cider-current-repl
```
(This may be an unrelated issue.)
> 👋🏻 This is my first pull request against Doom. Please let me know if I got anything wrong, or if you'd like me to submit an issue for the above behavior!
=> fix(clojure): Add clojurec-mode repl+eval handlers

modules/lang/php/autoload.el, modules/lang/php/config.el, modules/lang/php/packages.el
Replace the php repl handler with psysh
Fixes #5965
* Removed php-boris from php module packages and replaced it with [psysh](https://github.com/emacs-php/psysh.el)
* Set repl handler for php-mode to use psysh
=> feat(php): replace php-boris with psysh

modules/lang/org/README.org
Fix a typo in org module capture example
=> docs(org): fix type in org README capture example

modules/lang/javascript/config.el
Fixes https://github.com/emacs-lsp/lsp-mode/discussions/3308
lsp-mode doesn't detect the correct indentation, since it treats the derived tsx-mode as a web-mode. This change modifies the lsp-mode internal alist to recognize tsx-mode correctly. Ideally lsp-mode would have a better way to modify its known mode lists but I couldn't see it.
=> fix(javascript): incorrect lsp formatting for tsx

modules/completion/vertico/README.org, modules/completion/vertico/autoload/vertico.el, modules/completion/vertico/config.el, modules/completion/vertico/packages.el
- a rework of how the `completing-read-multiple` keybindings work (see commit message for details)
- module bump 
- added `C-c C-s` binding for `embark-collect-snapshot`
- all embark buffers are now handled as popups, and don't die after dismissal
- add `+default/search-emacsd` to manual preview list
=> `:completion vertico` improvements

core/cli/upgrade.el
Make master branch accessible before trying to use it.
Fixes #5999
=> fix(cli): switch to master on upgrade

modules/lang/haskell/doctor.el
So that if someone follows the advice of the warning, it will then go
away
=> docs(haskell): add lsp predicate to format check

modules/app/rss/autoload.el
This is to make it conform to the convention that all other app
workspaces conform to (plus it was bugging me)
=> tweak(rss): use asterisk around workspace name

modules/editor/evil/autoload/evil.el
Taking a look at the built in windmove functions shows that Emacs has a
built in function for swapping windows called `window-swap-states`.
Using this ensures the window state is maintained.
=> Maintain window states in +evil--window-swap

modules/lang/clojure/doctor.el
I've added a doctor.el to the clojure module with a check for the clj-kondo binary, required by flycheck-clj-kondo.
I end up forgetting to install clj-kondo when setting up a new computer, and doom doctor has always been a friend.
Please let me know if there's anything that needs fixing - the warning text or other things - as this is my first contribution here :eyes: 
I saw on discord we should actually target master right? This is the correct PR now (I previously targeted develop with https://github.com/hlissner/doom-emacs/pull/6029)
=> feat(clojure): add doctor.el for clj-kondo

modules/term/vterm/README.org
Some time late 2019 emacsPackagesNgGen was removed from NixOS. This commit updates the instructions in the vterm readme to use the modern alternative: emacsPackagesFor.
=> docs(vterm): update nixos install instructions

modules/term/eshell/autoload/eshell.el
This pull request corrects a mistake in the function docstring for `+eshell/here`. This function reuses the current  window but not the current buffer.
EDIT: See `+vterm/here`.
=> docs(eshell): fix +eshell/here docstring

modules/editor/evil/autoload/advice.el
`window-selection-change-functions` expects hooks to have one argument.
Edit: functions such as `treemacs--follow-project` (by `treemacs-project-follow-mode`) will raise errors after calling `evil-window-vsplit`.
=> fix(evil): wrong-number-of-arguments when run-hooks window-selection-change-functions

modules/lang/julia/config.el
As of 1 Dec, Julia v1.6 is the [new LTS release](https://discourse.julialang.org/t/julia-v1-7-0-has-been-released-and-v1-6-is-now-lts/72336). ~~This bumps the docs to reflect this~~ as well as the configuration for the default environment in the lsp backends.
EDIT: The update to the docs will be in another commit.
=> tweak(julia): update lsp environment to recent LTS

modules/lang/julia/README.org
This is the docs portion of the update from #6010 
As of 1 Dec, Julia v1.6 is the new LTS release. This bumps the docs to reflect this change.
=> docs(julia): update lsp environment to recent LTS 

modules/lang/org/contrib/pretty.el, modules/lang/org/packages.el
The contents of this pull request prettify tables for users of `(org +pretty)`. This is done through the `org-pretty-table` package. This package uses overlays to replace the '-', '+', and '|' characters in tables with unicode glyphs
=> feat(org): add org-pretty-table for +pretty

core/cli/install.el
That's helpful when we need to `doom install` in a non-git directory.
Ref: #5878
Close: #5862
=> feat(cli): Allow opting-out of deploying git hooks

modules/lang/python/config.el
[this PR](https://github.com/joaotavora/eglot/pull/742/) has preconfigured pyright in eglot. So these lines can be removed.
revert #5355
=> tweak(python): update eglot with `+pyright` flag

modules/emacs/dired/config.el
Module `(dired +icons)` currently display icons in monochrome (i.e black & white). 
This PR aims to provide a better default UI with colored dired icons.
=> display dired-icons with colors

modules/lang/plantuml/doctor.el
As it is stated in the plantuml [quickstart](https://plantuml.com/starting) guide, plantuml has a soft dependency, which is graphviz/dot.
However, for like 90% of its functionality (10% being sequence diagrams) is required. Therefore it is safe to say it must be in the doctor.el of the module.
Also, it depends on libawt and one other libawt_xawt.so not just "java". The point is, it requires a full openjdk-jre installation not a headless version. Headless version does not provide the second file so java throws a long exception.
I am not gonna add that to the doctor.el. But I suggest it is needed. A pseudo-code like this is my mind but since I was not sure I didn't try to add it for I know there are more aware guys here who can do this in a more optimized manner:
```lisp
(when …
```
=> Add graphviz/dot check to plantuml/doctor.el

modules/completion/vertico/config.el
`(car. cdr)` -> `(car . cdr)`
Fix dotted pair syntax in `marginalia-command-categories` for `+default/find-file-under-here`, so all the completion-category-driven machinery works as intended.
=> fix(vertico): completion category of +default/find-file-under-here

modules/tools/tmux/autoload/tmux.el
Executing `+tmux/rerun` after `+tmux/run`, should rerun the shell command specified in the `+tmux/run` call.
The following backtrace appears after executing `M-x +tmux/rerun`
```elisp
Debugger entered--Lisp error: (wrong-number-of-arguments ((t) nil "Rerun the last command executed by `+tmux' and `+t..." (interactive "P") (if +tmux-last-command nil (user-error "No last command to run")) (apply #'+tmux +tmux-last-command)) 1)
+tmux/rerun(nil)
funcall-interactively(+tmux/rerun nil)
command-execute(+tmux/rerun record)
execute-extended-command(nil "+tmux/rerun" #("tmux" 0 4 (ws-butler-chg chg)))
funcall-interactively(execute-extended-command nil "+tmux/rerun" #("tmux" 0 4 (ws-butler-chg chg)))
command-execute(execute-extended-command)
```
Running `doom sync`, `doom upgrade`, `doom build` …
=> fix(tmux): +tmux/rerun fails due to malformed +tmux-last-command

modules/term/vterm/autoload.el
this is no longer necessary as vterm handles this
natively. moreover, it creates a redundant nested
ssh session whenever `SPC o t` is used to re-open an
existing vterm popup.
=> fix(vterm): remove +vterm--change-directory-if-remote

modules/completion/vertico/autoload/vertico.el
Previously, +vertico/embark-export-write doesn't let embark execute other added hooks in embark-after-export-hook.
Edit: Add the edit command at the end of the hook list since other hooks may assume that the buffer isn't yet editable.
=> fix(vertico): let C-c C-e run existing embark-after-export-hook

modules/app/rss/autoload.el, modules/app/rss/config.el
Created a new symbol, `+rss-workspace-name`, which holds the value of the name of both the elfeed buffer and elfeed workspace. Then, I changed the `kill-buffer-hook` so it kills the workspace with this value. A previous commit changed the name of the workspace and buffer, but no the target of the `kill-buffer-hook`. This change fixes it avoiding repetition as well.
=> fix(rss): kill-buffer-hook removes +rss-workspace-name

modules/app/rss/config.el
I introduced an umbalanced parens expression in https://github.com/hlissner/doom-emacs/pull/6065, this PR fixes it.
=> fix(rss): unbalanced parens in map!

modules/lang/org/contrib/dragndrop.el
Org-attach (and thus org-download) can work before the first headline if the user sets `org-attach-auto-tag` to `nil`. But when inserting files in this situation, the `+org--dragndrop-then-display-inline-images-a` advice will display an error message due to using `org-back-to-heading`. So I think it makes more sense to use `org-back-to-heading-or-point-min` in the advice.
=> fix(org): don't error org-download at top level

modules/emacs/undo/packages.el
ideasman42/emacs-undo-fu-session@edf050d61334 -> ideasman42/emacs-undo-fu-session@3e810c7c9ab7
I changed the commit hash for undo-fu-session, as upstream seems to have squashed the commit:
[edf050d6](https://gitlab.com/ideasman42/emacs-undo-fu-session/-/commit/edf050d6133478d04fc06cc65914517b18d6bcc6) -> [3e810c7c](https://gitlab.com/ideasman42/emacs-undo-fu-session/-/commit/3e810c7c9ab75d2b6f92c7c876290abbc164e750)
Only 3e810c7c is attached to [master](https://gitlab.com/ideasman42/emacs-undo-fu-session/-/commits/master).
There are no changes between these two commits with the exception of a log line, but I was getting some warnings that the edf050d6 object could not be found when running doom upgrade a few times:
First run of doom upgrade
```
> (80/291) Re-cloning …
```
=> bump: update squashed hash in emacs-undo-fu-session

modules/lang/org/packages.el
emacsorphanage/gnuplot@d1a6a60 -> emacsorphanage/gnuplot@7138b13
Temporarily fixes #6080 
Reverts bump of gnuplot from commit 2557e17, as it breaks running gnuplot blocks from org-mode (babel).
=> revert(org): gnuplot 8.0.0 does not work with org babel

modules/lang/web/+html.el
web-mode renamed the function to re-highlight the buffer. It is now called `web-mode-reload`. This PR fixes it.
=> fix(html): web-mode did rename web-mode-buffer-highlight to web-mode-reload

modules/lang/csharp/packages.el
emacs-csharp/csharp-mode@fe8a68e9849fc7617e0c870cacd6599b8a797638 -> emacs-csharp/csharp-mode@9917e1b97d6a374c8043124817142ea3419a649b
Bump csharp-mode to its latest tag.
=> bump: :lang csharp

init.example.el
Without +lsp, both irony-mode and rtags require extra configuration for
system header path on macOS.
With +lsp, clangd works well out of the box, and it's easier to
configure than two separate daemons.
Ref: https://github.com/Sarcasm/irony-mode/wiki/Mac-OS-X-issues-and-workaround
Ref: Andersbakken/rtags#811
=> tweak(cc): default to +lsp

modules/lang/emacs-lisp/config.el
Enable `emacs-lisp-mode`'s local leader commands for `lisp-interactive-mode`.
Those commands work in the latter mode, too.
=> tweak(emacs-lisp): local leader for lisp-interaction-mode

modules/email/mu4e/config.el
Use all-the-icons for nicer symbols, and add helpful minibuffer on-hover descriptions.
=> feat(mu4e): more helpful headers mode-line symbols

modules/config/default/+evil-bindings.el
Hello,
This is my first PR in this wonderful project!
The default bindings for `multiple-cursors` are great, however, when making multiple cursors (from a selection for example using `evil-mc-make-and-goto-next-match`), I often like to skip some matches in some cases, something like this:
```
Make a cursor here▋and here▋but not here, then make another one here▋
```
`evil-mc` have a solution for this through `evil-mc-skip-and-goto-next-match`, `evil-mc-skip-and-goto-prev-match`, `evil-mc-skip-and-goto-next-cursor` and `evil-mc-skip-and-goto-prev-cursor`. But the default bindings do not include them. I've added bindings for these commands in my config file, but I think they should be present in Doom.
I propose to add a binding under:
-   `g z s` and `g z S`, `s` for `skip`.
-   `g z c` and …
=> feat(multiple-cursors): add bindings to `evil-mc-skip-*`

modules/editor/evil/init.el
Fixes #6119.
By appending the value of `evil-collection-key-blacklist` (if set by user, else nil by `defvar`) when setting it.
=> tweak(evil): respect users' evil-collection-key-blacklist

modules/emacs/ibuffer/config.el
Error message on C-x C-f in `ibuffer` :
```
(wrong-number-of-arguments ((t) (_file &optional _wildcards) "Use `counsel-find-file' instead of `find-file'." (interactive) (counsel-find-file (let ((buf (ibuffer-current-buffer))) (if (buffer-live-p buf) (save-current-buffer (set-buffer buf) default-directory) default-directory)))) 0)
```
=> fix(ibuffer): Wrong number of arguments to ibuffer-find-file with ivy enabled.

modules/lang/idris/config.el
Now that `lsp-mode` registers an LSP client for idris I've updated the doom idris module with support for the `+lsp` flag to reflect this change.
=> feat(idris): add +lsp to idris language configuration

modules/editor/multiple-cursors/config.el
The keybind for evil-mc-make-and-goto-last-cursor was set to "C-N". The "map!" macro doesn't account for letter capitalization when using the Control prefix so the bind for evil-mc-make-and-goto-last-cursor overrides the bind for evil-mc-make-and-goto-next-cursor. Same situation with evil-mc-make-and-goto-first-cursor overriding the bind for evil-mc-make-and-goto-prev-cursor. This fixes this by instead using "C-S-n" and "C-S-p" keybinds to make the Shift explicit.
=> fix(multiple-cursors): fix keybinds for evil-mc-make-and-goto-next(last)-cursor

modules/tools/magit/config.el
Add the two main keybindings expected in the [README of code-review](https://github.com/wandersoncferreira/code-review): `r` for a transient menu with all actions, and `RET` to add or edit a comment. Both should only be enabled while in a `*Code Review*` buffer.
=> feat(magit): add maps for code-review keys

modules/lang/org/autoload/org-babel.el, modules/lang/org/config.el
Added new keybinds for easy removal of RESULTS blocks in org-mode.
`SPC m k` - delete RESULTS block under cursor
`SPC m K` - delete all RESULTS blocks under cursor
`SPC u SPC m K` - delete all RESULTS blocks in buffer
=> feat(org): keybinds for removing RESULTS blocks

modules/lang/org/contrib/journal.el
Fixes #5239.
I have just started using Doom Emacs and found that many useful keybinds for org-agenda (for example 'SPC m d s' for scheduling) are not working. They are not working only when using org-journal, so moved org-journal keybinds, that are conflicting, to prefix 'SPC m j'.
=> fix(org): move journal entry keybinds to 'SPC m j'

modules/lang/clojure/packages.el
Hi!
I help out maintaining various https://github.com/clojure-emacs packages. Today we've released CIDER 1.3.
Last week we released clj-refactor 3.4.0 as well.
A good portion of our users use this software via Doom, so it's important that the offered versions represent their latest stable ones; otherwise we find ourselves debugging already-fixed code (has happened a few times just this year).
Cheers - V
=> bump: :lang clojure

modules/lang/fortran/README.org
This PR updates the `fortran` module's documentation to reference the more modern `fortls` LSP.
=> docs(fortran): reference the newer fortls LSP

modules/completion/vertico/autoload/vertico.el
Ignore svn and hg dirs in the `+vertico-file-search ` function, which is used for implementing `+vertico/project-search`
=> tweak(vertico): ignore svn and hg dirs in file search

modules/lang/web/+html.el
web-mode-attribute-transpose should be bind to SPC m a t, instead of SPC m a p
=> fix(web): typo

modules/lang/fortran/README.org, modules/lang/fortran/autoload.el, modules/lang/fortran/config.el
This PR expands the Fortran module to allow build tool control through modeline menus.
Note: This contains a commit of #6176 , which should be merged first.
=> Expanded Fortran UI

modules/lang/org/autoload/org.el
After using the `+org--insert-item` of #6084 for a decent time, I have found multiple issues with it, e.g. the labels of ordered lists were not updated and it also made a difference if the point is before or after the bullet.
This pr fixes this behavior, but uses a horrible hack. For the edge
case of an empty item, it inserts a no-break space momentarily, so that
`org-insert-item' does the right thing.
=> fix(org): multiple fixes for +org--insert-item

modules/lang/python/config.el
Fixes https://github.com/hlissner/doom-emacs/issues/3327
This PR changes three small things in the python module config:
- adjust smartparens to automatically close f-strings (#3327)
-  adjust smartparens to not insert a trailing `:` in functions (clashes with `def` snippet)
- Add `pyproject.toml` to the list of project files
I've had these changes in my stripped-down python module for a while and haven't experienced any issue. Also gave it a quick test with the python module from this PR.
=> Minor python updates

modules/completion/vertico/autoload/vertico.el
Change vertico-resume-* to vertico-repeat-*.
I think it was a typo, since vertico-resume-* does not exist at https://github.com/minad/vertico/blob/main/extensions/vertico-repeat.el
=> fix(vertico): vertico-resume to vertico-repeat.

modules/tools/lookup/config.el
`consult-xref` is autoloaded anyway. There are some packages that
require `xref` (such as lispy through requiring etags) so without
deferring, loading those packages may cause `consult.el` to be loaded.
=> perf(lookup): defer consult-xref

init.example.el, modules/lang/graphql/README.org, modules/lang/graphql/autoload.el, modules/lang/graphql/config.el, modules/lang/graphql/packages.el, modules/lang/org/packages.el
This module enables [GraphQL](https://graphql.org) support, including LSP and a
schema viewer.
Automatic installation for LSP is currently blocked by [this
issue](https://github.com/graphql/graphiql/issues/2264) but instructions are
included to install manually. Once that PR is resolved, I'll update the
documentation.
(Marked as draft until others have tested)
=> Add `:lang graphql` module

modules/lang/org/contrib/roam2.el
When I found out that `zr` works in Org-Roam buffers, I automatically assumed `zm` also does. It currently doesn't, but maybe it would be a good idea to add it?
=> tweak(&org-roam2): map zm to close all folds

modules/config/default/+emacs-bindings.el
vertico-repeat was replaced by vertico-repeat-last in https://github.com/minad/vertico/commit/a92b1e47ffe343e2c3096e2ea61af013a8a02af9.
=> fix(default): replace vertico-repeat with vertico-repeat-last

modules/lang/graphql/config.el
The faces were defined wrong, so every time a buffer came into focus, it
would spam `*Messages*`.
I had it during testing but I assumed it was leftovers from my previous failures.
=> Remove *Messages* spam

modules/lang/org/contrib/present.el
Leaving org-tree-slide-mode did not unhide #+ constructs.
Now +org-present-hide-blocks-h is triggered when leaving the mode as
well, fixing the behaviour.
=> fix(org): #+ constructs hidden forever

modules/completion/ivy/config.el
Makes `counsel-descbinds` consistent with the other counsel commands.
As mentioned in #4593, `helpful-symbol` prompts are a bit annoying, so I keep `counsel-describe-symbol-function` the same.
=> tweak(ivy): use helpful for counsel descbinds

modules/completion/vertico/README.org, modules/completion/vertico/autoload/workspaces.el, modules/completion/vertico/config.el, modules/completion/vertico/packages.el, modules/tools/lsp/packages.el
refactor!(vertico): fix embark-collect and rebind to C-c C-l
BREAKING CHANGE: `embark-collect-snapshot` has been renamed upstream to
`embark-collect`. Since the `C-s` mnemonic doesn't really make sense
anymore, I've moved the binding to `C-c C-l`, which has the nice bonus
of being next to the similar `C-c C-;`, and being nicer.
--
bump: :completion vertico consult-lsp
gagbo/consult-lsp@5a3c4e3f4233 -> gagbo/consult-lsp@a8eb3a062feb
iyefrat/all-the-icons-completion@9e7d456b0934 -> iyefrat/all-the-icons-completion@286e2c064a12
minad/consult@36b8bc706500 -> minad/consult@d30213aa2093
minad/marginalia@a514c024ac27 -> minad/marginalia@dbc37b373e73
minad/vertico@7ec0f0c07694 -> minad/vertico@46e8e0565079
--
fix(vertico): update +vertico-workspace-buffer-state to new api
also adapt upstream …
=> `:completion vertico` updates

modules/config/default/+evil-bindings.el
I use this function a lot, and the native `C-x x r` binding isn't really doom's style
=> feat(default): on evil bind rename-buffer to <leader> b R

modules/lang/org/README.org
Exporting an org file to pdf via LaTeX (org-export-dispatch or 'SPC m
e', then 'l p') requires texlive-latexextra (Arch package name) to be
installed on the system.
For reference, the error raised when texlive-latexextra was missing was
that the file 'wrapfig.sty' was not found. The specific error likely
depends on the contents of the exported file. Internet searches reveal
that pdflatex may also complain about 'utf8x.def' being missing; this
file is also provided by texlive-latexextra.
=> docs: add texlive-latexextra dependency for pdflatex exports

modules/completion/vertico/config.el, modules/completion/vertico/packages.el
-------
This adds `vertico-posframe` to match the similar feature in ivy. I tried to copy the variables from ivy but they didn't seem to be needed? Let me know if there's any feedback, thanks!
=> feat(vertico): add +childframe option similar to ivy

modules/lang/fortran/README.org, modules/lang/fortran/autoload.el, modules/lang/fortran/config.el, modules/lang/fortran/doctor.el
This PR extend the `fortran` module with a new `+intel` flag, enabling support for the well-known Intel Fortran. This establishes Doom as the only alternative to Eclipse for off-the-shelf IDE support on Linux.
=> Fortran: Intel Support

modules/lang/clojure/config.el, modules/lang/clojure/doctor.el
As discussed on Discord #contributing, it's pretty common to users manually disable cider and clj-refactor features even if using +lsp flag, this PR just check if +lsp is enabled and avoiding enable those features, using lsp ones
=> feat(clojure): use lsp features when +lsp flag is enabled

modules/lang/python/config.el
Doom doctor croaks:
> Checking Doom Emacs...
.config/emacs/modules/lang/python/config.el: Warning: ‘letf’ is an obsolete alias (as of 27.1); use ‘cl-letf’ instead.
=> fix(python): usage of obsolete alias letf

docs/modules.org, init.example.el, modules/input/bidi/README.org, modules/input/bidi/config.el
This pull requests adds better support for bidirectional and rtl text. It provides:
- a buffer-local `+bidi-mode` that undoes doom's anti-bidi optimizations, and sets the bidi initial alignment algorithm to start from scratch each line, so there is no need for empty lines to separate paragraphs.
- a global variant `+bidi-global-mode` if people just want it on all the time (off for read-only buffers due to fontification shenanigans)
- `+bidi-(hebrew|arabic)-font` (and faces) for easily setting a better font for these languages
- `+bidi-want-smart-fontify` uses for using said fonts on spaces and punctuation after RTL characters, since in hebrew at least there are almost no good monospace fonts
- instructions in the readme on further customization users probably want to make that can't be …
=> Add `:input bidi` module

modules/input/bidi/README.org
-------
I missed fixing this before the merge, and the docs branch isn't up to date enough to have the bidi readme yet.
=> docs(bidi): fix #+DATE field in readme

modules/editor/evil/autoload/textobjects.el
Fix: #5698
Defining `*-any-quote` objects via the exiting `*-block` helpers leads
to incorrect behaviour, where the trailing boundary is also included as
part of the selection (cursor on `|`, selection between `|`):
```
start: "te|st"
v i q: "|test"|
```
The expected behaviour is the same as `v i "`:
```
start: "te|st"
v i q: "|test|"
```
=> fix(textobjects): define *-any-quote directly

modules/lang/fortran/autoload.el
This fixes a bug reported to me over Discord. Previously, files that were the direct target for compilation would fail the process if they had a space somewhere in their full filepath.
=> fix(fortran): account for spaces in filenames

modules/tools/lookup/autoload/online.el
-------
I ran into this bug because I have helm and ivy installed for easy lookup, but not active. Why have i not been doing google searches from doom this whole time.
=> fix(lookup): check ivy|helm-mode before using their backends

modules/lang/fortran/autoload.el
Previously the output was always the default `a.out`. Note that this is only for the single-file non-fpm case, where the user just wants to compile and run a one-off Fortran program.
=> feat(fortran): name executable after the file name

modules/checkers/spell/config.el
Inline source blocks shouldn't be spell-checked. I also fixed the alphabetic sorting of org-cite while I'm at it.
-----
=> tweak(spell): ignore org-inline-src-block

modules/lang/emacs-lisp/autoload.el
As noted in #6181, 7290f85cfd35acdee1ed9053627dcdd93c23179f introduced an issue with `+eval/*` in non-file elisp buffers. Let's fix that.
Fixes #6181
-----
=> fix(emacs-lisp): don't expect all buffers to be files

modules/lang/zig/config.el
`zig fmt` changes the content of the file, which is very annoying and hard to troubleshoot when someone doesn't want their code formatted (like me).
`zig ast-check` is used instead to locate syntax errors.
-----
=> fix(zig): use zig ast-check for flycheck checker

modules/ui/window-select/config.el
Currently, when `switch-window` is used with >6 windows, an error is thrown. This was happening to me every time I used `dap-debug` since `dap-ui-mode` creates many windows. Allow me to explain why this happens:
When you execute `switch-window`, `switch-window--enumerate` assigns a single key to each window from `switch-window-qwerty-shortcuts`, which at this point is `'("a" "s" "d" "f" "g" "h" "j" "k" "l")`. However, keys which bound in `switch-window-extra-map` are excluded from being assigned to a window. Therefore, the only keys which can be assigned are `'("a" "s" "d" "f" "g" "h")`, which is only six keys. 
The change I propose in this pull request is to allow `switch-window-qwerty-shortcuts` to keep its default value of `("a" "s" "d" "f" "j" "k" "l" ";" "g" "h" "q" "w" "e" "r" "t" …
=> fix(window-select): allow Switch Window to work with >6 windows

modules/completion/vertico/config.el
Corfu makes completion-in-region-function a local variable in buffers
where it is enabled, so when this form is evaluated in one of those said
buffers (such as opening a file with Emacs before accessing the
minibuffer), completion-in-region-function will just be set locally
there.
This is currently not a problem for `company` users, but ones who try `corfu` will notice that where `corfu` isn't used (such as `M-:`), `vertico` should step in but the `*Completions*` buffer is presented instead.
=> tweak(vertico): use setq-default to set completion-in-region-function (for Corfu)

modules/completion/vertico/config.el
Currently, embark-consult bindings don't get loaded if consult hasn't
been loaded yet, leading to missing embark actions until the first
manual consult load
=> fix(vertico): load consult after embark

modules/email/mu4e/config.el
The date header only includes the first two digits of the year, making it look like all messages were received in 2020.
Before (Messages from February 2022):
After:
-----
=> tweak(mu4e): increase human-date width to fit year

modules/editor/fold/README.org, modules/lang/agda/README.org, modules/lang/cc/README.org, modules/lang/csharp/README.org, modules/lang/elixir/README.org, modules/lang/elm/README.org, modules/lang/go/README.org, modules/lang/java/README.org, modules/lang/javascript/README.org, modules/lang/json/README.org, modules/lang/julia/README.org, modules/lang/nix/README.org, modules/lang/ocaml/README.org, modules/lang/php/README.org, modules/lang/python/README.org, modules/lang/ruby/README.org, modules/lang/scala/README.org, modules/lang/sh/README.org, modules/lang/swift/README.org, modules/lang/web/README.org, modules/lang/zig/README.org
Companion PR to #5401. Currently fails the CI because `tree-sitter` isn't a valid scope.
cc @jeetlongname
=> docs(tree-sitter): document +tree-sitter flag in :lang readmes

modules/app/rss/autoload.el
Change-Id: Ic42528fcda679ff3538db2fad4c7d4dae6fc8d7a
This is my first pull request. Hope to merge it in the near future.
If you use in the way M-x elfeed, then quit \*elfeed-search* will show error prompt "\*rss* workspace doesn't exist". As +rss-cleanup-h will always delete \*rss* workspace, i add checker for \*rss* and switch to previous buffer when quit \*elfeed-search*.
-----
=> fix(rss): fix *rss* workspace doesn't exist

modules/config/default/+emacs-bindings.el
The keybindings `M--`, `M-=`, and `C--` override the built-in commands `negative-argument` and `count-words-region`. Moreover, the `C--` command, `er/contract-region`, is already bound transiently to `expand-region-contract-fast-key` while expanding regions.
=> tweak(default): remove M-{-,=,+} and C-- keybinds

modules/lang/go/autoload.el
When specifying a specific test to run using `go test`, the function name is accepted as a regex, not an exact string match. Previously, the `+go/test-single` and `+go/bench-single` functions specified the function name as a raw strings; this meant that these functions could sometimes test/benchmark other functions that contained the name of the intended test.
-----
=> fix(go): exactly match test function name

modules/lang/nix/autoload.el
Before
After
now it works on vertico or any other completion based on completing-read
-----
=> feat(nix): add generic completing-read support to +nix/lookup-option

modules/lang/org/config.el
Fixes a regression that disabled org ID links.
-----
=> fix(org): make last arg of '+org--follow-search-string-a' optional

modules/lang/org/autoload/contrib-present.el
When leaving org-tree-slide-mode, the window fringes are reset via  `set-window-fringes`
`fringe-mode` stores the default fringes and has multiple possible types, including cons cell, which cannot be passed directly to set-window-fringes. So this PR matches on the type of `fringe-mode` to figure out how to properly call `set-window-fringes`, otherwise a `wrong-type-argument` error occurs.
=> fix(org): wrong arg type when leaving present mode

modules/lang/org/packages.el
Add org-babel support for F#
There are still a number of issues to work out, once they're resolved I'll mark
this as ready.
=> Add ob-fsharp

modules/lang/fsharp/packages.el
Resolves issue causing the inferior-buffer to block when adding nuget
packages
fsharp/emacs-fsharp-mode@b3aa4c53fc9e -> fsharp/emacs-fsharp-mode@c1e58c61f9b5
=> bump: :lang fsharp

modules/email/mu4e/README.org
The variable name for toggling org-msg by default was changed in commit 6118ad5c124c2fa436abd19fe087de0f836c59d7, leading to the provided snippet not actually disabling org-msg.
-----
=> docs(mu4e): fix incorrect variable name in snippet

modules/email/mu4e/config.el
Messages from the current day do not fit with the current width since they are formatted as times (Ex: "05:17:23 PM"). It seems that 11 is a sufficient width for this but the increase to 12 matches the [mu4e defaults](https://github.com/djcb/mu/commit/0276ea04089106e77d4c0f65d83cc7bd3f6a49b9).
This was recently increased already (#6427), but I missed that the formatting is different for messages from the current day. Sorry about that!
Before:
After:
-----
=> tweak(mu4e): increase human-date to fit full time

modules/os/macos/autoload.el
The symbol `newwindow?` in 39 should be a macro's symbol, not a function's one.
This fixes a bug introduced by #6318.
=> fix(macos): void-variable newwindow? error

modules/email/mu4e/autoload/email.el, modules/email/mu4e/autoload/mu-lock.el, modules/email/mu4e/config.el
This is basically an iteration on #6549 that should improve compatibility (backwards and forwards).
I've tested this and it seems to work well on 1.8. Ideally, someone could test 1.6 and confirm that this doesn't break anything.
Fixes #6511
Replaces #6549
-----
=> fix(mu4e): Support mu 1.8

core/core-projects.el
The referenced commit incorporates https://github.com/bbatsov/projectile/pull/1784 to fix #6504.
-----
=> fix: strip './' from projectile file list produced by fd

modules/tools/pass/config.el
This enables `evil-collection` support for `tools/pass`, making sure the bindings are displayed properly in the `pass` header.
Originally, `pass` was launched in `emacs-state` because `evil-collection` didn't support `pass` when the module was written, but it does now.
It also removes stale code relative to the `PASSWORD_STORE_DIR` environment variable, since the password store path is not hardcoded in `pass.el` anymore.
-----
=> fix(pass): enable evil-collection bindings

modules/lang/python/config.el
The binding for `pyimport-remove-unused` currently clashes with the binding for `py-isort-region`.
In `python-mode`, these are both triggered by:
- <kbd>leader</kbd><kbd>localleader</kbd><kbd>i</kbd><kbd>r</kbd>
This currently makes only `py-isort-region` accessible through bindings.
To fix this, make `pyimport-remove-unused` to be triggered by capital a `R`:
- <kbd>leader</kbd><kbd>localleader</kbd><kbd>i</kbd><kbd>R</kbd>
---
=> fix(python): edit `pyimport-remove-unused` binding

modules/tools/tree-sitter/README.org, modules/tools/tree-sitter/packages.el
Bump the module, This should fix an issue with the M1 macs pulling down the wrong parsers
Remove mentions of +tree-sitter-keys-mode as it no longer exists
-----
=> `:tools tree-sitter` amendments

modules/lang/lua/packages.el
https://git.sr.ht/~technomancy/fennel-mode@50ef3c6246f3 -> https://git.sr.ht/~technomancy/fennel-mode@566435734946
A fix was added upstream to fix `fennel-repl` no longer returning the
repl buffer. This fixes `+eval-open-repl` in fennel-mode.
This was fixed for #4263, but there was a regression which was fixed upstream.
-----
=> bump: :lang lua

modules/config/default/autoload/default.el
when available instead of plain flymake-show-diagnostics-buffer.
=> tweak(default): consult-flymake in a branch of +default-diagnostics

modules/email/notmuch/autoload.el
Currently, update buffer creates an additional window that stays on. I
think it's better to delete the window and bury the buffer. That way
user still can open the buffer later to check the update status.
=> notmuch: improve update

modules/config/default/+evil-bindings.el
As `SPC b i` is already bound to `ibuffer`, this new binding is really convenient and consistent with Doom's current default binding.
=> feat(default): bind 'SPC b I' to open ibuffer for workspace

modules/completion/vertico/autoload/vertico.el
`consult--regexp-compiler` now has three arguments.
Ref:  minad/consult@f0e696d
-----
=> fix(vertico): +vertico/consult-fd breaking due to API change in consult

modules/tools/tree-sitter/README.org
This PR fixes up the formatting of the new Tree Sitter README. There were some spacing and punctuation issues.
cc @jeetelongname
=> docs(tree-sitter): improve README formatting

modules/editor/evil/config.el
Remove the `evil-want-C-w-scroll` variable. It is not used anywhere and appears to have been added accidentally in 8b9d4a94bbe9db38eb2783c73ef9c7edca0cf91a
I was browsing the various `evil-want-` variables (with `M-x helpful-variable`) and this one caught my eye. It sounded out of place and had no documentation. (I hope this isn't considered too trivial a change to warrant a PR, as it caused some genuine confusion for me as a user.)
-----
=> refactor!(evil): remove evil-want-C-w-scroll

modules/emacs/vc/autoload/hydra.el
New hydra head:
`"n"` (subject to change) `(progn (smerge-vc-next-conflict) (recenter-top-bottom (/ (window-height) 8)))`
Allow us to conveniently jump to the next merge conflict in current project without leaving the hydra and opening `magit`.
Alternative to #5431.
=> feat(vc): add next conflict in project to +vc/smerge-hydra

modules/config/default/autoload/text.el
Emacs 29 with PGTK's kill-new doesn't return its STRING argument (with the default settings) anymore, so we explicitly pass the file path to prevent "Copied path to clipboard: nil", (the command still correctly copies the path without this patch, though).
=> fix(default): +default/yank-buffer-path echos the file name as nil on Emacs 29 PGTK

modules/tools/terraform/config.el
Introduce a variable for the terraform executable and as terragrunt supports everything terraform does, use that instead of terraform if found on the path. 
We should probably also set `compile-command` - comments?
This doesn't touch the formatter in any way (ref https://github.com/hlissner/doom-emacs/issues/3921)
=> feat(terraform): support terragrunt

modules/lang/ocaml/config.el
Corrects the name for the tree-sitter function in the ocaml module.
-----
=> fix(ocaml): ocaml tree-sitter function typo

modules/lang/org/autoload/org-tables.el
Fixes unsubmitted bug with org tables autoaligning:
In function for automatically align table on exit of insert state
added check for standard variable ~org-table-automatic-realign~
Documentation
Non-nil means automatically re-align table when pressing TAB or RETURN.
When nil, aligning is only done with M-x org-table-align, or after column
removal/insertion.
Troubleshooted that when attempted to figure out how to stop table that realigned for 11 seconds after exit of insert mode.
Found that there's a variable for that and that doom custom function doesn't respect it
-----
=> fix(org): respect org-table-automatic-realign

lisp/lib/process.el
Update `doom-exec-process` to use `doom-print--format` instead of `doom--format`, which was removed in fe16de690418393c4b1dd79277f01a1c72b3be10add5a48022befe35b5f2e89c
-----
=> fix(lib): doom-exec-process use doom-print--format

modules/email/mu4e/README.org
The recent 1.8 release of mu renamed the mu4e~get-mail-password-regexp variable which is mentioned in the module docs. I updated the docs accordingly.
-----
- [ x ] I searched the issue tracker and this hasn't been PRed before.
- [ x ] My changes are not on [the do-not-PR list](https://doomemacs.org/d/do-not-pr) for this project.
- [ x ] My commits conform to [the git conventions](https://doomemacs.org/d/git-conventions).
- [ x ] Any relevant issues or PRs have been linked to.
=> docs(mu4e): mention variable renamed in mu-1.8

lisp/doom-lib.el
Fix the behavior of `defer-feature!` when called with one argument.
If `defer-feature!` was called with one argument (as is the case in the `:lang common-lisp` module), `FNS` defaulted to an empty list. As a result, `FEATURE` would be deferred but never added back to the features list, and `after!` blocks would never trigger for `FEATURE`.
Instead of defaulting to an empty list, fallback to a singleton list `(FEATURE)`. This aligns with the behavior the macro had prior to 5b8b04f0c8b6458a3ac4b41417c69413a3bae92e, which generalized `FNS` to support a list of functions rather than just one.
-----
=> fix: defer-feature! fallback FNS

modules/lang/csharp/packages.el
I didn't see any relevant issues/PRs when searching a few things like `sln`, `csharp`, etc, but maybe I missed something
-----
- ~My changes are visual; I've included before and after screenshots.~
-  ~This a draft PR; I need more time to finish it.~
-----------------------
While trying to use sln-mode via the csharp module, I noticed that it would not load because it was missing a dependency `font-lock-ext`. Examining the source of sln-mode, we see
```
(require 'font-lock-ext) ; https://github.com/sensorflo/font-lock-ext/
```
Now this is a trivial & tiny package (see for yourself), but as I don't want to rewrite any of the packages involved, the simplest fix for this is just to add this package to the module.
On a slightly separate note: I actually originally was trying to enable support …
=> fix(csharp): add dep pkg for sln-mode

lisp/lib/debug.el
If `doom-emacs-dir` contains a "~", calling `doom/version` will generate an error like:
```
fatal: cannot change to '~/.config/emacs/': No such file or directory
```
This is because `git` is invoked via `call-process`, so "~" is not expanded as it would be in a shell command.
Fix this by canonicalizing the filename.
-----
=> Fix doom/version (canonicalize filenames in git calls)

modules/tools/pdf/README.org
The documentation claimed that epdinfo will be built as soon as a pdf
file is opened. However, support for automatically building epdfinfo was
removed in the commit referenced below.
Ref: daa50557a4f2
- [ x ] I searched the issue tracker and this hasn't been PRed before.
- [ x ] My changes are not on [the do-not-PR list](https://doomemacs.org/d/do-not-pr) for this project.
- [ x ] My commits conform to [the git conventions](https://doomemacs.org/d/git-conventions).
- [ x ] Any relevant issues or PRs have been linked to.
=> docs(pdf): fix instructions to build epdfinfo

modules/completion/vertico/autoload/vertico.el
Fix a typo and add a missing function docstring in the vertico module.
-----
=> nit(vertico): fix typo and docstring

modules/tools/magit/README.org, modules/tools/magit/packages.el
the magit module has an error where a default module package (code review) has forge as a dependency, forge is only meant to be downloaded if one provides the `+forge` flag
now code review is locked behind `+forge` flag, this way the dependencies are in the correct order
-----
=> fix(magit): only install forge if asked

modules/tools/debugger/config.el
Probably missed when adding eglot support code in the module
=> fix(debugger): fix dap-ui conditional loading

modules/lang/nix/config.el
The `nix-mode` package already does this (see https://github.com/NixOS/nix-mode/blob/34d51e2731408b5b615f785a83faa3d6dc2a92a1/nix-drv-mode.el#L48) and it shadows other entries for the `.drv` files in `auto-mode-alist` (namely Guix derivations).
=> fix(nix): remove :mode hook for `nix-drv-mode`

lisp/doom-editor.el
Fix a typo that resulted in a void-variable error.
-----
=> fix: error caused by typo in doom--recentf-file-truename-fn

lisp/doom-ui.el
In `doom--make-font-specs`, the `base-specs` argument is not specified by any callers, but if it were, it would be ignored, since the body of the function binds a value, overriding any value the caller specified.
-----
=> nit: remove unused base-specs arg in doom--make-font-specs

lisp/lib/print.el
Remove an unreachable `buffer` element from `doom-print-class-alist`. An earlier element in this alist associates buffer with `doom-print--buffer`.
-----
=> refactor(lib): remove unreachable code in doom-print-class-alist

modules/email/mu4e/config.el
**Before**
**After**
I also tweak the line order and whitespace while I'm at it, to show the
overall styling more clearly.
-----
=> tweak(mu4e): set last-child thread symbol

modules/email/mu4e/autoload/email.el
With mu4e came a new face for the header view. While this is nice for
the text, it had the consequence of making the account stripe (the
vertical bar) a bit jarring. This patch fixes that behavior to make the
stripe non-italic by append `'default` to the face.
=> fix(mu4e): force the account stripe face to be non-italic

modules/config/literate/autoload.el
I feel like this is pretty simple and self-explanatory.
Without this change the sync and async tangling functions can (will) use different Org versions.
-----
=> fix(config): tangle with the same Org as Doom uses

modules/completion/ivy/config.el
Overriding `ivy--flx-featurep` here would always prevent flx from being loaded and enabled---even if it were `t`---because ivy `require`s it in `ivy--flx-featurep`'s initvalue. So instead, this sets the variable if and only if it should be disabled. Because flx isn't installed when +prescient is enabled, I've included that in the condition for disabling ivy--flx-featurep as well
Fix: https://github.com/doomemacs/doomemacs/issues/6034
Amend: https://github.com/doomemacs/doomemacs/commit/bae7ab0d8dbb2ace3fb54692f3525826b69ed60a
-----
~~I tried to scope this as fix(ivy), but I was getting a lint error that ivy was not a valid scope. I may have misunderstood the scoping rules~~
=> fix(ivy): ensure flx is loaded with (ivy +fuzzy)

modules/lang/org/autoload/org.el
Doom replaces [org-insert-heading](https://git.savannah.gnu.org/cgit/emacs/org-mode.git/tree/lisp/org.el#n6187) with `+org--insert-item` and leaves no equivalent for [org-insert-heading-hook](https://git.savannah.gnu.org/cgit/emacs/org-mode.git/tree/lisp/org.el#n1615).
As discussed on [discord](https://discord.com/channels/406534637242810369/695219268358504458/1012348488085946418) the proposed change adds this hook again, enabling convenient features such as adding a time stamp after inserting a new heading:
```elisp
(defun my/org-set-creation-date-heading-property ()
(save-excursion
(org-back-to-heading)
(org-set-property "CREATED" (format-time-string "[%Y-%m-%d %T]"))))
(add-hook 'org-insert-heading-hook #'my/org-set-creation-date-heading-property)
```
-----
=> Adds org-insert-heading-hook to +org--insert-item

modules/input/layout/+bepo.el, modules/input/layout/autoload/bepo.el
Fixes an issue where binding rotations in Bépo were happening too soon,
resulting in some remaps not being visible to the user when interacting
with magit, :editor evil +everywhere, and :input layout +bepo
Ref: https://discourse.doomemacs.org/t/layout-bepo-does-not-properly-remap-k-in-magit/3063
=> fix(layout): Bépo rotation happening before magit

modules/config/literate/autoload.el
While this is a hidden buffer, it's raised when an error occurs. In such situations, it can be a little confusing to see the result of every tangle to date instead of just the last tangle. It's easy enough to simple clear the buffer at the start of the tangle process.
-----
=> tweak(literate): clear the tangle output buffer

modules/tools/magit/config.el
When using `evil +everywhere`, we disable the default forge bindings.
We must then explicitly remap `magit-browse-thing`, as it's just a placeholder command (bound in multiple places).
-----
=> fix(magit): remap magit-browse-thing to forge-browse-*

modules/email/mu4e/config.el
It's a bit silly to just unconditionally widen the current frame when you could have the mu4e headers view in another frame entirely. Instead we can look for the mu4e headers buffer, and only widen frames where it is the active buffer.
-----
=> fix(mu4e): only widen the mu4e headers frame

modules/email/mu4e/autoload/email.el
Originally this was added to have the order of attached files match the order of mark selection. Recent usage indicates that this was either misguided or the behaviour has changed, as this now achieves the opposite effect --- with nreverse files are attached in reverse order. Removing nreverse provides the expected behaviour.
-----
=> tweak(mu4e): don't reverse dired marks to attach

modules/email/mu4e/autoload/mu-lock.el
`+mu4e-lock-availible` seems like a potential entry-point to the mu-lock functionality, e.g. on startup check if another Emacs process has mu4e active, and so it might as well be turned into an autoload.
-----
=> tweak(mu4e): autoload +mu4e-lock-available

modules/app/calendar/autoload.el, modules/app/irc/autoload/irc.el, modules/app/rss/autoload.el, modules/email/mu4e/autoload/email.el, modules/email/notmuch/autoload.el
In the #emacs-lisp channel of the Doom Emacs Discord, we were discussing how the current behavior of `=mu4e` can be annoying because if a user is already reading an email, leaves the `*mu4e*` workspace, and switches back with `=mu4e`, the Mu4e main buffer is opened again in the active window, forcing the user to manually `switch-to-previous-buffer`. I have implemented an improvement upon this behavior for various modules so that if we call `=mu4e`, `=rss`, etc., and that workspace is already in Mu4e/Elfeed, etc., we do not call `(mu4e)`, `(elfeed)`, etc. again (respectively).
While reviewing these various app modules, I have found some behaviors that seemed odd to me such as `=irc` emitting an error if the workspace is already in an IRC node or `=notmuch` using the workspace name …
=> DWIM for most app-switching commands (=mu4e, =elfeed, =calendar)

lisp/lib/debug.el
Swap the **THEN** and **ELSE** in `symlink-path` so that symlinks are displayed correctly.
Currently, `bin/doom info` displays a non-symlinked path like,
```
~/.config/emacs/ -> ~/.config/emacs/
```
and a symlinked path like,
```
~/.config/emacs/
```
-----
=> fix(lib): doom-info symlink-path

modules/ui/treemacs/config.el
`treemacs-collapse-dirs` cannot be changed by setting `+treemacs-git-mode` to `extended` or `deferred`
Fixes #6850
-----
=> fix(treemacs): treemacs-collapse-dirs not changing

modules/os/macos/config.el
Might be worth introducing a "remote trash command", but for now this seems to work.
Closes #6804
=> fix: only use trash on local hosts

modules/email/mu4e/autoload/email.el
There are two changes to the default optional read-file-name arguments that should be made for the purpose of attaching files:
1. The optional MUSTMATCH argument should be set, as one can't exactly attach non-existent files.
2. The INITIAL argument should be set to the empty string so that if default-directory is customised for some reason or another that selecting it leads to the expected directory being selected. Without INITIAL or DEFAULT-FILENAME being specified, the current file path will be used, which is never desirable as this is simply a path to the message buffer.
-----
I'm not sure about the commit subject here, but I couldn't think of anything better within 50 chars.
-----
=> fix(mu4e): file attachment prompt arguments

modules/email/mu4e/autoload/email.el, modules/email/mu4e/config.el
In 4d9ea6853b88 I reacted to a either a change that I presume occurred in org-msg at some point, or behaviour originally unnoticed, that led to bulk-selected files being attached in reverse. Further investigation has indicated that this isn't actually making attachment order work as expected, just hiding the reverse behaviour from bulk-attachment. The better approach is to keep the dired mark reversal, and change org-msg-attach-attach to add new files to the end, not the start, of the list of attachments.
-----
=> tweak(mu4e): try harder to attach files in order

lisp/lib/files.el
Fix the handling of a nil `path` within `doom/delete-this-file`.
If `path` is nil (e.g. called interactively when buffer is not visiting a file), avoid calling `abbreviate-file-name` on nil, otherwise an error will be signaled:
```
(wrong-type-argument stringp nil)
```
Additionally, fix the subsequent path checks. These were treating two distinct scenarios as a "Buffer is not visiting any file" user-error:
- nil path
- non-existent path
Only the first should result in that error. The second should proceed to the next path check (which was previously unreachable), to signal the appropriate error, "File doesn't exist: %s".
_Note_: I noticed that this function calls `user-error` in some cases and `error` in others. I'm not sure whether that's intentional, so I didn't change it.
-----
=> fix(lib): doom/delete-this-file nil path handling

modules/config/literate/cli.el
It's good for config tangling behaviour to be consistent across:
1. interactive sessions
2. asynchronous calls
3. the doom CLI
(1) of course uses the Doom-installed org, (2) was taken care of in #6778, and this should make (3) behave the same.
Without this, one can run into bugs and behavioural differences between the emacs-bundled Org and the (more recent) doom-installed Org, for example, see https://git.savannah.gnu.org/cgit/emacs/org-mode.git/commit/?id=cb8bf4a0d which fixes an issue with `:noweb-ref` references not being expanded in some situations.
-----
=> fix(literate): use same org install when using CLI

modules/email/mu4e/autoload/mu-lock.el
Some time ago I noticed the cooperative lock file management wasn't working as I remember. I forget what exactly I was thinking, but basically I've poked at the code until it seems to work better.
If some other people could test this and report back, that would be much appreciated.
-----
=> fix(mu4e): cooperative lock file watching

modules/checkers/grammar/config.el
-----
- turns out brew install language-tool has different location
- plus it provides binary tool
-----
=> fix(grammar): use languagetool in $PATH, if available

lisp/doom.el
Change the value of `warning-suppress-types` back to a list of list of symbols.
I noticed this issue in my python repl setup, based on this backtrace:
```
Debugger entered--Lisp error: (wrong-type-argument listp defvaralias)
warning-suppress-p((python python-shell-prompt-regexp) (defvaralias))
display-warning((python python-shell-prompt-regexp) "Python shell prompts cannot be detected.\nIf your e..." :warning)
lwarn((python python-shell-prompt-regexp) :warning "Python shell prompts cannot be detected.\nIf your e...")
python-shell-prompt-detect()
python-shell-prompt-set-calculated-regexps()
inferior-python-mode()
```
This appears to be a regression introduced in [8c442d84b9c055200e61c4333e117c1ce914027d](https://github.com/doomemacs/doomemacs/commit/8c442d84b9c055200e61c4333e117c1ce914027d) …
=> fix: change warning-suppress-types to list of lists

modules/tools/magit/config.el
For some reason, the transient-append-suffix adding magit-worktree back
to magit-dispatch — after its potential replacement by
magit-gitflow-popup — was having no effect. (It does when moved into
(after! magit-gitflow), so the issue must have something to do with when
transient-append-suffix is called.) magit-worktree wasn't appearing in
the magit-dispatch popup when magit-gitflow was enabled, nor was the '*'
keybind for magit-worktree in effect outside (or inside) the popup,
unlike '%' for magit-gitflow-popup.
Replace the ineffectual transient-append-suffix with a normal and visual
mode keybind for magit-worktree in magit-mode-map (and move the
unconditionally defined keybind for magit-gitflow-popup into (after!
magit-gitflow)). Also, append the magit-gitflow-popup transient suffix
to …
=> fix(magit): evil keybinds for magit-worktree

modules/email/mu4e/autoload/email.el
The current config is kinda confusing, it uses the same symbol for both forwarded/passed mails and replied mails. FontAwesome provides a nice icon for "reply", why not use it!
-----
=> tweak(mu4e): change icon for reply flagged mails

bin/doomscript
Sync definition of __DOOMGEOM in bin/doomscript with corresponding variable of bin/doom.
* bin/doomscript (__DOOMGEOM): split tput call into two separate calls
Ref: beef0aef0211
The tput call of __DOOMGEOM of bin/doom has been splitted into two tput calls by commit beef0aef0211 but the defintion for the same variable in bin/doomscript still use the old definition.
-----
=> fix(cli): split tput call into separate calls

modules/lang/haskell/packages.el
haskell/haskell-mode@cb573c8db5b856eb37473009f2c62e0717a1cd02 -> haskell/lsp-haskel@90503413f4cdb0ed26871e39c4e6e2552b57f7db
emacs-lsp/lsp-haskell@7cf64944ab3a25ea5d6f8d5e0cd33124182df991 -> emacs-lsp/haskell-mode@485c1148ce4d27030bb95b21c7289809294e7d31
The emacs upstream will raise an error now when `otherwise` or `t` clause is not the last clause in a `cl-case`. There is a such `cl-case` in `haskell-commands.el` which is apparently a typo and should be fixed. This is fixed then we should bump the version here.
Reference: https://github.com/haskell/haskell-mode/commit/4010de30ec6ae691aaf1ec715ccd23df7dfbe48a
https://git.savannah.gnu.org/cgit/emacs.git/commit/?id=6d8f5161ead689b7a2e44a7de0a695f0ab4c833b
-----
=> bump: :lang haskell

modules/lang/org/autoload/org-capture.el
Check `WAYLAND_DISPLAY` for `+org-capture-frame-parameters`.
PGTK emacsclient also use this logic, see references below.
References https://github.com/masm11/emacs/pull/13
=> fix(org): check WAYLAND_DISPLAY for bin/org-capture

modules/ui/modeline/packages.el
seagle0128/doom-modeline@bed80b82d7bf -> seagle0128/doom-modeline@b66d5e5006df
- Fixes error with eglot 1.9 (due to rename of eglot--major-mode)
-----
Consider this a bug request as I understand you don't want PR for modules for now.
=> bump: :ui modeline

modules/tools/lsp/+lsp.el
-----
This is an important fix IMO since `lsp-auto-guess-root` is disabled by default for a long time ⚠️, after long debugging why when finding the definition with LSP of a library file, like a external jar or dependency, even if lsp consider that file as part of the current workspace, doom would still ask for the project root, which doesn't make sense, this is a 2 year bug introduced after calling `lsp--calculate-root` which asks for project root interactively.
Since the custom hook function `+lsp-display-guessed-project-root-h` was created just to log when a project root was guessed, it should check the `lsp-auto-guess-root`
Example of wrongly prompt:
=> fix(lsp): stop logging project root

modules/tools/ansible/config.el
IDK if this literally closes #1139, but it's relevant.
Although it's common to use the extension `.yml` rather than `.yaml` for yaml files in ansible projects, this is not required except in like 1 or 2 cases, and also `.yaml` is a much better extension for yaml files and I will fight anyone who disagrees IRL.
AFAICT, there isn't a way to use a regexp here (i.e. `:match` isn't `:files` but with regexps) , so I just added the other path to the disjunction, but if the reviewer knows otherwise LMK.
=> tweak(ansible): also match tasks/main.yaml

modules/config/default/+emacs-bindings.el, modules/config/default/+evil-bindings.el
This PR proposes the default keybinding `:leader "t v"` to toggle the `visible-mode`.
This keybinding is useful inside `org-mode` buffers when editing links.
Furthermore, it is especially useful if you have `org-hide-emphasis-markers` set to t.
-----
=> feat(default): bind :leader "t v" to visible-mode

modules/email/notmuch/README.org
The method for customizing +notmuch-sync-backend was changed in 19d4126 to accept a string; consequently the current example in the docs results in an error:
`user-error: Invalid notmuch backend specified: custom`
-----
=> docs(notmuch): fix custom sync backend snippet

modules/lang/org/config.el
Adds `org-file-reverse` keybinding, which puts items at the top of the list
-----
=> feat(org): bind '<localleader> r R' to org-refile-reverse

modules/lang/org/README.org, modules/lang/org/doctor.el
- add doctor warning about eventual removal
- clarify the readme notice, since the migration-wizard has stabilized
=> docs(org): warn about org-roam-v1 status

modules/tools/eval/autoload/repl.el
Otherwise, if the REPL was not in insert mode the send-to-buffer would
fail.
=> fix(eval): lookup RET binding in insert if evil

modules/editor/god/config.el, modules/editor/god/packages.el
Enabling god-mode was broken in 7a2be67efadf63f28b948849240f78508579fb3e.
Fixes #6954.
=> fix(god): enable god-mode on init

modules/editor/fold/config.el
Hi,
Currently, when I enable the `tree-sitter-hl-mode`, Doom Emacs will throw a lot of the warning `Warning: setting attribute ‘:foreground’ of face ‘ts-fold-replacement-face’: nil value is invalid, use ‘unspecified’ instead.`
Here is a screenshot of the `*Message*` buffer:
This PR will fix the issue by configure `foreground` of `ts-fold-replacement-face` to `unspecified` instead.
-----
- [v] I searched the issue tracker and this hasn't been PRed before.
- [v] My changes are not on [the do-not-PR list](https://doomemacs.org/d/do-not-pr) for this project.
- [v] My commits conform to [the git conventions](https://doomemacs.org/d/git-conventions).
- [v] My changes are visual; I've included before and after screenshots.
=> fix(fold): set ts-fold-replacement-face fg to unspecified

lisp/lib/help.el, modules/completion/vertico/config.el
refactor!(vertico): remove consult-apropos remap
BREAKING CHANGE: This command is obsolete since 0.20; consult-apropos
has been deprecated in favor of Embark actions: M-x describe-symbol
<regexp> M-x embark-export M-x describe-symbol <regexp> M-x embark-act a
---
fix: consult case of doom--help-search
advise consult--ripgrep-make-builder instead of reimplementing
=> fix(vertico): things that slipped by the previous bump PR

modules/completion/vertico/autoload/vertico.el, modules/completion/vertico/config.el, modules/completion/vertico/packages.el, modules/emacs/vc/packages.el, modules/tools/lsp/packages.el, modules/tools/magit/packages.el, modules/ui/modeline/packages.el
---
bump: :completion vertico compat consult-lsp magit git-commit
emacs-straight/compat@7ca7d300d1d2 -> emacs-straight/compat@2bedcb5ea919
mhayashi1120/Emacs-wgrep@f9687c28bbc2 -> mhayashi1120/Emacs-wgrep@edf768732a56
minad/consult-flycheck@7a10be316d72 -> minad/consult-flycheck@51b1b48e8dad
minad/consult@16b2dc5e34c8 -> oantolin/orderless@ae849b3d9f8c
minad/marginalia@c1365bf0c7b5 -> minad/marginalia@6d48ed54be87
minad/vertico@bedd146c3ffc -> minad/vertico@f303790546ed
oantolin/embark@629cce948c56 -> oantolin/embark@4882b395cef9
oantolin/orderless@847694e78c12 -> minad/vertico@f303790546ed
tumashu/vertico-posframe@a3d0802d7b4a -> tumashu/vertico-posframe@790f74b49d53
gagbo/consult-lsp@58b541476203 -> gagbo/consult-lsp@f8db3252c0da
magit/magit@0ef98ef51811 -> magit/magit@6d325d90ba13 …
=> bump: :completion vertico (and some requirements)

modules/app/everywhere/config.el
This adds an icon to indicate that Emacs Everywhere is being used, to ease at-a-glance identification. The "exit_to_app" material icon was chosen as it seems like a good fit for a window that will return you to the application it was invoked from. The padding on the right stops the icon from being right up against the very edge of the window.
It's a minor thing, but I think it's visually nice.
=> tweak(everywhere): add icon to right of modeline

modules/editor/god/autoload.el
When switching themes (light to dark or vice versa) with god-mode enabled sometimes the cursor becomes invisible.
This change removes the hard coded value and keeps the cursor color in sync with the current theme.
=> fix(god): remove hard coding of cursor color

modules/lang/scala/packages.el
hvesalai/emacs-scala-mode@598cb680f321 -> hvesalai/emacs-scala-mode@5d7cf21c37e3 emacs-lsp/lsp-metals@097d6021a4ff -> emacs-lsp/lsp-metals@a2df7263ece6
Upgrades scala-mode & lsp-metals. Bumping lsp-metals fixes an incompatibility with a recent treemacs change.
Fixes https://github.com/doomemacs/doomemacs/issues/6961
-----
=> bump: :lang scala

lisp/doom-keybinds.el
The old name is doom-after-init-modules-hook, should be changed to `doom-after-modules-init-hook`.
-----
=> fix: correct name of doom-after-modules-init-hook

modules/email/mu4e/autoload/advice.el
Note: I see that PRs for modules are not being accepted at the moment – is it ok if I leave the PR open (possibly as a draft)? Since it’s a minor change to a module, I think it should be straightforward to adapt after the changes to the modules. Happy to close and reopen later if you’d prefer!
In the leuven theme (and possibly others), the use of `(mode-line-emphasis bold)` results in white text on a white background, making the shortcut keys invisible.
The original function mu4e--main-action-string uses mu4e-highlight-face, and changing back to this fixes the problem.
I can’t tell from the git history what the reasoning for the face change specifically was: the new function seems to have been made mainly for changing the bullets to unicode versions.
Fixes #7010
Before screenshot:
After …
=> mu4e: Use mu4e-highlight-face for main view actions

modules/lang/emacs-lisp/autoload.el
In emacs 29 wrong quotes in docstrings throw up compilation errors,
which pop up randomly with no real context when using doom. I have found
a reference to url's being single quoted in the emacs wiki\[0], but the
emacs manual shows the standard format[1], not sure if it changed or was
a mistake. Also it should have a URL prefix apparently.
\[0]: https://www.emacswiki.org/emacs/DocString
[1]: info elisp 'Documentation tips'
=> fix(emacs-lisp): docstring url format which error popup

modules/ui/vc-gutter/config.el
Add required autoloads for `vc-gutter` to fix errors from `which-key`. See the issue below.
Fixes #6957
-----
=> fix(vc-gutter): add missing autoloads

modules/ui/workspaces/autoload/workspaces.el, modules/ui/workspaces/config.el
This PR introduces functions for persisting the tab-bar data for the `workspace` module.
The `workspace` module has supported integration with tab-bar currently, but the tab-bar data cannot persist after reopening the workspace. This PR adds functions for saving and loading the tab-bar data from the file.
=> fix(workspaces): save current tab-bar tabs to file

modules/emacs/dired/packages.el
alexluigit/dirvish@73dcaa404da9 -> alexluigit/dirvish@4fe9c0089430
This "lateral" bump buys us more time until doomemacs/doomemacs#6760 lands.
`dirvish`'s repository apparently rebased the commit we have pinned.
Visiting it gives us:
```
This commit does not belong to any branch on this repository, and may
belong to a fork outside of the repository.
```
Te new pinned version references the same commit contents, but on a new
position. They're correctly identified as identical by git. The new
commit also contains an explicitly reference to the old one:
```
Former-commit-id: 73dcaa4
```
Ref: https://github.com/alexluigit/dirvish/compare/73dcaa404da9..4fe9c0089430
=> bump: :editor dirvish

modules/lang/org/config.el
Org-mode's behavior when org-attach-store-link-p is 't' recently
changed. See:
Commit: 0d60013f0e3980fab959542eeb171ab9a02b450c
https://git.savannah.gnu.org/cgit/emacs/org-mode.git
When the value of org-attach-store-link-p is 't' org-store-link now
suggests a 'file:' link to the attachment's original location. Setting
the value to 'attached' instead suggests an 'attachment:' link utilizing
the attachment directory.
Fix: #6952
-----
=> fix(org): update org-attach-store-link-p default

modules/lang/scheme/autoload.el, modules/lang/scheme/config.el, modules/lang/scheme/packages.el
Fix the popup rule not matching Geiser buffers (buffer naming changed upstream).
Fix repl/eval behavior to use `geiser-eval-region` instead of the default `+eval/send-region-to-repl` which doesn't work properly with Geiser.
Replaced calls to deprecated `switch-to-geiser` to avoid warning messages.
Introduced a scheme-mode package which backports `scheme-mode` fixes from master for Emacs <29.
-----
=> Fixes for Scheme/Geiser REPL integration

modules/lang/php/README.org
Hi,
There is a few important information on PHP's lsp documentation that is either outdated and/or lacking, such are:
- PHP 8 has been released a few years ago, tho I see no reason to point out it.
- [boris](https://github.com/borisrepl/boris) is now unmaintained and has been replaced by [pysh](https://github.com/bobthecow/psysh)
-  installation:  add Debian example
-  phpactor:  add note that it won't even install with php 8, globally at least
-----
=> docs(php): update version info and fix repl package name

lisp/lib/text.el
That's a bit tricky to explain, but here it is. I'm on macOs Ventura 13.1 (not that it matters), Emacs is
```
GNU Emacs     v27.2            nil
Doom core     v3.0.0-pre       HEAD -> master e96624926 2023-01-01 21:55:13 -0500
Doom modules  v22.10.0-pre     HEAD -> master e96624926 2023-01-01 21:55:13 -0500
```
When I copy something outside of Emacs (terminal / Safari / whatever) and then then call `doom/backward-delete-word` (usually via `c-w` hotkey or `m-backspace` in my case) before I paste (yank) right afterwards, instead of what I copied before I get some rubbish from the end of the current `kill-ring`. Not an expert in Emacs, but it does look to me that even though `kill-ring` is overridden in `let` block and not actually modified, the pointer is still modified which is causing …
=> fix(lib): don't overwrite kill-ring on doom/backward-kill-word

modules/lang/clojure/config.el
Introduced in #5730. `breakpoint-disabled` is defined in `gdb-mi.el`, not sure why that specifically was used here, but `shadow` is better than spamming `*Messages*`.
=> fix(clojure): undefined face on +light modeline

modules/completion/vertico/config.el
Related to bug
https://github.com/doomemacs/doomemacs/issues/7064
Was causing the "invalid preview key"-error in themes preview.
Fixes #0001
References #0000
Replaces #0000
-----
=> fix(vertico): consult-theme: invalid preview key error

modules/emacs/vc/config.el
As reported on the Discord earlier today.
`browse-at-remote--get-remote-type` uses this list to match hostnames to remote types, and it assumes the entries are plists. The codeberg cons cell broke `+vc/browse-at-remote{,-kill}` because of this due to a `(wrong-type-argument stringp nil)` error.
-----
=> fix(vc): string type error caused by codeberg support

modules/tools/lookup/autoload/docsets.el
When `(lookup +docsets)` enabled, open Doom Emacs, `SPC s k` shows error: `Symbol’s function definition is void: consult--async-throttle`.
This is due to `consult` not loaded.
References [Discord thread](https://discord.com/channels/406534637242810369/1046468107822170142)
- modules/tools/lookup/autoload/docsets.el (`+lookup/in-docsets`): require consult for `vertico` completion
-----
=> fix(lookup): require consult in +lookup/in-docsets

modules/lang/python/autoload/python.el
For Emacs 29 whose branch has been cut, respect `python-shell-dedicated` for `+python/open-repl`.
-----
=> fix(python): repl: respect python-shell-dedicated

modules/ui/window-select/config.el
winum-atuo-setup-mode-line should be set first before calling winum-mode
```emacs-lisp
(define-minor-mode winum-mode
"A minor mode that allows for managing windows based on window numbers."
nil
nil
winum-keymap
:global t
(if winum-mode
(winum--init)
(winum--deinit)))
```
`winum-mode` calls `winum--init`
```emacs-lisp
(defun winum--init ()
"Initialize winum-mode."
(setq winum--window-count (length (winum--window-list)))
(if (eq winum-scope 'frame-local)
(setq winum--frames-table (make-hash-table :size winum--max-frames))
(setq winum--numbers-table (make-hash-table :size winum--window-count)))
(when winum-auto-setup-mode-line
(winum--install-mode-line))
(add-hook 'minibuffer-setup-hook 'winum--update)
(add-hook 'window-configuration-change-hook 'winum--update)
(dolist (frame (frame-list)) …
```
=> fix(window-select): unset winum-auto-setup-mode-line sooner

lisp/cli/doctor.el
Currently final report of `doom doctor` is always printed in plural form, even if there is only 1 warnings or message. This change fixes it.
-----
=> fix(cli): doctor: pluralizing single errors/warnings

modules/input/chinese/config.el
Pyim has replaced the `pyim-cregexp-build-regexp-string` with `pyim-cregexp-build`.
Fixes: `Error in pre-command-hook (vertico--prepare): (void-function pyim-cregexp-build-regexp-string)`
References https://github.com/tumashu/pyim/issues/468
-----
=> fix(chinese): update pyim-cregexp-build func

modules/lang/fortran/config.el
In the Elder Days, it was common to give Fortran files the extensions of `.FOR` or later `.F90`. The major modes for Fortran don't automatically detect this conversion. The former was already accounted for in Doom's module, but not the latter. This commit rectifies this.
See also: https://fortran-lang.discourse.group/t/fully-featured-fortran-setup-for-linux-mac-in-emacs-intel-fortran-support-included/3532/14
-----
=> fix(fortran): account for the `.F90` extension

lisp/lib/help.el
Slipped by manual testing due to consult not being loaded at the time
and doom--help-search going to default grep-find usage instead of
hitting the failiure.
Amend: 54c4340740ec
=> fix(lib): letf! in doom--help-search

modules/lang/lua/config.el
A small typo in the lua tree sitter implementation, This removed the trailing ! which got in. 
I have checked all the other languages and it seems lua is the only one. Sorry for that. 
-----
=> fix(lua): remove trailing ! in modulep!

modules/lang/csharp/config.el
in Emacs 29.0.60 the function (csharp-tree-sitter-mode) is void and deprecated, and seems that tree-sitter works just fine without it. So i have Removed it
Fixes #0000
References #0000
Replaces #0000
-----
=> fix(csharp): csharp-tree-sitter-mode: void-function error in Emacs 29+

modules/lang/common-lisp/autoload/common-lisp.el, modules/lang/common-lisp/config.el, modules/lang/common-lisp/packages.el, modules/lang/haskell/autoload.el, modules/lang/sh/autoload.el, modules/tools/eval/autoload/repl.el
This PR fixes a previously unreported bug, where not all available REPL-opening functions would be displayed via `SPC o r` in major modes that don't have an associated REPL (like the `*doom*` buffer). Further, this PR improves the UI a bit, displaying more human-readable names for the available modes.
Before:
After:
**NOTE:** There is still a strange bug here involving loading. In particular, from a __fresh__ restart of Doom, I'm able to open a Lua, Elisp, and Scheme repls, but not:
- Sh: `Symbol's value as variable is void: sh-shell`
- Lisp (`sly-mrepl`): `Couldn't find a valid REPL for +doom-dashboard-mode`
- Indeed `sly-mrepl` (the symbol found in `+eval-repls`) is not a `commandp`, while `sly` is! __Is the `commandp` requirement too strict?__
- Haskell: `Symbol’s function definition …
=> :tools rework REPL selection UI

modules/lang/org/autoload/contrib-present.el
This implements the fixes described on takaxp/org-tree-slide#54
`org-flag-region` was deprecated on org 9.6, superseded by `org-fold-region`, which takes different `spec` argument.
Fixes takaxp/org-tree-slide#54
Fixes doomemacs/doomemacs#7058
References https://github.com/emacs-straight/org-mode/blob/5f817f21fcbbe7c122fcbbc0fb5f43f26fef6259/lisp/org-compat.el#L463
-----
=> fix(org): org-flag -> org-fold, add spec argument

modules/lang/common-lisp/autoload/common-lisp.el, modules/lang/common-lisp/config.el
Doing so manually in a Sly REPL is otherwise time consuming and repetitive.
This is a breaking change due to the restoration of `SPC m t` as a testing prefix, as it is commonly used in other language modules. The previous binding to `SPC m t` has been moved to `SPC m T`.
-----
=> feat(common-lisp): add project loading and testing commands

modules/lang/elm/autoload.el, modules/lang/elm/config.el
Present in basically every other language module, these were mysteriously missing for Elm.
------
=> feat(elm): add bindings for project compilation

modules/lang/clojure/config.el
The cider library is loaded too late for clojure-mode to rely on, so we
load after the cider-mode package instead.
Fix: #7130
=> fix(clojure): load against the correct package

modules/completion/company/config.el
Add hook for `company-abort` when `+childframe` option is enabled.
-----
=> fix(company): hook company-abort when +childframe enabled

modules/email/mu4e/autoload/email.el
`(mu4e)` accepts an optional argument, `background`, which is useful if you want to jump straight to `mu4e-headers-mode`. `=mu4e` does useful things in addition, but ignores this parameter. It should pass it on.
(In general, `=FUNC` commands should not mask optional arguments, if any.)
-----
=> fix(mu4e): Do not shadow `mu4e` arguments

lisp/lib/help.el, lisp/packages.el, modules/completion/vertico/autoload/vertico.el, modules/completion/vertico/packages.el
iyefrat/all-the-icons-completion@4da28584a1b3 -> iyefrat/all-the-icons-completion@b08f053cee44
minad/consult@ffaaf6da909d -> minad/consult@052399ed0537
minad/marginalia@ccf573e2145d -> minad/marginalia@2633b2dee222
minad/vertico@6f22ff129886 -> minad/vertico@b6b8420d2943
oantolin/embark@5497a19eef92 -> oantolin/embark@3ffb27a833d3
oantolin/orderless@d09aab37951b -> oantolin/orderless@e6784026717a
tumashu/vertico-posframe@f57b170b435e -> tumashu/vertico-posframe@7da6d648ff42
emacs-compat/compat@38280a7b54a6 -> emacs-compat/compat@7775c3185764
---
consult--grep added support for searching in multiple directories, so we
can drop the advice in `doom--help-search`. The other changes just adapt
to upstream API changes.
=> bump: :completion vertico compat

modules/ui/unicode/autoload.el
unicode mode would unset `doom-unicode-font` prior to adding the hook for `+unicode-setup-fonts-h`, thus bypassing #3334.
This also addresses #3298 without disabling unicode module, as required for
@teu5us's issue: https://github.com/doomemacs/doomemacs/issues/3298#issuecomment-731711911
=> fix(unicode): don't unset `doom-unicode-font`

modules/tools/magit/packages.el
magit/closql@c3b34a6ec438 -> magit/closql@0a7226331ff1
---
closql c3b34a6ec438 breaks code-review
wandersoncferreira/code-review#245, and the current forge commit (but
forge does have an upstream fix), pinned as a temporary measure to
prevent user breakages
Ref: wandersoncferreira/code-review#245
Ref: magit/closql#8
Fix: #7191
=> revert: closql

modules/lang/nix/packages.el
NixOS/nix-mode@c18a24e -> NixOS/nix-mode@719feb7
Compare: https://github.com/NixOS/nix-mode/compare/c18a24e9ac569a221e88ba9d74d52c7b02b6eb77...719feb7868fb567ecfe5578f6119892c771ac5e5
-----
=> bump: :lang nix

modules/lang/org/README.org, modules/lang/org/config.el
Move org-crypt and related hooks behind a '+crypt' flag
Doom marks this as a TODO and it's easy to implement. What's more, doom add `org-encrypt-entries` hook to `before-save-hook`, which makes saving buffer not work due to a recent bug from GnuPG: https://stackoverflow.com/questions/76388376/emacs-org-encrypt-entry-hangs-when-file-is-modified. This PR fixed this problem for those who don't enable encryption on org file.
-----
=> refactor(org): move org-crypt and related hooks behind a `+crypt` flag

modules/lang/ledger/config.el
This PR maps `<localleader> r` in `ledger-report-mode-map` to `ledger-report` function. 
`ledger-report` function is very often used and the keybinding `<localleader> r` is already mapped to `ledger-report` in `ledger-mode-map` (notice not a "report" mode map).
The issue is after a report is generated you can't type the same key sequence to choose another report to generate.
It's because the active buffer is changed to the report one and `ledger-report-mode-map` doesn't have the very same keybinding defined. 
It means you have to switch the buffer back to your ledger file and type the sequence again. 
In the ledger-mode.el the keybinding to generate a report works in both buffers. 
Hope it makes sense.
That's my first time here, please let m know if I missed anything important. 
-----
=> tweak(ledger): map `ledger-report` in `ledger-report-mode-map`

lisp/lib/system.el
If a NixOS machine has `lsb_release` in its PATH, `lsb_release` will be used instead of `nixos-version` to determine the version.
Move the more general `lsb_release` check after the NixOS check.
-----
=> fix(lib): doom-system-distro-version: check nixos-version first

lisp/lib/text.el
Hi,
I found out that Doom Emacs get regions incorrectly for `evil-emacs-state-mode`, because `evil-visual-beginning` and `evil-visual-end` are used to get regions in emacs state mode.
I added additional conditions check to fix this issue.
Can you review and merge this PR?
Thanks!
-----
=> fix(lib): doom-region-*: only use evil visual range in visual mode

modules/config/default/+emacs-bindings.el
In anticipation of the Corfu module, this PR feature-gates the company-mode keybindings for non-Evil users. This is already done for Evil users. 
While feature-gating keybindings is on the do-not-PR list, I am hoping that an exception will be made on the basis that the company keybindings are currently feature-gated for Evil users but not for non-Evil users.
=> tweak(config): feature-gate company keybindings

modules/lang/scala/README.org, modules/lang/scala/doctor.el
warn about metals binary instead of metals-emacs.
there's no need for a custom binary for each editor
- https://github.com/NixOS/nixpkgs/pull/182087#issuecomment-1296195328
- https://github.com/scalameta/metals/blob/45df705da236edfddcea7e358592fd3202bb9460/docs/editors/vim.md?plain=1#L81
-----
=> fix(scala): remove -emacs suffix from metals executable

modules/tools/lookup/autoload/lookup.el
Set the selected `identifier` to `pdf-view-active-region-text` in the case of being selected in pdf-view-mode.
=> fix(lookup): correctly scrape identifier in pdf-view-mode

modules/lang/javascript/autoload.el
JavaScript monorepo packages can contain a child `node_modules`, hence we need to grab the one at the workspace root if possible.
=> fix(javascript): use top-level node_modules in monorepos

templates/config.example.el
Do not default to setting the user's name to John Doe or their email to john@doe.com. It is better to leave these variables unset than to set them incorrectly.
Currently, if the user edits the Doom config and ignores those two lines, their name and email get set to "John Doe" <john@doe.com>, which is probably not what they want.
I could not find any explanation for why the lines are uncommented when you added them in 18d8ea22f6c81e6b46c87448476d62c9be6685f2
Thank you!
-----
Related #4553
=> docs: don't set user-* variables by default

modules/ui/popup/autoload/popup.el
Previously, +popup/other would do nothing if a window with the no-other-window property that was not a popup was focused. Now +popup/other will always select different window if there is another popup or window with the no-other-window property. This fixes #7119.
=> fix(popup): cycle windows with no-other-window property

modules/config/default/+evil-bindings.el, modules/tools/collab/README.org, modules/tools/collab/config.el, modules/tools/collab/doctor.el, modules/tools/collab/packages.el, templates/init.example.el
Add a collaborative editing module, powered by crdt.el.
@artenator and I (@jming422) are the authors of this module (we used crdt.el to write it collaboratively!), and we're offering to maintain it as best we can also.
**Some things we'd love feedback on:**
- Keybindings -- For now we put it at the leader `SPC l`, but are very willing to change this!
- UI look & feel -- Some of the interfaces used by crdt.el feel "vanilla Emacs-y", and we're not totally sure what to do about it. The menus for creating a new session with `crdt-share-buffer` and connecting to someone else's session using `crdt-connect` especially fall into this category - they use the `forms-mode` builtin major mode for these menus.
**Some things we still have in progress, but that shouldn't block initial review:** (all …
=> module: add :tools collab

modules/editor/lispy/README.org
Add documentation on how insert brackets `[]` with `lispy` enabled. 
By default `lispy` binds commands to `[` and `]` even in insert state, which caused myself (and a [few](https://github.com/noctuid/lispyville/issues/36) [others](https://github.com/abo-abo/lispy/issues/83)) confusion when first using the module.
-----
=> docs(lispy): add "Working with Brackets"

modules/lang/julia/README.org, modules/lang/julia/autoload.el, modules/lang/julia/config.el, modules/lang/julia/doctor.el, modules/lang/julia/packages.el
[Julia Module Refactor](https://discourse.doomemacs.org/t/julia-module-refactor/2797)
-----
=> Add julia +snail 

lisp/lib/sessions.el, modules/ui/doom-dashboard/config.el
This PR adds in a few safeguards when loading sessions. As quickloading a session can be destructive to a current session it makes sense too 
1. remove reload session as the top menu item and replace it with something non destructive (in this case I replaced it with the "Recently used files" action) 
2. ask for confirmation when you do want to restore a session. For good measure I have also allowed for the universal argument to be supplied to bypass this confirmation.
Now this is somewhat opinionated. With the first point its easy to restore. 
```lisp
(setq +doom-dashboard-menu-sections
'(("Reload last session"
:icon (all-the-icons-octicon "history" :face 'doom-dashboard-menu-title)
:when (cond ((modulep! :ui workspaces)
(file-exists-p (expand-file-name persp-auto-save-fname …
```
=> Quickload safeguards

modules/editor/multiple-cursors/config.el
For evil compatibility (switching to emacs state during multiple cursors), when evil is enabled locally by evil-local-mode but not globally by evil-mode, using the former to check is more accurate.
Also make the state variables local since MC maybe used for multiple buffers: activate current buffer and while not deactivating here, go to another buffer and activate there.
-----
=> fix(multiple-cursors): check evil-local-mode instead of the global one (+multiple-cursors-compat-switch-to-emacs-state-h)

modules/tools/lsp/doctor.el
The logic to check npm existence when `+eglot` flag is enabled is wrong.
```
(lsp +eglot)
```
- In shell
```shell
❱ which npm
/etc/profiles/per-user/james/bin/npm
```
- In Emacs
```emacs-lisp
(executable-find "npm")
> "/etc/profiles/per-user/james/bin/npm"
```
- Before the fix
```shell
❱ doom doctor
The doctor will see you now...
> Checking your Emacs version...
! Detected a development version of Emacs (29.1)
This is the bleeding edge of Emacs. Doom does not support it because
Emacs HEAD is in an especially unstable period of its development. If
you've found a stable commit, great! But be cautious about updating
too eagerly!
Because development builds are prone to random breakage, there will be
a greater burden on you to investigate and deal with issues. Please
make extra sure that your …
```
=> fix(lsp): check npm when eglot is enabled

lisp/lib/projects.el
Unquotes `base-directory` argument added to `project-file-exists-p!` in b1cc719. It was triggering the error (void-variable base-directory).
Fixes #7356
-----
=> fix(lib): unquote base-directory in project-file-exists-p!

modules/config/default/autoload/default.el
`consult-man` is a better version of `man` that computes its candidates asynchronously and allows the user to pass arguments directly to the man command. It's basically like `consult-grep` but for `man`. Before merging this, please double-check that `consult-man` is defined in our pinned version of `consult`.
=> feat(default): add use consult-man if available

lisp/lib/help.el, modules/lang/org/autoload/org.el
This PR addresses https://github.com/doomemacs/doomemacs/issues/7206. Currently, `+org/open-fold` is not working because `(outline-visible-p)` does not check for the `org-fold-outline` property. So I replaced all calls of `(outline-visible-p)` with the redefinition by jesseylin, which checks for `org-fold-outline`.
=> fix(org): check org-fold-outline in invisible property

modules/ui/popup/+hacks.el
Previously, wdired actions will not close popup windows, which is cumbersome to use. We've already added similar hacks to dired. Now it's time to add similar hacks to wdired.
-----
=> fix(popup): add wdired hacks

lisp/lib/help.el
When a package is added via straight local-repo recipe, no homepage can be determined. Prevent `doom--help-insert-button` throwing an error when `help-packages` is called for such a package. Instead insert "n/a" for this section, similar to other sections without data.
-----
- while trivial, this fixes an error preventing display of help
=> fix(lib): doom/help-packages: handle missing homepage

modules/app/irc/autoload/irc.el, modules/app/irc/doctor.el
This PR tweaks the IRC module to make disabling circe notifications not cause an
error.
=> tweak(irc): check circe-notification is bound

modules/editor/snippets/autoload/snippets.el
I've been playing with the snippets module lately and ran into a couple bugs and some small opportunities for enhancement.
Bugs:
- `+snippet--completing-read-uuid` always returns nil, breaking `+snippets/new-alias`, `+snippets/edit`.
Rather than attempting to read the uuid from a text property on the selected completion -- which gets stripped by vertico (and possibly helm) -- grab it from a lookup alist of completion-candidat->uuid.
Essentially the same as the proposed implementation by @jgrey4296 on #4127
- Couple issues related to `default-directory` binding in new and new-alias:
1. `+snippets--ensure-dir` would error out when default-directory was bound to a non-existent dir. I modified it to return the dir if it already existed or was created and bound its result to …
=> snippets module command fixes and enhancements

modules/lang/fortran/autoload.el, modules/lang/fortran/config.el
This PR adds a new convenience function and binding to the `fortran` module.
-----
=> feat(fortran): `SPC m f o` opens project config

modules/editor/evil/config.el
In emacs-29, native tree-sitter adds new major modes for the C++ language, named c++-ts-mode. As a result, hooks in c++-mode will not run. This commit adds the angle bracket fix hook for c++-ts-mode.
-----
=> fix(evil): add evil-embrace support for c++-ts-mode

modules/editor/evil/autoload/evil.el
At some point `windmove-find-other-window` stopped loading reliably, such that `SPC w H` would complain of a missing symbol. Indeed navigating to the implementation of `windmove` within Emacs's Lisp we find warnings that `windmove-find-other-window` has mostly been superceded by newer window APIs since 2013, and is implemented in terms of `window-in-direction`.
By using `window-in-direction` directly, the loading problem disappears.
-----
=> fix(evil): more reliable window detection

modules/ui/treemacs/packages.el
Alexander-Miller/treemacs/@00e96c8 -> Alexander-Miller/treemacs/@b4e2ad8
I've bumped the version of treemacs  to fix issue with inconsistent SVG icon sizes on macOs.
Fix: #7409 
Ref: #7409 
Close: #7409 
-----
=> bump: :ui treemacs

modules/ui/workspaces/autoload/workspaces.el
This change uses completing-read to get the new name from the user when renaming workspaces, to allow them to more easily make a small change to the existing name of a workspace.
Note: I haven’t included screenshots because I don’t think this is a big enough visual change to need them. Let me know if this is the wrong conclusion!
-----
=> tweak(workspaces): prefill current name on rename

modules/lang/common-lisp/config.el, modules/lang/emacs-lisp/config.el, modules/lang/hy/config.el, modules/lang/scheme/config.el
`apheleia--indent-lisp-buffer` does not exist.
Ref: #6369
-----
=> fix(format): use correct lisp format function

modules/ui/tabs/config.el
Current problem: `centaur-tabs` requires explicitly set the icon font, if not, it will use all-the-icons as default. Since all-the-icons has been replaced in doomemacs, `centaur-tabs-icon-type` can be set as `'nerd-icons` by default.
<details open>
<summary>Before</summary>
</details>
<details open>
<summary>After</summary>
</details>
-----
=> fix(tabs): replace all-the-icons with nerd-icons

modules/editor/format/README.org, modules/editor/format/autoload/format.el
This prevents apheleia complaining about the editing buffer being
killed.
From https://github.com/doomemacs/doomemacs/pull/6369#issuecomment-1720717000
=> fix(format): update missing values & set buffer modification

modules/editor/format/config.el
The function `+vc-gutter-init-maybe-h` is not defined for `+diff-hl` so I am getting a void function error without this PR.
=> fix(format): use +vc-gutter-update-h instead

modules/lang/ocaml/config.el
Previously, loading the `ocaml` module and opening a file in Tuareg mode would result in every buffer having its formatter set to `ocp-indent`. This now restricts the formatter override to the current buffer.
-----
=> fix(ocaml): Prevent clobbering +format-with globally

modules/emacs/dired/packages.el
Fix: #5579
New version of nerd-icons-dired contains the fix for icon jumping.
-----
=> Bump nerd-icons-dired

modules/emacs/vc/packages.el
magit/magit@97a95f70079b -> magit/magit@48818355728c
The pinned version of `magit` in `:tools magit` needs be the same as that of `git-commit` in `:emacs vc`.
`straight.el` prepares the repo only once, and if `git-commit` is processed first, its pinned version wins out and the more recent pinning of `magit` is ignored.
As noted in #7363, processing order may be non-deterministic, so the inconsistent pinning may not be apparent on every system.
This may not fully close #7363, because in addition to the immediate problem of inconsistent pinned versions of `magit` and `git-commit`, that issue suggests that having to define the pinning in two different places might itself be an issue that should be resolved.
Fix: #7363
Ref: #7277
Ref: 7c63b353d290
-----
=> bump: :emacs vc

modules/ui/ligatures/autoload/ligatures.el
resetting font-ligatures means passing `nil` as the second argument of `(set-font-ligatures!)`
Using `ligatures-ignored-major-modes` to cancel ligatures is too brittle, because "resetting ligatures for `prog-mode`" would have bad semantics with all its derived modes. The user probably just wants to remove the default ligatures and then configure `foo-mode`, but pushing `prog-mode` to `ignored-major-modes` might just disable ligatures across all modes _derived from_ `prog-mode`.
This commit changes things in 2 ways:
- resetting ligatures now directly manipulates ligature.el internal state (the `ligature-composition-table` alist)
- in order to work, Doom must maintain an extra invariant on that alist, multi-modes keys (`'(foo-mode bar-mode)`), cannot be used, only single modes.
That mostly …
=> fix(ligatures): proper resetting of font-ligatures

lisp/lib/docs.el, modules/lang/org/autoload/org-link.el, modules/lang/org/config.el
The fancy Org docs links had some regressions with the switch to Nerd Fonts. In the process of addressing those, I ended up finding and taking care of several other quirks. See the commit messages for more details.
Before:
Note the changed codepoint for the variable icon resulting in a folder glyph from Nerd Fonts as well as the scissors in place of the package Octicon. Also, the face icon (U+E90F, ) will appear as tofu for people who don’t happen to have all-the-icons installed, Nerd Fonts don’t have a glyph at that code point.
After:
Note the shadowed unbound symbols and the passthrough of the `fixed-pitch-serif` face (it’s a bit subtle in this particular case, but you can at least see the difference in the `f` glyphs). Packages (italic) and modules (bold) that are found on their load …
=> Fix Org docs links

modules/email/mu4e/autoload/advice.el, modules/email/mu4e/config.el
This commit fixes several Doom mu4e functions which are broken on later versions of mu4e due to the variable prefix change from mu4e~ to mu4e--. I also added them to the forwards-compatibility aliases.
-----
=> fix(mu4e): replace obsolete/removed functions

modules/lang/org/config.el
org-attach-delete-one and -all are bound to keys, thus requiring autoload. Otherwise an error occurs when executing them before org-attach is loaded.
-----
=> fix(org): add missing autoloads for org-attach

modules/lang/ruby/packages.el
pd/yard-mode.el@ef3426ff55b6 -> pd/yard-mode.el@de1701753a64
nonsequitur/inf-ruby@6f1df882ab31 -> nonsequitur/inf-ruby@03475ac1cca4
dgutov/robe@b9d5ab549f73 -> dgutov/robe@912ae2ba1f46
pezra/rspec-mode@62853a428b41 -> pezra/rspec-mode@29df3d081c6a
Updates packages related to the Ruby language to the latest released versions. All packages contain mostly documentation changes except for:
- `yard-mode` dropped require of `cl` in https://github.com/pd/yard-mode.el/commit/de1701753a64544c3376b015805f3661136d8038
- `rspec-mode` added support for `podman` and `nerdctl` commands in https://github.com/pezra/rspec-mode/commit/c59cb897383089273ac5c46f3c71a6f3e49e0eee
-----
=> bump: :lang ruby

modules/lang/ocaml/config.el
Added `dune-project` to the `projectile-project-root-files` for the `ocaml` module.
-----
=> fix(ocaml): add dune-project to ocaml projectile root files

modules/completion/vertico/config.el
`consult-buffer` uses `recentf` to populate file candidates. It is not uncommon to use `consult-buffer` as a single entry point to buffers, bookmarks and recent files, effectively replacing `recentf` and `consult-recent-file`.
To improve startup performance, Doom enables `recentf-mode` after the first file is opened (0e851ace9ba4). When executing `consult-buffer` at startup, `recentf-mode` won’t be enabled yet. Add it to the `consult-recent-file` advice to ensure that can’t happen.
Unlike `consult-recent-file`, `consult-buffer` does have significant functionality without `recentf-mode`, but for the tiny fraction of Doom users that disable `recentf-mode`, this is easy enough to `advice-remove`.
Fix: https://github.com/doomemacs/doomemacs/issues/7461
-----
=> fix(vertico): ensure recentf-mode for consult-buffer

modules/lang/data/config.el
`nxml-slash-auto-complete-flag` inserts the rest of the closing tag when `</` is inserted, but smartparens also defines `(sp-local-pair "<" ">")` for `sp--html-modes`, so two `>` are inserted for closing tags. Apply the upstream developer’s suggested fix.
Fix: https://github.com/doomemacs/doomemacs/issues/6331
Ref: https://github.com/Fuco1/smartparens/issues/397
Not sure why upstream doesn’t just include this in smartparens-html itself, but it’s straightforward enough to handle in the Doom module for now.
-----
=> fix(data): correct XML closing tag insertion

lisp/doom-ui.el
I'm using Emacs30 and on my version,
doom-apply-ansi-color-to-compilation-buffer-h does not colorize all the escape sequences. Using ansi-color-compilation-filter instead fixes this for me.
This PR addresses #6222. 
-----
=> fix: use ansi-color-compilation-filter on emacs28+

modules/lang/nix/README.org
Add a note about the `+lsp` flag of the nix module — I was pleasantly surprised to discover that it already exists when I needed it & wanted to look at how to add it, after I didn't find it in the module's documentation, so I thought having a note about it would be nice.
Ref: #6592 (added the flag)
-----
=> docs(nix): mention +lsp flag

modules/lang/rust/config.el
When invoking `rustic-cargo-run` a buffer called `*cargo-run*` is opened. This adds a rule such that this buffer opens in a popup window that is the same as the popup windows for other rustic cargo commands.
This PR is adding to the solution to [this issue](https://github.com/doomemacs/doomemacs/issues/2623).
-----
=> fix(rust): make cargo popups consistent

modules/email/mu4e/autoload/email.el, modules/email/mu4e/config.el
`mu4e` now has its own modeline that is quite flexible. These changes add icons inline with doom's style.
Also adds `mu4e`'s buffers to a popup rule since it now uses display-buffer-alist.
=> mu4e: add icons for mu4e's internal modeline

modules/ui/popup/+hacks.el
https://github.com/emacs-evil/evil/commit/a09fdca0b35ef4289cf55d7b0ffadf4cf3a5c9fc renames `evil-command-window-insert-commands` to `evil--command-window-insert-commands` so we have to change our function calls. Without this PR `evil-command-window` gives a blank buffer as no command is inserted.
-----
=> fix(popup): change evil function to call following upstream rename

docs/faq.org, lisp/doom-ui.el, modules/README.org, modules/ui/doom/README.org, modules/ui/ligatures/README.org, modules/ui/unicode/README.org, modules/ui/unicode/autoload.el, templates/config.example.el
See commit messages for details. Please comment if you can confirm this is an improvement, as font configuration varies from user to user and is somewhat dependent on environment and operating system. I’m fairly confident it’s good, though. To test, please remove any workarounds you may have made from your configs. Checking out my branch in your Doom installation and starting a new Emacs instance should be all you need to test. You can leave your current Emacs instance running if you have a bunch of stuff you’re working on. Just make sure to return to `master` when you’re done testing.
- Fix #2083
- Fix #3296
- Fix #5474
- Fix #5160
- Fix #5623
- Fix #7036
- Fix #7167
- Fix #7467
-----
=> Fix font fallbacks

lisp/doom-ui.el
317cea5eefda (part of https://github.com/doomemacs/doomemacs/pull/7448) assumed Emacs 28, but Doom still tries to support 27.
Closes https://github.com/doomemacs/doomemacs/issues/7505
-----
=> fix: premature use of emoji fontset in <=28.1

modules/ui/treemacs/config.el
If the variable `treemacs-python-executable` is set, then the git mode shouldn't be overwritten, even if python cannot be found in the PATH.
-----
=> fix(treemacs): do not overwrite git mode when treemacs-python-executable is set

modules/lang/org/autoload/org.el
Sometimes, `org-reveal` is called in the wrong buffer which throws an error.  For example, `org-link-open-from-string` creates an temporary org-mode buffer that gets killed very quickly which means that `org-reveal` gets called in a different buffer.  I have also had issues with org-reveal getting called in the org-roam buffer, which is why this commit also saves the buffer it was called in.
-----
=> fix(org): call org-reveal in correct buffer

modules/term/eshell/config.el
This PR adds Imenu support to Eshell. Simple as that.
-----
=> feat(eshell): add imenu support

modules/tools/lsp/+eglot.el
The `eglot-events-buffer-size` setting disables the `eglot-events-buffer` when 0, enabling more consistent performance on long running emacs instance. Default is 2000000 lines. After each new event the events buffer is pretty printed as a whole, which causes steady performance decrease over time. Quite a bit of CPU is spent on pretty printing and Emacs GC is put under high pressure.
Fix: #0000
Ref: #0000
Close: #0000
-----
=> perf(lsp): turn off eglot events buffer

modules/editor/evil/config.el
Hello. So my PR to Embrace to add prefix-function to the default pairs was accepted (https://github.com/cute-jumper/embrace.el/pull/26). Now we can use those anywhere using `C-f`. This is better than our current DWIM-style `f` because that way we can write Lisp anywhere and not have to remember if we are actually in a Lisp buffer when we call `embrace-commander`.
By the way, Embrace is also not pinned, I see. Not sure if that is important.
-----
=> refactor(evil): remove lisp prefix-function embrace pair

templates/packages.example.el
Hi team, I noticed `package.el` was using single semicolons for comments, which resulted in 40 character width indentation on format:
So the PR is to replace them with double semicolons as suggested by [Comment-Tips](https://www.gnu.org/software/emacs/manual/html_node/elisp/Comment-Tips.html)
(I couldn't find any related issues)
-----
=> docs: replace single -> double semicolons

modules/lang/markdown/config.el, modules/lang/markdown/packages.el
fixes the workaround for introduced in   aad7bc521f188ebee47
that was fixed in jrblevin/markdown-mode@44f0e89534e6
jrblevin/markdown-mode@c765b73b370f -> jrblevin/markdown-mode@b1a862f0165b
Ref: jrblevin/markdown-mode#578
-----
=> bump: :lang markdown

modules/lang/plantuml/config.el
The flycheck-plantuml is by default configured to always run plantuml via "java". This only works with a downloaded plantuml. However, I would prefer to have plantuml installed via my package manager (fedora/dnf).
A locally installed PlantUML executable is already detected by default for normal use (export/preview), we can also use it for flycheck.
If plantuml is downloaded using plantuml-download-jar, this jar is still used by default (see setq plantuml-exec-mode), so this should not affect previous setups.
Fix: #0000
Ref: #7546 (implemented together with that feature/diagrams as well)
Close: #0000
-----
- N/A My changes are visual; I've included before and after screenshots.
=> fix(plantuml): flycheck: executable support

modules/lang/clojure/README.org, modules/lang/clojure/packages.el
Bump to the latest versions of everything & add a note about using `enrich-classpath`. 
@vemv my understanding from the docs is this is still a wip flag, or is it ready to be a default yet?
Closes #7515
=> Bump :lang clojure

modules/lang/swift/config.el
The `use-package!` declaration for lsp-sourcekit in `config.el` did not match the `package!` declaration in `packages.el`: this meant that `lsp-sourcekit` would be loaded, but it was never actually installed. The removal of this package also resulted in there no longer being a proper LSP client with eglot—this has also been fixed.
Fix: #0000
Ref: #0000
Close: #0000
-----
=> fix(swift): don't load lsp-sourcekit with eglot

modules/editor/format/README.org, modules/editor/format/config.el
Edit 2023/11/21 - added an extra commit and updated the title to better reflect the PR's contents.
Previously, it was impossible to disable saving in certain modes. This was due to 
1) Improper feature name in `after!` call
2) Docs referencing behaviour which was not implemented in code
3) Docs not updated properly after 4ecd616cd8f60640d6b0be2ffc3d762e88099bb4 updated this module to use apheleia
Original PR text follows:
------
I was looking into forcing apheleia to always use the LSP formatter if available and wasn't sure if that should be done here or directly in the apheleia code. In the process of investigating that, I found several issues with the format module docs. I figured those should be addressed in a separate PR, I'm still looking into the LSP stuff but that may or may not …
=> fix(format): correct behaviour when disabling apheleia

modules/lang/latex/config.el
The current LaTeX module uses `TeX-command-run-all` for compilation, which by default opens the compiled document in a viewer. This behavior causes a loss of focus from the Emacs window, interrupting the editing workflow.
I address this by adding a custom compilation function, which saves the documents and compiles the project, but does not open it in a viewer. This allows users to continue editing without the need to manually switch back the focus to Emacs.
`TeX-command-run-all` is still a useful automation, so I keep it there but change the key binding.
-----
=> fix(latex): avoid stealing focus after compilation

modules/editor/format/autoload/settings.el, modules/editor/format/packages.el
fbd00b6a08300b453c15410e693823078c9015af changes `aphelia-core` to `aphelia`, but only in 1 out of 2 places *and* this is not the correct name in the version pinned in doom.
This PR fixes the other reference to `apheleia-core` and bumps `apheleia` to match.
Fix: #7568
- fix(format): correct name of feature
- bump: :editor format
-----
=> bump: :editor format

modules/lang/org/autoload/org.el
This fixes a bug introduced in bb3431a (#7509). This shows up for
example in `org-capture`, which uses multiple org buffers and the
initial one (with name `*Capture*`) will be dead already by the time the
timer runs.
Amend: #7509
-----
=> fix(org): don't call org-reveal in dead buffer

modules/config/default/+evil-bindings.el
This also makes the check for the presence of vundo consistent with the rest of the file by using modulep! instead of fboundp.
If there's interest, I could also add an emacs binding. The built-in binding of undo-tree-visualize is C-x u, so we could use the same for vundo. But feel free to suggest a better one, I'm not familiar with the conventions for emacs bindings.
-----
=> tweak(default): add binding for undo-tree

modules/lang/org/config.el
Currently the documentation for `:lang org`, among some others, does not load correctly. It would not enter `doom-docs-org-mode` with error
```
File mode specification error: (user-error Invalid action)
```
It turns out that `org-link-set-parameters` accepts `:face` for a function returning a face or a symbol naming a face. Passing `org-priority` directly would cause it being evaluated as a function, preventing documents containing `doom-user:` links from loading.
-----
=> fix(org): correct :face parameter for doom-user links

modules/completion/vertico/autoload/workspaces.el
This fixes the embark file action +vertico/embark-open-in-new-workspace not being interactivity callable which meant we get the following error when calling the action via embark:
```
embark PCH: (wrong-number-of-arguments ((t) (file) "Open file in a new workspace." (interactive) (+workspace/new) (find-file file)) 0)
```
-----
=> fix(vertico): embark open in new workspace action

lisp/lib/files.el
This avoids an issue where emacs yells at me with a popup like the following when I open `init.29.el`, e.g., when pressing `SPC c k` when the cursor is over `set-popup-rules!`:
```
These default coding systems were tried to encode the following
problematic characters in the buffer ‘init.29.el’:
Coding System           Pos  Codepoint  Char
utf-8-unix            25779  #x3FFFD0   
25780  #x3FFFCF   
25784  #x3FFFE1   
[...]
```
Strictly speaking, this issue goes away with either the second or the third commit, but I believe both are good changes.
-----
=> fix(lib): use unibyte in binary temp buffers

lisp/lib/packages.el
The old check was a bug fix to work around noisy values that somehow made it into diff checks. The `package!` symbol is never actually present in the list of values yielded by the search in `read-package`, so this commit alters the lookup to respect what is actually present, thus guaranteeing that `destructuring-bind` succeeds and bump diffs are actually detected.
-----
=> fix(lib): doom/bumpify-diff: respect structure of given list

modules/term/eshell/packages.el
Hi. Attempting to upgrade `doomemacs` with the `upgrade` or the `sync` command fails if you have enabled the `eshell` module:
```
✓ (212/338) emacs-fish-completion: d34d0b9 -> df42e15 [1 commit(s)]
ERROR: Couldn't collect commit list because: fatal: bad object df42e153082927536763bdf408184152a7c938c3
```
It seems that `emacs-fish-completion` package has a new owner and it was moved to GitHub now - https://github.com/Ambrevar/emacs-fish-completion
This merge request updates the `emacs-fish-completion` pkg recipe to the new home. I think that the fix here should work. Let me know if this should be done in another way. Thanks!
ambrevar/emacs-fish-completion@df42e1530829 -> LemonBreezes/emacs-fish-completion@d34d0b96fde6
-----
=> bump: :term eshell

modules/ui/doom/packages.el
doomemacs/themes@4aee1f5a0e54 -> doomemacs/themes@ff26f26ea3d7
Improves Emacs 30 compatibility (see ref).
Ref: https://github.com/doomemacs/themes/issues/809
-----
=> bump: :ui doom

modules/lang/common-lisp/autoload/common-lisp.el, modules/lang/common-lisp/config.el, modules/lang/common-lisp/packages.el
This allows us to offload system loading and testing to a third-party library.
Close: #7488 
-----
=> feat(common-lisp): use `sly-asdf`

modules/completion/vertico/autoload/vertico.el
Fixes the `:args` parameter of `+vertico-file-search` being unusable: the command-line args given through this parameter were being incorrectly escaped before appending them to `consult-ripgrep-args`. The fix is to not escape them at all.
We were using `shell-quote-argument`, which is meant for passing file
names, strings and so on, not command-line arguments. For example,
`(shell-quote-argument "--foo=bar")` yields "--foo\\=bar", which is
obviously invalid unless we're trying to pass an option named '--foo\'.
At any rate, there is no quoting/escaping for shells in the default
value of `consult-ripgrep-args`, so it doesn't look like this is
something we need to do.
-----
=> fix(vertico): don't shell-quote consult-ripgrep-args

modules/tools/upload/config.el
#7513 changed the expected value of `ssh-deploy-on-explicit-save` to be an integer, but the default value was still `t`. This commit changes it to be `1`.
-----
=> fix(upload): change ssh-deploy-on-explicit-save's default value to 1

modules/ui/popup/+hacks.el
As noted in #7556, the advice `+popup--evil-command-window-a` fails, preventing the command window from being opened. This is because `evil-command-window` has been rewritten extensively.
In particular, https://github.com/emacs-evil/evil/commit/a09fdca0b35ef4289cf55d7b0ffadf4cf3a5c9fc made it use `display-buffer` instead of `switch-to-buffer`, so that users could customize how the window opens. Since this was the function of this advice, it is obsolete and can be removed.
Fix: #7556 
-----
=> fix(evil): obsolete `evil-command-window` advice

modules/editor/file-templates/autoload.el
Replaced a call to `evil-initialize-state` with a call to `evil-change-state` since the former was recently changed to no longer accept any arguments.
See:
emacs-evil/evil@1c4c3bf
-----
- [X ] I searched the issue tracker and this hasn't been PRed before.
- [X ] My changes are not on [the do-not-PR list](https://doomemacs.org/d/do-not-pr) for this project.
- [X ] My commits conform to [the git conventions](https://doomemacs.org/d/git-conventions).
- [X ] Any relevant issues or PRs have been linked to.
=> fix(file-templates): invalid function call

modules/lang/emacs-lisp/config.el
We set `flycheck-emacs-lisp-load-path` to 'inherit, which evaluates `load-path` when spawning the Emacs subprocess. flymake relies on a static variable, hence the advice.
Ref: https://github.com/flycheck/flycheck/blob/e56e30d8c66ffc9776d07740658d3b542c1a8e21/flycheck.el#L8725-L8727
Ref: https://git.savannah.gnu.org/cgit/emacs.git/tree/lisp/progmodes/elisp-mode.el?h=emacs-29.1#n2166
Ref: https://emacs.stackexchange.com/questions/48661/how-do-i-get-flymake-to-recognize-files-in-my-load-path
---
We need to set up [+emacs-lisp-non-package-mode](https://github.com/doomemacs/doomemacs/blob/56187fc35af21246b23b8020bc9ffa8cabee1157/modules/lang/emacs-lisp/autoload.el#L278) for flymake as well. A simple approach would be to remove/restore `elisp-flymake-byte-compile` from buffer-local …
=> fix(syntax): add elisp flymake load path advice

modules/lang/emacs-lisp/autoload.el, modules/lang/emacs-lisp/config.el
This PR reduces the amount of false positives and erronious warnings the elisp flymake backends throw off. this PR brings flymake up to UX parity with flycheck. 
-----
=>  feat(emacs-lisp): add reduced-flymake-byte-compile

modules/term/eshell/config.el
Hi. I have taken over maintainership of `fish-completion` and have added a customization option for inhibiting the warning for a missing `fish` executable.
-----
=> Remove fish-completion HACK for inhibitting error

modules/completion/ivy/README.org
Depending on the system, this can cause sorting to be disabled long before the performance hit would be felt, and it's not obvious that this is the reason.
-----
=> docs(ivy): mention lowered `ivy-sort-max-size`

modules/lang/org/README.org, modules/lang/org/config.el, modules/tools/lookup/config.el
Adds some Kagi search goodness in-line with duckduckgo/google.
Didn't bother with the preview because that was ivy specific, and I'm not sure how popular that is anymore, and how many of those users would use the preview.
-----
=> Add Kagi search features

modules/emacs/dired/config.el
Hello,
With recent update https://github.com/doomemacs/doomemacs/commit/e242ac9548487ae50857ec1b169a20d946019816 `dired +dirvish` fails with `void-variable dired-omit-files error`.
Fix: #6562
=> fix(dired): void-variable dired-omit-files error

modules/lang/common-lisp/config.el, modules/lang/common-lisp/packages.el
`sly-overlay` is an extension for [Sly](https://github.com/joaotavora/sly) that enables the overlay of Common Lisp evaluation results directly into the buffer in the spirit of [CIDER](https://github.com/clojure-emacs/cider) (Clojure) and [Eros](https://github.com/xiongtx/eros) (Emacs Lisp).
Strangely, `SPC m e d` is the defaulting `eval` binding for Emacs Lisp and Clojure, but it wasn't for Common Lisp. So this new function swoops in and claims that as the default. The old binding remains on `SPC m e f`.
-----
=> feat(common-lisp): introduce `sly-overlay`

lisp/doom-modules.el
Fix `SPC h d m` error "Symbol's value as variable is void: doom-modules-load-path".
-----
=> fix: doom-module-load-path typo

modules/editor/file-templates/templates/text-mode/__license-lgpl3
Apologies if this goes against the "No less than 3 trivial changes per MR", but this is not just a spelling error, it gives me an error in the minibuffer saying "Ignoring unknown directive "contribuer" in file: /home/ben/.emacs.d/modules/editor/file-templates/templates/text-mode/__license-lgpl3" every start which is a minor annoyance.
This is related to a recent change in yas-snippet: https://github.com/joaotavora/yasnippet/commit/25f5d8808af23fb3b3dd6a7aacb06e17006ffca6 that introduced the warning.
-----
Maybe borderline, it is a single trivial change, but it does not only fix a spelling error but also removes an annoying warning
=> fix(file-templates): correct spelling of contributor in __license-lgpl3

modules/lang/fortran/README.org
This tweaks the documentation of the `fortran` module to demonstrate how `fprettier` can be customized. This was spurred by an issue [reported by a user here](https://fortran-lang.discourse.group/t/fully-featured-fortran-setup-for-linux-mac-in-emacs-intel-fortran-support-included/3532/19?u=fosskers).
-----
=> docs(fortran): show how to customize fprettier

lisp/lib/files.el
It's possible for the user to type shell variables (something like `$MYVAR/dir/filename`) as part of the filepath, so we need to call `expand-file-name`.
=> fix(lib): sudo file path: expand-file-name

modules/lang/org/config.el
Change the binding for archiving to `org-archive-subtree-default`, which is the recommend "catch-all" command in the org manual. The user can specify the actual command in `org-archive-default-command`. The default for this variable is `org-archive-subtree`, which we previously used for the binding, so this commit changes behavior only for users who have set `org-archive-default-command` explicitly.
-----
=> tweak(org): honor default command when archiving

modules/emacs/dired/config.el
Omit the flycheck file in Dired, which can show up while flycheck is checking a buffer.
-----
=> feat(dired): omit flycheck file in dired

modules/completion/vertico/config.el
Bind to both `TAB` and `<tab>` - if they have been mapped to different commands anywhere, Emacs will no longer treat them as equivalent, and this mapping will not work.
=> fix(vertico): mapping for embark open in workspace

lisp/doom-ui.el
Currently, `SPC b k` does not allow us to kill popup buffers. If we are say using a comint/eshell/eat buffer and we borked the state while testing hooks or we sent EOF to the underlying process, or the buffer has a process that is frozen, etc., our intention with `SPC b k` is to kill the underlying buffer.
I am interested in any other solutions people have to this. Maybe we should make a `:dedicated` parameter and set it to `nil` for `comint`, `eshell`, and `vterm` buffers.
=> fix(popup): allow killing popup buffers

modules/completion/vertico/config.el
Adds completion highlighting that works similarly to ivy/counsel's one (which is enabled by default). It'll highlight enabled major/minor modes and directories in a different face. On by default.
Before:
After:
-----
=> feat(vertico): completion highlights a la ivy

modules/completion/vertico/config.el
Minor mode highlights did not disable as long as the mode was enabled (e.g. I had visual-line-mode highlighted even in buffers when it wasn't on). This should fix that.
-----
=> fix(vertico): disable minor mode highlight duly

modules/lang/java/autoload/java.el
allow `+java-current-package` and `+java-current-class` functions to operate on `java-ts-mode` (the java tree-sitter mode) not just `java-mode`.
---
=> feat(java): java.el takes java-ts-mode into account

modules/email/mu4e/autoload/mu-lock.el
mu4e-quit now takes an optional argument, BURY, which is a boolean that determines whether to bury the buffer or kill it. This commit updates the advice to reflect this change.
-----
=> mu4e: fix advice for new mu4e release

modules/os/macos/config.el, modules/os/macos/packages.el
As the title says, osx-trash is no longer needed nowadays for emacs so one less package to install :-)
=> feat(macos): osx-trash is only needed by emacs < 29

modules/completion/corfu/README.org, modules/completion/corfu/autoload.el, modules/completion/corfu/config.el, modules/completion/corfu/packages.el, modules/completion/vertico/config.el, modules/config/default/+emacs-bindings.el, modules/config/default/+evil-bindings.el, modules/config/default/config.el, modules/tools/lsp/+lsp.el, templates/init.example.el
Implements a [corfu](https://github.com/minad/corfu) module, which can be used as a lightweight alternative to company. Overview of features (unchecked means it is not implemented, but planned to be):
~Removed, since they were implemented incorrectly, and probably belong in language modules rather than here.~
Added back by @LemonBreezes, with a proper implementation.
Removed, see review comments.
~For now, I've added yasnippet integration, but there's a catch, it depends on company. See the README for details.~
~I ended up rebasing completion support out, since it was very buggy and troublesome to use. It expanded snippets as soon as the abbreviation was typed, which led to unwanted text being written in place of what the user asked. I will revisit this idea when we have a tempel module, …
=> module: Add corfu

modules/editor/fold/autoload/fold.el
`+fold--ts-fold-p` just checks that treesitter mode is active and the `ts-fold` feature is active, which will block any other fold-method checks following it. So having the `cond` conditions for folds out of order can lead to inconsistent behavior if using specific folding mechanisms directly.
Move it to the end so other fold types have a chance, and consistently order fold type checks so unfolding will (more likely) use the same underlying mechanism as folding.
Here's a repro, which (for me) this PR resolves:
Create this Python file and, with point on `class`, call `(hs-hide-level)`.
```
class TestHideShow:
def __init__(self):
pass
```
You get:
```
class TestHideShow:
def __init__(self):  [ ... ]
```
Move point to `def` and call `+fold/open`. It will do nothing — it's a `hideshow` fold …
=> fix(fold): reorder fold type checks

modules/completion/corfu/config.el, modules/completion/corfu/packages.el
This tidy ups the corfu module to use the logic when a user enables
corfu +orderless without enabling vertico. Since that's probably a niche
situation, we only specify commit to pin to orderless in the vertico
module so that contributors aren't tripped up with trying to remember to
update orderless in two different code locations. Of course, if this
turns out to be a more popular use-case we can re-evaluate this logic.
=> refactor(corfu): consolidate +orderless logic without vertico

modules/completion/corfu/README.org
Hi. This adds some documentation I wrote up for debugging the `cape-dabbrev` completion candidates.
-----
=> docs(corfu): debugging cape-dabbrev

modules/ui/popup/autoload/popup.el
This caused a global variable `list` to be bound  
---------
=> Fix typo in local variable name

modules/editor/fold/autoload/fold.el, modules/editor/fold/config.el
- Make `+fold/close-all` work for outline-minor-mode.
- Distinguish between `zo` and `zO` for outline-minor-mode alone, by binding `zO` to a new function `+fold/open-rec`. `zO` will now trigger `outline-show-subtree` in outline-minor-mode, while `zo` will only trigger `outline-show-branches`, keeping the subheadings folded. This matches the behavior in org-mode.
- Fix a bug in `+fold/open-all`, introduced in 7b9d00d6616d67cbc92765bb9da0dd0d2d9e9581, that makes it only operate on vimish-fold folds.
Similar fixes were PRed in #5724, but it looks like the author proceeded to use that branch as their main branch, resulting in hundreds of commits from master being added to the PR, before giving up and closing it.
Note that I have not enabled outline-minor-mode anywhere it's not already on. So …
=> fix(fold): properly support outline-minor-mode

modules/email/mu4e/config.el, modules/email/mu4e/packages.el
Now that mu4e has its own notification feature since 1.10 (and as of
this commit version 1.12 is already out), we can just use that. Much
less code to maintain.
Closes: https://github.com/doomemacs/doomemacs/issues/6896
=> feat(mu4e): use built-in notifications instead of mu4e-alert

modules/completion/corfu/config.el
Although this error will not be triggered by most people, since auth-source is loaded by a lot of packages, it can still happen if you are debugging your configuration (e.g. enabling/disabling modules one-by-one).
-----
=> fix(corfu): prevent void-variable error

modules/completion/vertico/config.el
Although it is rare for a user to not enable the :config default module,
enabling/disabling modules one-by-one is common practice for debugging
Doom Emacs. This PR fixes an error that occurs when you have :completion
vertico enabled without enabling :config default.
=> fix(vertico): missing command error in consult 

modules/completion/corfu/config.el
The Corfu documentation has been updated to suggest more modes to ignore with `dabbrev-ignore-buffer-modes`. This commit updates the list of modes to ignore in `cape-dabbrev` to match the documentation.
-----
=> feat(corfu): update dabbrev-ignore-buffer-modes

lisp/doom-packages.el
The doom-package-list is a list of (module :key value ...). To get the plist,  apply cdr first.
=> fix(lib): doom-initialize-core-packages: correct filtering

lisp/cli/packages.el
If the package is local, the local-repo has absolute local file path, and straight-modified-dir will return as it is, which always exists.
Fix it by passing package only to straight-modified-dir.
-----
=> fix(lib): doom-packages-ensure: fix local packages always built

modules/lang/gdscript/config.el
This commit removes the keybinds to add and remove a breakpoint in a gdscript buffer, which were removed from gdscript-mode long ago, and replaces them with one binding to toggle a breakpoint.
Fix: #7254
-----
=> fix(gdscript): replace removed functions with new binding

modules/tools/debugger/config.el
This commit adds gdscript support to `:tool debugger +lsp`, which has been available in dap-mode since a year ago.
-----
=> feat(debugger): add gdscript dap-mode support

modules/config/default/+evil-bindings.el
git-timemachine keybind should not be guarded by the vc-gutter module
-----
=> fix(evil): bind git time machine without vc-gutter

lisp/lib/help.el
Although this is a refactor for normal users of Doom, it is a bugfix for one (I assume) unsupported configuration: when Doom is not running from a git checkout. In that case, `doom--help-package-configs` currently returns Git's error messages. This breaks `doom/help-packages` because it expects each returned line to contain at least one `:` character, so it errors out with `Wrong number of arguments: (file line _match &rest), 2`.
Using ripgrep here should be equivalent for normal users as long as they have not added untracked files not covered by Doom's .gitignore.
Assuming Doom outside of a git checkout is indeed unsupported, please close this PR if you don't want to spend time on it: when I saw the TODO in that function I figured I'd send this in, but it shouldn't be too hard to work …
=> refactor(lib): use ripgrep instead of `git grep`

lisp/doom-cli.el
The auto-generated script has bom characters on my mac. if bin/doom
exits with code 254, it gives me the below error:
`.../doom.123.0.sh: line 1: #!/usr/bin/env: No such file or directory`
Fix: #0000
Ref: #0000
Close: #0000
-----
=> fix(cli): auto-generated script error

modules/lang/org/config.el
fix(org): avoid `(file-exists-p "file://")` on Windows
Emacs bug#70914 handles `file://whatever` incorrectly, potentially
crashing emacs.
Fixed in emacs commit 350ae75f5c1c47a03560e43e8699781c04c9078a:
```
Avoid crashes on MS-Windows due to invalid UNC file names
* src/w32.c (parse_root): Avoid crashes due to invalid (too short)
UNC names, such as "\\".  (Bug#70914)
```
-----
=> Emacs bug 70914 dont lookup file uri with file exists p on windows

modules/editor/word-wrap/autoload.el
There is an edge case where `+word-wrap--major-mode-indent-var` becomes list, not symbol, which is the expected type.
Hence, this PR accounts for that edge case.
Concrete error:
```
(wrong-type-argument symbolp (yaml-indent-offset tab-width))
```
when adjust indenting in yaml file.
-----
=> fix(word-wrap): choose first element if indent-var is list

lisp/doom-modules.el, lisp/lib/autoloads.el
* lisp/lib/autoloads.el(doom-autoloads--scan) Remove invoke `file-truename` of file, keeping symbolic from being converted to a real path.
* lisp/doom-modules.el(doom-module-from-path) Replace `file-in-directory-p` with `string-match` to determine the module to which the file belongs.
Fix: #7821
-----
=> fix: 'doom sync' generates autoload files for symbolic link files

modules/lang/ocaml/README.org, modules/lang/ocaml/config.el, modules/lang/ocaml/packages.el
The PR adds configuration to install `opam-switch-mode` to manage OCaml's opam switches, instead of using a deprecated method in the `tuareg` package. 
-----
I'm not sure if the DNP on modules is still in place, since there's been no activity on the modules repository since the last comment on the DNP list.
=> Switch to using opam-switch-mode for :lang ocaml

modules/emacs/dired/config.el
This is another temporary fix to buy us more time until https://github.com/doomemacs/doomemacs/pull/6760
lands.
It also adds dirvish's `sub-tree` keybindings, mirroring `dired`'s.
Ref: #6760 
-----
=> fix(dired): update dirvish keybindings

modules/editor/fold/autoload/fold.el
This module is also used by non-Evil users. Also,
`evil-vimish-fold/next-fold` and friends just wrap the corresponding vimish-fold functions in `dotimes`, anyway.
=> fix(fold): don't expect evil-vimish-fold

modules/editor/fold/autoload/fold.el
With four folding systems in play, there are numerous ways to create nested folds (eg. hideshow folds inside folded outline headings with `+fold/close-all`). So `+fold/open-rec' needs to be able to open all kinds of folds within the newly unfolded region. It can't stop at unfolding the type of fold it was called on.
=> fix(fold): properly handle recursive folds

modules/editor/fold/autoload/fold.el
Without this change, we need to pass a prefix arg that is one more than the actual fold-level we're trying to achieve; `C-u 2` is equivalent to not passing a digit arg. While this looks intentional, I don't see what purpose it serves.
This change provides saner behavior that matches other commands that handle fold-levels (eg. `org-fold-hide-sublevels`).
=> fix(fold): fold-levels off-by-one

modules/editor/fold/autoload/fold.el
The docstring says that this function will move to the next outline heading, but this had not been implemented.
=> fix(fold): +fold/next: actually support outlines

lisp/lib/fonts.el
Calling `(doom-adjust-font-size 1)` repeatedly would keep increase the font size because an increment is passed.
When loading themes, the `doom-big-font-mode` minor mode gets loaded again therefore it causes the font to get increased.
Fix: #7845
-----
=> fix(lib): reset font size before setting big font mode

lisp/lib/projects.el
If DIR is not a project and does not have root markers, create a transient project instead. This ensures that `project-find-file-in`, and by extension Vertico, is still used in non-project directories instead of falling back to `find-file`
`+vertico/consult-fd-or-find` was removed from `doom-project-find-file` in 1b0af3bfc747, with the intention that Vertico users would instead use Vertico's integration with `project-find-file-in`. However, `project-current` returns `nil` for folders that are not projects and do not have any root markers. This causes `doom-project-find-file` to fallback to `find-file` for commands which use `doom-project-find-file` on directories which aren't necessarily projects, such as `doom/find-file-in-private-config`, `+default/find-in-notes`, and especially …
=> fix(lib): doom-project-find-file: use transient project

modules/tools/magit/packages.el
magit/forge@4adb94d23c8f -> magit/forge@0102834bb7c8 magit/magit@ea0f07e54967 -> magit/magit@9d1f8db507e0
Bump magit-forge and magit; closql has changed its interface, and forge needed to update, so here we are. I've run with this bump and it's all working fine.
/cc https://github.com/magit/forge/commit/fb272bd93bf1793606728d39f1dbf59b64cc002b
-----
=> bump: :tools magit forge

modules/tools/ansible/packages.el
As per emacs-ansible old repo's README https://github.com/k1LoW/emacs-ansible the package moved into gitlab
so I just updated `:pin` in `packages.el` to read from the new source https://gitlab.com/emacs-ansible/emacs-ansible
Before:
After:
-----
=> fix(ansible): update emacs-ansible to fetch from the new repo on gitlab

modules/editor/format/autoload/lsp.el
apheleia runs `+format-lsp-buffer` in a scratch buffer (where lsp is disabled) so checking for an active lsp mode to invoke the right formatter fails. Change `+format--lsp-fn` to run `+format--lsp-fn` in context of main buffer rather than apheleia's scratch buffer so that the lsp mode can be discovered.
-----
=> fix(format): apheleia doesn't invoke lsp formatter

modules/checkers/syntax/config.el, modules/checkers/syntax/packages.el
https://github.com/flycheck/flycheck/commit/02148c6ce7edb0fd0986460db327cc9463939747 -> https://github.com/flycheck/flycheck/commit/e8d1472aeab6ac4e19c8339e6be93e91e878f819
---
[tweak(syntax): use close-circle-outline icon for errors](https://github.com/doomemacs/doomemacs/pull/7942/commits/a7a618786435eacbed966c8a6697bb09dd560787)
The same is used by [doom-modeline][1] to show flycheck errors.
[1]: https://github.com/seagle0128/doom-modeline/blob/1505c13564b83e44d3187611e326a48b742cad3a/doom-modeline-segments.el#L818
=> bump: :syntax flycheck & minor flycheck fixes

modules/lang/scheme/packages.el
geiser-guile is a little broken at the moment. This PR bumps it by just one commit which contains the fix and nothing else. Easy peasy.
-----
-->
=> Tiny bump to fix geiser-guile

modules/ui/vc-gutter/config.el
This is a trivial bug fix for an issue that I believed appeared in 7c5d8641a141777dd48ba52bc1406a534959c724.
I was getting this message on startup: "Symbol’s value as variable is void: diff-hl-disable-on-remote".
I believe it's as simple as checking whether the variable is bound, and considering unbound equivalent to false.
I hope you don't mind that I didn't create an issue to track this -- it felt like a lot of overhead for a tiny fix.
-----
=> fix(vc-gutter): check 'diff-hl-disable-on-remote is bound

modules/lang/org/README.org
The org-yt package has been removed via commit 321f2d2249a5a933e4a4a3ef684e30ce0a7a74cf therefore the custom link type `yt:...` is no longer supported.
Let's update the docs to no longer include it either 😊 
-----
=> docs(org): Remove org-yt custom link type

lisp/cli/sync.el
When running `doom sync --rebuild` after emacs upgrade the user is prompted with "Installed packages must be rebuilt. Do so now?", even though doom was explicitly instructed to rebuild. This PR removes this prompt when the `--rebuild` option is provided
-----
=> tweak(cli): rebuild silently if --rebuild is set

modules/ui/workspaces/autoload/workspaces.el
It seems that `persp-save-to-file-by-names` has an optional `keep-others` argument which I believe is the default behaviour
Fix: #0000
Ref: #0000
Close: #0000
-----
=> Adding a single character so other workspaces could persist automatically

modules/lang/latex/config.el
enable `lsp` with `LaTeX-mode` (new AUCTeX (version >= 14) naming conventions).
See AUCTeX changes here: https://github.com/emacs-straight/auctex/blob/master/NEWS.org#1401---2024-02-08
-----
=> fix(latex): update latex module to new AUCTeX naming conventions

modules/lang/go/README.org, modules/lang/go/config.el, modules/lang/go/doctor.el, modules/lang/go/packages.el
BREAKING CHANGE: Removes go-guru from the Go module. It has been deprecated upstream in favor of gopls, the official Go LSP server.
Close: #7995
Ref: golang/go/issues/65880
**Note**: I have discarded the [bump](https://github.com/doomemacs/doomemacs/issues/7995#issuecomment-2299971269) to `go-mode.el` because that introduces a [deprecation](https://github.com/dominikh/go-mode.el/commit/166dfb1e090233c4609a50c2ec9f57f113c1da72) that requires more updates to the Go module.
I'll be happy to tackle those, as well as other issues I've recently noticed, once this PR is accepted.
Being my first non-trivial contribution, I didn't want to mix too much stuff, for the sake of clarity.
=> refactor!(go): remove go-guru

modules/lang/go/config.el
Trying to execute `go-remove-unused-imports` renders this error message in the minibuffer:
‘go-remove-unused-imports’ is an obsolete command (as of 1.7.0); set ‘gofmt-command’ to goimports instead, or use LSP and gopls’s "Organize Imports" code action.
Ref: dominikh/go-mode.el@166dfb1e0902
-----
=> fix(go): remove bind to deprecated function

modules/completion/vertico/config.el
The original implementation of `+vertico-orderless-dispatch` match pattern by prefix and suffix in pairs. In that case, '=&&' will go for branch `(string-suffix-p "&" pattern)`, not `(string-prefix-p "=" pattern)`, which fail to filter literal '&&'.
We probably should match all prefixes first, then all suffixes. Just like orderless does.
Ref: https://github.com/oantolin/orderless/blob/178b0c55f2cb49f27cd972f731ea45e5d3aea262/orderless.el#L159
-----
=> fix(vertico): orderless filtering

modules/tools/tree-sitter/packages.el
Bump  evil-textobj-tree-sitter to latest
⚠️ ~~Beware that while this fixes Typescript grammar, **it will break haskell, php and r textobj queries**~~
~~See https://github.com/meain/evil-textobj-tree-sitter/issues/117#issuecomment-2302112038~~
=> All good now
Fix: #8006 
-----
=> bump: evil-textobj-tree-sitter

modules/term/vterm/config.el
when using vterm and accidently opening nano (wrong $EDITOR set and using git via cli) closing nano is not possible because sending C-x is not possible.
not even in `<insert-state>`
With `C-q` mapped to `vterm-send-next-key` it's possible to send it via `C-q C-x`
=> tweak(vterm): vterm-send-next-key mapped to C-q

modules/lang/clojure/config.el
We're currently discarding all evil-collection bindings on `cider--debug-mode`. Given that `j` is bound to a particularly disruptive and non-cancellable command, this brings some friction to evil users.
This commit adds those bindings back under `evil +everywhere` and creates some missing debug commands recently added.
The in-buffer and minibuffer displayed keybindings were adjusted to match, but not easy-menu's.
Ref: doomemacs/doomemacs#4627
-----
=> fix(clojure): leverage evil-collection-cider

modules/completion/corfu/README.org, modules/completion/corfu/config.el, modules/config/default/config.el
Adds a new value of `+corfu-want-ret-to-confirm` to cover the case where the user wants to select the candidate as well as perform the normal behavior of RET.
Also, the logic for RET behavior has been refactored for clarity, and the variable's documentation has been clarified a little.
-----
=> feat(corfu): `both` option for RET behavior

modules/email/mu4e/README.org
Recently, the Emacs package `mu4e` has been [moved into a separate derivation output](https://github.com/NixOS/nixpkgs/commit/2081e7e07de42d7e991d863ab8ec72ce3718ae12) (which broke my existing setup after a system upgrade). Now you need both the `mu` package (installing the program) as well as its `mu4e` output, which adds the Emacs package to the system.
I've updated the docs accordingly, but since the change is very recent, I've added disclaimer explaining that only newer versions of `nixpkgs` need it.
-----
=> docs(mu4e): update NixOS installation instructions

modules/ui/nav-flash/config.el
Changing workspace is big motion so we should blink the cursor. We can not use `+nav-flash-blink-cursor-maybe-h` as the point is not yet in the correct buffer when the hook is triggered.
-----
=> feat(nav-flash): blink on workspace change

modules/emacs/dired/autoload.el
`<leader> o p` is bound to `+dired/dirvish-side-and-follow`, but the command was previously called `+dired/dirvish-side-or-follow` instead.
-----
=> fix(dired): typo in command name

modules/tools/lsp/+lsp.el
Current workaround for https://github.com/emacs-lsp/lsp-mode/issues/3577 is disabling terraform lsp even for terraform users, because of incorrect section.
Ref: #7713
-----
=> fix(lsp): lsp-terraform removal condition

modules/emacs/dired/autoload.el
This prevents getting load errors when calling the command `+dired/dirvish-side-and-follow` before `dirvish` has been loaded.
The errors occur when calling `dirvish-side--session-visible-p`:
>let: Symbol’s function definition is void: dirvish-side--session-visible-p
----
=> fix(dired): require needed for `dirvish-side'

modules/editor/fold/autoload/fold.el, modules/editor/fold/config.el
Some modes are not supported by `hs-minor-mode`, but can still support some of the `+fold/` commands. For example, `pdf-outline-minor-mode` recognizes the same commands as `outline-minor-mode`, but `hs-minor-mode` is not applicable. In cases like these, we shouldn't try to enable `hs-minor-mode`, as this will produce an error that will terminate the command.
-----
=> fix(fold): avoid Hideshow-not-supported error

modules/ui/ligatures/config.el
Otherwise, `prettify-symbols-alist` will be set to a list whose first element is the mode name, a symbol. That makes `prettify-symbols-alist` an invalid alist, so when `prettify-symbols-mode` is enabled, there's a type error in `prettify-symbols--make-keywords`.
Amend: c07f359d648a
-----
=> fix(ligatures): use `alist-get` instead of `assq`

modules/lang/emacs-lisp/autoload.el
As per the description in 6671adc68, this module should always use Helpful's functions as long as Helpful is available (ie. not explicitly disabled by the user in packages.el). The remapping of `describe-symbol` is irrelevant here - the user might prefer to rebind `C-h C-o` to `describe-symbol` (as `helpful-symbol` cannot look up types), but that doesn't necessarily mean they want this module not to use it.
=> fix(emacs-lisp): always try Helpful for doc lookup

modules/lang/clojure/config.el
When I call (doom/reload) there is an error like:
```
⛔ Warning (initialization): An error occurred while booting Doom Emacs:
Error in a Doom module: modules/lang/clojure/config.el, (wrong-type-argument consp nil)
```
There is small bug with replacing param which doesn't handle case where param already replaced
=> fix(clojure): type error evilifying cider-debug keys

modules/lang/python/config.el
https://github.com/doomemacs/doomemacs/commit/1fa1eba5ac38d654a0763282f3ddd631e873c273 pined `python-pytest` to `dcdaec6fe203f08bda0f5ee1931370dfd075a4ff` which included [this change](https://github.com/wbolster/emacs-python-pytest/pull/75/files#diff-ec3a68c754a7f498ad96a584a259278a8827ede06e61b45dc43176e1f2dd92f5R294) that renamed:
* `python-pytest-function-dwim` -> `python-pytest-run-def-or-class-at-point`
* `python-pytest-function-dwim` -> `python-pytest-run-def-or-class-at-point-dwim`
=> fix(python): renamed python-pytest commands

modules/lang/ruby/config.el
Replace the obsolete macro `featurep!` with `modulep!`.
Fix: N/A
Ref: N/A
Close: N/A
-----
=> fix(ruby): replace the obsolete macro `featurep!` with `modulep!`

modules/email/mu4e/config.el
Toggle behavior:
The `(integerp current-prefix-arg)` check didn't appropriately catch `C-u`/`SPC u` prefixes, where `current-prefix-arg` typically is `(4)`. This attempts to use `(prefix-numeric-value current-prefix-arg)` instead to normalize these cases.
Variable naming:
I'm not sure if this was supposed to continue to be called `+mu4e-compose-org-msg-toggle-next` or if the rename to private `+mu4e--compose-org-msg-toggle-next` was intentional and the usage wasn't updated accordingly. I see the `mu4e` README still mentions it, so I would guess the former and this was a typo.
Ref: #8073
Relevant change: https://github.com/doomemacs/doomemacs/commit/a78237cc01adeabe0fd4a83ff8b8aca7cb269482#diff-e4ae34fcacdffca06aea528ca819a5b6b2332032b20005392503b6ac0e9d04aaR445
-----
=> fix(mu4e): org-msg: toggle behavior

modules/editor/fold/autoload/fold.el
This function may be called by `+fold--ensure-hideshow-mode-a`, before autoload/fold.el has been loaded.
Amend: #8067
-----
=> fix(fold): autoload `+fold--ensure-hideshow-mode`

modules/lang/factor/packages.el
factor/fuel@31dc1a386b06 -> factor/fuel@6d0e98494f89
Melpa's upstream and recipe for `fuel` changed (see https://github.com/melpa/melpa/commit/4a3d7cdefacce68fcc53e9428cb2a9a5ec1bf978): previously it was pulled from a subdirectory of the main `factor` repository, it now has its own repository. Applying Doom's previous pin to the new recipe does not seem to work correctly, so update.
-----
=> bump: :lang factor

modules/lang/agda/config.el
With version 2.7.0 of Agda and the introduction of mimer (instead of agsy) for agda auto mode, the auto mode call changed in agda mode emacs setting: https://github.com/agda/agda/blob/8512b9cd91761e7366291e111ada5141c0fad23a/src/data/emacs-mode/agda2-mode.el#L235
this change in Agda's agda-mode breaks the current doomemacs setting and doomemacs call for agda auto mode does not work. The proposed PR fixes this issue.
Fix: #0000
Ref: #0000
Close: #0000
-----
=> Fix agda auto functionality reference to mimer

modules/tools/eval/autoload/repl.el
Using `+eval/open-repl-other-window` in a window that isn't associated with a given repl (for example, the starting screen), I would get duplicate entries in the prompt, because cl-delete-duplicates compares with `eql` by default.
Another issue that I see that's similar is that the different python repls (`+python/open-jupyter-repl`, `+python/open-repl`) are listed under the same name in the prompt. This pr doesn't fix that, however.
=> fix(eval): remove duplicate REPL entries

early-init.el
Recent changes to early-init.el accidentally moved some arguments intended for `load` to an inner `let`, which means only the last argument gets passed to `load`. This results in
```
> Debugger entered--Lisp error: (wrong-type-argument stringp nosuffix)
>   load(nosuffix)
>   (or (load (let ((windows? (memq system-type '(ms-dos windows-nt cygwin)))) (expand-file-name...
```
when starting Doom (or running a doomscript) with DOOMPROFILE set.
Move these arguments back out of the `let`.
Amend: 9ae7aa1122781c8b4353fad049bc7b5cea1b0638
-----
=> fix: early-init with DOOMPROFILE set

lisp/lib/autoloads.el
This typo is responsible of a startup error `delayed-warnings-hooks void-variable warning-minimum-log-level` because of common-lisp module
Fix: #8144 
-----
=> fix(common-lisp): typo file instead of pfile

modules/tools/eval/autoload/repl.el
Using `+eval/send-region-to-repl` makes the python repl add too many newlines and causes double prompts.
The `+eval/send-region-to-repl` function takes a region, formats it, and adds a newline at the end of it. Then each line is fed to the repl one by one, i.e. each line is pasted into the repl buffer and submitted by simulating a "RET" key press. Because there is a newline added at the end of the region and "RET" is simulated, there are essentially two newlines being sent to the repl with the last line of the region. This double newline causes the odd spacing and double prompting.
The solution is to not concatenate a newline at the end of the region. This prevents the double newline on the last line sent to the repl.
https://github.com/user-attachments/assets/12234c82-7452-4209-ab33-cc6f0 …
=> fix(tools): double prompt when region sent to repl

modules/editor/file-templates/config.el
Factor template application code into command file-templates-apply. This allows it to be invoked by the user.
Personally, I find file templates very annoying, and 9/10 times I would end up just deleting the template boilerplate, so I disabled it. However, in some cases I might want to use it. Rather than having to reconfigure whether templates are enabled and re-create the file, we simply pull the couple of lines where the template is actually applied out into a function and add `(interactive)`. Now I can just `M-x file-templates-apply` in the buffer where I want to use the templates.
-----
=> feat(file-templates): add apply method

modules/lang/python/autoload/python.el
+python-executable-find cannot find `ipython` since `/bin/python` is hardcoded instead of using the parameter that tells which executable we are finding. Therefore this commit fix `+python/open-ipython-repl`
=> fix(python): +python-executable-find ipython

modules/lang/cc/autoload.el
opencl-mode source code was updated, renaming it to `opencl-c-mode`, as can be confirmed on the pinned commit it:
```el
(package! opencl-mode :pin "204d5d9e0f5cb2cbe810f2933230eb08fe2c7695")
```
https://github.com/salmanebah/opencl-mode/commit/204d5d9e0f5cb2cbe810f2933230eb08fe2c7695
So opening *.cl files the expected mode does not get applied. 
Also mentioned in the discord help
https://discord.com/channels/406534637242810369/1312189226774954105
-----
=> fix(cc): replace opencl-mode with opencl-c-mode

modules/ui/modeline/config.el
It looks like CR was only the default line ending type for Mac in Mac OS 9 and earlier, and it's now quite uncommon:
- https://retrocomputing.stackexchange.com/a/21906
- https://superuser.com/a/439443
-----
=> fix(modeline): change macOS default EOL type to LF

modules/email/notmuch/autoload.el
The `-a` option will cause afew to process all the user's mail. If the user has a lot of mail, this will take an extremely long time, every time. The expected usage is to process only mail that has been tagged 'new' by notmuch (which requires the [correct
setup](https://github.com/afewmail/afew/blob/master/docs/quickstart.rst)).
-----
=> fix(notmuch): afew: process only new mail

modules/ui/workspaces/autoload/workspaces.el
feat: Switches workspace left and right more than one at a time.
scope: For doomemacs/doomemacs
Added optional number to switch the workspace left or right by a count
Added optional number to `+workspace/switch-left`(and right) to be able
to jump more than one workspace at a time because
`+workspace:switch-next`(and previous) jumps directly to the numbered
workspace not the next 'nth' workspace from current one. I find this
more intuitive (for vim/evil though) and easier to add here where
it (hopefully) won't mess with anybodies config rather than breaking
`+workspace:switch-next' (and previous).
FILENAME: /modules/ui/workspaces/autoload/workspace.el
-----
=> Update +workspce/switch-left[right] in workspaces.el

modules/completion/vertico/config.el
`consult-man` is not a good drop-in replacement for `man`. `consult-man` searches man pages and descriptions (like the apropos program). The original `man` function lets the user pick a man page from the list of man pages.
-----
=> tweak(vertico): remove consult-man remapping

modules/editor/fold/autoload/fold.el
`point-min` and `point-max` were used in some places in `+fold--open-rec-between` instead of `beg` and `end`. This caused `+fold/open-rec` to open all folds rather than only the one the curser is on.
-----
=> fix(fold): fix recursive unfolding

modules/tools/ansible/config.el
galaxy metadata file is now the main component of Ansibe collections, this should help with #1139 (collections with playbooks only, custom layouts).
Fix: #1139
-----
=> fix(ansible): check for metadata/config file

lisp/doom-editor.el
When `nconc` was changed to `add-to-list`, that made this fallback rule be added to the beginning of `auto-mode-alist` instead of the end.
=> fix: `auto-mode-alist`: make `/*rc` rule low-priority

lisp/lib/projects.el
`project-current-directory-override` takes a string, not a `t`. [It overrides `default-directory`](https://github.com/emacs-mirror/emacs/blob/6c1c3120b98652de149ee9d8c241cd3636755171/lisp/progmodes/project.el#L196-L198) which is always a string.
This was causing a crash for me when using `doom/find-file-in-private-config` from a buffer outside a project:
```
Debugger entered--Lisp error: (wrong-type-argument stringp t)
file-remote-p(t)
projectile-project-root(t)
project-projectile(t)
run-hook-with-args-until-success(project-projectile t)
project--find-in-directory(t)
[...lots, available on request, but it doesn't seem relevant...]
doom-project-find-file("/Users/user/.doom.d/")
doom/find-file-in-private-config()
funcall-interactively(doom/find-file-in-private-config) …
```
=> fix: project-current-directory-override takes a directory

modules/tools/debugger/config.el
Fixed name of rustic mode in the +debugger--dap-alist which was preventing debugger from being configured correctly for rust in DAP mode
Fix: #8245 
-----
=> fix: name of rustic mode in the +debugger--dap-alist

lisp/doom-straight.el
This reverts a workaround for straight that is no longer necessary because it has been applied upstream and we've bumped the package since.
For some reason I don't understand, this reproducibly fixes a reoccurrence of the original problem for me: Before this commit, some files of the citar package were not byte-compiled. After this commit,the problem is gone.
This effectively reverts 54a084fed7e1, though it's not a reverting commit in strict sense because the code has been moved to a different file.
Revert: 54a084fed7e1
Ref: d80c5e51159f
Ref: #7707
Ref: radian-software/straight.el#1132
Ref: https://discourse.doomemacs.org/t/is-it-expected-that-doom-sync-does-not-byte-compile-native-compile-some-files/4946
-----
=> fix(cli): some package files not being byte-compiled (2nd take)

modules/lang/emacs-lisp/autoload.el
Sometimes elisp files specify a local outline-regexp which does not match any groups so with this PR, outline-level returns a default value of 0 instead of an error. As an example, take `gptel-rewrite.el`. 
This is part of my goal of reducing the amount of errors I see while using Emacs to as close to 0 as possible. I would rather the highlight be incorrect than see an error, because errors distract us from working on things that are more important to us.
=> fix(emacs-lisp): handle malformed outline-regexp

modules/lang/org/config.el
I do not see any evidence of a [tab] binding in `outline-mode-cycle-map` in Emacs29, Emacs30, nor Emacs31. Moreover, this keybinding is overriding our TAB keybinding in GUI Emacs, so YaSnippets are not being expanded.
This references "yasnippet in org-mode. Fix TAB for jumping to $1 and $2" from the Discord server.
Also references
conversations spread around other issues & PRs.
=> fix(org): allow tab to expand yasnippets in org

modules/tools/lookup/autoload/lookup.el
Without this dumb-jump uses that older deprecated style of completion either via the popup library or completing read, but it didn't conform as nicely with the all the xref goodies like line numbers, file separators, consult previewing etc..
This (albeit a little hacky) way of temporarily setting the xref-backend-functions to be dumb jump after lsp-mode completion fails, works quite nicely. 
Fix: #0000
Ref: #0000
Close: #0000
-----
=> fix: use dumb-jump xref instead of dumb-jump-go

modules/tools/magit/config.el
I noticed that recently the default option for [showing/hiding the transient menu](https://github.com/magit/transient/blob/32a7e256aab281bada5db8569e0871c8c3ad2115/CHANGELOG#v080----2024-12-06) in transient changed
> While the minibuffer is in use, the menu window is now hidden by default
It seems like this conflicts with `transient-display-buffer-action` being set to `display-buffer-below-selected` for some reason.
This PR restores the old default behavior of keeping the transient menu visible while the minibuffer is active, resolving the unexpected window splitting behavior.
Fix: #8194 
Ref: https://github.com/doomemacs/doomemacs/issues/8194#issuecomment-2645868695
-----
Solves #8194
=> fix: restore previous default transient menu visibility during minibuffer use

modules/lang/elixir/config.el
LSP will now correctly auto start when you have both +lsp and +tree-sitter flags on elixir module.
As this was easy fix, I'm creating PR without creating a bug report.
-----
=> fix(elixir): start lsp when ts and lsp are enabled

lisp/doom-lib.el
Hi. I'm thinking we can avoid using `pp` in `setq-hook!` and to avoid loading `pp` and use the faster `prin1-to-string` since it's rare that people look at the form `setq-hook!` outputs anyways.
=> perf: do not load pp at startup

modules/completion/vertico/autoload/vertico.el
Fix display issue on vertico with embark-act-all
-----
Before
After:
=> fix(vertico): fix display with embark-act-all 

lisp/lib/packages.el
Fixes package unavailability based on https://github.com/doomemacs/doomemacs/issues/7171#issuecomment-2574991205 's idea.
With the recent Emacs release it feels that more people are upgrading and facing this issue. Tested locally.
Fix: #7171 
Ref: https://github.com/doomemacs/doomemacs/pull/8271
Close: #7171
Based on my interpretation of `straight-vc-git-default-protocol` then this should be better than #8271.
-----
=> fix(packages): use mirror for nongnu-elpa

modules/lang/kotlin/packages.el
When checking module requirements for =flycheck-kotlin= there is a typo in the =:tools= used, leading to package not getting installed.
-----
=> fix: correct typo in module check for flycheck-kotlin

lisp/doom-projects.el, lisp/packages.el
Fixes: #8288 
There have been changes to Helm that make it no longer compatible with the version of projectile we are using. There have been many changes to the caching architecture of Projectile. As such, some of the cache hacks we are currently using are obsolete. Now projectile uses a per-project cache file. 
Otherwise, probably the projectile prefix can be looked at again and improved.
=> bump: :doom projectile

modules/completion/vertico/config.el
Fix this error when using "Find file":
Error in post-command-hook (vertico--exhibit):
(error "Invalid completion style +vertico-basic-remote")
Remove undefined style completion type +vertico-basic-remote Relative to this comment:
URL_TOO_LONG /issues/7491#issuecomment-2012682178
* modules/completion/vertico/config.el : remove `+vertico-basic-remote` use as it's not defined.
Fix: #7491
Fix: #7491
-----
=> fix(:completion): Remove undefined completion

modules/completion/corfu/config.el
After setting +corfu-want-minibuffer-completion to t, I noticed that it Corfu was still being enabled in Consult when finding files. This change fixes that by ensuring that Corfu gets disabled in the minibuffer whenever another completion framework is active.
-----
=> fix(corfu): fix default minibuffer completion

modules/lang/latex/+viewers.el, modules/lang/latex/README.org, modules/lang/latex/autoload.el, modules/lang/latex/config.el, modules/lang/latex/packages.el
Since latex-preview-pane is unmaintained, replace it with auctex-cont-latexmk.el and a simple function to compile the document and open the default viewer. It can potentially fix #5249 with a single extra line to start the correlation server, but at minimum it leaves that issue irrelevant since it removes latex-preview-pane.
Fix: #3128
-----
=> refactor(latex): replace latex-preview-pane w/ auctex-cont-latexmk

modules/lang/org/contrib/pretty.el
Small fix on top of 9dfcb5401f5655168bb90fcaec5149e8c159f535 to make the check for `org-indent-mode` more robust: because Org only requires `org-indent` when needed, one cannot assume that `org-indent-mode` has been declared.
-----
=> fix(org): do not rely on org-indent being loaded

modules/editor/evil/config.el
Zero matches on `M-x evil-ex-search-next` and `M-x evil-ex-search-previous` persists and cannot be escaped when pressing `<escape>` or `C-g`; anzu mode's state (`"0/0"`) will persist in the modeline. The pr adds an extra check into `doom-escape-hook` when getting zero evil-ex-search matches.
Reproducing the problem:
1. `M-x evil-ex-search-word-forward` on a symbol/word to start an evil-ex-search. The last search will be continued/resumed when invoking `M-x evil-ex-search-next` and `M-x evil-ex-search-previous`.
2. Change into another buffer where the last searched word doesn't exist. Invoke `M-x evil-ex-search-next` in this new buffer. This will create a Zero match search state which currently cannot be escaped with `<escape>` or `C-g`.
-----
=> fix(evil): clear modeline search highlights on zero matches

modules/input/bidi/config.el
In function `+bidi--set-font`, the character set was incorrectly hardcoded to `'hebrew` instead of using the provided character set `name` parameter. This caused `+bidi-arabic-font` to have no effect when set.
Additionally, setting the scale throws an error:
string-match-p: Wrong type argument: stringp, DejaVu\ Sans
Converting the font family property to string fixed the issue.
-----
=> fix(bidi): set the font for Arabic characters

modules/tools/magit/config.el
Without this PR, Forge will try to transmit progress updates to the modeline. However,  these progress updates are tied to the magit status buffer so after you kill it, they will stop being relayed even if you run `magit-status` again. 
With this PR, the Forge status updates are relayed through `message` instead when you fetch all topics in a repository, say with `SPC g g @ f f` in `~/.config/emacs`.
To reproduce this issue, do  `SPC g g @ f f` in `~/.config/emacs`, then kill the magit status buffer. When you run magit-status again, the status updates of the Forge pull operation will no longer show up in the modeline and `forge--mode-line-buffer` will say KILLED BUFFER.
Refer to the discussions on https://github.com/magit/forge/pull/744 and https://github.com/magit/forge/discussions/633 …
=> fix(magit): use messages instead of modeline

modules/term/vterm/autoload.el
Previously +vterm/toggle would only set +vterm--id if the vterm popup window already existed.
This happened because switching major modes removes all buffer-local variables.
-----
=> fix(vterm): always set +vterm--id in +vterm/toggle

modules/emacs/vc/config.el
This PR fixes errors that happen when invoking `+vc/browse-at-remote` from git-timemachine buffers.
The function `browse-at-remote--get-url-from-remote` returns a plist. Previously, these plist values were not being read correctly. The first commit fixes this.
Previously, having an inactive region/unset mark in a git-timemachine buffer and invoking `+vc/browse-at-remote` would return an error. Also line selection and highlighting at remote remained inconsistent with the behavior seen when browsing to remote from non git-timemachine buffers. This PR (second commit) fixes these issues.
-----
=> fix(vc): browse to remote from git-timemachine revisions

modules/tools/terraform/config.el
Both `fmt` and `destroy` are defined on `f`. In my case, this mean that which-key hinted `fmt`, but actually ran `destroy`. This mapping looks like a typo, and I have updated it to use `d`, matching the convention of using the first letter of the command.
=> fix(terraform): fix incorrect mapping

modules/lang/cc/README.org
Improve docs for cc to specify that bear needs `--` before the command (as specified in its [README](https://github.com/rizsotto/Bear/blob/master/README.md)). Otherwise it doesn't work (tested with version 3.1.5)
-----
=> docs(cc): Bear requires `--` for command

modules/lang/coq/config.el
The recent fixes for corfu integration in 61f69ca reference `company-coq` to access the Company backend. This does not exist and causes the following error on pretty much any text insert keystroke
> Error running timer ‘corfu--auto-complete-deferred’: (void-function company-coq)
The (main) backend appears to be called `company-coq-master-backend`, so I've updated the reference to use this instead. With this fix, completion works correctly and I see completion candidates in my UI
-----
=> fix(coq): void-function company-coq

modules/ui/workspaces/autoload/workspaces.el
When Emacs is started as a daemon and no frames exist, `emacsclient -c` should simply switch to the main workspace. However, before `+workspaces-associate-frame-fn` is called, the new frame is already added to the frame list, which causes `persp-frame-list-without-daemon` to always return a non-empty list. A new workspace will be created instead of switching to the main one.
Before:
``` bash
emacs --daemon
emacsclient --eval "(+workspace-list-names)"
emacsclient -c --eval "(+workspace-list-names)"
```
Affter:
``` bash
emacsclient -c --eval "(+workspace-list-names)"
```
-----
=> fix(workspaces): avoid duplicate workspace creation when no frame exists

modules/ui/hl-todo/README.org
Commit 0893edefae1fe548c7e1112038c6e50b9e35bd26 removed magit-todos and the "SPC p t" keybinding. The documentation of hl-todo does not reflect this change.
This commit removes said keybinding from hl-todos documentation.
REF: 0893edefae1fe548c7e1112038c6e50b9e35bd26
-----
=> docs(hl-todo): Remove removed keybinding

modules/tools/magit/config.el
The magit documentation on https://magit.vc/manual/magit/Git-Executable.html 
says the optimization is already done by default on windows and macOS.
Also, this hook breaks the ellipsis feature in magit-process, so removing it fixes it.
Fix: https://discourse.doomemacs.org/t/magit-process-doesnt-show-ellipsis-for-magit-git-global-arguments/5103/2
Before:
After:
-----
=> fix(magit): Remove +magit-optimize-process-calls-h

modules/emacs/eww/autoload.el, modules/emacs/eww/config.el
1. Add jump-to-heading functionality for EWW buffers (replaces jump-to-url in `imenu`)
The new functions are based on existing `eww--capture-url-on-page` and `+eww/jump-to-url-on-page`. However, I took a different approach and used alists to hide the position/coordinates from the `completing-read`. Also, unlike `+eww/jump-to-url-on-page`, we don't give the user an option of limiting the scope to a region or visible portion of the buffer. `+eww/jump-to-heading-on-page` always prompts based on the entire buffer.
Examples:
1. `<h1>H1</h1>`
- "H1"
3. `<h1>H1</h1><h2>H2</h2>`
- "H1"
- "H1/h2"
4. `<h1>H1</h1><h2>H2</h2><h3>H3</h3>`
- "H1"
- "H1/H2"
- "H1/H2/H3"
5. `<h1>H1-1</h1><h2>H2</h2><h1>H1-2</h1>`
- "H1-1"
- "H1-1/H2"
- "H1-2"
Gaps in the hierarchy (for example a `<h2>` followed by an …
=> feat(eww): Add jump-to-heading in EWW

modules/lang/latex/config.el
This avoids inserting braces when you type "a_", so you end up typing "a_i" instead of "a_{i}".
The official LaTeX manual says that braces are correct, but it doesn't matter for many cases, e.g., when the sub/superscript is just a single token like "i". It's simply a matter of taste in these cases.
- Frank Mittelbach, a LaTeX maintainer, says that he types "a_i": https://tex.stackexchange.com/questions/82329/how-bad-for-tex-is-omitting-braces-even-if-the-result-is-the-same#comment176261_82331
- David Carlisle, another LaTeX maintainer, says that a_i "arguably improves the look of the source code": https://tex.stackexchange.com/a/82337
- Joseph Wright, yet another LaTeX maintainer, says that he "would always use braces here, so favour a_{i}": https://tex.stackexchange.com/a/1929
And I …
=> tweak(latex): don't insert braces after sub/superscript

modules/lang/markdown/doctor.el
Note that we are pinned to the latest release of `seagle0128/grip-mode`, which supports¹ alternate grip-like programs, namely `mdopen` and `go-grip`. Although a specific one can be configured, `grip-mode` will try and load any of the three (the two mentioned plus `grip`).
I’ve added them in the same order that `grip-mode` searches for them².
¹: https://github.com/seagle0128/grip-mode?tab=readme-ov-file#alternative-markdown-preview-without-accessing-github-api
²: https://github.com/seagle0128/grip-mode/blob/96a927dce69d7607b981d7754cf8b415ebf9d6a8/grip-mode.el#L177-L179
-----
=> tweak(markdown): doctor: allow for alternate grips

modules/editor/fold/autoload/fold.el
Replace direct calls to `hs-looking-at-block-start-p` and `hs-find-block-beginning` with their corresponding function variables to ensure compatibility with hideshow mode's configurable function handling.
These function variables are set in [`treesit` in Emacs 31][1]. It broke fold because `hs-block-start-regexp` is set to `nil` explicitly by treesit overrides.
The default for `hs-looking-at-block-start-p-func` and `hs-find-block-beginning-func` are same as what was being called before.
[1]: https://github.com/emacs-mirror/emacs/commit/2e3b085d447bc2cd1a0e779145be9cab9a15d7af
=> fix(fold): Use function variables over direct func

modules/os/macos/autoload.el
Use the full path for the MacOS "open" command.
Using plain "open" will conflict with nushell's "open" command. Use the full path for open to make it working.
=> tweak(macos): use full path for open

modules/lang/latex/config.el
Sorry, I had to skip the linter again. It claims that "latex" is not a valid scope. (Or is anything wrong with my commit messages?!) Perhaps a bug introduced by https://github.com/doomemacs/doomemacs/commit/ed9190ef005829c7a2331e12fb36207794c5ad75?
---
This disables smartparens pairs for quotation marks, which are broken.
Before this commit, typing a LaTeX comment
```
% "Foo"
```
inserted
```
% ''Foo`|`''
```
where `|` indicates the position of the cursor (wtf!).
Let's better AucTeX's support for quotation marks for now and accept
that the user won't get automatic insertions of closing quotation marks.
This also removes a wrong comment mentioning the non-existing variable
`+latex-enable-plain-double-quotes'.
=> fix(latex): disable smartparens pairs handled by AucTeX

lisp/doom-editor.el, modules/ui/workspaces/packages.el
Bad-ptr/persp-mode.el@82680795b3dbb9f9fb023b1754902f38519d9875 fixes a nasty problem where jumping to a destination of a new eglot workspace corrupts the current buffer to be read-only and renamed.
When jumping to definition in a different Rust crate using rustic & eglot, the buffer I'm jumping from becomes uneditable and its name becomes `*EGLOT (axum-core-0.5.2/(rustic-mode)) stderr*` (depending on the destination).
Since persp-mode hooks `kill-buffer`, the `jsonrpc` subprocess stderr buffer mechanism gets corrupted:
`jsonrpc.el`:
```lisp
(cl-defmethod initialize-instance :after ...
(let* ((stderr-buffer-name (format "*%s stderr*" name))
(stderr-buffer (jsonrpc--forwarding-buffer stderr-buffer-name "[stderr] " conn))
(hidden-name (concat " " stderr-buffer-name)))
(setq proc (if …
```
=> fix persp-mode eglot workspace corruption when jumping to definition in new workspace

modules/lang/erlang/config.el
Missing `:url` in the config caused error during the initialization, if Erlang module with `+tree-sitter` was turned on in `init.el`.
-----
=> fix(erlang): correct tree-sitter config

lisp/lib/sandbox.el
Configure tree-sitter extra load path for vanilla versions of the sandbox.  This allows using installed tree-sitter grammar libraries if a tree-sitter major mode is used in the vanilla environment without having to manually configure `treesit-extra-load-path`.
-----
=> fix(lib): doom/sandbox: tree-sitter extra load path

modules/lang/ada/README.org, modules/lang/ada/config.el, modules/lang/ada/packages.el
GNAT Project modes (`gpr-mode` and `gpr-ts-mode`) exist to handle .gpr files. These modes are now used instead of the Ada major mode.
Lines may need to be re-indented when RET is pressed.  This is to handle cases of incomplete syntax and ambiguity in what may be entered when an empty line is initially indented.  Re-indenting after text has been entered corrects incorrectly guessed initial indentation.  To accommodate this scenario, RET is remapped to `reindent-then-newline-and-indent`.
Also updates documentation to reflect these changes.
-----
=> fix(ada): use gpr-specific modes and indent properly
