doomemacs/doomemacs

init.example.el, modules/lang/elm/config.el, modules/lang/elm/packages.el
Hi @hlissner 
Would you be interested in user contributions? I made this tiny elm module, it was very easy thanks to your organization!
I'm not an e-lisper, so my code might be clunky...
=> lang/elm: first attempt

init.example.el, modules/lang/purescript/config.el, modules/lang/purescript/packages.el
Also of interest, a PureScript attempt. Let me know if you don't like the syntax I use in `config.el`
=> lang/purescript: first attempt

init.example.el, modules/private/hlissner/+bindings.el, modules/ui/evil-goggles/README.org, modules/ui/evil-goggles/autoload.el, modules/ui/evil-goggles/config.el, modules/ui/evil-goggles/packages.el
Added evil-goggles per #92 following the structure and location of nav-flash. I can move it to a different location if we decide it should live somewhere else.
Thanks!
=> added module ui/evil-goggles

init.example.el, modules/lang/hy/config.el, modules/lang/hy/packages.el
=> addition of Hy (hylang.org)

modules/lang/elixir/config.el
=> support exs extensions

modules/lang/emacs-lisp/config.el, modules/lang/emacs-lisp/packages.el
I started writing some elisp again and I'm getting back to my old Elisp setup.
If it's getting too much just tell me. :-)
=> Add: lang/emacs-lisp: macrostep

modules/lang/emacs-lisp/config.el, modules/lang/emacs-lisp/packages.el
Useful in combination of ert-runner for tests.
I use it in combination with firestarter but it's not quite there yet as a well integrated system so I'm not doing a PR for that yet.
=> Add: lang/emacs-lisp: overseer initial commit

init.example.el, modules/tools/prodigy/config.el, modules/tools/prodigy/packages.el
I implemented this in my config and prodigy seems neat in general:
https://martinralbrecht.wordpress.com/2016/05/30/handling-email-with-emacs/
=> Add tools/prodigy

init.example.el, modules/feature/hydra/autoload/evil.el, modules/feature/hydra/autoload/hydras.el, modules/feature/hydra/config.el, modules/feature/hydra/packages.el, modules/feature/version-control/+git.el, modules/feature/version-control/autoload.el, modules/feature/version-control/config.el
This is a better show case than what I had up before.
=> Hydra feature + smerge + git-gutter hydra

modules/tools/rgb/config.el, modules/tools/rgb/packages.el
Improved upon by feature/hydra
issue: #126
=> Add: tools/rgb: initial commit (rainbow-mode + kurecolor)

modules/completion/company/config.el
How about disabling company for gud-mode too?
=> disable company for gud-mode

modules/feature/jump/autoload/jump.el
Targeting https://github.com/hlissner/doom-emacs/issues/227
=> Fix dump jump local advice

core/core-editor.el, init.example.el, modules/ui/window-select/README.org, modules/ui/window-select/config.el, modules/ui/window-select/packages.el
This pull request modularize ace-window and adds switch-window as a replacement option.
This module was an idea that we discussed in issue #218
=> Module to visually select windows

modules/lang/nix/config.el
For editing files that use https://nixos.org.
=> lang/nix: initial commit

modules/lang/web/+html.el
Support `.vue` Vue.js files in web-mode.
=> Add Vue file to web mode

modules/lang/latex/+fontification.el, modules/lang/latex/README.org, modules/lang/latex/autoload.el, modules/lang/latex/config.el, modules/lang/latex/packages.el
Completion with company mode.
Selection of bibliography using Ivy or Helm.
Later preview panel or okular as viewers.
LatexMk for compiling code.
Prettified indentation with adaptive-wrap along with good indentation of environments.
Additional fontification of common commands.
=> Latex module revamped

modules/feature/popup/+hacks.el
See commit descriptions for details.
=> Fix popup evil command window execute

modules/app/calendar/autoload.el, modules/app/calendar/config.el, modules/app/calendar/packages.el, modules/app/calendar/readme.org
Added calendar app with `calfw` and `org-gcal`
=> Add: =calendar app

init.example.el, modules/tools/pdf/config.el, modules/tools/pdf/packages.el
The promised pdf-tools settings.
I'll add the updates of init-example.el in the next pull request.
=> add pdf-tools settings

init.example.el, modules/app/write/README.org, modules/app/write/autoload.el, modules/app/write/config.el, modules/app/write/packages.el
This PR add `languagetool`, `wordnut`, `synosaurus` and mixed-pitch support to +write module.
=> Enhance +write module

modules/ui/doom-dashboard/config.el
=> Fix org-agenda-list showing on dashboard

modules/lang/plantuml/config.el
added org-plantuml-jar-path for org-bable
=> plantuml path for org-bable

modules/lang/web/+html.el
Twig files already work nice with web-mode. So detecting them here.
=> Add twig files

modules/lang/elixir/config.el
Just a minor setting for defining REPL for elixir-mode.
=> Add REPL definition for elixir-mode.

init.example.el
=> Add: lang/nix: add to init.example.el

modules/app/irc/config.el
last few common types of lines for formatting
added docstrings
inclusion of disconnect hook
=> a few app/irc improvements

modules/feature/lookup/README.org
=> update documentation for +lookup/documentation

modules/config/default/+bindings.el
Adds a default workspace rename binding, SPC-tab-r
=> add workspace rename binding

modules/tools/ein/config.el
- Added a hydra inspired by spacemacs.
- Fix popup rules, company config, and default jupyter server setting
=> EIN module updates & fixes

modules/lang/javascript/packages.el
=> remove mention of tern in comment

modules/ui/doom-modeline/config.el, modules/ui/doom-modeline/packages.el
=> Plain anzu mode

modules/config/default/+bindings.el
=> Fix: desc of keymap git staging

modules/config/default/+evil-commands.el, modules/lang/latex/config.el
- lang|latex
- !feature-p evil
=> Towards fixing byte compilation

core/core-editor.el
I uses mu4e a lot, `ace-link-mu4e` is a must have for viewing emails.
=> Add: ace-link-mu4e autoload

modules/lang/web/+html.el
Thanks for Doom, I'm enjoying using it so far.
I work on a lot of Ember apps, which use Handlebars templates as `.hbs` files. I think this is all that's needed to use the correct mode.
Thanks!
=> Support handlebars templates

init.example.el, modules/lang/qt/config.el, modules/lang/qt/packages.el
Includes very basic syntax highlighting for qt modes.
=> Add basic qt support

modules/lang/cc/config.el
=> rtags is `rdm` not `rtags`

core/core-packages.el, modules/lang/python/+conda.el, modules/lang/python/autoload/conda.el, modules/lang/python/packages.el
Cleaned up from #617. I finally needed it so it got done.
@fuxialexander Would appreciate a README maybe and add anything I missed, please.
=> Add +conda

.gitignore, init.example.el, modules/ui/treemacs/config.el, modules/ui/treemacs/packages.el
=> Add treemacs module

modules/feature/file-templates/config.el, modules/feature/file-templates/templates/solidity-mode/__sol
Add Trigger and basic file template. Nothing else to say really.
=> Add Solidity Template

modules/feature/snippets/autoload/snippets.el
Fixes https://github.com/hlissner/doom-emacs/issues/702
=> feature/snippets: add missing autoload cookie

modules/emacs/vc/config.el, modules/ui/vc-gutter/config.el
=> ui/vc emacs/vc: unify hydra design

modules/ui/pretty-code/autoload.el
=> Add new symbols.

modules/emacs/eshell/config.el
=> why isn't this a thing already

modules/completion/ivy/autoload/ivy.el, modules/completion/ivy/config.el, modules/feature/workspaces/config.el
=> Add ivy action to counsel-find-file and counsel-projectile-switch-project

modules/lang/org/+export.el
Necessary to not create plain HTML presentations.
=> org: Update +export to generate revealjs stuff

modules/lang/haskell/+dante.el, modules/lang/haskell/+intero.el, modules/lang/haskell/config.el, modules/lang/haskell/packages.el
Testing by `intero` users is welcome!
=> Haskell quality-of-life improvements

core/core-ui.el, modules/lang/cc/config.el, modules/lang/emacs-lisp/config.el, modules/lang/python/config.el, modules/lang/sh/config.el, modules/lang/web/+css.el
Seems inconsistent only added to a few select packages, this will just add it to all progmode stuff
=> Highlight-numbers on every prog-mode

init.example.el
Update `init.example.el` with `deft` and `coq` modules.
=> init.example.el update

modules/lang/idris/README.org, modules/lang/idris/config.el, modules/lang/idris/packages.el
Adds basic support for the [idris](https://www.idris-lang.org/) programming language.
=> :lang idris

modules/tools/magit/config.el
=> add shortcut to "magit-gitflow-popup" with '%' in magit-mode

modules/lang/python/config.el
=> add anaconda3 home path '/usr/local/anaconda3'

modules/lang/clojure/config.el
Fix `SPC m r` for `clojure-mode`
=> Fix clj-refactor bindings

init.example.el, modules/config/default/+bindings.el, modules/tools/docker/config.el, modules/tools/docker/packages.el
Add docker module
https://github.com/Silex/docker.el
=> Add docker module

modules/lang/haskell/+intero.el, modules/lang/purescript/config.el
Hopefully self-explanatory improvements to a couple of modules.
Improvements:
* Registers `intero-company` with company for proper completions in Haskell.
* Adds a couple of lookup handlers in PureScript.
=> Haskell + PureScript module improvements

modules/lang/go/README.org
See https://github.com/hlissner/doom-emacs/pull/933
=> Updated documentation to use better gocode fork (again)

modules/tools/terraform/config.el, modules/tools/terraform/packages.el
This PR adds a simple terraform feature
=> Added feature terraform

init.example.el, modules/lang/vala/packages.el
Just added one package: 'vala-mode'. Provides syntax coloring for Vala language. Nothing more, nothing less.
=> Add vala-mode

modules/lang/clojure/config.el
- Add a popup rule for the history buffer, since we want to see the REPL change while it's open
- Add hooks to enable company fuzzy completion
- Add more cider configuration options
- Configure Shift-Return to insert a newline and indent in the REPL without submitting the result
- Bind normal state keybindings for the CIDER history buffer
Thank you for contributing to Doom!
Before you submit this PR, please make sure your PR is targeted at develop, not
master (unless this is a fix for a critical error). Then replace this message
with a description of your changes.
=> lang/clojure: More changes

modules/lang/purescript/config.el
=> purescript: Properly register company backend

modules/lang/python/config.el
=> Miniconda3 add path

modules/ui/popup/autoload/popup.el
Changed visibility check to consult all frames
=> Fixed +popup--kill-buffer visibility check

modules/config/default/+bindings.el
So I can make more one line PRs quickly.
=> Add MagitHub default binding

modules/lang/python/config.el, modules/lang/python/packages.el
Adds a nice pytest interface that uses magit popup to run the commands.
=> Add pytest

core/core-projects.el, modules/lang/common-lisp/autoload/hydras.el, modules/lang/common-lisp/config.el, modules/lang/common-lisp/packages.el
Some fixes for common-lisp module
=> Various changes

modules/lang/elixir/config.el, modules/ui/pretty-code/autoload.el
https://i.imgur.com/3xpCDDI.png
=> Elixir pretty-symbols

modules/completion/helm/autoload/evil.el, modules/config/default/+evil-commands.el
removed in 7f5e778b0c3abe14b2597f9b93fb399ff2335e62
some functions were left over that error out, this removes them
=> Clean up after swoop removal

modules/lang/rust/config.el
add rust mode key bindings description
=> add rust key bingding description

modules/config/default/+evil-bindings.el
seems to have been lost in the binding wars of 2018
=> Bind SPC-/-p to +helm/project-search if using helm

modules/lang/go/config.el
Makes the map for go-mode easier to discover.
=> Add descriptions for go-mode map

modules/tools/password-store/autoload.el
=> [tools/password-store] copy-user key in ivy-pass

core/autoload/packages.el
=> Fix doom/update-package

modules/config/default/+evil-bindings.el
Using which-key, I noticed "increase text size" had the opposite effect then noticed that the actual function that increased text size had a vague description.
I assumed this was a description error because the contrary would mean a universal hotkey change.
=> Fix description for increase/decrease font size

core/autoload/editor.el, modules/config/default/config.el
I don't think anything in here is *too* crazy
=> More MacOS bindings

modules/app/irc/README.org
=> Add port to circe network config

modules/lang/latex/+viewers.el, modules/lang/latex/config.el
Add [SumatraPDF](https://www.sumatrapdfreader.org/free-pdf-reader.html) as PDF viewer on Windows
=> Add: sumatrapdf as pdf viewer on Windows

modules/lang/ruby/packages.el
Signed-off-by: Huy Duong <huy.duong@employmenthero.com>
=> Don't install robe if lsp is enabled

modules/config/default/+emacs-bindings.el
Keeps consistent with helpful and apropos bindings.
=> Add forward/back-button bindings in help-mode

core/autoload/buffers.el
Prompts for an open project and kills all its buffers.  This is useful for closing `.emacs.d` in an effort to get some *billable* work done.
Added `doom-fixup-windows` and `doom-kill-buffer(s)-fixup-windows` helper functions for leaving affected windows on a real buffer or the fallback buffer.
Fixed `doom/kill-this-buffer-in-all-windows` to properly "fixup" windows.
Remaining issues:
- does this need some suppression of `buffer-list-update-hook`?
- dashboard ends up wonky, how to ensure resize?
=> Add doom/kill-project-buffers command

init.example.el, modules/lang/terra/autoload.el, modules/lang/terra/config.el, modules/lang/terra/packages.el
A very simple conversion of the lua module to support terra.
Adds syntax highlighting, code execution, and basic autocompletion.
If someone has a better humorous language comment, I'd like to hear it.
=> [WIP]Add Module for terralang

modules/completion/ivy/config.el
Thanks for all of your amazing work on Doom!
This commit restores the functionality of the `+ivy-buffer-icons`
variable. I tested it in both childframe and regular mode.
=> fix: restore +ivy-buffer-icons config var

init.example.el, modules/lang/kotlin/autoload.el, modules/lang/kotlin/config.el, modules/lang/kotlin/doctor.el, modules/lang/kotlin/packages.el
Simple Kotlin module, modelled after the `lang/rust` module.
=> Add Kotlin module

modules/lang/javascript/README.org
I tried documenting all the keys available under the local leader for all the js modes here.
=> Add documentation for JS module keymaps

init.example.el
=> Nitpick comment alignment in init.el

modules/lang/agda/config.el
Add support for commonly used movements (https://agda.readthedocs.io/en/v2.5.4.1/tools/emacs-mode.html)
=> Add `agda2-next-goal` and `agda2-previous-goal`

modules/ui/treemacs/config.el, modules/ui/treemacs/packages.el
I thought this might be useful to setup and install when using both treemacs and magit. Cheers.
=> Use treemacs-magit package

modules/tools/docker/README.org
This an early draft for the documentation of the docker module.
@hlissner could you please check if this is going in the right direction?
What I did was gather all the relevant docs from the included packages.
=> Add a draft for docker module documentation

modules/lang/org/config.el
I used to wrong function for the localleader binding to set tags in org files. Sorry.
=> fix command to set tags

modules/lang/python/config.el
also rename shortcut to pytest repeat to "r"
=> add option to run only one function

init.example.el, modules/lang/fsharp/README.org, modules/lang/fsharp/config.el, modules/lang/fsharp/doctor.el, modules/lang/fsharp/packages.el
(WIP) This is a pretty simple F# language module
=> [WIP] Implement fsharp :lang module

core/autoload/buffers.el, core/autoload/debug.el, core/autoload/files.el, core/autoload/ui.el, core/core-ui.el, modules/app/regex/autoload/regex.el, modules/config/default/+evil-bindings.el, modules/editor/evil/+commands.el, modules/editor/evil/+everywhere.el, modules/lang/ess/config.el, modules/term/eshell/autoload/eshell.el, modules/tools/magit/config.el, modules/tools/pdf/config.el, modules/ui/tabbar/config.el
As per the documentation for kill-this-buffer, it should only be invoked
from the menu and behaves unpredictably when invoked programmatically.
=> Replace kill-this-buffer with kill-current-buffer

bin/doom, bin/doom-doctor, bin/org-capture, bin/org-tangle
Modifies the scripts
- bin/doom
- bin/doom-doctor
- bin/org-capture
- bin/org-tangle
so they are compatible with any POSIX compliant shell.
=> Posix compliance

bin/doom, bin/doom-doctor, bin/org-capture, bin/org-tangle, core/cli/patch-macos.el
See https://en.wikipedia.org/wiki/Shebang_(Unix)#Portability
=> fix shebang

modules/lang/nix/config.el
See https://github.com/NixOS/nix-mode/pull/79
cc @ar1a
=> use default `nix-indent-function`

modules/emacs/vc/autoload/vc.el
fix error: Cannot open load file: No such file or directory, emacs/vc/autoload
=> fix: file not found in autoload

modules/lang/lua/config.el
=> Wrap :on-load for +lua-love-mode in a progn

modules/lang/rust/README.org
Update of Rust README.org file.
=> Rust readme

modules/lang/fsharp/README.org, modules/lang/fsharp/config.el
This PR adds support for LSP in the F# lang module.
=> Add LSP support for F# lang module

modules/email/mu4e/README.org
=> Add NixOS example

modules/lang/python/config.el, modules/lang/python/packages.el
Building on #1600, my branch juggling broke that PR.
=> Adding lsp-python-ms with patch so it doesn't force itself to be installed

modules/lang/elixir/README.org
=> Add README for lang/elixir

modules/lang/org/packages.el
https://github.com/magit/orgit
=> lang/org: Package orgit if magit is enabled

modules/lang/racket/config.el
Looks like my last refactor in #1580 broke racket-mode (apparently I didn't test it after making that change). Sorry about that!
=> lang/racket: Fix bug in configuration

modules/tools/docker/README.org
- Proofread a bit
- Add #+SINCE: v2.0.9
- Change some formatting to proper Org syntax
=> tools/docker: Update README.org

modules/lang/data/config.el, modules/lang/data/packages.el
This PR adds support for jsonnet using [jsonnet-mode](https://github.com/mgyucht/jsonnet-mode).
=> Feature: Added support for jsonnet

modules/lang/python/autoload/python.el, modules/lang/python/config.el, modules/lang/python/packages.el
> To ensure that this PR is processed as quickly as possible, please ensure the
> following steps have been taken:
> - [ ] This PR targets the develop branch and not master
> - [ ] If your PR is a work in progress, include [WIP] in its title
> - [ ] Its commits' summaries are reasonably descriptive
> - [ ] You've described what this PR addresses below
> - [ ] You've included links to relevant issues, if any
> - [ ] You've deleted this template
>
> Thank you for contributing to Doom Emacs! <3
Your description here...
=> Sort python imports

modules/lang/org/config.el
I added two key-bindings for adding attachments and setting properties
in org-mode.
=> Add org-mode keybindings

modules/lang/cc/packages.el, modules/lang/data/packages.el
=> use emacsmirror for cmake-mode and protobuf-mode

modules/emacs/dired/README.org
Hi!
Here is a small pull request that adds a bit of documentation about the `dired` module.
Related to #1166.
=> emacs/dired: add README.org

modules/lang/agda/README.org
we no longer use agda-mode locate
=> Fix wiki for agda

modules/lang/go/autoload.el
This command wasn't implemented yet it seems. I've implemented it.
=> Fix +go/test-rerun

modules/lang/coq/config.el
These bindings are modelled afer the bindings in spacemacs
=> Add coq key bindings

init.example.el, modules/lang/lean/config.el, modules/lang/lean/packages.el
This isn't full working yet - I'm not sure why company is failing. I appreciate any help however.
=> Add a module for the lean theorem prover

modules/config/default/+evil-bindings.el, modules/lang/org/config.el, modules/lang/org/contrib/journal.el, modules/lang/org/packages.el
As discussed in chat, there was an interest for adding support to this package.
=> Add support for org-journal

modules/lang/python/README.org
=> ADD modules/lang/python/README.org

modules/editor/lispy/README.org, modules/lang/cc/README.org
I came across these super minor typos.
=> Fixed a couple typos in READMEs

modules/ui/workspaces/README.org
Update Commands & Keybindings in Workspaces README
Related to #1166
=> Update Commands & Keybindings in Workspaces README

modules/app/twitter/README.org
This PR adds as much info as I could infer from the code. There are some TODOs
left in the readme for hacks, configuration etc. since I felt they were out of
my reach.
=> Adds README for app:twitter

modules/lang/ledger/README.org
Adds README for lang:ledger
Relates to #1166
=> Adds README for lang:ledger

init.example.el, modules/README.org, modules/lang/faust/README.org, modules/lang/faust/autoload.el, modules/lang/faust/config.el, modules/lang/faust/doctor.el, modules/lang/faust/packages.el
I'm just looking for a catchy description for in  init.example.el. ;)
=> Add faust module

modules/lang/latex/config.el
=> lang/latex: fix setting variables #1910.

modules/lang/latex/config.el
=> lang/latex: fix loading style files #1910.

modules/config/default/+evil-bindings.el
Just a couple of useful bindings which were missing.
=> Add some bindings for apropos and info-mode

core/autoload/help.el
This is quit similar to `SPC h d l` except that it will only search for loaded files.
Here's a very common use case for this: you get an annoying `(message ..)` and you don't know where it's coming from. How do you find it? `SPC h d l` works but isn't so good because it might bring up a lot of false positive. This command is both faster and will avoid false positives.
I can factor out the copy-paste if you want, but I assume you have more plans for this anyway. Note that this requires `elisp-refs` uless you want to copy paste the function to get all loaded files.
=> Add comment to search loaded .el files

docs/faq.org
Fix links in the faq which were absolute
=> Fix paths in the FAQ

modules/input/chinese/packages.el
> To ensure that this PR is processed as quickly as possible, please ensure the
> following steps have been taken:
> - [x] This PR targets the develop branch and not master
> - [ ] If your PR is a work in progress, include [WIP] in its title
> - [ ] Its commits' summaries are reasonably descriptive
> - [ ] You've described what this PR addresses below
> - [ ] You've included links to relevant issues, if any
> - [ ] You've deleted this template
>
> Thank you for contributing to Doom Emacs! <3
Your description here...
=> Add pyim package to :input chinese

modules/lang/faust/config.el
=> configure faust company backends

core/autoload/sessions.el
=> add confirmation message after loading a session from file

modules/ui/hydra/README.org
This is mostly a stub, the keybindings are just the one I chose for my own usage, I don't know if there are better choices or not :(
=> [FEATURE] Add :ui hydra README

core/autoload/help.el
Signed-off-by: Rudi Grinberg <me@rgrinberg.com>
=> Fix autoload cookie for doom/help-search-loaded-files

modules/lang/org/packages.el, modules/lang/rst/config.el, modules/lang/rst/packages.el
Uses sphinx-mode and adds a few common bindings
=> Add rst module

modules/lang/org/config.el
I don't feel strongly about any of these bindings. Feel free to tweak them as you wish.
=> Add clock bindings to org agenda

modules/lang/coq/config.el
It's just an annoying splash screen message. Users don't need to see it.
=> Disable hello company coq

docs/index.org, modules/tools/terraform/README.org
=> tools/terraform: add readme file

modules/emacs/dired/config.el
A simple PR for ranger using dired-git-info package.
=> emacs/dired: ranger catch up dired-git-info

docs/faq.org
My first PR :-)
Not sure if my change breaks any alignment guidelines ... ?
=> Fix grammar in faq.org

init.example.el, modules/lang/factor/README.org, modules/lang/factor/config.el, modules/lang/factor/packages.el
Factor is a stack based programming language with an awesome emacs mode :)
=> Add factor module

modules/lang/ocaml/config.el, modules/lang/scheme/config.el
For OCaml repls and geiser buffers
=> More popup rules

modules/tools/magit/autoload.el, modules/tools/magit/config.el, modules/tools/magit/packages.el
Pretty simple and cool package.
@hlissner I'm going to request you do the keybinding for
`github-review-forge-pr-at-point`, or shoot me an example of binding something
in a magit buffer, and what you'd like the binding to be.
=> [WIP] add github-review

modules/ui/popup/config.el
*Compilation* and *compilation* are both allowed
=> Fix regex for detecting compilation buffer

docs/faq.org
=> docs/faq: add broken upstream pkg to common issues

modules/config/default/+emacs-bindings.el
Adding more vanilla keybindings based off previous work by @UndeadKernel,
feedback welcomed!
=> bindings: add more sections to vanilla keys

docs/faq.org
I just happened to notice a small typo while linking this. Please no shoot.
=> Small typo fix

modules/editor/lispy/config.el
Dune uses an sexpression based syntax as well
=> Add dune-mode to lispy modes

core/core-editor.el
=> Enable smartparens-mode during pp-eval-expression

core/templates/packages.example.el
=> Typo pnned -> pinned

modules/lang/rust/config.el
=> fix message

modules/lang/org/autoload/org-capture.el
Fixes centralized org-capture for projects
=> fix: use org-capture-projects-file

modules/lang/sh/README.org, modules/lang/sh/config.el
=> Add lsp support to sh module.

modules/lang/elixir/config.el, modules/lang/elixir/packages.el
This patch updates the check for enabling flycheck bindings to the new
module location.
=> Update feature check of flycheck in elixir mode

modules/lang/erlang/README.org, modules/lang/erlang/config.el, modules/lang/erlang/packages.el
Add LSP support to the erlang module.
Should probably make a Readme.md too...
=> Add LSP Support to Erlang

modules/emacs/dired/config.el
Fixes https://github.com/hlissner/doom-emacs/issues/2439
=> Don't use dired git highlighting if remote

modules/lang/rust/packages.el
Rustic was broken because of brotzeit/rustic#88
=> Bump to brotzeit/rustic@124e028

modules/editor/snippets/packages.el
Bump to hlissner/doom-snippets@2781b782a3.
=> Bump to hlissner/doom-snippets@2781b782a3

core/packages.el
Bump to Fuco1/smartparens@be8d5c9.
=> Bump to Fuco1/smartparens@be8d5c9

bin/org-capture
use OPTARG to get key argument in org-capture sh script
=> use OPTARG to get key argument

modules/config/default/+evil-bindings.el
=> evil: smerge hydra on `SPC g m`

modules/editor/file-templates/README.org
Added documentation on adding and overriding file templates.
I wanted to create a new template, and in the lack of documentation read the
code, and thought that I might as well update the README on how to do so as its
marked as TODO.
Also please confirm that I've got the overriding part right, I'm not 100% certain
about it.
=> file-templates README: registering & overriding

modules/tools/terraform/config.el
Emacs LSP has support for Terraform these days.
=> Add LSP for Terraform

modules/tools/lsp/config.el, modules/tools/lsp/packages.el
This updates `lsp-mode` and `lsp-ui`, pulling in 2 performance improvements (https://github.com/emacs-lsp/lsp-mode/commit/da406084aef627eedaadeb94d96e1ddd53860673 and https://github.com/emacs-lsp/lsp-mode/commit/2fc0963a50488c47a5be3836ad042380b71d1cfb). There was one small breaking change introduced by https://github.com/emacs-lsp/lsp-mode/commit/4d59bded6bbba6d3bc73032305d1b3c071eb73c4 which I have tried to address; noticed no other breaking changes.
Opening this PR so other people can test it as well; I've only given it a few hours of superficial testing so far (using C++ and TypeScript language servers)
=> Update to latest lsp-mode, lsp-ui

docs/getting_started.org
Pretty minor change. Just trying to set up Doom for the first time!
=> Fix for the package-management link in README.

docs/modules.org, modules/lang/ruby/config.el, modules/lang/ruby/packages.el
This is WIP, I've picked the upstream keyindings with minor changes for now.
Fixes https://github.com/hlissner/doom-emacs/issues/2461, https://github.com/hlissner/doom-emacs/issues/2275
=> Add Rails support to Ruby module

core/core.el
- Fix TLS disabled due to a typo
- Add some more reasonable security settings for 2020
=> Use TLS by default and add more security settings

modules/lang/dart/+flutter.el, modules/lang/dart/README.org, modules/lang/dart/config.el, modules/lang/dart/doctor.el, modules/lang/dart/packages.el
It's been a while that @Sevensidedmarble left that issue unresolved.
I made my own changes and repurposed it, in case he never continue his job. (*Because it is a demanding module between my colleagues* who happen to have no idea how to config their Emacs Doom!)
Since I'm a newbie, I just followed the instructions of @hlissner (Really awesome instructions!) and really didn't change much.
If a module "requires" an active maintainer in order to be merged, I suppose I can "dogfood" the package (however not flawlessly, due to my lack of technical understanding of the project, but just saying I can get the job done till somebody qualified shows up!)
(Pardon me for possible English mistakes)
=> Updated: Add lang/dart module #2549 (Originally by @Sevensidedmarble)

modules/lang/org/contrib/dragndrop.el
Fix https://github.com/hlissner/doom-emacs/issues/2429#issuecomment-599085171
=> Fix inserted filename for org-download-screenshot

modules/editor/god/packages.el
Bumping god-mode to `b82ce18ae4`.
=> Update god-mode version pin

modules/lang/clojure/README.org
+ Fix linter links to mention the currently used one (it was changed in [this PR](https://github.com/hlissner/doom-emacs/pull/2580))
+ Add actual description for the module
=> Update Clojure module README

modules/editor/fold/config.el
Yet another LaTeX PR...
Closes #2805. See it for a screenshot.
=> Add latex env support to editor/fold with hideshow

modules/tools/lookup/config.el
Fixes https://github.com/hlissner/doom-emacs/issues/2852
=> Fix helm-xref when using Emacs 27+

modules/lang/web/config.el
This adds support for django templates.
I'm not sure the mode line is correct but at least I got this working in my
setup.
=> web: add +web-django-mode

modules/lang/org/contrib/roam.el
Fix https://github.com/hlissner/doom-emacs/issues/2846
=> Load org-roam after org-mode

modules/lang/org/contrib/roam.el
Makes for a more consistent UX.
=> Configure org-roam completion backend

modules/config/default/+emacs-bindings.el
Add a reasonable emacs binding to search a project for the symbol at point.
=> Add KB for searching for symbol in project

modules/lang/dart/README.org, modules/lang/dart/config.el, modules/lang/dart/doctor.el, modules/lang/dart/packages.el
* Change to use `lsp-dart`.
* Add [`hover.el`](https://github.com/ericdallo/hover.el) for flutter development.
=> Improve dart lang module

modules/email/mu4e/README.org
Just changed a bit the documentation and fixed a typo.
=> Added details to the mu4e documentation.

modules/lang/web/+css.el
LSP works fine with scss-mode but currently has to be started manually.
=> Autostart LSP also in scss-mode

modules/lang/org/contrib/journal.el
=> Fix: contrib/journal: `buffer-file-name' is nil in *Capture* buffer

modules/editor/evil/+commands.el
Only when evil +everywhere and ibuffer are enabled
=> Make :ls/:buffers invoke ibuffer

modules/lang/dart/packages.el
`lsp-dart`: `1.3` -> `1.6.5`
`flutter.el`: test support fixes
=> [dart] Update lsp-dart and flutter.el packages

README.md
Abbrev-mode betrayed me :( for that you get two commits for the price of one.
<kbd>SPC h for</kbd> → <kbd>SPC h f</kbd>
=> Oooops, I did a boo-boo

modules/checkers/grammar/config.el
Fixes https://github.com/hlissner/doom-emacs/issues/2072.
I have left the mac portion alone as I don't have a mac handy to test this.
=> Fix langtool config for Linux

modules/lang/java/README.org
I tried to take inspiration from other documentations and adapt it from them. So far the documentation includes the module flags as well as a comparison between the lsp and meghanada flags since they are mutually exclusive. Furthermore a few installation instructions for Ubuntu and Fedora was added.
=> First draft for java documentation

modules/lang/dart/packages.el
=> Bump :lang dart

modules/tools/debugger/packages.el
Bump to latest release of dap-mode `0.4`
=> Bump :tools debugger

modules/tools/lsp/packages.el
I'd like to include my PR:
https://github.com/emacs-lsp/lsp-mode/pull/1625
=> Bump to emacs-lsp/lsp-mode@d0096cc

modules/email/mu4e/config.el
=> mu4e action to view email in browser

modules/lang/kotlin/config.el
=> Add Kotlin REPL support

modules/lang/java/autoload.el, modules/lang/java/config.el
* Add Groovy REPL support
* Set the Dash docsets for Groovy
=> Improve Groovy support

modules/editor/file-templates/templates/java-mode/.yas-setup.el, modules/editor/file-templates/templates/java-mode/__, modules/editor/file-templates/templates/java-mode/__main
Fix the Java file templates:
- `yas-java-project-package` -> `+java-current-package`
- `yas-java-class-name` -> `+java-current-class`
=> Fix Java file templates

modules/lang/nix/README.org
I added all the things I know about this module but there might be
something I don't know about so check and validate.
This is part of  #1166 effort.
=> Add lang/nix barebone readme.

modules/lang/kotlin/README.org, modules/tools/rgb/README.org
pretty short, but the module is small and I think I covered everything
=> README for tools/rgb, also minor typo fix

modules/completion/ivy/packages.el
abo-abo/swiper@9e0803c -> abo-abo/swiper@84efa3a
fixed #3069
=> Bump :completion ivy

modules/tools/upload/README.org
I tried to keep it minimal since it mostly wraps `ssh-deploy`.
=> Add initial upload README

README.md
Sorry if this contribution does not follow community standards, I haven't visited the contribute section yet! :^)
=> Fixed "Contribute" link in toc of README.md

modules/config/default/+emacs-bindings.el, modules/config/default/+evil-bindings.el
Tested the evil bindings but not the emacs bindings.
=> Add open email bindings

docs/modules.org, modules/lang/purescript/config.el, modules/tools/lsp/README.org
[this PR](https://github.com/emacs-lsp/lsp-mode/pull/1596) merged, so I added lsp flag to PureScript.
=> Added +lsp flag to lang/purescript

modules/tools/debugger/config.el
=> activating dap web modules in TS mode

modules/app/rss/README.org
Simple readme for rss module. 
Should contain all important things to begin use app/rss
=> add app/rss readme

core/packages.el
raxod502/straight.el@f606bfa -> raxod502/straight.el@846956e
jwiegley/use-package@c873d55 > jwiegley/use-package@d2640fe
bbatsov/projectile@768f057 > bbatsov/projectile@5103cfc
noctuid/general.el@42e3803 > noctuid/general.el@a0b17d2
=> Bump :core

modules/lang/org/autoload/org-link.el
Refer https://orgmode.org/manual/External-Links.html.
=> lang/org: Support option in custom org links

modules/lang/clojure/packages.el
add insert and toggle to tables  which  we should probably move from b  as  b would better fit the babel functions.
=> Add Tree Subtree function to bindings to lang org 

modules/emacs/vc/README.org
Adds a simple readme for emacs/vc
=> Add emacs/vc readme

modules/config/literate/README.org
This is simple readme for config/literate but most of the things and quirks should be clear with this.
Part of #1166 issue.
=> add config/literate readme

modules/tools/pass/README.org
=> add tool/pass readme

modules/lang/dart/packages.el
emacs-lsp/lsp-dart@80f8eca -> emacs-lsp/lsp-dart@afdcce3
`1.8.0` -> `1.11.9`
=> Bump :lang dart - lsp-dart

modules/tools/lsp/+lsp.el
Make LSP checker in lsp-mode work with other checkers.
=> tools/lsp: Make lsp checker chained to other checkers

modules/lang/rust/packages.el
I forgot to fix a mistake I did some time ago...
Since I don't use rust at the moment, it would be really great to get some help with the package, even if it's only for reviewing and testing the stuff I'm pushing. So if anybody here wants to help me I would very much appreciate it and gladly give write access to others. It seems the number of users has been increasing(I think doom is a major reason) and it makes it even more annoying when I introduce bugs that I don't notice because I don't use the package.
=> bump rustic

modules/lang/json/config.el, modules/lang/json/doctor.el, modules/lang/json/packages.el
Co-authored-by: rushsteve1 <rushsteve1@rushsteve1.us>
Wasn't sure if this was flag worthy or not. I also wasn't sure if my loading and mapping was correct I just tried to follow the `python` config.
=> Feat: add counsel-jq

README.md
=> Nix and Guix is a great idea!

modules/config/default/+emacs-bindings.el, modules/config/default/+evil-bindings.el, modules/tools/macos/README.org, modules/tools/macos/config.el
Add support for keychain
Add README.
Add shortcut for open in iTerm.
=> Updates for macos module

core/templates/config.example.el, init.example.el
Fixed parts left out in ee972e7a3f9751ffc6b685ad9d6740dfbb24eed8
=> Update doc comments in {init,config}.el templates

modules/tools/taskrunner/config.el
Add popup rule for taskrunner buffer so that we can close it by pressing Esc.
=> tools/taskrunner: Set popup rule for taskrunner buffer

modules/app/calendar/config.el, modules/app/calendar/packages.el
=> Include calfw-ical package in :calendar

modules/config/default/+evil-bindings.el, modules/lang/scheme/config.el
=> Minor scheme module improvements

README.md, docs/getting_started.org
=> Fix link to screenshots + minor correction in "Getting started"

modules/lang/rust/packages.el
brotzeit/rustic@f7a94c4 -> brotzeit/rustic@7c0e113
=> Bump :lang rust

modules/ui/hl-todo/config.el
Been crawling in [Wikipedia](https://en.wikipedia.org/wiki/Comment_(computer_programming)#Tags) and found XXX and BUG tags interesting.
=> Add the BUG and XXX tags to hl-todo

modules/lang/php/config.el
I'm not pretty sure if Types are redundant or not since Php is not so much around types... But I added them just in case.
=> Add pretty symbols to php-mode

modules/lang/ledger/config.el
This provides pretty, and very useful completion of accounts.
Inspired by the Finance layer for Spacemacs.
Signed-off-by: Johan Thoren <johan@thoren.dev>
=> Set company-capf as backend for ledger-mode.

modules/lang/org/contrib/roam.el
=> Ensure org-roam-directory is a directory

modules/tools/ansible/packages.el
=> Bump :tools ansible

modules/checkers/spell/README.org
Spotted reviewing patch differences
=> Fix typo in checkers/spell/README

modules/lang/dart/README.org
* Add more feature items
* Add me as dart module maintainer
* Add hover explanation
=> Update dart module README

modules/lang/latex/README.org, modules/lang/latex/config.el, modules/lang/latex/packages.el
[evil-tex](https://github.com/iyefrat/evil-tex) is a plugin for better latex editing in evil-mode. @iyefrat and I worked very hard on it, and I think its a fine addition to the latex module.
=> Add evil-tex package to :lang latex

modules/ui/doom-quit/README.org, modules/ui/hl-todo/README.org, modules/ui/ligatures/README.org
I have updated the README for doom quit to fit with the new format and have added some configuration (the configurations i know)   information to ui ligatures. also redid hl-todo to fit the new format. I am now heading to bed
=> updating docs for doom-quit and ligatures and hl-todo

modules/lang/racket/config.el
Fixes #2922.
It works, but I bet the code could've been better. Critique welcome.
=> Fix bindings for racket-mode

modules/config/default/+emacs-bindings.el, modules/config/default/+evil-bindings.el, modules/editor/evil/config.el
Fixing keybindings using recently introduced +flyspell flag ;)
=> If +flyspell enabled, disable spell-fu keybindings and use flyspell ones

modules/checkers/spell/config.el
This list is not exhaustive, but its a lot better than nothing at all.
=> Add latex faces to +spell-excluded-faces-alist

modules/completion/ivy/config.el
More details here: emacs-lsp/lsp-ivy#18 (comment)
=> fix ivy not working well with lsp-ivy-workspace-symbol

modules/input/layout/+bepo.el
No need to fiddle with g-maps here
=> Set navkeys for evil-markdown in bepo

modules/emacs/dired/config.el
`dired-create-destination-dirs` : set to "ask", non-existent directories will be created when copying, if the user consents.
`dired-vc-rename-file` : rename file using the vc system, if present
=> configure dired-aux variables

modules/config/default/+emacs-bindings.el, modules/config/default/+evil-bindings.el
Added a keybinding `SPC n j J`` to create a scheduled entry in Org Journal.
=> Add `org-journal-new-scheduled-entry` Keybindings

modules/lang/org/contrib/journal.el
Silences some obsolescence warnings when navigating among entries
=> Adjusting org journal functions to new commands

modules/ui/workspaces/config.el
function was renamed in persp-mode
fix #4025
=> fix #4025 renaming of function in persp-mode

modules/lang/haskell/+lsp.el, modules/lang/haskell/README.org, modules/lang/haskell/packages.el, modules/tools/lsp/README.org
Switch to haskell-language-server, see https://neilmitchell.blogspot.com/2020/09/dont-use-ghcide-anymore-directly.html
=> Bump :lang haskell

modules/lang/dart/config.el, modules/lang/dart/packages.el
After some months coding with dart I ended with these mapping which I find it's very useful.
* Improve mappings for dart
* Bump hover and lsp-dart(add test tree feature) to latest version
=> Bump dart module and improve keybindings

docs/faq.org
=> Larger link. Fitt's law

init.example.el, modules/lang/idris/README.org
=> update idris module to new format

docs/modules.org, modules/lang/sh/README.org, modules/lang/sh/config.el, modules/lang/sh/packages.el
Added ability to get syntax highlighting on powershell scripts. Also added check for LSP to enable completion
=> Add +powershell to lang/sh module

modules/ui/ligatures/README.org
Fixes documentation type found in #4061
=> Fix ligature documentation typo

modules/tools/biblio/packages.el
Bump :tools biblio
tmalsburg/helm-bibtex@b14b628 -> tmalsburg/helm-bibtex@12f8809
Signed-off-by: Brian McGillion <brian@ssrc.tii.ae>
=> Bump :tools biblio

modules/lang/ledger/doctor.el
Hi. I've added doctor.el for checking ledger binary.
=> lang/ledger: Add doctor.el for :lang ledger

modules/lang/cc/config.el
I should find some way to test on Mac OS I guess, or test in CI or something at least. That would make those small errors easier to catch than trying to review it 1000 times
=> [:lang cc] Fix list in call for cpu count command

modules/input/layout/+bepo.el
Reference is 2491c8ed2cc078e128ce899c334acfb2d737a8ea
=> [bepo] tools/lsp: add t/s/C-t/C-s for lsp-ui-peek

core/cli/upgrade.el
=> Print diff url in terminal in case emacs is in a remote server

docs/modules.org, init.example.el, modules/config/default/+emacs-bindings.el, modules/config/default/+evil-bindings.el, modules/ui/emoji/README.org, modules/ui/emoji/config.el, modules/ui/emoji/packages.el
Uses the emojify package to enable displaying and inserting emojis. Also adds a new binding "SPC i e" to insert an Emoji.
=> ui/emojis: New module for inserting/displaying emojis

modules/editor/file-templates/templates/text-mode/__license-gpl3
I can't really think of any description to add, beyond the title itself --- so here's a limerik!
> A wonderful bird is the Pelican.
> His beak can hold more than his belly can.
> He can hold in his beak
> Enough food for a week!
> But I'll be darned if I know how the hellican?
Enjoy!
=> Licences: Add tabstops with defaults to gpl3

modules/lang/latex/config.el
=> Map Tex-view to localleader-v

modules/input/japanese/config.el
Escape skk-mode on `doom/escape`.
=> Escape skk-mode on doom/escape

modules/lang/web/+html.el
Load web-mode when [eco](https://github.com/sstephenson/eco) files are opened.
=> Associate .eco files with web-mode

modules/config/literate/README.org
=> Fix 404 link in literate module readme.

modules/lang/cc/README.org
I didn't test all 4 of these, hopefully no terrible mistake slipped in
=> [:lang cc] Add LSP configuration snippets

core/cli/packages.el
This is a workaround for `doom build` hanging on native-comp Emacs when run with an empty cache.  We're effectively automating the process of killing `doom build` and trying again.
Re: #3655
Re: #3983
=> Bootstrap trampolines to prevent doom build hang

modules/lang/cc/README.org
Just a minor doc update related to the recent Cmake language server support
=> Adding doc update for cmake-language-server

modules/email/mu4e/config.el
=> Update org-msg org-msg variable.

modules/lang/elixir/README.org, modules/lang/elixir/config.el, modules/lang/elixir/packages.el
I modeled this off the definition for `rspec-mode` in the `ruby` module. Let me know if there is anything I missed or need to adjust.
🍻
=> Add exunit mode for Elixir

modules/input/layout/+bepo.el
Related to #4325 and c1bdd63dcd1ab23bf9365af7e0c7ae29c56c50e2
=> [:input layout] Follow evil-magit migration

modules/checkers/syntax/packages.el
Has the fix for https://github.com/alexmurray/flycheck-posframe/issues/21
=> Bump :checkers syntax flycheck-posframe

modules/lang/scheme/packages.el
jaor/geiser@2accab7 -> jaor/geiser@cd00be6
flatwhatson/flycheck-guile@2940f16 -> flatwhatson/flycheck-guile@e46d6e5
=> Bump :lang scheme

modules/tools/lookup/config.el
Thought having the ability to search on MDN would be useful!
=> Adds MDN search to online lookup

modules/config/default/+emacs-bindings.el, modules/config/default/+evil-bindings.el
Thanks to this blog post for teaching me about it:
https://emacsredux.com/blog/2020/12/10/essential-magit-file-commands/
=> Bind useful magit-file-dispatch

modules/checkers/spell/README.org
This PR adds some missing install commands for the spell checkers.
=> Add missing install commands for spell checkers

modules/completion/company/autoload.el, modules/lang/org/config.el
See https://github.com/hlissner/doom-emacs/issues/4477
=> Fix company backends for text and org modes

modules/lang/org/README.org
Add some more instructions to use +jupyter for jupyter babel blocks.
=> org: jupyter prerequisites

core/core-modules.el
=> Fix :unless in (doom!) block.

init.example.el, modules/app/everywhere/README.org, modules/app/everywhere/cli.el, modules/app/everywhere/config.el, modules/app/everywhere/doctor.el, modules/app/everywhere/packages.el
No need to leave Emacs any more.
Module discussed on discord. See the `README.org` for more information on this.
=> New module, :app everywhere

modules/completion/ivy/config.el
=> Enable `ivy-rich-project-root-cache-mode`.

docs/modules.org
Perhaps a silly suggestion, but when I followed the link I wasn't sure I'd landed in the right place.
=> Title the Module Index "Module Index"

modules/lang/purescript/config.el, modules/lang/purescript/packages.el
- Add keybindings
- Enable flycheck
- Add psci based repl
=> Purescript mode improvements

modules/app/rss/autoload.el
I basically looked at the calendar app and copy/pasted the code into the rss app.
I tested it on my machine and it worked.
=> Add workspace support to rss/elfeed

modules/tools/lsp/autoload/flycheck-eglot.el
Since joaotavora/eglot@da7ff4883d3108468265fdc16a217d8e6aff92f2,
the callback defined by `eglot-flymake-backend` is only called when
flymake-mode is active. ~~To circumvent this limitation, we let-bind
`flymake-mode` around `eglot-handle-notification`.~~ Not relevant, see later comment for the actual workaround
Relates to flycheck/flycheck#1592 discussion
=> Re-document flycheck-eglot compatibility layer

modules/tools/terraform/config.el
Set docsets for terraform-mode.
=> lang/terraform: Set docsets for terraform-mode

core/core-cli.el
=> Load `autoload/system` in `core-cli`

modules/ui/nav-flash/autoload.el
Raised on discord, without this causes issues with ivy in most cases. (sorry about the dirty commits)
=> Fix nil issue with nav-flash & ivy

modules/lang/elixir/README.org
Link to official installation guide
Mark asdf as recommended for easier switching of versions
=> Update Elixir Installation instructions

modules/lang/go/README.org
Simple doc change hopefully clarifies things
=> go: README: Specify req of (format +onsave) for gofmt

modules/lang/factor/config.el
* Add bindings to fuel-help-mode
* Add more bindings to factor mode
* Add more bindings to fuel-listener mode
=> Improve factor configuration

modules/tools/lsp/+eglot.el, modules/tools/lsp/autoload/flycheck-eglot.el, modules/tools/lsp/packages.el
EDIT : use `eglot-flymake-backend` new version properly.
=> Fix eglot integration with flycheck

docs/modules.org, modules/config/default/+emacs-bindings.el, modules/config/default/+evil-bindings.el, modules/ui/treemacs/README.org, modules/ui/treemacs/config.el, modules/ui/treemacs/doctor.el, modules/ui/treemacs/packages.el
* Add a basic template for treemacs
* Add the +lsp flag to treemacs which adds lsp-treemacs and some useful keybindings
=> ui/treemacs: add +lsp flag

modules/lang/latex/config.el
These have been in my config for a long time, I think having them as defaults is an improvement.
=> :lang latex improvments

modules/input/layout/+bepo.el
=> fix(input layout bepo): unmap t/s in Info-mode-map

modules/lang/markdown/packages.el
Bump :lang markdown
https://github.com/jrblevin/markdown-mode/commit/051734091aba17a54af96b81beebdbfc84c26459 -> https://github.com/jrblevin/markdown-mode/commit/ac9ea26b941eef512a3c206375a6404625c229ed
https://github.com/seagle0128/grip-mode/commit/98d566db769b865f102a0c6802a08ebce8ae5e7f -> https://github.com/seagle0128/grip-mode/commit/28552059c4643f571ef0883ad543270a48241572
=> Bump :lang markdown

modules/lang/emacs-lisp/autoload.el
This PR reimplements `+emacs-lisp--module-at-point` on top of `syntax-ppss` to make it more robust and make it recognize module flags not starting with a `+`.
Fixes https://github.com/hlissner/doom-emacs/issues/4896.
=> Reimplement +emacs-lisp--module-at-point to fix #4896

modules/input/layout/+azerty.el, modules/input/layout/config.el
This is an initial commit to add azerty support
=> Add azerty layout

modules/tools/prodigy/config.el
This allows using evil-collection's bindings for this mode.
=> Set initial state in prodigy to normal

modules/email/notmuch/README.org
Hey,
Adding a few things I hope newbies to notmuch and emacs email will find helpful. I broke these changes out into very specific and targeted commits, just in case there are any you want me to drop.
Cheers,
Will
=> Notmuch: docs to add

modules/input/layout/+bepo.el
Fixes #5002
Draft because untested.
=> fix(input layout bepo): remap visual-line-mode-map

modules/completion/ivy/README.org, modules/lang/rust/README.org, modules/lang/rust/config.el
This PR tweaks the Rust installation instructions and fixes a few minor typos.
=> Rust/Ivy Module Docs

modules/input/japanese/packages.el
w.r.t https://github.com/skk-dev/ddskk/issues/190 
Bump ddskk version to include fix.
=> Bump ddskk

modules/ui/treemacs/README.org
This is a stub I need to finish but I wanted to upload it for... I don't really know. Also its pertinent to #1166
=> doc: adding treemacs readme

modules/lang/scheme/README.org
Fixed a small copy / paste error on schemes README.md. The Geiser-chibi link was pointing to the chez repo.
=> Fix schemes README.md

modules/app/irc/README.org
This PR swaps all mention of Freenode for Libera.Chat in the `app/irc` module help.
=> app/irc: Libera.Chat

modules/editor/file-templates/templates/java-mode/__annotation-type, modules/editor/file-templates/templates/java-mode/__class, modules/editor/file-templates/templates/java-mode/__enum, modules/editor/file-templates/templates/java-mode/__interface, modules/editor/file-templates/templates/java-mode/__record
Add Java file templates:
- `__annotation-type`
- `__enum`
- `__interface`
- `__record`
- `__` → `__class` (rename)
=> lang/java: Add file templates

modules/ui/deft/README.org
Re: #1166
I've updated the README for ui/deft to fit the new format (first time contributor).
=> Update ui/deft README to new format

modules/checkers/spell/autoload/+flyspell.el
=> spell: fix undefined variable

core/autoload/packages.el
=> fix: use new commit format in `doom/bumpify-diff`

init.example.el, modules/lang/dhall/config.el, modules/lang/dhall/packages.el
=> Add module for the dhall config language

modules/email/mu4e/README.org, modules/email/mu4e/autoload/email.el
This PR introduces some minor additions and modifications to the mu4e-module documentation and doc-strings.
=> Enhance mu4e docs

modules/email/mu4e/README.org, modules/email/notmuch/README.org
- fix broken links in notmuch readme
- use links for early project mentions in mu4e
- fix table formatting in install matrix
=> readme fixes for notmuch and mu4e

modules/ui/doom-quit/config.el
I loved the idea, so I added it :)
Fixes #5373
=> Adds quit message from Sid Meier's Alpha Centauri

modules/ui/doom-quit/config.el
I'm sure Cave Johnson would approve.
> The lab boys just informed me that I should not have mentioned the control group. They're telling me I oughtta stop making these pre-recorded messages. That gave me an idea: make more pre-recorded messages. I pay the bills here, I can talk about the control group all damn day.
=> Holy hercules! more portal quit lines

modules/lang/web/+html.el
Fixes #5442 
Add `heex` extension to Elixir web-mode.
=> feat(web): add *.[lh]?eex support

modules/tools/magit/packages.el
magit/magit@1e40d00 -> magit/magit@f53148a
magit/forge@f97bc47 -> magit/forge@483baae
Fix magit/forge#382
Fix #5530
=> bump: :tools magit

modules/ui/doom/packages.el
To include the recently merged pull requests to `doom-themes`
=> bump: :ui doom

modules/email/mu4e/config.el
At some point in the original PR alerts stopped working. I've finally
tracked down why and found three components to the problem:
- I'm calling `start-process` incorrectly
- `truncate-string-to-width` is called on `nil` when no from name is
given
- mu4e-alert uses :docid to check for duplicates, which is not provided
in mu 1.6, and so :message-id must be used instead.
=> fix(mu4e): make alerts work again

modules/tools/upload/config.el
=> fix(upload): deploy force on explicit save

core/core-ui.el
So that reverting it is easier.
=> fix: use advise-add instead of fset to override yes-or-no-p

modules/completion/vertico/autoload/vertico.el, modules/completion/vertico/config.el, modules/completion/vertico/packages.el
- minor code reorganization
- which-key embark indicator improvements
- `+vertico/search-symbol-at-point` preview fix
- bump packages
- add [consult-dir](https://github.com/karthink/consult-dir)
=> `:completion vertico` improvements

modules/tools/biblio/README.org
A few minor grammar-related changes to the biblio module's README.
=> docs(biblio): improve grammar

modules/lang/clojure/config.el
See https://github.com/hlissner/doom-emacs/issues/5762#issuecomment-978337753
Fixes #5762
=> fix(clojure): localleader labels in clojurec-mode take 2

modules/tools/lookup/packages.el
SavchenkoValeriy/emacs-powerthesaurus@93036d3b1119 -> SavchenkoValeriy/emacs-powerthesaurus@02c9d11a3f40
jacktasia/dumb-jump@f3176fbf9c11 -> jacktasia/dumb-jump@dbb915441a2b
tkf/emacs-request@68003b3f8597 -> tkf/emacs-request@3336eaa97de9
Fix https://github.com/SavchenkoValeriy/emacs-powerthesaurus/issues/17
=> bump: :tools lookup

modules/tools/biblio/packages.el
andras-simonyi/citeproc-el@c8ff95862823 -> andras-simonyi/citeproc-el@e5b5f86defe2
bdarcus/citar@41ec5d4d5d62 -> bdarcus/citar@9e6817900160
tmalsburg/helm-bibtex@bb47f355b0da -> tmalsburg/helm-bibtex@aa775340ba69
A simple bump commit.
=> bump: :tools biblio

modules/tools/magit/README.org
=> docs(magit): add docs for #5846

modules/term/vterm/packages.el
This fixes a recently introduced SEGFAULT.
=> bump: :term vterm

core/autoload/buffers.el, core/autoload/help.el, core/autoload/packages.el, core/autoload/projects.el, core/core-lib.el, modules/config/default/+emacs-bindings.el, modules/emacs/dired/config.el, modules/email/notmuch/autoload.el
Little defects I noticed while browsing the sources and documentation.
=> nit: fix several docstring typos and minor code tweak

modules/lang/common-lisp/packages.el
joaotavora/sly@540a8c5 -> joaotavora/sly@2e00c3b
Bump SLY to latest commit
=> bump: :lang common-lisp

modules/tools/biblio/config.el
- Remove outdated config for org-roam.
- Set org-cite-bibliography to citar-bibliography
=> refactor(biblio): update citar config

modules/lang/org/README.org
Updates org module's readme to show the changes made upon merging #6033
=> lang(org): update readme to show recent changes

modules/tools/lsp/README.org
Add reference to LSP tuning guide in docs.
=> docs(lsp): add reference to LSP tuning guide

modules/ui/modeline/README.org
Solve some `TODO` documents for `modeline`, according to https://github.com/hlissner/doom-emacs/issues/1166
=> fix: add some documentation for modeline

modules/editor/snippets/README.org
Add docs to write custom `snippets`
=> docs(snippets): add docs to write custom snippets

modules/lang/org/autoload/org.el
When you have a structure like
``` org
- ThisX
- Hi 
- No
```
in org mode and execute `+org-insert-item` (the "X" represents the pointer), with the current behavior the following is created:
``` org
- This
- X
- Hi 
- No
```
This pr will change the behavior, so that its equivalent to the one of headlines:
``` org
- This
- Hi 
- No
- X
```
=> fix(org): parity for headlines & items in `+org--insert-item`

modules/editor/evil/autoload/unimpaired.el
change `+evil/next-preproc-statement` to `+evil/next-preproc-directive`
=> fix(evil):jump preprocessor directive bug.

core/autoload/help.el
this was first PR'ed in #6122 but that PR was closed.
-------
=> nit: fix typo in tuareg mode

modules/lang/coq/packages.el
ProofGeneral/PG@2145c23f44a0 -> ProofGeneral/PG@df19c7ba0ead
bump ProofGeneral to latest master commit.
=> bump: :lang coq

modules/editor/file-templates/templates/solidity-mode/__sol
Solidity template was outdated and inconvenient
=> tweak(file-templates): update default solidity template

modules/ui/hydra/autoload/windows.el
Add `winner` commands to `+hydra/window-nav`
=> feat(hydra): add winner commands to +hydra/window-nav

modules/completion/company/README.org
Add docs for code completion with multiple keywords.
=> docs(company): code completion with multiple keywords

core/core-ui.el
Enable `hl-line-mode` in `dired-mode`
=> ui: enable hl-line-mode in dired-mode

modules/tools/direnv/packages.el
purcell/envrc@e161624b9155b5d171d7f64d35531313ca1075d6 -> purcell/envrc@57d78f0138d9c676dff182e713249ad055ccf85d
=> bump: :tools envrc

modules/editor/file-templates/templates/org-mode/__, modules/editor/file-templates/templates/org-mode/__contact.org, modules/editor/file-templates/templates/org-mode/__invoice.org, modules/editor/file-templates/templates/org-mode/__project.org
See https://list.orgmode.org/87tuuw3n15.fsf@nicolasgoaziou.fr/.
=> nit(org): lower case keywords in file templates

README.md
Update repo links in README, from `github.com/hlissner/doom-emacs` to `github.com/doomemacs/doomemacs`
=> docs: update repo links in readme

modules/tools/pdf/packages.el
vedang/pdf-tools@326552eef71ae6d53e215c46be5bf532575b7abb -> vedang/pdf-tools@f9ccdf99e560bae70d3a13325cec9dc0e3cc45b0
Ref: vedang/pdf-tools#96
Ref: vedang/pdf-tools@4460a4fd3122e6b53cab1b7d86d6e19022d81fb1
Fix: vedang/pdf-tools#102
Fix: politza/pdf-tools#706
Fix: vedang/pdf-tools#90
Fix: vedang/pdf-tools#86
Edit: Bumped again cause now `epdfinfo` doesn't need as many dependencies to compile, yay!
-----
=> bump: :tools pdf

modules/lang/dhall/packages.el
psibi/dhall-mode@ad259c8a2292 -> psibi/dhall-mode@c77f1c1e75b6
References https://github.com/psibi/dhall-mode/pull/36
=> bump: :lang dhall

modules/completion/vertico/config.el
Closes #6258
Could maybe do with some nicer Marginalia annotations, but it functions as expected.
=> feat(vertico): add tramp sources to consult-dir

modules/config/literate/autoload.el
Does what it says on the tin. I think it's great, and some users have mentioned huge improvements.
=> feat(literate): add async config tangling

modules/lang/scala/packages.el
This PR bumps the [lsp-metals](https://github.com/emacs-lsp/lsp-metals) to the latest commit up to this date. Namely to support server updates to the latest versions - when such is managed by Emacs. 
Ref: https://github.com/emacs-lsp/lsp-metals/pull/73
-----
(I believe I have covered all the points, but please let me know if I'd missed anything)
=> bump: :lang scala

modules/lang/dart/config.el
Improving the keybinds for Flutter control on a dart file buffer.
------
=> feat(dart): improve keybindings for better Flutter control

modules/lang/sh/doctor.el
Added a doctor check in sh module for shfmt.
-----
=> docs(sh): add doctor check for shfmt

modules/lang/latex/+viewers.el
When using Skim as the viewer to open PDF files from AUCTeX, it would better reload from disk to reflect the changes. Skim has an option to reload automatically, but it does not work properly, and the authors "discourage you from using it". (https://sourceforge.net/p/skim-app/wiki/TeX_and_PDF_Synchronization/)
-----
=> tweak(latex): ask Skim.app to reload pdf

modules/lang/php/README.org
Update php docs to use correct variable
=> nit(php): update readme

modules/email/mu4e/autoload/email.el
=> fix(mu4e): add missing icons for mu 1.8.X

modules/lang/go/autoload.el, modules/lang/go/config.el
Added to `go` module a new keybinding `SPC l t f` pointing to a new function `+go/test-file`.
The new function provides the posibillity of running all tests under the current buffer (similar to vscode `run file tests`) 
-----
=> feat(go): add test-file function and keybinding

modules/completion/vertico/README.org
Add documentation for the `+childframe` flag.
-----
=> docs(vertico): add `+childframe` flag

modules/tools/tree-sitter/README.org, modules/tools/tree-sitter/autoload.el, modules/tools/tree-sitter/config.el
as well as documentation updates to reflect this update
this is still a work in progress as there is also a lazy load bug in this change as well as update for the latest docs
-----
=> `:tools tree-sitter` syntax highlighting 

modules/editor/fold/packages.el
Hi, I am the author of [ts-fold](https://github.com/emacs-tree-sitter/ts-fold). The repo has moved under the same domain `emacs-tree-sitter`, this PR updates the repo link.
=> bump: ts-fold

bin/doomscript
Fixes #6772, and addresses several other issues found by sh-shellcheck in `bin/doomscript`
-----
=> Fix doomscript

modules/email/mu4e/autoload/email.el
Replace the rather crude "don't do anything if already in a mu4e-y buffer" behaviour with a more refined approach that tries to find the live mu4e buffer likely of the most interest and switch to that, before calling (mu4e) if no such buffer is found.
-----
=> feat(mu4e): more DWIM-y mu4e entry point (=mu4e)

modules/email/mu4e/autoload/email.el
Just a small and simple PR, the title is all that's needed.
-----
=> fix(mu4e): +mu4e/capture-msg-to-agenda with mu 1.8

lisp/cli/upgrade.el
Improves documentation.
Fixes #6712
References #6712
+Replaces #0000+
-----
=> docs(cli): doom upgrade: s/-f/--force

modules/lang/org/README.org, modules/lang/org/config.el, modules/lang/org/packages.el
A recent commit of org-contrib removed a number of packages.
Closes #6740
=> feat: add back relevant removed org-contribs

modules/ui/workspaces/autoload/workspaces.el, modules/ui/workspaces/config.el
This PR makes `tab-bar` tabs workspace-local.
=> feat(workspaces): make tab-bar tabs workspace-local

lisp/packages.el
Update `straight.el` ([Straight.el issue](https://github.com/radian-software/straight.el/pull/1013))
Fixes #6960
References #6960
-----
=> bump: :core (Deal with new NonGNU ELPA recipe format)

modules/lang/rust/README.org
=> docs(rust): add missing +tree-sitter flag

lisp/lib/docs.el, modules/lang/org/README.org, modules/lang/org/autoload/org-link.el, modules/lang/org/config.el
This is not the final form of the Docs, but it allows for this work to be reorganised and then further improved down the line.
For fun, here are a few screenshots of the Org docs with these changes.
=> Glamorous doc links

modules/lang/clojure/README.org, modules/lang/clojure/config.el, modules/lang/erlang/README.org, modules/lang/erlang/config.el, modules/lang/ess/README.org, modules/lang/ess/config.el, modules/lang/haskell/README.org, modules/lang/haskell/config.el, modules/lang/lua/README.org, modules/lang/lua/config.el, modules/lang/yaml/README.org, modules/lang/yaml/config.el, modules/tools/tree-sitter/packages.el
- Bump the module
- add support for
- haskell
- lua
- erlang
- ess-r
- yaml
- as well as docs for all
-----
=> bump: :tools tree-sitter

modules/lang/org/contrib/pretty.el
=> feat(org): add hook for org-appear

modules/checkers/spell/README.org
Add a note in case of different personal dictionary settings.
References #6246 
-----
=> docs(spell): mention possible mismatch in ispell-personal-dictionary

modules/lang/clojure/README.org, modules/lang/clojure/config.el, modules/lang/clojure/packages.el
- Update the README
- Better gate clj-refactor to not get in the way of LSP
- Add support for jet & neil
=> :lang clojure module refactor

modules/editor/parinfer/config.el
=> fix(parinfer): activate for `fennel-mode`

modules/completion/vertico/packages.el
iyefrat/all-the-icons-completion@b08f053cee44 -> iyefrat/all-the-icons-completion@8eb3e410d63f
minad/consult-flycheck@fda630411ad9 -> minad/consult-flycheck@3f2a7c17cc2f
minad/consult@511d8c0b072a -> minad/consult@fe49dedd7180
minad/marginalia@b900ec545706 -> minad/marginalia@866e50aee4f0
minad/vertico@926234ab3fbe -> minad/vertico@a28370d07f35
oantolin/embark@9b17d9a63b69 -> oantolin/embark@9a44418c349e
=> bump: :completion vertico

modules/editor/evil/config.el, modules/tools/lsp/+eglot.el, modules/tools/lsp/doctor.el, modules/tools/lsp/packages.el
A couple of small changes that improve the Eglot experience.
=> Minor Eglot improvements

modules/emacs/undo/README.org
=> docs(undo): unfo-fu -> undo-fu

modules/lang/latex/README.org
`texlive-core` package recently has been splitted into several packages as stated on the archlinux website
https://archlinux.org/news/tex-live-package-reorganization/
-----
=> Updated recommended packages to install for LaTeX module on Arch Linux

modules/checkers/syntax/README.org
Add flymake flag to readme
-----
=> docs(syntax): add flymake flag

modules/checkers/syntax/config.el, modules/config/default/+evil-bindings.el
=> fix(syntax): s/use-package/use-package!

lisp/lib/ui.el, modules/completion/vertico/config.el, modules/config/default/+emacs-bindings.el, modules/config/default/+evil-bindings.el, modules/editor/file-templates/autoload.el, modules/lang/javascript/config.el, modules/lang/org/autoload/org-capture.el, modules/lang/org/contrib/present.el, modules/term/eshell/config.el, modules/ui/emoji/README.org, modules/ui/popup/+hacks.el
A collection of small improvements. It felt a bit silly to open 8 issues and PRs for these, but if you want the traceability let me know and I can do that.
-----
- considered `feat` for the `tweak`s, but “Code changes that changes defaults and user-facing behavior, but not drastically” seemed more applicable than “code introducing a new feature or extends an existing one”
=> Miscellaneous fixes

modules/completion/vertico/config.el
Removes the dependence on docker-tramp, can later be cleaned up with
`tramp-container--completion-function` when we drop support for <29.
Aware this probably isn't the _cleanest_ way to handle this, happy to drop ootb support for docker & podman and leave it up to the user to add whichever they want.
=> refactor(vertico): consult-dir: drop dependence on docker-tramp

modules/lang/lua/config.el
Fennel's syntax is based on Lisp. It's easier to see matching parentheses with rainbow delimiters.
-----
=> feat(lua): enable rainbow-delimiters in fennel-mode

modules/ui/workspaces/autoload/workspaces.el
Fix: #7139
-----
-----
Add a check before load tab configurations of workspace from saved file, which solves the issue mentioned in #7139
=> fix(workspaces): check before loading tab configuration

modules/ui/doom-quit/config.el
Nitpick wrt quit message.
Might come under under 3 trivial corrections ? 
Couldn't find any
=> tweak(doom-quit): make quit message OS-sensitive

modules/app/rss/packages.el
remyhonig/elfeed-org@7f3ad86 -> remyhonig/elfeed-org@fe59a96
Ref: remyhonig/elfeed-org#88
* fix elfeed-org-export-opml error
* perf: use temporary buffers instead of find-file
* replace outline-on-heading-p with org-at-heading-p
* fix typo in last changes
-----
=> bump: :app rss

modules/app/rss/README.org
Found a missing quote while reading the doc.
-----
=> docs(rss): add a missing double quote in README

modules/tools/terraform/README.org
Fix: #0000
Ref: #0000
Close: #0000
-----
=> docs: added +lsp flag to terraform module

modules/completion/company/packages.el
Bump packages:
sebastiencs/company-box@766546b2668b -> sebastiencs/company-box@b6f53e26adf9
company-mode/company-mode@2ca3e29abf87 -> company-mode/company-mode@9b21604d1969
Fix: doomemacs/doomemacs#6710
-----
=> bump: :completion company

modules/lang/org/config.el
=> fix(org): restart org-mode before indirect buffer

modules/ui/popup/autoload/popup.el, modules/ui/popup/test/test-popup.el
=> fix(popup): find internal major side windows

modules/ui/modeline/packages.el
https://github.com/seagle0128/doom-modeline/commit/93f240f7a0bf35511cfc0a8dd75786744b4bcf77 -> https://github.com/seagle0128/doom-modeline/commit/bf880ae56f3f6aab7bd334de9bd9b455c63a24c0
-----
=> bump: :ui modeline

modules/lang/idris/doctor.el
Add doctor.el to check the idris interpreter.
=> Add doctor.el for idris

modules/email/wanderlust/README.org, modules/email/wanderlust/config.el, modules/email/wanderlust/packages.el
Here I've updated wanderlust to the last version and shared some nice tricks from my local config which I belive quite useful.
It also uses https://github.com/doomemacs/doomemacs/pull/7621 to make very nice alerts on macOS.
=> Taking care of wanderlust integration

modules/email/wanderlust/config.el, modules/email/wanderlust/packages.el
Here a bump for wanderlust which increase stability of IMAP connections.
Also, I've add to ignored headers list one more technical header.
=> bump: :email wanderlust

lisp/cli/meta.el
To improve the quality of "did you mean?"-style suggestions, shift from using [Ratcliff-Obershelp](https://en.wikipedia.org/wiki/Gestalt_pattern_matching) similarity to the [Restricted Damerau-Levenshtein](https://en.wikipedia.org/wiki/Damerau%E2%80%93Levenshtein_distance#Optimal_string_alignment_distance) string distance (also known as Optimal String Alignment).
This code is a translation of a [Julia implementation](https://github.com/tecosaur/DataToolkitBase.jl/blob/v0.4.1/src/model/utils.jl#L40-L107) I wrote a while ago.
=> tweak(cli): use a fancier string-distance algorithm for suggestions

modules/tools/biblio/config.el
Debugging this has me seriously considering GNU nano. Or GNU cat.
Fix: https://github.com/doomemacs/doomemacs/issues/7701
-----
=> Fix oc-csl dependency cycle and tidy biblio module

modules/lang/clojure/config.el
=> tweak(clojure): fix obsolete variable usage

modules/ui/popup/autoload/popup.el
Fix: #7647
Amend: #7598
---
Yes, the logic in my previous PR #7598 was a bit too simplistic. This PR should make more sense, and I tested that it resolves the specific problem that @45mm reported in #7647.
@45mm @vherrmann Can you check if this commit resolves the issues?
=> fix(popup): fix finding of major side window

modules/config/default/autoload/default.el, modules/email/mu4e/README.org, modules/lang/latex/autoload.el
Fix: #0000
Ref: #0000
Close: #0000
-----
=> chore: remove repetitive words

modules/completion/vertico/config.el
=> feat(vertico): add orderless annotation filtering

modules/app/everywhere/config.el, modules/ui/modeline/README.org
Quickfix to 665d808d09ecba0be1b2de3977950e579bb5daee.
=> fix(modeline, everywhere): adjust checker -> check

modules/lang/common-lisp/config.el, modules/lang/common-lisp/packages.el
=> feat(common-lisp): add more sly packages

modules/tools/magit/config.el
Renamed upstream
Ref: magit/forge@ba752a4e9b42
-----
=> fix(magit): forge-browse-dwim -> forge-browse

modules/ui/ligatures/autoload/ligatures.el
Fix: #7433
Ref: #7433
Close: #7433
https://github.com/doomemacs/doomemacs/issues/7433#issuecomment-1729267699
cc @gagbo
-----
=> fix(ligatures): set-font-ligatures! reset on nil

modules/email/wanderlust/config.el, modules/email/wanderlust/packages.el
=> Backport local tweaks and update of wanderlust

modules/lang/org/packages.el
emacs-straight/org-mode@7fa1694ec6ba -> emacs-straight/org-mode@39272e2165ad
Security fix, see notes at https://github.com/emacs-straight/org-mode/commit/e6de8408899c22e05cf62dd0b5d41c346b8f91ff
-----
=> bump: :lang org

modules/email/mu4e/README.org
Covers configuring SMTP servers, authentication to them, some Gmail-specific issues, and sending mail without blocking Emacs.
-----
=> docs(mu4e): instructions for SMTP setup

modules/lang/clojure/packages.el
babashka/neil@a1db63d420b8 -> babashka/neil@a38be9f0821b
borkdude/flycheck-clj-kondo@9089ade9e01b -> borkdude/flycheck-clj-kondo@e38c67ba9db1
clojure-emacs/cider@aa26d62ac599 -> clojure-emacs/cider@105da319b09a
clojure-emacs/clj-refactor.el@fa3efe18e715 -> clojure-emacs/clj-refactor.el@dc1bbc8cdaa7
clojure-emacs/clojure-mode@222fdafa2add -> clojure-emacs/clojure-mode@59888c84b610
Incorporate bug fixes and new features from CIDER, e.g. cheatsheet in a buffer.
Note: Minimum supported version of Clojure was bumped to 1.10.
-----
=> bump: :lang clojure

modules/lang/org/autoload/org-link.el, modules/lang/org/config.el
Fix originally proposed by Khoulaiz here:
https://github.com/doomemacs/doomemacs/issues/7222#issuecomment-1535932540
Fix: #7222 #3185
Co-authored-by: Khoulaiz
=> fix(org): attachment image inline preview

modules/lang/python/config.el
Use the `(PREFIX . DESCRIPTION)` syntax for the python mode map.
this vs this:
Fix: #0000
Ref: #0000
Close: #0000
-----
=> tweak(python): verbose prefixes for keybindings

modules/lang/org/config.el
Fix: https://github.com/doomemacs/doomemacs/issues/7737
-----
=> fix(org): restart org in all optimized buffers

modules/lang/erlang/README.org, modules/lang/erlang/config.el, modules/lang/erlang/doctor.el
[erlfmt](https://github.com/WhatsApp/erlfmt) is maintained by a large corporation rather than an individual, and has a rationale for [_each and every_](https://github.com/WhatsApp/erlfmt/tree/main/doc) style decision.
-----
=> tweak(erlang): format w/ erlfmt instead of efmt

modules/tools/terraform/config.el
Add shortcuts for `validate`, `fmt` and `destroy`
-----
=> feat(terraform): Add terraform shortcuts for validate, fmt and destroy

modules/completion/corfu/config.el
Fixes the change from #8262 which created a void variable error `local-map`.
=> fix(corfu): void variable local-map

modules/lang/org/autoload/org-refile.el
Allow +org/refile-to-current-file to file to top level.
Fix: #5272
-----
=> fix(org): allow refiling to top level

lisp/doom-ui.el
Recent changes have add advice to `comint-output-filter` to protect previous terminal output from being modified. 
However, these advises assume the `comint-output-filter` is called from the buffer associated to the provided process. This turns out to not always be the case as for example `ess--flush-accumulated-output` calls the output filter from inside of a separate accumulation buffer, resulting in the following error: "error in process filter: Wrong type argument: number-or-marker-p, nil". 
To fix this issue and other potential side effects, this PR wraps the function body in a `with-current-buffer` form.
-----
=> fix(:term): ensure process-buffer is current

lisp/cli/ci.el
When you fail to provide a correct commit message, it may just become lost without this adjustment.
This patch echos the commit message attempt on the cli, since one probably entered interactively in e.g. `vim` and would loose it otherwise.
(fun fact: this feature was used to fix its own commit message 4 times)
=> feat: cli/ci/commit-msg: echo failed commit message
